### ISSUE TITLE
[issue] Thunderlords description

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#10]
Our player (his nickname: Linker) today noticed that description of 'Thunderlord' contain certain info about pet:

> Thunderlords have tamed the Great Eagles of Middle-Earth and use them in their hunts. They need a very long time to gain experience, as both bird and man need to gain levels. They need to eat often.

So Linker asked me - how to get this pet? And I've explained that it's just a lore.

So maybe description of this race could be changed so it won't make players believe that this race could have a pet.

**Comment by draconisPW** [comment]
In fact a Thunderlord is actually the combination of a human and an eagle, the pet is simply not visible since you're supposed to be constantly riding it. The description is therefore perfectly accurate and doesn't need to be changed.
