### ISSUE TITLE
Linux compilation problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#105]
[jezek](https://www.tomenet.eu/phpBB3/memberlist.php?mode=viewprofile&u=1489) from TomeNET forums wrote:

> I don't now, how travis did it, but I'm unable to compile...
> I used https://github.com/igroglaz/PWMAngband
> Followed instructions on https://tangaria.com/linux/ wit no succes... all times make crashed with some error...
> I've tried also come configure params, like:
> ./configure --disable-curses --disable-x11 --enable-sdl --enable-sdl-mixer
> ./configure --disable-curses --disable-x11 --enable-sdl
> ./configure --disable-curses --enable-sdl --enable-sdl-mixer
> ./configure --enable-sdl --enable-sdl-mixer
> ./configure --enable-sdl
> 
> always make fails due to various (specific for params) errors...
> 
> PS: I'm on ubuntu mate 64bit 19.10
> PPS: in instructions for debian on ubuntu 'apt install build-essentials' didn't work the right name was 'build-essential'. You also need 'autotools-dev' and 'automake' package. And the runing of './autogen.sh' before './configure' is missing...

**Comment by draconisPW** [comment]
Unfortunately I have no idea how Linux works so putting this here will not do anything since I won't be able to help at all. I try to update the makefiles and ensure that the Travis build always works, but apart from that you'll be on your own for Linux.

**Comment by jezek** [comment]
Ok, today I tried again, to provide logs and the ```make``` after ``` ``` did work. Here has to be a better star alignment today or I made a mistake yesterday. :)

But after that, the ```sudo make install``` throwed error:
```
Entering directory src.
Successfully installed pwmangclient.
Successfully installed pwmangband.
Leaving directory src.
Entering directory lib.
Entering directory gamedata.
Successfully installed activation.txt.
Successfully installed artifact.txt.
...
Successfully installed trap.txt.
Successfully installed vault.txt.
/usr/bin/install: cannot stat 'world.txt': No such file or directory
Failed to install world.txt!
make[2]: *** [../../mk/buildsys.mk:435: install] Error 1
make[1]: *** [../mk/buildsys.mk:430: install] Error 2
make: *** [mk/buildsys.mk:430: install] Error 2
```

**Comment by draconisPW** [comment]
ok the makefile is not up to date with /gamedata/, I'll update it.

**Comment by jezek** [comment]
I've used the ```--with-no-install``` configure parameter, built, runned ```./src/pwmangclient``` from the ```PWMAngband``` directory, the client started. After logging to main server (a), it crashed with:
```
Failed to retrieve random name fragments.
```

**Comment by jezek** [comment]
QUESTION: Right now, everything I do on [```igroglag``` repository](https://github.com/igroglaz/PWMAngband). Would in not be better to talk about compiling this repo?

**Comment by draconisPW** [comment]
Makefile updated in 7ae72ba.

**Comment by igroglaz** [comment]
jezek, better to use https://github.com/draconisPW/PWMAngband as it's main repo; my is just a clone which I use to make commits to PW repo
