### ISSUE TITLE
'solo' monster flag to prevent appearing in pits/vaults (death golems problem)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#106]
As there is some monsters which could be especially powerful and shouldn't in general appean in big packs, it will be fun to add 'solo' monster flag (means that it could appear only solo, not in pit)

**Comment by draconisPW** [comment]
Pits have flag restrictions for this.

**Comment by igroglaz** [comment]
I've checked NONLIVING monsters and there are just mimics swords and base:minerals; I thought this pits removed cause death golems:
```
#name:Unlife
#room:2
#alloc:1:110
#obj-rarity:20
#flags-req:NONLIVING
```
