### ISSUE TITLE
lose_exp doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#107]
```
name:Lose Memories
graphics:!:d
type:potion
level:10
weight:4
cost:0
alloc:10:10 to 15
pile:25:2
effect:LOSE_EXP
```

But after the 1.4 dev#3 update this flag won't work it seems:

280320 001624 Unknown effect 'LOSE_EXP'.
280320 001624 Parse error in object line 3564 column 3: : invalid effect
280320 001624 Parse error in object line 3564 column 3.

**Comment by draconisPW** [comment]
Potion + effect have been removed in V 4.2

**Comment by igroglaz** [comment]
Let's bring it back? :) A lot of stuff which were removed in V could still have place in PWMA - like scrolls of curse armour/weapon which were too recently removed. It was fun to had it.
