### ISSUE TITLE
exclude `wearing` from !* inscription

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#108]
one of the most often used inscriptions in TomeNET was !* - to forbid dropping, selling, destroying, etc. In PWMA it's also includes wearing which is IMHO not so comfortable; as it's very rare case when I wanna exclude wearing; and if so I'll use !*!w on it.

It's made very nicely in TN:
https://www.tomenet.eu/guide.php?chapter=0.3&highlight=inscription#r15

**Comment by draconisPW** [comment]
Implemented.
