### ISSUE TITLE
dev versions numbers

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#109]
I compare dev version manually; for example right now I've got 3 folders of PWMAngband 1.4.0: dev 1, dev 2, dev 3. But when I download them there is no dev numbers, it's just PWMAngband 1.4.0

Maybe to add one more number there? Eg PWMAngband 1.4.0.3. It will also help to write patchnotes on the website, eg right now I name it "PWMAngband 1.4.0 dev #3 version" (https://tangaria.com/news/pwmangband-1-4-0-dev-3-version/)

**Comment by draconisPW** [comment]
This already exists.

**Comment by igroglaz** [comment]
Cool :) Please could you add this sub-version numbers to patchnotes and .7z file names
