### ISSUE TITLE
Protect players in case of server restart

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#11]
add admin '&' command to return all players to town immediately - it would help to protect players from nasty deaths if server was restarted and they logged in into nasty lvl afterwards\

another way to solve it - could be to return players to town automatically before server save upon closing server window

**Comment by draconisPW** [comment]
This will be hard to implement because 1) players are not always on a level related to a town and 2) players don't always want to lose the level they're on. A better solution would be to give GoI for a couple turns, like it was implemnted in MAngband for Ironman servers.

**Comment by igroglaz** [comment]
GoI.. Then it should be a very short count, otherwise I afraid that it could give possibility to cheat

**Comment by draconisPW** [comment]
MAngband fixed the issue like this: https://github.com/mangband/mangband/issues/1014

**Comment by draconisPW** [comment]
Fixed in ecfff27.
