### ISSUE TITLE
Option to disable 'Enter' menu

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#110]
Enter menu is good for singleplayer Angband, but for multiplayer it's often become a problem when player could accidentally summon it and die because of it. It will be fun to add an option to disable its appearance.

**Comment by flambard-took** [comment]
Angband 3.0.8 (which introduced that menu) suggests a blank keymap to disable it:

```
# Turn Enter into Spacebar
A:\s
C:0:\r
C:1:\r
```

(not sure if keymap format is still the same in V4/PWMA pref files, but you get the idea).

**Comment by draconisPW** [comment]
Implemented.
