### ISSUE TITLE
Dungeon.txt chances

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#112]
As now we could add loads of interesting terrain to the dungeon - it will be fun to assign small details there; but as right now lowest chance is 1%; as we got field 197×65 (?), it could have 13199 tiles on level. So with 1% we will get 131 tiles of the same type, which is way too much. It will be fun to have single items in the dungeon, to surprise players (even if you visited dungeon 100500 times, you will still sometimes will see something new).

It will be great to raise max probability from 100 to 10000 for
```
# floor : floor feature : chance of getting the feature
# wall : wall feature : chance of getting the feature
```

The same could be made for 
`# rule : chance of using the rule : apply to all monsters`

So in the dungeon you could sometimes see some wierd monster. It will help to make some places like The Sandworm Lair less boring.

**Comment by igroglaz** [comment]
please could you take a look into this issue. It will give possibility to create much much more beautiful dungeons

**Comment by igroglaz** [comment]
Thanks :) Another great this that it will give possibility to assign more than 100 features per wall/floor/door as I'm already stumbled upon this limitation

**Comment by draconisPW** [comment]
Implemented.
