### ISSUE TITLE
Problems with light

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#113]
Description:
All objects which don't have flag:
`PROJECT`
are always got yellow light on it - trees, walls, etc

Demo:
https://youtu.be/XkIqOUlo0eM
(it's not public video; accessible only via link; will delete it soon)

**Comment by draconisPW** [comment]
It's coded like that in V:

if (square_iswall(c, grid) && !square_islitwall(p, c, grid))
if (square_islit(c, grid))
if (OPT(p, view_yellow_light)) g->lighting = LIGHTING_TORCH;

So features that don't have PROJECT, which are not surrounded by lit floor (check your video -- some trees that are "alone" are not lit in yellow) but are lit themselves appear with "torch" light if "view_yellow_light" is set.

Frankly I've copied/pasted to code but I have no idea why this is so. It feels really weird in town, and I'm sure the rubble in V looks the same. I'll take a look at this.

**Comment by draconisPW** [comment]
Ok I've watched the video again and made some debug code to show LIGHTING_XXX when inspecting terrain with the 'l' + 'p' command. For dungeon, everything is correct:
- walls and non walls all use LIGHTING_TORCH in corridors, since the tile is not SQUARE_GLOW (permanently lit)
- walls and non walls all use LIGHTING_LOS in room, since the tile is permanently lit
If you see "yellow" walls, it means your walls have the same tile for "torch" and "los", you should modify graf-xxx.prf, it's a problem with your mapping.

Considering features in town, the debug code shows those as LIGHTING_TORCH, which is stupid. Since the code is supposed to ensure that "Lit walls only show as lit if we are looking from the room that's lighting them", there is no reason to check for features not inside a room. I'll change that.

**Comment by igroglaz** [comment]
There is a problem with LIGHTING_LOS in dungeon's rooms. As LIGHTING_LOS in room color floors to white - walls also should be colored in white, but they are yellow. And I can't remove `torch` from walls - as the same wall used in corridors.

Is it possible to do not affect walls in LIGHTING_LOS in dungeon's rooms? Because it's weird to see 'white' lightned floors and yellow lightened walls in the same room.

**Comment by igroglaz** [comment]
Before the update LIGHTING_LOS in dungeon's rooms was correct, eg: https://youtu.be/dhClunpBf8s?t=429

**Comment by draconisPW** [comment]
Be careful: LIGHTING_LOS features should ALWAYS be white. Only LIGHTING_TORCH features should be yellow. I have no problem at all in PWMAngband. If you have an issue locally, fix your tileset.

**Comment by igroglaz** [comment]
I didn't touch tileset in these parts :) It worked before update as always.

I suppose I've used 'LIGHTING_LOS' in a wrong way, sorry; by it I meant rooms in the dungeon which are lightened by default. There are rooms in the dungeon which always have white light. And they've got proper white light at floors. But they've got wrong yellow light at granite walls. 

As at this fragment of video (before update): https://youtu.be/dhClunpBf8s?t=429 - this room has proper lighting - floors and walls both got white light.

At video with current version: https://youtu.be/XkIqOUlo0eM?t=20 - this room has wrong lighting - floors are white (as should be), walls are yellow (and it's wrong).

**Comment by draconisPW** [comment]
Seems like V also updated lighting without changing tileset mapping.

Before:

feat:granite wall:torch:0x96:0x92
feat:granite wall:los:0x96:0x92
feat:granite wall:lit:0x96:0x93
feat:granite wall:dark:0x96:0x94

Now:

feat:granite wall:torch:0x96:0x92
feat:granite wall:los:0x96:0x93
feat:granite wall:lit:0x96:0x94
#feat:granite wall:dark:0x96:0x94 (don't care about this one, with new system LIGHTING_DARK is not used anymore)

I'll ask on V forums, I'm really puzzled atm.

**Comment by igroglaz** [comment]
Damm.. Is it possible to restore DARK? :) I've already got it for all features in tileset.. maybe monsters who decrease light -2 could make surrounding stuff as 'dark'... Or maybe add it as aftermath after being blinded (so everything is black for some time).. It's just a good piece of effect which is a pity to throw away.

**Comment by draconisPW** [comment]
Waiting for a response on V forums. I'm almost tempted to revert this lighting stuff which is more confusing than bringing anything new.

**Comment by draconisPW** [comment]
Ok:
- change squares that have negative light to LIGHTING_DARK
- change mappings in graf-xxx.prf so torch is mapped to LIGHTING_TORCH (tile 1), los is mapped to LIGHTING_LOS (tile 2) and lit is mapped to LIGHTING_LIT (tile 3); dark will also be mapped to tile 3 (I don't think we need a tile 4 for this)

**Comment by draconisPW** [comment]
Changed my mind... this is too much hassle for nothing. I'll simply update the tileset as above when I remap the missing tiles.

**Comment by igroglaz** [comment]
is this hassle is about coding or actually remapping tileset? if it's only about tileset rework - please let's implement proper lightning - I can help you to assign to PWMA tileset proper shadows for LIGHTING_DARK terrain. If it's hard in terms of coding - then maybe @flambard-took could also look into this problem (Two heads are better than one).

It's a pity to dump proper LIGHTING_DARK.. In my tileset I've spent weeks to map all my terrain to all four lightning types, eg:

```
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

But as PWMA tileset is really tiny compared to mine (I've got hundreds of different terrains, all of them with proper 1,2,3,4 lightning) - fixing a few terrain in PWMA with proper LIGHTING_DARK will be easy for me.

**Comment by draconisPW** [comment]
New lighting simply switched los/lit/dark (torch=los) to torch/los/lit (dark=lit). If you don't like how it looks with tiles 1/2/3/4 just use tiles 2/3/4 and remove tile 1. I suppose it's those who look yellow. For PWMAng I remapped the tiles, everything's fine.

**Comment by igroglaz** [comment]
I have _hundreds_ of terrain tiles which have proper lightning mapping - 1,2,3,4, eg

```
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

deleting torch in hundreds of places will take hours.. and it's totally pointless and dull work. Even mischievous work - as I had to castrate properly mapped tileset (with 1,2,3,4 correctly mapped features) into lame tileset with cutted off proper lightning :(

Deleting torch looks like a destruction of my tileset :( I won't do it, sorry. I would rather just play with `view_yellow_light=off` feature in hope that this problem will be fixed one day.

So the result of new lightning system is breaking properly worked old system :( It's very sad.

**Comment by igroglaz** [comment]
Anyway I'm ready to help with PWMA tileset 1,2,3,4 mapping in photoshop, if it's a reason why you don't want to implement lightning properly. It will take a hour or so. But destroying my tileset (deleting torch mapping) - will take several hours.

So if it's a coding issue, but tileset - please let's make it properly.

**Comment by draconisPW** [comment]
How to remap tileset in ten seconds:
- open graf-dvg.prf with any text editor
- search/replace feature: search ":torch:" replace with ":dark:"
- search/replace feature: search ":los:" replace with ":torch:"
- search/replace feature: search ":lit:" replace with ":los:"
- search/replace feature: search ":dark:" replace with ":lit:"
- save file

And you're done... :p

Note: since you don't delete anything in the tileset (4th tile will be assigned but not used), reverting would also take 10 seconds ;)

**Comment by igroglaz** [comment]
No.

Eg, we have original: 

```
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

Now take your steps:

> search/replace feature: search ":torch:" replace with ":dark:"

```
feat:granite wall:dark:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

> search/replace feature: search ":los:" replace with ":torch:"

```
feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

> search/replace feature: search ":lit:" replace with ":los:"

```
feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

> search/replace feature: search ":dark:" replace with ":lit:"

```
feat:granite wall:lit:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:lit:0xBD:0x87
```

> since you don't delete anything in the tileset (4th tile will be assigned but not used), reverting would also take 10 seconds ;)

Ooook. Now how to revert it? While we have TWO _lit_? THIS IS (SPARTA!) - irreversible:

```
feat:granite wall:lit:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:lit:0xBD:0x87
```

If you will replace lit back to dark - you will have two dark.

**Comment by draconisPW** [comment]
Oops my bad. You need first to change ":dark:" to something else like ":foo:"

**Comment by igroglaz** [comment]
thanks. it seems also foo should be renamed to dark in the end, or client won't start with foo.

2692 tiles replaced... with this guide:

> ##########################################
> # !!! should be revered when dark tiles will be used again.
> # 1) search/replace ":dark:"  replace with ":foo:"
> # 2) search/replace ":torch:" replace with ":dark:"
> # 3) search/replace ":los:"   replace with ":torch:"
> # 4) search/replace ":lit:"   replace with ":los:"
> # 5) search/replace ":dark:"  replace with ":lit:"
> # 6) search/replace ":foo:"   replace with ":dark:"
> #
> # So later on it should be done from 6 to 1 (backwards)
> # DONT FORGET TO MOVE THIS INSTRUCTION from .prf file or it will be replaced too.
> ########################################


**BUT. It doesn't work. It's actually become worse than before, screenshot:
https://i.snipboard.io/arlsw5.jpg**

**Comment by igroglaz** [comment]
thanks. it seems also foo should be renamed to dark in the end, or client won't start with foo.

2692 tiles replaced... with this guide:

```
##########################################
# !!! should be revered when dark tiles will be used again.
# 1) search/replace ":dark:"  replace with ":foo:"
# 2) search/replace ":torch:" replace with ":dark:"
# 3) search/replace ":los:"   replace with ":torch:"
# 4) search/replace ":lit:"   replace with ":los:"
# 5) search/replace ":dark:"  replace with ":lit:"
# 6) search/replace ":foo:"   replace with ":dark:"
#
# So later on it should be done !backwards! from 6 to 1.
# DONT FORGET TO MOVE THIS INSTRUCTION or it will be replaced too.
# // see github from 03 april 2020
########################################
```

```
# granite wall
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

become:

```
# granite wall
feat:granite wall:lit:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

**BUT. It doesn't work. It's actually become worse than before, screenshots:
https://i.snipboard.io/arlsw5.jpg
https://snipboard.io/k5T3QW.jpg**

**Comment by draconisPW** [comment]
Yes that's incorrect. It should be:

feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:lit:0xBD:0x87

So let's do this step by step...

From:
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87

# 1) search/replace ":dark:"  replace with ":foo:"

feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:foo:0xBD:0x87

# 2) search/replace ":torch:" replace with ":dark:"

feat:granite wall:dark:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:foo:0xBD:0x87

# 3) search/replace ":los:"   replace with ":torch:"

feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:foo:0xBD:0x87

# 4) search/replace ":lit:"   replace with ":los:"

feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:foo:0xBD:0x87

# 5) search/replace ":foo:"  replace with ":lit:"

feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:lit:0xBD:0x87

This should be it. Finally... :D

**Comment by igroglaz** [comment]
It's also wrong :(

https://i.snipboard.io/JDgK3L.jpg

```
# granite wall
feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87
```

become

```
# granite wall
feat:granite wall:dark:0xBD:0x84
feat:granite wall:torch:0xBD:0x85
feat:granite wall:los:0xBD:0x86
feat:granite wall:lit:0xBD:0x87
```

**Comment by draconisPW** [comment]
Ok I'll revert changes and simplify lighting even more. Use the original mapping:

feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x87

- torch: used in corridors for torchlight grids ONLY
- los: used in rooms when in los
- lit: used anywhere else
- dark: not used

When using the regular 3 tile system (PWMAngband), mapping should be:

feat:granite wall:torch:0xBD:0x84
feat:granite wall:los:0xBD:0x85
feat:granite wall:lit:0xBD:0x86
feat:granite wall:dark:0xBD:0x86

**Comment by draconisPW** [comment]
Hope this finally ends this waste of time. I'd rather continue implementing stuff. Lighting isn't perfect, but feels fine locally.
