### ISSUE TITLE
`view_yellow_light` off

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#118]
Based at (https://github.com/draconisPW/PWMAngband/issues/113):

/rfe
turn off yellow light by default
```
# Option 'Color: Illuminate torchlight in yellow'
N:view_yellow_light
```

**Comment by igroglaz** [comment]
Thanks to @draconisPW , now I know that it's possible to change it on client-side at pref.prf file

**Comment by draconisPW** [comment]
view_yellow_light and view_orange_light are now off by default.
