### ISSUE TITLE
Increase message window length

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#12]
Message line is 60 characters long; it makes hard to chat with players - as you need to make a lot of short messages. I suppose TomeNET got 240 symbols there, maybe PWMA could have the same amount?

There is a way to char in 'chat' window, but only minority of players using it

**Comment by draconisPW** [comment]
I've removed the 60 character limit... but it still doesn't work because the keypress handling function that gets text from the top line only accepts 80 characters. So the message buffer is longer but not very much longer (70 characters).

**Comment by draconisPW** [comment]
Implemented a very simplified version of TomeNET's "input line" in ff80c4e. Hope this didn't add bugs.
