### ISSUE TITLE
[bug] msg_self doesn't work for new items

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#121]
I've added several new potions/scrolls, eg Potion of Death:
`msg_self:Once again you've cheated death!`

but upon use they do not show msg_self

**Comment by draconisPW** [comment]
Oops... unfortunately, msg_self is hardcoded and only displays for a few effects (because some conditions need to be tested). Implemented a general case to display msg_self.

**Comment by draconisPW** [comment]
Note: msg_self is attached to an effect, not to the object. If the object has no effect, use effect:END_INFO as a dummy effect. For example:

name:Blabla
graphics:!:d
type:potion
level:30
weight:4
cost:8000
alloc:30:30 to 100
pile:10:2
effect:END_INFO
msg_self:Blablabla...

This dummy potion just displays a message without doing anything else.
