### ISSUE TITLE
LOSE_EXP, CURSE_ARMOR and other effects

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#122]
Please could you put LOSE_EXP effect back? 
`EFFECT(LOSE_EXP, false, NULL, 0, EFINFO_NONE, "drains {25%%} of your experience total")`
It's good to have it, as PWMA variants (like Tangaria) could use it in gamedesign. If PWMA don't need `Lose Memories potion` - such potion simply could be deleted from PWMA; but why to delete effect? It's could be used in loads of awesome traps and items.

I see that some other effects which are commented out in list-effect.h:

```
/*EFFECT(CURSE_ARMOR, false, NULL, 0, EFINFO_NONE, "curses your worn armor")*/
/*EFFECT(CURSE_WEAPON, false, NULL, 0, EFINFO_NONE, "curses your wielded melee weapon")*/
```
...while it's code still exist in effects.c :

```
/*
 * Curse the player's armor
 */
static bool effect_handler_CURSE_ARMOR(effect_handler_context_t *context)
{
    struct object *obj;
    char o_name[NORMAL_WID];
.....
```

Lets return them too? Simply uncomment curse flags in list-effect.h and voila! I'll be glad to use this feature!

I could compile PWMA with this features myself, but then it will be a hassle to recompile it with every new PWMA update; so I really like to stay on 'pure' PWMA, without compiling my variant.

**Comment by draconisPW** [comment]
Effects are back.
