### ISSUE TITLE
Edit keymaps to '%'

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#123]
/rfe 
Assign ('=' → 'k') to '%' key. 

It's quite annoying to get to the macro through options... I still can't get used to it after a year of PWMA. Macroes it's the most frequently used game option, it will be fun to get there really fast. It's often happening when you need to remacro something in dungeon and every second is precious... using =k is spending this second in vein :(

Current % (time) could be moved somewhere, like alt+t.

**Comment by draconisPW** [comment]
Alt cannot be used. And there are no room left for commands.

**Comment by igroglaz** [comment]
**?** → **a** shows a lot of empty keys:
j
n
H
N
O
X
Y
Z
^B
^H
!
^K
^N
^T
^U
^V
^Y

What about ^H (hour) or ^T (time)?

**Comment by draconisPW** [comment]
All these keys are used in roguelike keyset. Basically we're out of commands at this point. Once V adds a new command, we'll have to make another menu to group some.

**Comment by igroglaz** [comment]
Some temparary workaround:
1) show time at players menu '@' (so if player will puish '@' he will see there time and date).. or other screens, for example '`' (current knowledge)
2) show time at 'l' → 't' (look -> time.. or l -> w: look -> watch); so player will be able to trigget time by looking command
3) add /command to show time (`/t` will do goot, as shortone)
4) move time to options screen (swap it with macroes)
