### ISSUE TITLE
unhardcode default client options at server

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#124]
After character creation server sends player file with it's options in \lib\user\<character_name>.prf

It will be fun to have this options unhardcoded, so server admin could edit their default values.. It could be server.prf file where admi could define default settings.

**Comment by draconisPW** [comment]
Don't see anything hardcoded here, and prf are client side.

**Comment by igroglaz** [comment]
Oh.. I got it, thanks. So I should put it on client at pref.prf file and it will work.
