### ISSUE TITLE
House Creation scrolls -> create new houses

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#125]
Found an old document by EvilEye - https://web.archive.org/web/20070824083733/http://mangband.org/documentation/mang/pernhouse.txt :

You may, if you are very lucky, find a scroll of House Creation. This is 
highly unlikely, but should you find one or buy one in the BM (Black 
Market - shop 7), you will want to know how to use it. Reading a scroll in
the wilderness will allow you to walk around, creating walls as you move.
You get 25 moves per scroll, and reading subsequent scrolls allows you to
add extra moves (still 25) to your current move counter. Moving 
diagonally, and running out of moves will cause your building attempt to
fail. Also, if another player is building, your attempt will fail (the
builders are on strike). Building around existing buildings is not 
permitted for security reasons - it will fail. Building upon moats 
belonging to houses will cause the spell to fail also.

A house may be built deliberately without a floor - a courtyard. All the 
grass, trees, water, etc. are kept just as they were. This can be done by 
inscribing the scroll (First scroll) with @F. Building subsequent houses
inside another house IS possible, even though building around existing 
houses is not.

WE NEED THIS SYSTEM! :D It's the super awesome.

**Comment by draconisPW** [comment]
House creation already exists. Since it's a complex system and I have no intention to change it, closing this.

**Comment by igroglaz** [comment]
Yeah, it sounds like a space-ship :) One day...
