### ISSUE TITLE
private players messaging

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#127]
I didn't find this in the guide; it seems it's not there. Low priority issue, but will fun to have it one day.

**Comment by draconisPW** [comment]
Already implemented. Just put in chat "playername:message" and it will display in green the message to that player. Using "party:message" also works. There are also "chat channels" (#) to make a "chat room" in game. By default, the channel used is #public.

**Comment by igroglaz** [comment]
Cool :D It should be in the guide (I'll add at website)
