### ISSUE TITLE
port V roll char stat randomly + server option

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#128]
I dream for a long time about random character generation parameters. It's truly RPG feature, which bring the spirit of oldschool dice-and-paper games.

And... Vanilla actually got it already - at their 'standart roller': you could re-roll your stats several time there.

/rfe
1) add third option for stat rolling - 'dice roller' (which works as in V)
2) add server.cfg option to make only one roller available (so server owner could enforce it's own ruleset, eg I would like for all player to rolls stats for raising roleplay spirit)
3) add server.cfg option to set number of attempts which you could use in dice roller generator.

Eg I would love to have 10 attemps to roll stats. At each attemp you could consider to stop and choose stats which you've got. But if you are unlucky - you just play with character which you've got :)

**Comment by draconisPW** [comment]
Sorry, but standard roller is stupid. For example, this was the only option available in games like Eye of the Beholder, and you could end up with a warrior with 3 strength or a mage with 3 intelligence. Basically, you waste half an hour making a character to enter the game and suicide and start over. This was also the case in early MAngband days when people simply spent almost an hour suiciding over chars before actually playing. This was a nonsense. For this reason, MAngband and PWMAngband now have the "standard roller" which allows to put 17 in the main stat, 15 in the second stat and 12 in the third stat, while keeping the others at decent value. This method of "internally rolling until you get decent char" is the standard now.
