### ISSUE TITLE
Time-bubble indicator should be more "responsive"

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#13]
I had a lot of other players feedback on this. Players do not understand when turn is ended at 'bubble' -> push keys, they queue -> char dies:

when time seizes - it's hard to understand when turn pass - **and which action would be performed next, which one is queued**. eg.
player is '1' life; monsters chasing him. Player drinks a potion and try to run further. Because of 'slow time' effect it's very hard to understand did your previous command worked or not. So you could cancel your previous action and not to drink potion, but run further.

Possible suggestions (variants):

1) to mark end of each turn in 'low hp mode' as red line, like
_**********************************_
in game messages window.

2) when player push any key while in 'low hp mode' - show this action as (queued) in game messages window. eg:

(**planned**) you are to drink a potions of cure light wounds

and when this action was completed, write it in game message window with yellow ink something like:

(**completed**) you finished your action queue

3) just write in 'messages' windows which action is queued and would be performed at next turn

**Comment by draconisPW** [comment]
MAngband has adressed this. See: https://github.com/mangband/mangband/issues/1329

**Comment by draconisPW** [comment]
First draft in bbc377b.

**Comment by draconisPW** [comment]
Not satisfied with the result. I need better indicator, especially at the end of turn.

**Comment by draconisPW** [comment]
Indicator reworked:
- when bullet time kicks in, switch immediately to bubble color (violet if playing with "numbers", white if playing with "hp_changes_color") and adjust blinking speed to half the normal speed (2 turns)
- when the player doesn't have the energy to act, blink normally
- when the player gains enough energy to act, blink much faster (visual clue about when to use commands)

**Comment by draconisPW** [comment]
Implemented in 32d2793.

**Comment by draconisPW** [comment]
This only works in ASCII mode. Now let's implement this indicator in tile mode!

**Comment by draconisPW** [comment]
Done in b49904d.

**Comment by igroglaz** [comment]
... Bubble indicator is still unrecognizable. Even I, with all my experience - do not 'understand' - when there will be a new turn if time slowed - I just ignore this blinking (as it doesn't say anything) and trying to 'feel' the turns.

Thi indicator should work like this:
1) player got low hp -> time slowed
2) hp number, eg '5' blinks one time.. then it blink 2 times fast.. then it blinks 3 times fast.. then new turn comes.

so - the player will see more intense blinking near the time when next turn will happens.

@flambard-took may also look into this idea

**Comment by igroglaz** [comment]
one player suggested to add to main UI turn counter (which already exist in 'C' screen)
