### ISSUE TITLE
Resurrect uniques after beating Morgoth?

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#132]
Idea from PernMAngband. I'm not sure about it, but it feels interesting. Maybe it could be implement as a server.cfg option? So we would be able to test it and to understand- would it be fun or not.

It feel like a rainbow after the rain... You kill everything and then again - you meet this uniques. Quite fun?

**Comment by draconisPW** [comment]
Seeing Sauron and co resurrect after beating Morgoth makes no sense. Sorry...

**Comment by igroglaz** [comment]
Hm, true. Maybe then exclude all `flags:FORCE_DEPTH` monsters from ressurection list?
