### ISSUE TITLE
Detect Monsters spell @ "L"

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#135]
I play without "big map" option and I need to "L" a lot (move my view between map sectors). Problem is that spell "detect monsters" dissapear when I move screen with "L". It makes quite bad playing experience cause I play without big_map and need to move my view around a lot.

/rfe 
save detected items when you move screen

I've reported this issue long time ago in TomeNET and it was fixed there eventually: https://tomenet.eu/phpBB3/viewtopic.php?f=9&t=911

**Comment by draconisPW** [comment]
This is indeed a big problem. I have no idea how to fix this, but this will have to be fixed at some point. Leaving this on "future" milestone for now, but it would be great to fix this for 1.6.0.

**Comment by igroglaz** [comment]
it seems you accidentally closed this issue by mistake

**Comment by draconisPW** [comment]
In fact this was pretty simple to implement: just added a boolean "locating" that is set when 'L' is pressed and unset when ESC is pressed and only decreased the timer on detection when not "locating". For the case when "pause_after_detect" is "yes", you can press 'L' to clear the pause and it'll start locating automatically.
