### ISSUE TITLE
option to show short-desc: in 'floor' at UI

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#136]
https://cdn.discordapp.com/attachments/596389778992398356/698421176296538112/hide-floor.png

add a client option:
1) to show `short-desc:` field in 'floor' at UI (it will be cutted to certain pount cause of size; but still better then names which I've got now, as I've 75% names in tileset I've got like `FC double 0`
2) if there is no `short-desc:` assigned - do not show anything in this field (make it blank)

**Comment by draconisPW** [comment]
Good idea

**Comment by draconisPW** [comment]
Done. But to stay consistent with V, if there's no short description, the name is still displayed.
