### ISSUE TITLE
Druid + 9 store = crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#138]
reproduce
enter with female human druid to 9 store

**Comment by draconisPW** [comment]
Game also crashes when entering the General Store.

**Comment by draconisPW** [comment]
Bug with Lightning Strike spell.

**Comment by draconisPW** [comment]
This is because the damage of the spell is (player level / 4)d4, which crashes the tooltip if player level is less than 4 (because zero damage). I've fixed this by simply adjusting the damage to (player level / 4 + 1)d4.
