### ISSUE TITLE
unhardcode admin equipment

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#139]
for testing purposes I need to create certain pre-defined items at my admin char; sometimes it's dozen times per day. making it through `&` command every time is hell.

/rfe
add somewhere in `.txt` list of items for admin char, eg
```
equip:....
equip:....
equip:....
...
```

**Comment by draconisPW** [comment]
Done. In PWMAngband, admins now also get a Rod of Recall.
