### ISSUE TITLE
macro suggestions to improve ergonomics

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#142]
right now to assign macro we need:
to start macro: 
= k d
// I've suggested to make = k as % there https://github.com/draconisPW/PWMAngband/issues/123 ; but in this ticket I wanna show other problems.

Then.....

1) we push a key // it's ok
2) now we have [ESCAPE]... this is problematic place. Because it's not possible at this particular point to push Esc or Enter - because game will think that we want use them in macro. BUT. It's much easier and more ergonomic to use \e and \n and to be able to cancel macro with Esc or approve it with Enter.. because pushing $ at the end - it's really not fun, as to push it we should use two hands.
3) also there is no need to ask 'Save this keymap?' - because it's just takes an excess acton on every macro. If user made mistake in macro - he could reenter it or just do not save macro to file and relauch client

/rfe , an example how it should be imho:
1) enter macro menu and push 'd' to create macro
2) push a key, eg F1
3) assign a command (at the beggining should be predefined escape key; the same way as it's right now, but not [escape], but \e; so it will be, for example:
\em1a
4) now user push Enter to finish creating macro
5) the end. he don't need to confirm anything.

This way use will need to make twice less efforts to macro a key

**Comment by igroglaz** [comment]
lets move time hotkey (%) to `/time` console comamnd.. so % will be macro hotkey. It will make macroing so much fun :D

**Comment by draconisPW** [comment]
Implemented just as above:
- '%' is back to "Interact with keymaps"
- time is displayed via the "/time" chat command
