### ISSUE TITLE
AI_ANNOY monsters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#143]
it will be fun to have monters which will be especially smart in terms of the distance, like AI_ANNOY monsters from TomeNET.. I suppose it's possible to use to create it on foundation of FRIGHTENED flag which works perfectly

**Comment by draconisPW** [comment]
Nope sorry, this is not TomeNET. AI_ANNOY monsters are plain stupid.

**Comment by igroglaz** [comment]
I think it's great to have more different AI types, just to make game more diverse. I also don't like too much AI_ANNOY (when a lot of monsters have it), but some 'flavour'-AI in certain monsters, seldom found - could be interesting
