### ISSUE TITLE
terrain flag to prevent dropping there when used stairs

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#146]
I've got a lot of floor terrain which is fun to use as walls too. But as I've got disconnected_stairs - player could be 'dropped' (when used stairs) inside of walls - on floor tile, which I've assegned as wall.

/rfe
add terrain flag which will prevent player to spawn after he used stairs, eg NO_STAIR

**Comment by draconisPW** [comment]
NO_STAIRS flag added
