### ISSUE TITLE
custom shop crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#147]
> 150420 031011 Light: You hit the Mountain Gorge's rock lizard.
> 150420 031011 Light: You hit the Mountain Gorge's rock lizard.
> 150420 031011 Light: You have slain the Mountain Gorge's rock lizard.
> 150420 031020 Light: There is a tree blocking your way.
> 150420 031021 Light: There is a tree blocking your way.
> 150420 031022 Light: There is a tree blocking your way.
> 150420 031022 Light: There is a tree blocking your way.
> 150420 031023 Light: There is a tree blocking your way.
> 150420 031026 Light: There is a tree blocking your way.
> 150420 031030 Light: There is a pile of rubble blocking your way.
> 150420 031032 Light: There is a pile of rubble blocking your way.
> 150420 031033 Light: There is a pile of rubble blocking your way.
> 150420 031034 Light: There is a pile of rubble blocking your way.
> 150420 031034 Light: There is a pile of rubble blocking your way.
> 150420 031035 Light: There is a pile of rubble blocking your way.
> 150420 031035 Light: There is a pile of rubble blocking your way.
> 150420 031036 Light: There is a pile of rubble blocking your way.
> 150420 031036 Light: There is a pile of rubble blocking your way.
> 150420 031037 Light: There is a pile of rubble blocking your way.
> 150420 031039 Light: There is a tree blocking your way.
> 150420 031039 Light: There is a tree blocking your way.
> 150420 031045 Disconnected from server...
> 150420 031045 Goodbye Light=Eugene@Eugene-PC ("Client quit")
> 150420 092223 Shutting down (panic save).
> 150420 092223 Server panic info save succeeded!
> 150420 092223 Unable to (re-)stock store 10. Please report this bug.

shop 10 is (AFAIU it's the one with certain info number):

```
name:Rinswind the Wizard
graphics:@:s
priority:18
################################################################################
short-desc:old man with bright blue eyes. He's a wizard it seems. No hat though
flags:SHOP | PROJECT | PASSABLE | PERMANENT | INTERESTING | EASY | VENDOR
info:10:0
desc:.
```

It's got:

```
store:Rinswind the Wizard
owner:5000:Rinswind the Wizard (Human)
owner:5000:Rinswind the Wizard (Human)
slots:0:4
turnover:1
#######################################################################
always:fortune cookie:Who are ya? What do ya need? Whaat? I can't hear 
always:fortune cookie:you.. *grumbles* They come.. and go.. come.. and
always:fortune cookie:sometimes not come back..
always:fortune cookie:*whipped up* So.. Can ya read? If you can't,
always:fortune cookie:I can't help ya.. But if you do - take a look at
always:fortune cookie:this finest books about miracles. With them you 
always:fortune cookie:would be able to conquer world!.. What?? 
always:fortune cookie:I can't hear ya!! Speak louder, yongster! Whaat?
#######################################################################
always:nature book
always:shadow book
always:psi book
always:elemental book
#######################################################################
normal:fortune cookie:*sings* Once I came to the land of dreams...
normal:fortune cookie:*sings* Three trolls.. In the forest of mourn..
normal:fortune cookie:*sings* Don ya tell me wat todo, little fairy..
normal:fortune cookie:Did ya know there is a secret passage nearby? shh
buy:nature book
buy:shadow book
buy:psi book
buy:elemental book
```

It happened tonight;  before updating PWMAngband 1.4.0 beta 2.. but as I checked Light is human/warrior, not a druid who was bugged :)

**Comment by draconisPW** [comment]
That store cannot work. You have 28 "always" lines which exceeds the capacity of the store (24).

**Comment by igroglaz** [comment]
there is 8 always dialogues:
```
always:fortune cookie:Who are ya? What do ya need? Whaat? I can't hear 
always:fortune cookie:you.. *grumbles* They come.. and go.. come.. and
always:fortune cookie:sometimes not come back..
always:fortune cookie:*whipped up* So.. Can ya read? If you can't,
always:fortune cookie:I can't help ya.. But if you do - take a look at
always:fortune cookie:this finest books about miracles. With them you 
always:fortune cookie:would be able to conquer world!.. What?? 
always:fortune cookie:I can't hear ya!! Speak louder, yongster! Whaat?
```

+12 (4*3) books:

```
always:nature book
always:shadow book
always:psi book
always:elemental book
```

+4 normal dialogues

Which is 24 in total. It means that the limit is less then 24, not equal 24, right?

**Comment by draconisPW** [comment]
This is also what causes the crash in #148.

**Comment by draconisPW** [comment]
Shop has:
- always:fortune cookie (8)
- always:nature book (3)
- always:shadow book (3)
- always:psi book (3)
- always:elemental book (5)

but you added:
- always:prayer book (3)
- always:magic book (3)

Total: 28

The mandatory rule for shops is number of "always" items + number of max normal slots in "slots:min:max" line should be <= 24. If it's more, the shop is incorrect. Since you have 4 max normal items, you cannot put more than 20 "always" items.

**Comment by igroglaz** [comment]
! This crush happened before I've added 

```
always:prayer book (3)
always:magic book (3)
```

I've added it just today when noticed that newbie book shop doesn't have this two books.

So crush happened exactly when it had, as I wrote in first message:

```
store:Rinswind the Wizard
owner:5000:Rinswind the Wizard (Human)
owner:5000:Rinswind the Wizard (Human)
slots:0:4
turnover:1
#######################################################################
always:fortune cookie:Who are ya? What do ya need? Whaat? I can't hear 
always:fortune cookie:you.. *grumbles* They come.. and go.. come.. and
always:fortune cookie:sometimes not come back..
always:fortune cookie:*whipped up* So.. Can ya read? If you can't,
always:fortune cookie:I can't help ya.. But if you do - take a look at
always:fortune cookie:this finest books about miracles. With them you 
always:fortune cookie:would be able to conquer world!.. What?? 
always:fortune cookie:I can't hear ya!! Speak louder, yongster! Whaat?
#######################################################################
always:nature book
always:shadow book
always:psi book
always:elemental book
#######################################################################
normal:fortune cookie:*sings* Once I came to the land of dreams...
normal:fortune cookie:*sings* Three trolls.. In the forest of mourn..
normal:fortune cookie:*sings* Don ya tell me wat todo, little fairy..
normal:fortune cookie:Did ya know there is a secret passage nearby? shh
buy:nature book
buy:shadow book
buy:psi book
buy:elemental book
```
