### ISSUE TITLE
Stores ambient sounds

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#15]
/rfe to add flag for ambience in different shops. So when you enter particular shop - you hear ambience sound there, eg bubling potions in '5', whispering prayer in '4' etc. Also tavern could have special flag for happy songs.

This feature was implemented in TomeNET a year ago and I've made my soundpack with ambience music shops. **Examples of stores sounds:** 
https://drive.google.com/open?id=1S0eaDollUJ9Ji3OuYiVFKu9sXhWkMoJt
(pass for archive is: _pwma_)

Config file:
ambient_store_general = ambient/persistent/store/general-store.ogg
ambient_store_armour = ambient/persistent/store/armour.ogg
ambient_store_weapon = ambient/persistent/store/Weapon_Smith01.ogg
ambient_store_temple = ambient/persistent/store/temple.ogg
ambient_store_alchemy = ambient/persistent/store/alchemy-sound440.ogg
ambient_store_magic = ambient/persistent/store/magic.ogg
ambient_store_black = ambient/persistent/store/bm-sound500.ogg
ambient_store_book = ambient/persistent/store/book-LOOPMAGI.ogg
ambient_store_merchants = ambient/persistent/store/bank.ogg
ambient_store_official = ambient/persistent/store/official-sound493.ogg
ambient_store_misc = ambient/persistent/store/etc.ogg

It gives entering shop really special feeling :) Like in oldschool RPG like Might&Magic 6

**Comment by igroglaz** [comment]
there is pretty useful search @github commits. it's easy to find ambient implementation at TomeNET: https://github.com/TomenetGame/tomenet/search?q=ambient&type=Commits

**Comment by draconisPW** [comment]
Variant territory.
