### ISSUE TITLE
multiple force-locations from monster

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#152]
eg I got goldfish which I wanna show in newbie location, in town and in some other early places. right now to be able to do so I had to create several monsters with different names (eg gold-fish, goldfishy, golden fish, etc) and assign for each one different location.

/rfe to be able to point several locs for monster:
force-location:Hunter's Valley | Farfest | Old Forest

this is a very minor issue; if it's hard to implement it, its totally alright to create several monsters, no worries

**Comment by draconisPW** [comment]
This will be perfect for me to remove mercenaries and veterans from Hobbiton so newbie players won't get killed by those when they leave the starting tavern.

**Comment by draconisPW** [comment]
Implemented.
