### ISSUE TITLE
some sounds don't play sometimes

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#153]
demo:
https://www.youtube.com/watch?v=rb-XhcbKuAM

some of problematic sounds (I didn't check all):
pls_man_ugh.mp3 (confusion!)
pls_tone_conk.mp3 (blindness!)
pls_man_gulp_new.mp3
pls_man_sniff.mp3

Not sure is this problem persist in game all the time, but still wanna report it just in case.

I've recorded new blindness/conf sound.. will include it in T package

**Comment by draconisPW** [comment]
I think it's because the sounds are too brief?

**Comment by draconisPW** [comment]
Sound file too short or unhearable or just small "clicks". I'll redo those.

**Comment by igroglaz** [comment]
if you wish, you could take my new sounds: https://github.com/igroglaz/Tangaria/tree/master/lib/sounds/t
for now it's blind and confusion.. I'm planning to record all the set.

**Comment by draconisPW** [comment]
I tested "pls_tone_conk" and it is indeed a small "tchunk". I used Audacity to listen to it and it works fine. The problem here is using Winamp which doesn't work so it's just a bug with Winamp. I'll rework the small sounds when I have time.

**Comment by draconisPW** [comment]
Normalize sounds and ensure they're at least 0.25s long.

**Comment by draconisPW** [comment]
Implemented in 1c92cda. Some sounds that were missing also got reimplemented. Now everything should be loud and clear.
