### ISSUE TITLE
CROWD_FIGHT progress

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#154]
it will be cool to add CROWD_FIGHT progress, eg

player-flags:CROWD_FIGHT[1+1d6]

eg, I've assigned CROWD_FIGHT to hydra's race. And when it's getting new head - it will be cool to increase radius of slash-attacks

**Comment by draconisPW** [comment]
Unfortunately, CROWD_FIGHT goes away with latest changes of blackguard.

**Comment by igroglaz** [comment]
please leave this flag existing in-game, even if classic PWMA won't use it :) its fun for hydra race
