### ISSUE TITLE
RAND_x player flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#156]
flag which work similar to monster's RAND_x - with certain chance to move erratically. for some player's races, it could be fun to assign RAND_5 or something like this to add some madness to gameplay :D

I suppose this effect could work similar to temp confusion eff, but with possibility to assign the chance of erratic movement

**Comment by draconisPW** [comment]
This would make anything unplayable sorry.

**Comment by igroglaz** [comment]
It will be playable and will add some flavour to certain Tangaria races.
