### ISSUE TITLE
cancellation of certain property on player

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#157]
eg I wanna disable monk levitation for certain races, eg hydra.. cause flying hydra is really stupid :D
So it will be fun to have some kind of 'cancellation' flag, eg

obj-flag:20:FEATHER[X]

which will mean that this property will be cancelled at lvl 20

**Comment by draconisPW** [comment]
You cancel the property and then go to the store and buy a ring and your hydra still flies...
Need to change that to a flag which counters the property. Could be done if flags get un-hardcoded.

**Comment by igroglaz** [comment]
"You cancel the property and then go to the store and buy a ring and your hydra still flies..."

but it won't be it's innate race ability.. in the nature hydras don't fly :) but magic could give them this property, of course.
