### ISSUE TITLE
crush on opening chest

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#158]
190420 140904 Tangar: There is a wall in the way!
190420 140904 Tangar: There is a wall in the way!
190420 140904 Tangar: There is a wall in the way!
190420 140904 Tangar: There is a wall in the way!
190420 140904 Tangar: There is a wall in the way!
190420 140912 Tangar: There is a wall in the way!
190420 140913 Tangar: The blue jelly (offscreen) wakes up.
190420 140914 Tangar: You have discovered a trap on the chest!
190420 140915 Tangar: You set off a trap!
190420 140915 Tangar: A small needle has pricked you!
190420 140915 Exception 0xC0000005 at 0x4CA58C
190420 140915 Shutting down (panic save).
190420 140915 Server panic info save succeeded!

**Comment by igroglaz** [comment]
I've sent save folder via discord PM for debugging

**Comment by draconisPW** [comment]
This stupid bug is now fixed...
