### ISSUE TITLE
DRAIN_EXP degrades character attack at lvl 1

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#159]
if DRAIN_EXP will lead your character to lvl 1 - it will have degraded to-hit parameter.

demo: https://youtu.be/7Fyobs0VTl8?t=902
(to compare and test it I've created two equal hydras, with the same parameters. but hydra which came out of dungeon (where she had her lvl lowered from 5 to 1) - had negative parameters of to-hit

**Comment by draconisPW** [comment]
Not a bug. Penalty to hit was not the result of drain exp... but simply because the char was hungry!

**Comment by igroglaz** [comment]
I'm stupid bastard :chicken: Will add it to the guide.. and also record sound for becoming hungry
