### ISSUE TITLE
rework colors in ASCII

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#16]
Current PWMA colors
https://cdn.discordapp.com/attachments/635431079154548746/637916442037059594/colors.jpg

1) some colors are duplacates, eg:
yYM
PVI
pvi
tZ
Tz

2) some colors are wrong, eg:
3o - isn't orange

3) it would be fun to rearrange then in proper order:
http://9go.ru/wp-content/uploads/2019/10/color-line-rainbow.jpg

The only problem - that current colors are bind to terrain and monsters... Maybe better just to add newly ordered colors after existing ones?

4) to add new colors, eg brown

5) add reference to _= v c_
about commands.. (n/N/k/K....)

6) add reference to 'dump color' file, generated with _= v b_

it's got format:
_Color: Dark_
color:0:0:0:0:1
.....
_Color: Deep Light Blue_
color:27:0:0:176:255

------

I suppose the easiest way is to assign rgb color numbers not in-game via (n/N/k/K....)-tool but in prf file

**Comment by igroglaz** [comment]
I found this color chart (~120 colors) - with special list of colors suitable for black background, with rgb codes:
http://www.tedmontgomery.com/tutorial/clrctgBL.html

It could be main pallete; it's in right order (from red to violet).

As our maximum is 256 colors, we would still have a lot of empty space for future additions (eg for future flickering colors like in [tomenet](https://tomenet.eu/guide.php?chapter=2.5a&highlight=Animated%20(flickering%20in%20multiple%20hues)#r82)

**Comment by igroglaz** [comment]
I've found even better solution - official X11 colors chart (138 colors). I put it in right order ('rainbow') at my website:
http://skobki.com/tablitsa-tsvetov-x11-v-pravilnom-poryadke/

It's better then chart in previous link, because I'm not aware about origin on color chart from 1st link.. And this is X11 - official pallet which used all over the web :)

**Comment by draconisPW** [comment]
Closing this as won't fix. The GCU port uses 16 colors, there is no way to increase that number. Since the game uses 28 colors, there will be duplicates, nothing can be done about it, it's just a limitation of the console.

**Comment by igroglaz** [comment]
As GCU is currently unplayable due https://github.com/draconisPW/PWMAngband/issues/18 this bug, maybe it could be dropped? 

So there would be left only mangclient.exe and mangclient_sdl.exe... Or mangclient_gcu.exe and mangclient.exe - it's the same thing?

**Comment by draconisPW** [comment]
GCU client is kept for use with Necklace of the Eye frontend. It should not be used as standalone, there is no reason for it.

**Comment by igroglaz** [comment]
Could we keep GCU at 16 colors, while use 256 colors in other clients? Like to have legacy 'layer', like in enhanced terrain

**Comment by flambard-took** [comment]
> GCU client is kept for use with Necklace of the Eye frontend. It should not be used as standalone, there is no reason for it.

Maybe not on Windows, but for UNIX users it's still a viable option.

**Comment by igroglaz** [comment]
Yep, not I see, that GCU is important. But still 

> Maybe there is a workaround with keeping GCU at 16 colors, while use more (27? as V has?) in other clients? To have legacy 'layer' for GCU, and advanced for other clients (like in enhanced terrain).

**Comment by igroglaz** [comment]
in FrogComposband 7.1.salmiak devs introduced 32 color:

```
* Moved to a 32-color palette and changed the colors of many monsters
-- NOTES: If your platform does not support more than 16 colors, or FrogComposband's coloring code for your platform is faulty, compile with --disable-xtra-colours to retain use of 16 colors only. If your platform does support more than 16 colors but you wish to stick to 16 (from nostalgic reasons or for greater contrast between colors), load user-lim.prf (typing &4 in-game does this automatically) or otherwise modify the colors with the '&' command
-- Special thanks to Oneiron for helping me debug the 32-color palette

```

Maybe we could also add it with having option for old display?
