### ISSUE TITLE
start with less satiation

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#160]
Atm new char starts with 89 % satiation, which makes hard to drink potions for ID and actually just drink any healing pots, as y immediately become slowed cause of gorged.. and it take AGES to get rid of gorged status

/rfe new char start with 70% satiation

**Comment by draconisPW** [comment]
Gonna be adjusted in V. Waiting to port that change.

**Comment by draconisPW** [comment]
Adjustments from V: digestion effects reduced from x5 to x2 + added mushrooms of purging in General Store. Closing this as I'll implement those changes.

**Comment by igroglaz** [comment]
Satiation for new char is still a problem. Please could setting of 70% satiation (or even 60%) be setted for new character?

**Comment by draconisPW** [comment]
Let's try with 80% and see how it works.

**Comment by igroglaz** [comment]
I've checked new git build on server; new chars still start with 89%

**Comment by draconisPW** [comment]
Must be reset elsewhere before entering the game.

**Comment by draconisPW** [comment]
In fact, the "timed" value is 100 times the percentage, so we should subtact 1000 and not 10 to make it 80%.

**Comment by draconisPW** [comment]
Fixed and working.

**Comment by igroglaz** [comment]
I've tested 80%
```
    /* Always start with a well fed player */
    p->timed[TMD_FOOD] = PY_FOOD_FULL - 1000;
```
it's still too much as one of first potions which you could find is Slim Mold juice.. and some other also increase satiation.. So I had to rest a bit to loose satiation. I suppose starting with 70% satiation will fix the issue one and for all

**Comment by draconisPW** [comment]
Players now start with 70% satiation.
