### ISSUE TITLE
allow race to have a curse

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#161]
some curses are non-fatal, but actually interesting. it will be fun for some races to have them, eg
curse:siren:100
curse:hallucination:100
curse:teleportation:100

the cool thing about curses that they are not constant, as just plain properties. so siren curse is much less dangerous then obj-flag:1:AGGRAVATE
so, for example, Tangaria's version of hydra could have it instead of aggravate

**Comment by draconisPW** [comment]
Those are worse than aggravation because aggravation is permanent and you know what to expect. Curses are fine on objects because if you don't like them you can remove them. Playing a race which randomly teleports or get hallucinations or whatever would be impossible.

**Comment by igroglaz** [comment]
1) it will be pretty playable for powerful race.
2) it will be MUCH easier than playing with perma-aggro
3) ..and it will be much more exiting experience as player will have to solve interesting gameplay situation -> game become less boring.

it will be great to allow this flag, if it's not too hard to implement.

**Comment by igroglaz** [comment]
please, please, please... consider to look into possibility to assign curses to race/classes. It will give MUCH more possiblities for customization because of time:1dx system there. It's not only about existing curses, but also about new ones

**Comment by draconisPW** [comment]
Ok keeping this for future reference, although I'm not sure how it would be feasible.
