### ISSUE TITLE
unhardcode invisibility

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#164]
based by class:
```
effect:TIMED_INC:INVIS:0:5
dice:$B+1d20
expr:B:PLAYER_LEVEL:+ 20
```

I wanna add act on artifact:
```
act:INVIS
dice:$B+1d20
expr:B:PLAYER_LEVEL:/ 2
time:500+d500
```

```
190420 231700 Initializing DM starting items...
190420 231700 Initializing artifacts...
190420 231700 Parse error in artifact line 163 column 1: dice: undefined directi
ve
190420 231700 Parse error in artifact line 163 column 1.
```

**Comment by draconisPW** [comment]
You're doing it wrong. In activation, add:

name:INVISIBILITY
aim:0
power:10
effect:TIMED_INC:INVIS:0:5
dice:$B+1d20
expr:B:PLAYER_LEVEL:+ 20
desc:makes you invisible for a short duration

In artifact:

name:of Foo
...
act:INVISIBILITY
time:80+d80 (adjust cooldown here)

**Comment by igroglaz** [comment]
thanks! :bear:
