### ISSUE TITLE
dragon race: accidentally breath on monsters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#165]
as there were discussion recently in discord about chaos dragon breath... which is very fun, but actually player could just do not breath at enemies and enjoy dragon resistances. it's np, but it could be really fun to make dragons breath their element sometimes automatically on their attack. make it very slim chance, eg 1%.. still it could bring some fun

It could be additional field in dragon_breed, eg:

`# info:commonness:experience factor:immune:chance to breath`

so some dragon could be more fierce than others and breath more often :) eg power dragon now could be easily rabalanced:

#dragon:power:0
#wyrm:Power:1
#info:1:200:0:10

--
maybe this way it will be possible to rebalance some dragons to make them more equal to each other (in terms of players preference).. to make `weakiest` dragons more obedient; while powerful will be more fierce and less controllable

**Comment by draconisPW** [comment]
Too silly sorry.

**Comment by igroglaz** [comment]
it's great idea :( it's a pity that you don't like it.

**Comment by igroglaz** [comment]
without the way to rebalance OP dragons - getting good breed is, like Nemo-The-Axolotl said: 

> Must be some kind of lottery winning easy mode then
