### ISSUE TITLE
property which forbids to move diagonally

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#168]
just an idea, not a /rfe really.. just in case if you like it:
1) there could be monsters which can not move diagonally (which is interesting property if added with eating walls).
2) an item property which forbids player to move diagonally. Could be a curse or just a property for a VERY heavy armour... as it could be hellish hard to move in heavy armour with a precise angle :)

**Comment by draconisPW** [comment]
And a property to make a character moonwalk. And one to move on one foot. LOL.

Replace "diagonally" by northwest/northeast/southeast/southwest. This is stupid, there's no reason to prevent that...

**Comment by igroglaz** [comment]
One of the most important thing in rlg is positioning and movement over grids, so such mechanic could be very insteresting and not stupid at all. But I hear you :)
