### ISSUE TITLE
FLOOR_SAFE does not prevent townies to spawn

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#169]
FLOOR_SAFE do not prevent townies to spawn

eg on this tile:

```
name:wood floor 0 bed
graphics:::s
priority:18
flags:LOS | PROJECT | PASSABLE | FLOOR_SAFE | BORING | OBJECT | EASY | BRIGHT
################################################################################
short-desc:bed
desc:.
```

 you could reproduce it with https://github.com/igroglaz/Tangaria (just enter and leave location and at certain point animals will appear in tavern)

my safe tiles are the same as in PWMA:

```
name:safe floor
graphics:.:w
mimic:open floor
priority:16
flags:LOS | PROJECT | PASSABLE | FLOOR_SAFE | BORING | OBJECT | EASY | BRIGHT
```

**Comment by igroglaz** [comment]
the only difference is constants:
# Number of townsfolk generated in the day */
#4
mon-gen:town-day:32
#8
# Number of townsfolk generated in the night */
mon-gen:town-night:64

**Comment by draconisPW** [comment]
FLOOR_SAFE is only tested when a monster moves and not when it is created. Currently, we only prevent mobs from getting generated in rooms and the only FLOOR_SAFE areas are houses and tavern which are also rooms. Need to add check on monster creation.

**Comment by draconisPW** [comment]
Fixed.
