### ISSUE TITLE
Dark blue color in GCU client

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#17]
Race/class/name in ASCII client in dark blue non-readable:
https://i.snipboard.io/S9ofm8.jpg

maybe it should be in D color

**Comment by igroglaz** [comment]
Also from the guide:

> 2.3.1.2   Dark monsters are hard to see
> Fix (reduce) the alpha on your screen, or use the "Interact with colors" screen under the options (=) menu. Navigate to the 8 using n and increase the color intensity with r(ed)/g(reen)/b(lue).

There is a problem with dark blue color in ASCII client. TomeNET got special option for use .ini file:

> ; - Use lighter 'dark blue' colour to increase readability on some screens
> LighterDarkBlue=1

Maybe we should add such option too.

**Comment by draconisPW** [comment]
GCU client uses 16 colors and doesn't allow to change colors, this means the only option is to redistribute the colors if the "dark blue" option doesn't fit. I'll go the same route as TomeNET: add a LighterBlue option in the INI file which will switch dark blue to light blue (which is already a quite dark color) and light blue to teal.

**Comment by draconisPW** [comment]
Implemented in fb02b12.
