### ISSUE TITLE
assigning doors in dungeon.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#170]
it will be great to be able to assign custom doors for different dungeons, so it will be:
floor:
wall:
door:

**Comment by draconisPW** [comment]
Good idea.

**Comment by draconisPW** [comment]
I've implemented this, but there is a "small" problem... when you open such door and close it, it becomes a regular door again.

**Comment by draconisPW** [comment]
I've added a new system to save the door feature when opening a door so that when the door is closed the saved feature is used. This means server savefile is incompatible and should be wiped before updating.
