### ISSUE TITLE
server option: gold drop on early levels

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#171]
new gold income on early levels is way too generous and game become too easy IMHO. Previous drop (when gold drop was reduced till -250 ft) was perfect to me.

I suppose it's this recent feature:
_Unnerf no_selling gold drops on early levels_

please could you add a server option to mangband.cfg LEGACY_GOLD which will have previous way of gold drops

**Comment by draconisPW** [comment]
I'll add an option for gold generation with multiple choices:
- Vanilla way (which imo is too generous early on and not enough later on since gold drops are the only income you get with no selling)
- old way
- new way which will linearize drops
Testing will be needed for the third option to balance things.

**Comment by igroglaz** [comment]
Thank you! When it will be released, I'll make tests of new linear drop asap. If it's better than legacy way, I'll stick with it... but I just can't imagine something better than it was before :bear:

**Comment by draconisPW** [comment]
Implemented as GOLD_DROP_NOSELLING. Setting GOLD_DROP_NOSELLING = 0 (default) will use current system (no_selling multiplies by 5). Setting GOLD_DROP_NOSELLING = -1 will use old system (no_selling multiplies by 5 starting from 250ft). Setting GOLD_DROP_NOSELLING = positive value will use a linear progression (multiplies by value * depth / 100, so setting to 10 will give same value at 2500ft, up to twice more gold at 5000ft and only basic value at 0ft).
