### ISSUE TITLE
flag to prevent monster spawning on tile

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#173]
with NO_STAIRS now we can use a lot of 'floor' tiles as 'walls' which is great. but there is a problem - some monsters now appears inside of 'walls':
https://cdn.discordapp.com/attachments/662334347163992104/704601417725509662/Screenshot_3.png

I've tried to remove OBJECT flag, but it didn't help (it seems it's used for items generation?)

/rfe add terrain flag which prevents monster spawn

**Comment by draconisPW** [comment]
Beta 5 fixed townies being generated on FLOOR_SAFE terrain. I'll revert that change and instead of using FLOOR_SAFE for monster generation I'll use a new NO_MONSTERS flag.

**Comment by draconisPW** [comment]
Implemented. I prefer this method, as it allows to have tiles that don't allow monster generation but allow generated monsters to walk on them. FLOOR_SAFE tiles are fine, as all of them are used in rooms thus mobs are already never generated on them.
