### ISSUE TITLE
add `closed door` and `broken door` flags to dungeon.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#175]
following https://github.com/draconisPW/PWMAngband/issues/170 : custom doors looks great :) but sometimes broken/open doors appears off-theme of dungeon.

/rfe
add closed door and broken door flags to dungeon.txt

**Comment by draconisPW** [comment]
First pass at implementing this:
- feat_save removed from square
- change door lines in dungeon.txt as "door : closed door feat : open door feat : chance"
- use above feats for open/closed doors in dungeons
- toggle between the two when opening/closing doors

Didn't have time to handle broken doors, will do later.

**Comment by draconisPW** [comment]
Implemented custom door skins for door mimics so they don't reveal themselves by being out of theme in the dungeon.

**Comment by draconisPW** [comment]
Custom broken doors implemented.
