### ISSUE TITLE
SDL client missing letters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#176]
SDL client got missing letters in new version; while other clients are alright

**Comment by draconisPW** [comment]
?

**Comment by igroglaz** [comment]
https://i.snipboard.io/OdKpHR.jpg

**Comment by draconisPW** [comment]
The only thing I changed in the SDL client has been to replace an occurence of strncpy by my_strcpy (that was part of a V commit), maybe I made a mistake, need to check.

**Comment by draconisPW** [comment]
Yes, my_strcpy cuts at "len - 1" not "len" so it was cutting all the last character in strings. This is now fixed.
