### ISSUE TITLE
expand character creation screen

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#177]
> if character screen will have information about stats gain, eg STR[-8+1d3] it will be easier to comprehend race progress for new players

> [16:16] PowerWyrm: because if you see -8 to str you will think "this is bad for warrior", if you see -8 then +1 every 3 levels this means you'll be good at level 24

> [19:30] flambard: just my 2cents: the notation STR[-8+1d3] confuses me a lot, I'd read it as "you get -8 AND maybe 1d3 during birth", not "every level".

> [19:53] PowerWyrm: currently we get detailed info by pressing "?" on the race or class, I can add the same system for stats and abilities

**Comment by draconisPW** [comment]
Added "!" option on character birth screen to show race/class stat gains.

**Comment by draconisPW** [comment]
Added abilities to the "!" option, should be complete now.
