### ISSUE TITLE
custom stairs, rubbles in dungeon.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#178]
following custom dungeon doors ( https://github.com/draconisPW/PWMAngband/issues/175 ), it will cool to add also custom rubbles (common and passable) and staircases.

also this ticket could be connected to other 'stairs' ticket (indoor/outdoor stairs): https://github.com/draconisPW/PWMAngband/issues/101

**Comment by draconisPW** [comment]
Custom stairs added.

**Comment by draconisPW** [comment]
Custom rubbles added.
