### ISSUE TITLE
custom dungeon border in dungeon.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#179]
/rfe add possibility to assign custom dungeon border (permawall which 'surrounds' dungeon level), because regular 'white' wall border looks out of style in some dungeons

**Comment by igroglaz** [comment]
yet another cool thing if this custom borders will also replace perma-wall borders for walls. then dungeon will be fully themed...

so it's kinda flag for dungeon.txt:
permawall:..

**Comment by draconisPW** [comment]
I've implemented this but there is one problem left: the fake permawalls used for pits/nests. These are used to fool players so they don't instantly recognize pits when they walk around them and make them think it's just a room.

**Comment by draconisPW** [comment]
Also this will fix fake permawalls having wrong color after the change of color for granite walls.

**Comment by draconisPW** [comment]
Done.
