### ISSUE TITLE
[bug] GCU client sometimes doesn't react on keys

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#18]
When I tested ascii in gcu client - I found that it glitches keybindings sometimes. Just try to run around for a while with shift and you'll see it. When you move to certain direction - char doesn't react to your keyboard sometimes. Other clients doesn't have this trouble

**Comment by draconisPW** [comment]
This is a known issue, along with some graphical glitch (misaligned symbols), in PDCurses. If I have time, I'll try to compile PDCurses 3.9 (PWMAngband is currently using PDCurses 3.4) and see if it changes anything, but I doubt it.

**Comment by igroglaz** [comment]
It's not critical, as there is a SDL client which is also could be used for ASCII :)

**Comment by draconisPW** [comment]
Can't get PDCurses 3.9 to compile so closing this as won't fix.

**Comment by igroglaz** [comment]
@flambard-took please, maybe you could look into this issues as GCU is Linux stuff ;)
