### ISSUE TITLE
magma/quartz vein flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#181]
atm quartz/magma veins 'streams' generated by default, without any flags, eg:
https://cdn.discordapp.com/attachments/662334347163992104/707565746200248400/Screenshot_1.png

It seems they are hardcoded and applied for any dungeon.

/rfe add flags for 'rock' veins, which will be like
`#DF(ROCK_VEIN, "May have quartz or magma streams")`

Then it will be possible to have dungeon without any streams in it (which is good in some cases, like in Mount Doom dungeon in screenshot above)

**Comment by draconisPW** [comment]
Added DF_STREAMS flag to all dungeons but Mount Doom.
