### ISSUE TITLE
SAND_VEIN glitch

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#182]
SAND_VEIN works only if it's the only flag for dungeon; eg there:
```
name:The Orc Cave
wpos:1:1
min-depth:4
max-depth:12
max-level:10
flags:SAND_VEIN | CIRCULAR_ROOMS | WATER_RIVER
```
...sand veins won't appear

**Comment by draconisPW** [comment]
Can't reproduce. SAND_VEIN works perfectly for me in any situation.

**Comment by igroglaz** [comment]
Damm rng.. It seems I was really unlucky when tried it and had several levels in row without sand (as it's generated not all the time). I've retested it and got sand :) Sorry for wrong alarm
