### ISSUE TITLE
DRAIN_EXP flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#183]
Currently DRAIN_EXP lower player leves. It gives problem with levels brackets for dungeons - as any player could drop his levels to be able to visit and grind low lvl dungeon

/rfe make DRAIN_EXP to do not drop exp below current level

**Comment by igroglaz** [comment]
but it gives potential problem with nazgul rings at end-game.. when player will reach lvl 50 - he will be safe to wear any drain_exp item.. not sure yet, how to fix it..

**Comment by igroglaz** [comment]
btw in TomeNET there is a new feature: https://github.com/Tokariew/tomenet-guide/commit/532932bb1f7db402ee46dff2a8bd79e87f4699ec :
getting Unlife and Necromancy are at 50.000 gives immune to experience drain, including the permanent drain effect from DRAIN_EXP items.

We need to think about exp_drain..

**Comment by draconisPW** [comment]
DRAIN_EXP now only works when the player is not idle. It is just an annoyance since the lost exp can be regained with potions of restore life levels.

**Comment by igroglaz** [comment]
There is a problem that DRAIN_EXP ruins concept of brackets for dungeons (limits on which player could visit certain dungeon) - as any player could drop his levels to be able to visit and grind low lvl dungeon

I do not know how to solve this problem in T, so I simply disable this property in gamedata :( Ideas are welcome

**Comment by igroglaz** [comment]
Also there are nazgul rings (hardcoded?), so I can't simply remove this property.. So I've replaced drain_exp with aggro at object_property.txt..

**Comment by igroglaz** [comment]
Even if drain_exp won't give possiblity to drop player below his current level - still it gives possibility to stay at one particular level for eternity.

Although maybe if drain_exp will _always_ go together with aggro property - maybe it won't be too bad?
