### ISSUE TITLE
'B'ash door

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#188]
it seems we do not have 'B'ash door command (shift+B). It's fun to have it as it give possibility to deal with locked doors for characters who are bad at disarming (eg T's hydra)

**Comment by draconisPW** [comment]
Bash door was removed a while ago as there are no more jammed doors. It is always on.

**Comment by igroglaz** [comment]
> It is always on.

What do you mean?

**Comment by draconisPW** [comment]
Opening a locked door always removes one "tick" to the "locked" count as if the @ was trying to bash the door until the door opens (or breaks).

**Comment by igroglaz** [comment]
I see, thanks. I'll add it to the guide.
