### ISSUE TITLE
number of stairs for specific dungeon

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#189]
it will be fun to be able to customize in dungeon.txt number of staircases in dungeon. Right now it's possible to assign it in dungeon_profile.txt, but not for a specific dungeon. Number of stairs is one of the most critical stuff in dungeon customization - as newbie dungeons should have more staircases (so it will be easier to dive for certain classes which are able to lvlup fast, eg warrior), while end-game dungeons should have less. Playing early-powerful class is quite boring atm as it's super boring to find staircases to go down fast...

This ticket connected with https://github.com/draconisPW/PWMAngband/issues/180 in certain way...

**Comment by igroglaz** [comment]
This is yet another very important issue which influence a lot of new players. To improve new players experience, we need to increase numbers of stairs in first dungeons.

**Comment by igroglaz** [comment]
please could you take a look at this issue :) it will improve new player experience a lot!

**Comment by draconisPW** [comment]
Implemented in next beta. For example: "stairs:1d2:2+1d2" will add 1d2 stairs up and 2+1d2 stairs down on any level for that dungeon.
