### ISSUE TITLE
MD negative value

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#190]
hydra with
`skill-device:-50`
have 83% chance for success with cure light wounds staff, as in character sheet (shift+C) hydra got 0 at MD.

/rfe allow negative values in MD

It will help to rebalance certain powerful races which will have additional bonuses, but won't be able to use MDs.

**Comment by igroglaz** [comment]
My archer lvl 38 got 64 MD.. chance to use Staves of Speed is 90%.. it's pretty imba. and it's the same even for really stupid races and non-magical classes.. while it should be ~30% for certain classes/races.

**Comment by draconisPW** [comment]
No idea what to do there. The V formula is complex and makes no sense to me. Feel free to discuss on V forums. For now I won't change anything.

**Comment by igroglaz** [comment]
http://angband.oook.cz/forum/showthread.php?p=151379

**Comment by draconisPW** [comment]
Keeping this for future reference, let's see how V handle this.

**Comment by draconisPW** [comment]
The formula has been changed in V, I'll implement it when porting the latest changes after the FEW_ENTRANCES overhaul.

**Comment by draconisPW** [comment]
The V change has been implemented.
