### ISSUE TITLE
wild_feat 1/10000

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#191]
allow wild_feat.txt customization up to 1/10000 for:
`# chance : index : terrain feat : chance of generation`

cause atm it's 1/100 max

**Comment by igroglaz** [comment]
Maybe it's also possible to remove 'index' field from there? to make it like dungeon.txt

**Comment by draconisPW** [comment]
Adding a 4th (optional) parameter (1-99) to represent 1/10000 chance:
"chance:n:feat:x:y" is now 1/100x+y chance (for example: 1:50 means 1.5% chance, 0:7 means 0.07% chance)
