### ISSUE TITLE
having more than 5 entries in wild_feat.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#192]
having more than 5 entries in wild_feat.txt , eg

```
name:grass
feat:5:grass:,
chance:0:floor 0 grass:20
chance:1:floor 1 grass::20
chance:2:floor w grass:20
chance:3:A5 plants I:38
chance:4:flower 0 green:1
chance:5:tree H:1
sound:WILD_GRASS

```
server won't start:

> 
> 110520 112435 Game Restarted
> 110520 112435 Initialised exit save handler.
> 110520 112435 Dungeon Master Set as [admin]
> 110520 112435 Timer delay 13 ms timer resolution is 1 ms
> 110520 112435 Initializing constants...
> 110520 112435 Initializing projections...
> 110520 112435 Initializing timed effects...
> 110520 112435 Initializing player properties...
> 110520 112435 Initializing features...
> 110520 112435 Initializing wilderness feats...
> 110520 112435 Parse error in wild_feat line 57 column 4: : invalid value
> 110520 112435 Parse error in wild_feat line 57 column 4.
> 

reproduce: https://github.com/igroglaz/tangaria (player's houses location)

**Comment by draconisPW** [comment]
Yes it's hardcoded with 5 max.

**Comment by igroglaz** [comment]
#define TERRAIN_TYPE_MAX    5
