### ISSUE TITLE
NPC dialogues limit

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#193]
recently I've added 'random' song to Mr. Underhill (in tavern)... it has 65 strokes. And it seems it's overflow certain limit, several NPCs got now got wrong 'normal' cookies

Reproduce: https://github.com/igroglaz/tangaria
1) speak with Rose (little girl, Erkenbrand granddaughter, `General Store` vendor: 
https://cdn.discordapp.com/attachments/662334347163992104/709337393982996500/1.png

2) she got wrong dialogues from `Old guard Barry`:
https://cdn.discordapp.com/attachments/662334347163992104/709337405026598922/2.png

3) now if I delete all new strokes from Mr. Underhill, like this (both in store.txt and object.txt):

```
store:Mr. Underhill
owner:5000:Mr. Underhill
owner:5000:Mr. Underhill
slots:0:1
turnover:1
#######################################################################
normal:fortune cookie:There is an inn, a merry old inn
buy:flask
```
...then Rose got right dialogues.

**Comment by draconisPW** [comment]
tval and sval are limited to 255 and there are more than 255 fortune cookies...

**Comment by draconisPW** [comment]
Dang even in V they use integers and we're still using bytes... I need to review the WHOLE code and increase the size of tval/sval from "byte" to "u16b".

**Comment by draconisPW** [comment]
Fixed. Since tval and sval are core fields, this change made savefiles of course incompatible and will require a full wipe of server.
