### ISSUE TITLE
custom rubble created among walls

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#194]
dungeon.txt custom rubble created among walls, not among floors...

`rubble:grass mountain e rubble:grass mountain f passable rubble:10000`

reproduce: https://github.com/igroglaz/tangaria Old ruins dungeon (newbie dungeon)

**Comment by draconisPW** [comment]
Not a bug. Your walls are missing the WALL flag. All walls should have the WALL | ROCK flags, the only features only having the ROCK flag should be rubble.

wall:obj_grass2 f:300

name:obj_grass2 f
graphics:#:s
priority:18
flags:TORCH | BORING | ROCK (missing WALL flag)
