### ISSUE TITLE
monster's dying on spawn in water

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#196]
I've noticed that some monsters dying from drawning when I enter to levels with water with admin char.. I suppose they spawn at water spots cause there is no 'NO_MONSTERS' flag - and as they won't allowed on such spots - they die..

maybe it will be right to prevent monsters from spawning on water spots, so only 'aquatic' monsters will spawn there.. I'm not sure about it, what do you think?

**Comment by draconisPW** [comment]
Also happens on lava tiles in Mt Doom, especially near vaults. I suppose it's due to not checking monster placement when generating escorts. I'll check this.

**Comment by draconisPW** [comment]
In fact this is a MUCH severe problem, as some monsters who "die" that way (from terrain) will be considered as being killed by another monster and drop loot on the square that is not suitable for drop. The game will process normally, but when you shut the server down and restart, you'll get a "corrupted savefile" message, as the item dropped cannot be placed again.

**Comment by draconisPW** [comment]
Placing monster correctly (not allowing placing on water/lava) STILL generates monsters on lava/water when it should NOT. Need to investigate this further as I don't understand yet why this is happening.

**Comment by draconisPW** [comment]
Ok I found the problem: streams (lava, water) are added AFTER vault generation, and monsters from escorts can be generated outside of the vault if there is no room inside. This means the lava or water tile is placed on top of monster and not the opposite. Easiest fix is simply not generate a lava/water tile if a monster that will be hurt by it is already present.

**Comment by draconisPW** [comment]
Finally found the "real" problem. In customize_features(), we replace floors with custom floors. For example, in Mt Doom, we have "floor:lava stream:1000". Then we have two problems:
- monster is generated on the tile and said tile is harmful (monster_hates_grid)
- object is generated on the tile and said tile cannot hold objects (square_isobjectholding)
In both cases, the tile should be replaced by some valid tile.

**Comment by draconisPW** [comment]
This is now fixed... I hope :)
