### ISSUE TITLE
NO_TELE_TO terrain flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#198]
noticed a problem in my ru-stream https://youtu.be/gkdpFIX85co?t=587

I teleport out to floor-walls and become stuck

/rfe add NO_TELE_TO flag - which prevents teleportation TO this specific terrain tile

**Comment by igroglaz** [comment]
this is pretty critical issue, as T atm quite uplayable for ranged classes; cause T got plenty of dungeons with F2W terrain (floors as walls) and you can't use there Phase Door properly

**Comment by draconisPW** [comment]
No need for a new flag. Let's say that NO_MONSTER is also true to players.

**Comment by draconisPW** [comment]
Fixed locally, I'll update Git after June 2.

**Comment by draconisPW** [comment]
Fixed in 8394ab9.
