### ISSUE TITLE
Show 'desc' of terrain instead of 'name'

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#20]
/rfe to make ASCII experience better - to add an option at server .cfg - to show 'desc' of terrain instead of 'name'

The problem:
with my _tiny_ tileset when player look at terrain objects (l -> p) it show objects names... and in tileset there are loads of objects with names like eg:
'obj_grass r provision'
'obj_grass s provision'
'obj_grass t provision'
this is 3 different graphical tiles. Or even worse names, like 
ED dirt a .... ED dirt z

so (l -> p) show such names, eg picture:
http://angband.oook.cz/forum/attachment.php?attachmentid=1711&stc=1&d=1554500129

Is it possible to implement: to show 'desc' field for 'look' command for terrain objects? so for example, when player look at obj_grass t provision, game would show this: _A pile of goods and provision._

it would be fun to show terrain objects description, cause it could show lore, eg

> name:obj_grass i graves
> graphics:::s
> priority:18
> flags:LOS | PROJECT | PASSABLE | TORCH
> desc:A tiny graves.. Looks like halflings buried there.
> 
> name:obj_grass c sealed portal
> graphics:::s
> priority:18
> flags:NO_SCENT | NO_FLOW | TORCH
> desc:A sealed portal. How to get inside?

This is especially useful for ASCII mode, cause in graphical mode player could at least see the object... And in ASCII 'l'ook at object is the only way to look around

**Comment by igroglaz** [comment]
1) there are several thousands of features and it's not possible to rename them, as I have todo it in 3 different files (terrain.txt, graf-tan.prf, town_feat.txt). If there would be 'desc' field used - only one file would be affected (terrain.txt)
2) also showing description with 'l' would give more text information and it's good for immersion and general RP feeling. Showing the name 'brick floor' when you look at object doesn't give player additinal MUD-style immersion, like it would be if he would 'l' on them and see:
_The floor is made of heavy stones which are very dark in color. Shadows lurk on it and almost seem to be moving as you look around yourself._ 

So ability to 'l' and see proper long description could give possibility to add new 'text' dimension to roguelike game. It could be agood start to this feature: **http://tangar.info/en/blog/roguelike-mud**

**Comment by draconisPW** [comment]
Adding a "short-desc" entry to terrain.txt to override the "name" in case it's a "code" and not a real "name". From now on, square_apparent_name() will return the "short desc" instead of the "name" if it's defined in terrain.txt and will display it via "l" + "p".

Reminder: to display the full description, use "l" + "p" + "r". This is already implemented and will not be changed.

**Comment by draconisPW** [comment]
Implemented in 7234348.
