### ISSUE TITLE
class/race brand for ranged attacks

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#201]
`brand:5:POIS_2` works only for melee attacks

there is 
```
spell:Poison Shots:5:1:10:4:0
effect:BOW_BRAND_SHOT:POIS
dice:5
desc:Covers your missiles with venom.
```
it will be fun to have brand type for class/race for ranged attacks (so it won't be a spell, but property)

**Comment by draconisPW** [comment]
Class brand will work on both melee + missiles. Race brand will only work for melee.

**Comment by draconisPW** [comment]
Implemented for beta 10.
