### ISSUE TITLE
manual gold rate assignment

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#204]
Currenlty we got:

```
# Option: method for generating gold drops for the NO_SELLING option.
# To use the classic method (constant factor of 5), set this to 0.
# To use the legacy method (constant factor of 5 starting at 250ft), set this
# to -1.
# To use a linear method (variable factor increasing with depth), set this
# to a positive value.
# (multiplies by value * depth / 100, so setting to 10 will give same value at 2500ft, up to twice more gold at 5000ft and only basic value at 0ft).
GOLD_DROP_NOSELLING = -1
```

I use legacy method, but it's still far from ideal, while linear method is too imba.

To have good possibility to gold income balance we need to create table with manual values - with it we will be able to find _perfect_ income balance.

To do so the most effective way is to have default value for drop x5 and then to be able to assing manual values for certain depths in config file. Right now I think that it's good to have this:

dungeon-level:gold-multiplier

```
1:2
2:2.5
3:3
4:3.5
5:4
```
....
now a 6-45 lvls are alright to have default values as x5
```
46:5.5
47:5.8
48:6
49:6.3
50:6.5
```

So at endgame we will add some extra gold (it's needed there).

Maybe after playtest we will need some more rearrangements. But it will be great to be able to assign certain values for certain depths manually to eventually create perfect balance

**Comment by igroglaz** [comment]
If it's hard to implement, then maybe it's possible at least to buff gold at 1-5 lvls twice. This is one of the most important issues, as new players struggle right now to get to -250 if they play certain classes..

**Comment by draconisPW** [comment]
Putting a table in cfg would be too complicated. I'll simply remove the linear method, which apparently doesn't work, and replace the "old" method by a hardcoded table that will follow the pattern described above. If it needs rebalance, I'll simply edit the table in the code as seems fit.

**Comment by draconisPW** [comment]
Table implemented in obj-make.c as 10x the multiplier for each depth between 1 and 127. Currently, the values are as follows:
- 50ft: 20
- 100ft: 25
- 150ft: 30
- 200ft: 35
- 250ft: 40
- 300ft to 4000ft: 50
- 4050ft to 4950ft: 51 to 69
- 5000ft and below: 70

**Comment by igroglaz** [comment]
Please is it possible to move table from Is it obj-make.c to constants.txt ? So it will be possible to change settings without need to modify resources after each update :)

**Comment by draconisPW** [comment]
This is something that will rarely change and has too many entries to be put into constants.

**Comment by igroglaz** [comment]
Most of constants.txt entries are rare to change.. But it gives possibility of easier experementation. I'm not sure that 
50ft: 20
100ft: 25
150ft: 30
200ft: 35
250ft: 40

will be good. I wanted to try first with

50ft: 20
100ft: 20
150ft: 20
200ft: 20
250ft: 20

Maybe we will make even more recustomization. It will be fun to change stuff without need to change the code

**Comment by igroglaz** [comment]
yep, definitely will be fun to assign it manually. current 1-5 lvls values are too high

**Comment by igroglaz** [comment]
I think about:
50ft: 15
100ft: 16
150ft: 17
200ft: 18
250ft: 19

**Comment by draconisPW** [comment]
I've changed gold drop rate to:

0ft: 10
50ft to 350ft: 15-20-25-30-35-40-45
400ft to 4000ft: 50

This keeps a linear distribution to avoid finding way more gold at next depth (19 at 250ft then 50 at 300ft would be too high gap). I'll modify again if it's still too much, but I don't think so.

**Comment by igroglaz** [comment]
Atm I'm testing 1.3 for 1-5 lvls as 15-19 was too much :) I found having this gap very comfortable and good for game's balance as at very early game player don't need to buy muh stuff to have interesting gameplay, while closer to lvl 10 player need to buy a lot of consumables to survive.

**Comment by draconisPW** [comment]
Ok if it's still too much I'll go with the following distribution, using a gradual increase:
0ft:10 50ft:12 100ft:15 150ft:19 200ft:24 250ft:30 300ft:40 then 50 from 350ft.

Feel free to use something else locally if you feel it's still not perfect.

**Comment by igroglaz** [comment]
If it's not too hard task - it will be great to move this values to .txt file or constants.txt or server config.. as this values need a lot of changes.. and sometimes when it's laggy I run server without debug from IDE, but from binary - and then it using different values, not which I wanna test :(

**Comment by igroglaz** [comment]
This table needs a lot of reassignment not only at first and last lvls, but also in the middle

**Comment by draconisPW** [comment]
Can't put into constants, best way is via txt file.

**Comment by draconisPW** [comment]
Implemented as new file /lib/gamedata/level_golds.txt. It contains 128 entries (one for each depth) formatted as "rate:depth:rate" with rate between 10 and 100. By default, it uses the values in the table that was created above.
