### ISSUE TITLE
curse on armour -> not updated items description until re-worn

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#207]
worn cursed item (cursed by a curse armour scroll):
https://cdn.discordapp.com/attachments/535396965433868288/721453357151027331/5xdCyQ.png

if I take it off and wear again:
https://cdn.discordapp.com/attachments/535396965433868288/721454230191210506/Screenshot_1.png

**Comment by draconisPW** [comment]
Also curse weapon. Curses are supposed to be learn on wield, so getting a wielded item cursed should automatically tell the curse.

**Comment by draconisPW** [comment]
Fixed for beta 11.
