### ISSUE TITLE
Keep player active during disconnection timeout

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#209]
Archer and other ranged classes plays without auto-retaliater.. And if they disconnected dye internet problems or electricity nearby to monsters - they are doomed.

/rfe
if player had auto-retaliater off - forcefully turn it on while player disconnected. Then when player reconnect back and got this option off - do not continue auto-retaliate.

I suppose it's quite hard feature to implement.. But it could be fun to have it one day.

**Comment by draconisPW** [comment]
It's worse than that, Jim. Currently, a player in QUIT state simply doesn't do anything, which means even a level 50 player could be killed by a level 1 monster if the timeout is long enough. The simplest thing to do is to allow process_player() to continue while the player is in QUIT state, so his "world" continues to be updated while no more commands are received from the client (so it's the same as the player standing AFK).

**Comment by draconisPW** [comment]
Implemented for next beta. During timeout, the player remains in game but client input is just severed. When attacked, the player will just retaliate, bypassing any !O or ^O inscription on equipment, and using item inscribed @O if any.
