### ISSUE TITLE
[problem] error with adding new object type

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#21]
I'm trying to add new object type - 'chat' to perform lore dialogs in shops but it doesn't work - I got an error considering wrong object type.

object_base.txt

```
name:chat:Chat~
graphics:yellow
#I've also tried
#name:chat
#graphics:yellow
```

store.txt

```
# Starter town tavern
store:Rinswind the Wizard
owner:5000:Rinswind the Wizard (Human)
slots:0:2
turnover:2
always:chat:Hello, stranger. What are you doing there, in this wild lands?
always:chat:You are not the first who came though.. Strange folk appeared recently.
always:chat:And all of them are interested in Old Ruins to the west from my tavern.
always:chat:I don't complain - finally I could get a few coins by selling this goods..
always:chat:Take a look at them:
always:cloak:Cloak
```

object.txt:

```
name:Hello, stranger. What are you doing there, in this wild lands?
graphics:?:y
type:chat
properties:0:5:0
desc:.

name:You are not the first who came though.. Strange folk appeared recently.
graphics:?:y
type:chat
properties:0:5:0
desc:.

name:And all of them are interested in Old Ruins to the west from my tavern.
graphics:?:y
type:chat
properties:0:5:0
desc:.

name:I don't complain - finally I could get a few coins by selling this goods..
graphics:?:y
type:chat
properties:0:5:0
desc:.

name:Take a look at them:
graphics:?:y
type:chat
properties:0:5:0
desc:.
```

I've sent you link to my setup in PM at forum & discord

**Comment by draconisPW** [comment]
I'm pretty sure it's because you added a colon in the last one: "Take a look at them:". This cannot work, remove the colon.

**Comment by igroglaz** [comment]
removed :

301019 132336 Initializing town feats...
301019 132336 Initializing towns...
301019 132336 Initializing dungeons...
301019 132336 Initializing object bases...
301019 132336 Parse error in object_base line 226 column 3: : unrecognized tval
301019 132336 Parse error in object_base line 226 column 3.

**Comment by draconisPW** [comment]
Ok, tvals are hardcoded in list-tvals.h, so you cannot add new object type like that. You need to add in list-tvals.h the line:

TV(CHAT, "chat")

and then recompile the game.

**Comment by igroglaz** [comment]
1) Is it possible to unhardcode them?
2) Or maybe I could just use any another item type for 'chat' items? would it be safe (so players won't find this 'items' in the dungeons?)
3) If previous two posibilities isn't possible - maybe you could add such item type in PWMA?.. maybe call it like 'etc' (so it won't be chat)

**Comment by draconisPW** [comment]
1. No, that would mean deep change to the game.
2. Just use "food" as base item (fortune cookie?). As long as you don't put an "alloc" line, the item will never be generated in the dungeon (for example: scroll of House Creation).
