### ISSUE TITLE
using staves and items from the ground

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#211]
when you use stave or item from the ground - there is no message comes to messages window, so to understand what you used (to see the name of IDed item) - you need to move away and back

/rfe if you use item from the ground - prompt message in message window

**Comment by igroglaz** [comment]
Also I've noticed that sometimes when I use item from the ground with (-) - it triggers teleport (which I've got also at (-) key :(

**Comment by draconisPW** [comment]
Keymaps redefine keys completely, so if you use for example "a" as a keymap, you will never be able to "aim" wands again. So don't use "basic" keys such as "-" for keymaps at least.

Using stuff from ground should definitely give a message though.

**Comment by draconisPW** [comment]
In fact, this is working as intended. The information (floor refresh) is present in Term 2. That's why I didn't feel the need to add a message. I'll add a message for chargeable items (usable items already get a message, since using them decreases the pile by 1).

**Comment by draconisPW** [comment]
Implemented in next beta.

**Comment by igroglaz** [comment]
Quite a lot of players using classic client with just two windows (as I'm), so having this message there will be useful. Maybe it could be added as an option?

**Comment by igroglaz** [comment]
"Keymaps redefine keys completely, so if you use for example "a" as a keymap, you will never be able to "aim" wands again. So don't use "basic" keys such as "-" for keymaps at least."

I used '-' key for a year and it was fine. Now occasionally I've got this strange problem - which looks like a bug.

Demo:
https://youtu.be/Y_LAbs2EQiY?t=317

in demo: I 'w' this spade and get teleported as '-' used for teleport staff. BUT it happend in ~10% of cases. In most cases teleport won't happen.

**Comment by igroglaz** [comment]
I suppose this problem could be connected to my favorite ever option: quick_floor (use single items from the floor instantly)

**Comment by igroglaz** [comment]
Maybe.. it happens when you use unIDentified items. I've tried to reintroduce it with admin char - but all items it touches is IDed. Also you can't give generated by admin char items to other chars - they will be IDed too..

**Comment by igroglaz** [comment]
OOOOOOOOOOK. I found the culprit.

if quick_floor turned ON it works like this:
- you step on the floor with an item
- you push 'w' to wear it
- item !automatically! weared from the ground without promt about - which item to wear

So sometimes I 'w' items and push '-' to choose item on the ground - while game do not ask me for it!

SO! quick_floor should work like this:
- you step on the floor with an item
- you push 'w' (or 'q', 'r', etc) to wear it
- game MUST asks you - which item to 'wear' (even if you don't have such items in you inventory!)
- if you push '-'  -- game should wear this item automatically without choice (if it's the only item on the ground)

SO..... With quick_floor option turned on you need also to choose a letter - which item to 'wear':
1) you step on the floor with an item
2) you push 'w' (or 'q', 'r', etc) to wear it
3) game asks you - which item to 'wear' - from your inventory or from the ground
4) you push from the ground (-)
5) !!!! now game asks you to choose a letter of the item even it's the only item on the ground 
..............
with quick_floor ON - game should do not ask you to choose a letter of the item if it's the only item on the ground . But it still ask you which item to use - from the ground or from inventory

**Comment by igroglaz** [comment]
so.. the trouble happens sometimes when game see that item on the ground is the only way to use (when nothing in inventory matches it) - then game automatically use the item; without prompt - to use it from the ground or from inventory

**Comment by igroglaz** [comment]
Hm... Actually it could be for the best - to have current system. I just need to get used to it. It's even better like it is now.

/rfe do not change anything :)

**Comment by igroglaz** [comment]
No, it's a bug/problem indeed.

if you stay on certain item and push 'w' - game will 'w' item from the ground automatically which could be sometimes bad thing.

so yep:

with quick_floor ON - game should do not ask you to choose a letter of the item if it's the only item on the ground . But it still should ask you which item to use - from the ground or from inventory

**Comment by igroglaz** [comment]
Why it's bad could be seen even there:
https://youtu.be/Y_LAbs2EQiY?t=317

It's not about teleportation, but about wielding item without prompt. So with quick_floor ON  when you stay at item atm - and push a 'w' for example, game will wear item from the ground automatically, which is stupid.

with quick_floor ON - game should do not ask you to choose a letter of the item if it's the only item on the ground . But it still should ask you which item to use - from the ground or from inventory

**Comment by draconisPW** [comment]
But did you have anything in inventory that could be wielded? If not, then wielding automatically from floor is working as intended, unless we decide to remove "wield" from the "quick_floor" option, like it was done for "pickup".

**Comment by igroglaz** [comment]
I see now, thanks.. But then it's quite confusing - to 'wield' item on the floor just with one key - you could easely do it by mistake and loose item. Please lets change it :)

Right now:

 quick_floor OFF:
1) you step on the floor with an item
2) you push 'w'
3) game asks you:  `wear or wield which item? (Inven: a-z, - for floor, ESC)`
4) you push '-'
5) game asks you:  `wear or wield which item? (Floor a-a, / for inven, ESC)`
6) you push 'a'
7) item weared

Right now quick_floor ON work like this:
1) you step on the floor with an item
2) you push 'w' (or 'q', 'r', etc) to wear it
3) item automatically weared from the ground _without_ any prompt

Please lets change quick_floor ON to this:
1) you step on the floor with an item
2) you push 'w' (or 'q', 'r', etc) to wear it
3) game asks you:  `wear or wield which item? (Inven: a-z, - for floor, ESC)`
4) you push '-'
5) if it's the only item on the floor - item weared (without need to push 'a', like in #6 of 'quick_floor OFF'). If there are several items - it goes as if it's quick_floor OFF

**Comment by draconisPW** [comment]
ROFL @ EN stream where you wield from the floor a cursed randart crown that teleports you around.

Ok fixing this ;)

**Comment by draconisPW** [comment]
Testing locally, this indeed only happens if you have nothing in the inventory to wield. So with quick floor off, you get: "wear or wield which item? (Floor a-a, ESC)" and that's it, which is the correct behavior. With quick floor on, you wield automatically the item. There is no reason to add "wear or wield which item? (Inven: a-z, - for floor, ESC)" since there is nothing in inventory. In this case, I'll just remove "wield" command from quick_floor option, this was just added for "using" items anyway.

**Comment by igroglaz** [comment]
Please lets change quick_floor ON to this:

you step on the floor with an item
you push 'w' (or 'q', 'r', etc) to wear it
game asks you: wear or wield which item? (Inven: a-z, - for floor, ESC)
you push '-'
if it's the only item on the floor - item weared (without need to push 'a', like in #6 of 'quick_floor OFF'). If there are several items - it goes as if it's quick_floor OFF

**Comment by draconisPW** [comment]
Implemented for next beta.

**Comment by igroglaz** [comment]
1) "Testing locally, this indeed only happens if you have nothing in the inventory to wield. So with quick floor off, you get: "wear or wield which item? (Floor a-a, ESC)" and that's it, which is the correct behavior. With quick floor on, you wield automatically the item. There is no reason to add "wear or wield which item? (Inven: a-z, - for floor, ESC)" since there is nothing in inventory."

The reason is - that player should get used to _one_ certain algoryth on operating with floor items. Algorythm:
action -> target that it's on the floor

It doesn't matter - does player got an item in inventory or not - if player will get used to this algorythm - it will make life much better

2)  In this case, I'll just remove "wield" command from quick_floor option, this was just added for "using" items anyway.

This will be very sad as 'w' items from the floor save a lot of time.

Please lets change quick_floor ON to this:

you step on the floor with an item
you push 'w' (or 'q', 'r', etc) to wear it
game asks you: wear or wield which item? (Inven: a-z, - for floor, ESC)
you push '-'
if it's the only item on the floor - item weared (without need to push 'a', like in #6 of 'quick_floor OFF'). If there are several items - it goes as if it's quick_floor OFF

**Comment by draconisPW** [comment]
As I said you won't ever get "wield which item? (Inven: a-z, - for floor, ESC)" if you have nothing inventory, but "wear or wield which item? (Floor a-a, ESC)" instead so you will press "a" instead of "-" to wield from floor.

**Comment by igroglaz** [comment]
Oh, I see now. It's great then! This 'using from the floor' feature is my favorite ever and I dreaded that it could be gone :crab: Thanks!

**Comment by igroglaz** [comment]
oook. I've tested new system: "_so you will press "a" instead of "-" to wield from floor._"... and it's not comfortable as it means that **`quick_floor`=ON doesn't work on wearable items**, while it should as it increase game ergonomic a lot.

Please lets change quick_floor ON to this:

you step on the floor with an item
you push 'w' (or 'q', 'r', etc) to wear it
game asks you: wear or wield which item? (Inven: a-z, - for floor, ESC) 
you push '-'
if it's the only item on the floor - item weared (without need to push 'a'). If there are several items - it goes as if it's quick_floor OFF

Why it's important:
- all actions with items on the flood should go with one single key (-) if it's the only item on the ground. It's the point of quick_floor=ON feature. When player step on the tile with single item (which happens in 90% cases) - if player will be able to use this item with one key (-) - it's much better then have to push two keys - sometimes (-) and sometimes (a). It's pretty annoying :(

**Comment by draconisPW** [comment]
quick_floor=ON doesn't work on wearable items: yes, that's the case. Because it's on client and you don't have much info at this time. Switch from inventory to floor is a toggle, so there is no way to tell at that time the behavior of floor vs inventory. I could try to figure out something, but it's not possible to have both the behavior or quick floor ON and quick floor OFF at the same time depending on whether you have items in the inventory or not. Basically: either you get #211 or #203, pick the one less annoying.

**Comment by igroglaz** [comment]
1) "Because it's on client and you don't have much info at this time.... so there is no way to tell at that time the behavior of floor vs inventory."

maybe client don't really need to know which kind of objects on the floor? It's just trying to do with it command which user sends. If it fails - it just don't do nothing

2) maybe it possible to use a 'wildcard', like an "alter" command - when you operate with the items on the floor - no matter is it consumable or wearable?

**Comment by draconisPW** [comment]
Went for the middle route. Quick floor is now enabled for wield if there is something to wield in the inventory. If not, it's disabled. Can't do anything else, so you'll have to live with it and just add a bit of documentation.

1) Nothing in inventory -- menu with "Floor: a-a" to avoid #203 (quick_floor disabled)
2) Something in inventory -- menu with "Inven: x-y, - for floor"
2a) quick_floor off: pressing "-" brings menu "Floor: a-a, / for Inven"
2b) quick_floor on: pressing "-" auto-wields the item on the floor

**Comment by igroglaz** [comment]
Thanks.. It's better than nothing. It's not a problem of documentation or newbie-experience, but an overal usability and comfort in gameplay, mostly for experience players, eg in TomeNET there is no such feature. I found that (-) makes gameplay much more relaxing.. as after years in roguelikes every _tiny_ detail which helps player to make less efforts in operating items/objects/inventory is a blessing.

**Comment by igroglaz** [comment]
previously if you were 'w'earing item from the ground with (-), item was swapped into the ground, which was very comfortable and useful. now it's putted to inventory so you need to make 2 extra actions :( is it possible to add possibility to put item on the ground when swapping from (-)?

**Comment by draconisPW** [comment]
The wield command has never swapped anything and never will.

**Comment by igroglaz** [comment]
It was. Check my vids.

you step on the floor with an item
you push 'w' to wear it
game asks you: wear or wield which item?
you push '-'
if it's the only item on the floor - item weared and item which you had on you appeared on the floor

it was damn good useful and comfortable. now its gone and it's sad :(

**Comment by draconisPW** [comment]
I can ensure you that this was never the case. If the item you wielded dropped on floor, it was just because your inventory was full. Looking at your vids, you're mainly playing as a packrat, picking everything even useless stuff, so your inventory is almost always full :)

**Comment by igroglaz** [comment]
I'm 100% sure that it worked before even with non-full pack. If you 'w' item from floor - it was swapped with item on the floor and it was useful and nice. I suppose it was removed in recent update when you've removed 'w' from quick_floor=ON
