### ISSUE TITLE
Townie generation

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#212]
we've got on server

```
# Number of townsfolk generated in the day */
#4
mon-gen:town-day:32
#8
# Number of townsfolk generated in the night */
mon-gen:town-night:64
```

but it's often to do not find any townies in town (Bree). Although it's got:

```
name:Farfest
# TOWN
short:0_1
wpos:0:1
max-townies:-1
#red tower
symbol:obj_grass2 e
```

I assume it could happen cause of townies wipe on dawn..

**Comment by draconisPW** [comment]
I'll check but I assume there are not many townies because there's too much non passable terrain. Or it could be -1 (I don't remember how this works).

**Comment by draconisPW** [comment]
No, it works properly. Not a problem with terrain.

mon-gen:town-day and mon-gen:town-night are values that are used when generating a town area the first time or when there are no-one that saved in the area, so the town is regenerated.

max-townies works fine

Problem is as follows:
- every dawn, townie list is wiped so the townie count is reset unless there is someone in the town
- no townie is ever generated if noone is in town
- when someone afks in town, about 20 townies are generated between dawn and next dawn

This is why you have the impression that no townies appear in town.

**Comment by draconisPW** [comment]
Easiest way to fix this: don't wipe monster list in towns at dawn if the number of townies is less than the value for "max-townies". This will allow a constant buildup and then a wipe when there are too many. If the buildup is slow, then the wipe will happen rarely.

**Comment by draconisPW** [comment]
Implemented in next beta.
