### ISSUE TITLE
command and hybrid macros

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#215]
based at this problem: https://github.com/draconisPW/PWMAngband/issues/211#issuecomment-651368742

To make macroing easier and add more possible keybinding - we could look into Command/hybrid macro concept:

https://www.tomenet.eu/guide.php?chapter=3.6&highlight=command%20macro#r144

```
**Command macros** are only executed if the game isn't currently waiting for a
specific input, for example "quaff which potion?" or while you're typing chat
messages. That means they won't "disrupt" any other command which is currently
being run. This is convenient for keys which you use in chat, but can be
dangerous if you define vital macros as command macros.
It is recommended to make your most important macros normal macros or at least
hybrid macros (for example a "panic key" macro). Command macros don't work
in shops.


**Hybrid macros**:
--------------
Use 'create hybrid macro' instead of 'create normal macro' in case you don't
want the macro to appear on hitting the corresponding key in a normal chat
message (for example useful for '-' key so it won't prevent you from
inscribing your Word of Recall scrolls).
Hybrid macros still work within input requests such as "quaff which potion?",
just not in STRING INPUT such as chat lines, polymorph-codes or money amounts.
Hybrid macros don't work in shops.
```

Maybe something in-between could be implemented - at least to solve the problem of using stuff from the ground - it's great feature and it's really sad that it's not possible to use it if you got action at '-' key.

**Comment by igroglaz** [comment]
Found an issue with using stuff from the ground... having command macroes could be nice to have too one day, but it's not critical atm

**Comment by draconisPW** [comment]
Macros are gone, it's keymaps now. The whole command/hybrid system is gone for ease of use. Keymap is what it is: a remap of a specific key. If you want to use a game command as a keymap, you lose that command. I do this all the time with my casters which have the "stone to mud" spell: I remap the "T" key (tunnel) which becomes obsolete due to using the spell for that. There should be enough "non command" keys to remap (instead of "-" you could use ctrl+"-" or shift+"-") to this be not an issue.

**Comment by igroglaz** [comment]
Nope, it's alright to use '-', it works.

Macros is better then keymaps. As you could macro whole keyboard for a lot of spells. I like to play with q-t, a-g, z-b as hotkeys for spells. I'm not sure that I'll be able with mage classes comfortable as there are not much hotkeys for magic :( Will see...

**Comment by igroglaz** [comment]
I mean.. this keymaps system frmo V - it's good for turn-based mode where you could easely use MUCH less keys as you do not hurry. But playing in real-time - you need much more hotkeys.
