### ISSUE TITLE
terrain flag for training dummy

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#216]
it's pretty cool to train macro on training dummy in town, but it's wondering around :) maybe make a little hack for him? eg:
1) add to config coordinates on which traning dummy will spawn
2) add flag for terrain to use this coods
3) ???
4) profit!

**Comment by draconisPW** [comment]
Need to rework the target dummy:
- make fixed coordinates so it doesn't get regenerated elsewhere when level is wiped
- remove from unique list since it's unkillable
- remove the death/pain/ailment messages

**Comment by draconisPW** [comment]
- new terrain "training grounds" for the Target Dummy

**Comment by draconisPW** [comment]
- training grounds generated randomly as a "lot" in the base town, target dummy coordinates fixed to that location and always regenerated at the same spot -- for custom town, define "training grounds" as a town feature, place the feature at a fixed location on the town map and that's it, the target dummy will always be generated there (only define ONE tile for the target dummy as it is NON object and would prevent otherwise items from dropping near the target dummy, for example when shooting arrows at it)

**Comment by draconisPW** [comment]
Don't have time for the rest for this beta, keeping this open for the next.

**Comment by igroglaz** [comment]
It works perfectly, thank you! :)

**Comment by draconisPW** [comment]
Implemented in next beta:
- don't display Target Dummy in the list of uniques
- don't display pain/death message for Target Dummy

**Comment by igroglaz** [comment]
```
[21:28] igroglaz: target dummy doesn't reappear
[21:28] igroglaz: (townies numbers changed from -1 to 100)
[21:43] PowerWyrm: needs to fill the 100 first
```

it seems it takes ages to spawn training dummy, while it's often really needed to test stuff with Traning Dummy. 

Also it's not possible to summon dummy with & admin menu ( & 3 2 ..) - it doesn't appear in town (tried in different places)

**Comment by draconisPW** [comment]
Target dummy can only spawn in base town it's hardcoded. To avoid problems, I can make him unmovable (aka you cannot teleport it) and "force depth" (like a dungeon boss).

**Comment by draconisPW** [comment]
TD cannot be teleported around anymore, this should ensure it's still at its defined place in town.

**Comment by igroglaz** [comment]
we still have problem with Dummy.. it's not there for months D:

/rfe add admin & command to spawn dummy

**Comment by draconisPW** [comment]
NO_DEATH monsters now respawn every dawn if they somehow disappeared
