### ISSUE TITLE
Critical fixes From V

### ISSUE THREAD

**Issue by draconisPW** [draconisPW/PWMAngband#217]
- fixed apparent issue with trampling of shape-changed monsters
- fixed bug with food counter that stopped starvation when the counter hit 0 and caused the food indicator to disappear
- fixed bug with tracking of shape-changed monsters on destruction/trampling
- fixed bug with tracking of shape-changed monsters on leaving level
- fixed bug with tracking of shape-changed monsters on game loading, which should also fix a previously reported bug of the same unique being killed more than once

Need to port this ASAP.

**Comment by igroglaz** [comment]
what is trampling? I mean - in terms of Angband.. when you 'go' towards monster?

**Comment by igroglaz** [comment]
oook :D http://angband.oook.cz/forum/showpost.php?p=146689&postcount=19
`Turns out one of the uniques is Huan and this brave Valinor hound immediately tramples in-form-Sauron into oblivion. Good dog!`

**Comment by draconisPW** [comment]
Trampling refers to monsters with KILL_BODY flag able to "eliminate" weaker monsters by simply walking over them.

**Comment by draconisPW** [comment]
- Stop Create Arrows creating special artifacts

Need to fix this funny bug too (using Create Arrows spell creates a randart ring). And while at it check all other cases of creating objects via make_object + tval.

**Comment by draconisPW** [comment]
Fixed for next beta.
