### ISSUE TITLE
auto-ignoring settings

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#219]
1) it will be fun to have one day possibility to assign auto-ignoring settings in .prf file, so eg if you play chars who can't read the books - you could just add it to config initially without need to add stuff with every RIP

2) make Power Dragon Scale Mail as 'no ignore' by default :)

**Comment by igroglaz** [comment]
This is one of the most important usability issues.. as players die often - every time player need to spend several minutes in item ignore setup to restore settings used for previous character

**Comment by draconisPW** [comment]
Currently this cannot be done, as ignore system is based on "flavor" and "seen" flag, so you can only ignore items you have seen in the current game. You can ask the V team to implement a different system, but I won't have time to code this myself.

**Comment by igroglaz** [comment]
added /rfe to V: https://github.com/angband/angband/issues/4661

**Comment by draconisPW** [comment]
V won't fix, so closing this.

**Comment by igroglaz** [comment]
Currently, it's quite inconvenient that auto-ignore settings aren't persistent - every time a player starts a new character, they have to go through the same process of customizing ignore settings from scratch. And since the death rate is pretty high - especially for new players - this becomes even more important.

/rfe
1) Support saving per-character auto-ignore settings in a separate .prf file. Something like autoignore-<charname>.prf could make a big difference in QoL.
2) Another useful addition would be class-specific ignores - for example, if you're playing a warrior who can't read, you wouldn't need to see any books lying around.

> Currently this cannot be done, as ignore system is based on "flavor" and "seen" flag, so you can only ignore items you have seen in the current game.

I suppose we can make our own system without interfering with the V auto-ignore. Just put a new layer on top - like a dirty hack that's applied at the end of the V system :D Not the cleanest solution, but it's worth it, as this would save a ton of time for our new players.

**Comment by igroglaz** [comment]
> Currently this cannot be done, as ignore system is based on "flavor" and "seen" flag, so you can only ignore items you have seen in the current game.

Hm.. maybe we can add on top a very simple feature, which would already be useful. Just simplify it to a setting in player options:
**always auto-ignore books**

This will help a lot :D In the game's menu, there are a lot of sections for each school with tons of books. So if a player goes with a non-magical class - even this small option will help a lot.

**Comment by igroglaz** [comment]
I suppose this tiny setting (always auto-ignore books) can be made like a hack on top of the current V auto-ignore system, without touching it - so compatibility with V fully persists.
