### ISSUE TITLE
allow more space in storage-house

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#222]
as there are happens quite often problems with 'server' file after even small updates - lets increase size of storage house in town till 24 slots (or even more, max amount)? it will be temporary measure, till active stage of development will pass

**Comment by igroglaz** [comment]
(because storage-house items saved even if 'server' wiped)

**Comment by draconisPW** [comment]
Good idea. I'll add a check vs BETA_VERSION define.

**Comment by draconisPW** [comment]
Implemented for next beta. As long as the server is tagged "beta", home has same capacity as all other stores.

**Comment by igroglaz** [comment]
maybe lets move it to config file? so it won't be needed to change the code if it's not beta already, but you still need this feature
