### ISSUE TITLE
[bug] admin's Mass Banishment effect doesn't dissapear

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#224]
reproduce:
1) with admin enter to the dungeon from the staircase
2) use & -> Summoning -> MB
3) take a step to any direction to redraw screen - you will see that monsters dissapeared
4) now exit dungeon by floating upward
5) enter dungeon again. if it will be other dungeon.. first you will see the mosnters. then if you will make a step to any side - they will dissapear, even though you didn't use MB this time

**Comment by draconisPW** [comment]
All commands in the "summoning" menu are "toggle" commands and work permanently. To stop summoning/mass banishing, you need to press "summoning off" in the menu.
