### ISSUE TITLE
don't wipe items from town if there is a player on it

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#225]
It's quite probable for players to loose items on trade if it's night->morning time - as they could be wiped. I've lost items this way (luckily during test via my admin character).

Maybe this could be a solution: do not wipe items on dawn if there is a player in location (make it static while someone around)

**Comment by draconisPW** [comment]
This is what is done for monsters (only wipe list if there is noone on the level). I'll do the same for objects, since there is not much players on the server. The only problem is if people start to connect and stay afk forever without ever playing (cf TomeNET).

**Comment by draconisPW** [comment]
Implemented for next beta.
