### ISSUE TITLE
Roguelike quest system

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#229]
**https://tangar.info/en/game-dev/roguelike-quest-system**

Quest system isn’t present in V because quests are not really good suited in *bands, good analytics about it [there](http://angband.oook.cz/forum/showpost.php?p=67076&postcount=19).

In addition in PWMA (and Tangaria) there are more problems:
– in PWMA quests influencing V-based economy (not too much though because of a lot of RNG in completing it/reward).
– quests to kill certain enemy are just boring.
– players often forget to take quests as it’s very rare to complete them and you got dull rewards; most just play without them

Those problems came because quests in roguelike games often implemented like in traditional MMO/RPG-quests (kill 5 chickens, bring 5 ribs), while it should have it’s own, roguelikish type of quests – to encourage players to have an adventure, with a proper risk VS rewards rate.

/rfe to improve quests and to encourage players to play in more roguelikish way – implement this minimalistic (and yet deep) system:

**Retrieve an ancient relic fragment from the dungeon vault** // reward: gold
– every (or some) dungeon will have an item which could appear only in the vault on the bottom level of the dungeon. It won’t appear often (as vaults appear not too often) – so you’ll have to look for it. Sounds like a good adventure;
– at low player’s lvls such relics will appear in small vaults, while at end-game only in Great vaults;
– after you pick up this item – you **can not** use ‘Word of Recall’ scroll. So you _have to_ get back with this relic using stairs (which is quite dangerous). So it’s like an optional way to turn the dungeon into NO_RECALL;
– while you holding this relic - there is a tiny chance to summon monsters around you (minor curse of summoning from V) - it makes way back more fun!

Actually this type of quests come from _original_ – from ‘Rogue’ where the player had to retrieve Amulet of Yendor and bring it to the surface. Oldies, but goldies. This is the right truly roguelikish quest system.

Benefits:
– to encourage players to get into the vaults and take the risk
– strong anti-cheezing (vaults provide it)
– easy to rebalance (to set certain gold amount as reward and rebalance it with gold drop table)
– these quests are still optional, so you could play without getting into quest hunt if you don’t want to get additional risks
– adding variability; some dungeons will be easier to complete, some are harder. Sometimes if you will kill everything on sight you will have too much exp to visit all dungeons – so you will need to play more strategically, sometimes to avoid battles. It’s adding yet another strategy to ‘win’ the game – like with completing all available quests (to do it you will need to spend a lot of gold for consumables, but you will get additional money back after completing quests) OR avoiding quests (be more economical in terms of consumables in general). 
– make the game deeper and bring back some traditional Yendor’ish flavour  – as there appears yet another goal and challenge – to complete all quests – gather the whole Relic from fragments

So.. The idea is to give additional motivation for players to get into the vaults. As right now *bands are quite winnable without getting your foot in most vaults. **Quest=vault=NO_RECALL** could be really good way to solve this problem.

====

Also.. It will be fun to make it possible to take quests when you speak with certain NPC (terrain flag) – eg in T it could be Decard Coin. It will bring more immersion to the game – like you got a real quest from NPC, not just pushed ^Q key.

**Comment by draconisPW** [comment]
Sorry but this would be an insane amount of work to implement for something nobody will ever use.
1) Early on, you cannot tackle vaults -- risk >> reward
2) Later on, the reward would be meaningless -- zero risk, zero reward
3) Having to waste one hour to go back to surface while in the meantime you could actually play and earn more + can't safely stop if you have to go afk

Having quests from NPC would be great, but need to think about something that would stay simple and not be a hassle to complete.

**Comment by igroglaz** [comment]
"1) Early on, you cannot tackle vaults -- risk >> reward "
I suppose at lvl 20 you already can do it (and it's good time to get the 1st quests). For new-born character quests are not needed really.

"2) Later on, the reward would be meaningless -- zero risk, zero reward"
it won't be meaningless if gold drop will be reduced

"3) Having to waste one hour to go back to surface while in the meantime you could actually play and earn more + can't safely stop if you have to go afk"
it's actually huge adventure - playing with a curse on you. 100500 times more interesting than normal grind. "Earn more" - depends of gold drop rate. if you want to go afk - go afk :) it's not a big deal - 3 seconds and character logged off.

"insane amount of work to implement"
Yep, it's just a concept for the future. One day..
