### ISSUE TITLE
effect:TIMED_INC:OPP_CONF dice:1

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#230]
Took this from clear mind mushroom:

effect:TIMED_INC:OPP_CONF
dice:50+7d7

and made it to potions to give 1 turn immunity to conf (to solve fatality perma-conf situations):

```
name:Cure Light Wounds
graphics:!:d
type:potion
level:1
weight:4
cost:20
alloc:80:1 to 15
pile:90:2d3
effect:TIMED_DEC:CONFUSED
dice:20
effect:TIMED_DEC:CUT
dice:20
effect:CURE:BLIND
effect:HEAL_HP
dice:20
effect:TIMED_INC:OPP_CONF
dice:1

name:Cure Serious Wounds
graphics:!:d
type:potion
level:5
weight:4
cost:70
alloc:80:5 to 40
pile:80:2d3
effect:CURE:CONFUSED
effect:CURE:BLIND
effect:CURE:CUT
effect:HEAL_HP
dice:40
effect:TIMED_INC:OPP_CONF
dice:1
```

but instead of 1 turn it works for 10 or even more :(

**Comment by igroglaz** [comment]
tried `dice:1+1d1` , 
the same :disappointed:

**Comment by draconisPW** [comment]
Same error in Vanilla. Timeouts are decreased after commands are processed, which means the actual duration of effects is (dice-1). Setting dice:1 means the effect has 0 duration. In Vanilla, the effect is removed, I need to check why it is not removed in PWMAngband.

**Comment by draconisPW** [comment]
Also the end message is never displayed because there is a test vs confusion resistance and while calculating player state temporary resistance is set as permanent for confusion. Same error in Vanilla.

**Comment by draconisPW** [comment]
In fact due to this bug, this is just a visual error. You see "rConf" on the screen, but you're actually not protected from confusion anymore.

**Comment by draconisPW** [comment]
Both problems fixed in next release:
- only check permanent pConf for timer notification
- move decrease_timeouts() function before process_pending_commands() so effects actually last n turns and not (n-1)
