### ISSUE TITLE
mangclient.exe performance issues

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#231]
I've recorded a video demonstration:
https://youtu.be/zk2WA4z4fDQ

In short: sdl client works perfectly, while regular (which I use daily) works much much slower... Quite unplayable at my old notebook.

**Comment by draconisPW** [comment]
I can reproduce this, but it's because the Windows client redraws all the tiles using ReadDIB2_PNG() function, which is way slower than the SDL version.

**Comment by draconisPW** [comment]
Note that this is pretty obvious using Tangaria's tileset, since you have so many different tiles in dungeons or towns and the Windows client struggles drawing all these tiles while the SDL client has no problem with that.
