### ISSUE TITLE
sdl client: hide UI customization menu and borders

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#233]
/rfe add possibility to start SDL client without upper menu and borders between windows as these elements take useful space while user customize UI only once... so there is no point to have upper menu toggled during gameplay

such option could be added to sdlinit.txt.. it could be called something like 'dark' mode - similar to the mode which I use with my addon - just the game on black background without excessive elements - borders, menus, game name window, etc

**Comment by igroglaz** [comment]
so the thing is - not only to hide useless menu, but also to move game 'up', so player will have more overview instead of the menu

**Comment by s88100** [comment]
possibly function of displaying windows in Options menu, Hide window border: OFF,A,B or 0,1,2 variants.
I commented // in main-sdl.c line 1884 SDL_FillRect( https://github.com/draconisPW/PWMAngband/blob/master/src/client/main-sdl.c#L1884 and the window is displayed without an upper border, it can be moved if you select the up border with the mouse.
and commented // 1111 sdl_DrawBox( https://github.com/draconisPW/PWMAngband/blob/master/src/client/main-sdl.c#L1111 and the windows hiden (also can be moved) like in Tangar Addon

1884: if ! variant=a || b then SDL_FillRect(win->surface, NULL, SDL_MapRGB(AppWin->format, 160, 160, 60));
1111: if ! variant=b then sdl_DrawBox(AppWin, &rc, colour, win->border);

https://cdn.discordapp.com/attachments/699917093717671946/832597526367698954/screen-2021-04-16-18-33-15.png
https://cdn.discordapp.com/attachments/699917093717671946/832597550388477952/screen-2021-04-16-18-38-01.png

**Comment by draconisPW** [comment]
I believe this is now done.
