### ISSUE TITLE
sdl client: 'options' menu not accessible if not in fullscreen mode

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#236]
1) turn off fullscreen via options button in sdl client
2) now you can not access 'options' menu.. the only way to get back to fullscreen is to edit sdlinit.txt

**Comment by draconisPW** [comment]
Can't reproduce :(

**Comment by igroglaz** [comment]
I suppose it was a glitch with the 'options' dialog - it was hidden behind main window if game was not in fullscreen. After I've changed layout this problem gone.
