### ISSUE TITLE
main window: remove width and height limits

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#237]
atm both in SDL and classic clients it's seems it's not possible to make window less than 80 cols width, eg in sdlinit I've got:

```
Resolution = 1806x859
Fullscreen = 1
NiceGraphics = 0
Graphics = 0
TileWidth = 1
TileHeight = 1

Window = 0
Visible = 1
Left = 0
Top = 13
Width = 1924
Height = 879
Keys = 1024
Font = 24x36tg.fon
```

you can't make it less than 80... the same thing for main window in 'classic' clients:
NumCols & NumRows got certain limits which can't be reduced... with it I can't play at my 17' screen laptop with my blind-friendly font

**Comment by draconisPW** [comment]
80x24 is hardcoded almost everywhere. If you want reduced screen, the only way is to use 64x64 tileset like Shockbolt and decrease max-sight and max-range in constants.txt.
