### ISSUE TITLE
forbid char to shoot specific ammo on auto-retalliation

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#238]
right now character shoots on auto-ret with any stuff which I've got in quiver

eg
I've got magic arrow and arrows (+5,+5)
I wish to save +5,+5 arrows for a boss fight. But my char shoots them on auto-ret even they've got ^O inscription

/rfe add an inscription which prevents shooting on auto-ret with particular ammo

**Comment by draconisPW** [comment]
Why not use @f0 on your magic arrow and @f1 on your +5 arrows to reorder the quiver? You could use 'h' to fire the magic arrow and retaliate and a '@f1*t' macro to shoot your good arrows during a boss fight...

**Comment by igroglaz** [comment]
I tried it. It work in normal cases, but there is a problem is auto-retalliation as I've mentioned in the ticket.

**Comment by igroglaz** [comment]
Without this option it's much harder to play archer.. you forced just to ignore all +arrows :(

**Comment by draconisPW** [comment]
I don't see why auto retaliation uses your +5 arrows if the magic arrow is inscribed as @f0, sounds like a bug to me, I need to investigate...

**Comment by draconisPW** [comment]
As I thought, everything works as intended. I generate a bow which I inscribe @O, a magic arrow that I inscribe @f0 and some arrows of flame. I make a "f1'" macro for the arrows of flame which I use during hard fights. Char autoretaliates normally with the magic arrow. It must be a macro/inscription error on your part.

**Comment by igroglaz** [comment]
Thanks. I've tested it twice.. I'll make yet another test this weekend and will record video if this problem exist...

**Comment by igroglaz** [comment]
Ok, I've tested, f0 works as intended, thank you very much :)

There is a _minor_ problem is: player often want to shoot an arrow to a certain direction - when
1) he fight invisible enemy
2) enemies not visible due distance
3) enemies could come out of corner
4) you wanna check is it death sword or other mimic

How to do it? I push: 
1) `f` - game asks which projectile to use
2) '1' - as it's closest button to your active hand

with f0 as default hotkey for magic arrows or auto-ret - it's kinda not comfortable to push f -> 0 when you wanna shoot arrows in certain direction

/rfe
move default auto-retalliation inscription from f0 to f1

this could be solved by inscribing enhanced arrows with f<2...9> and macroing it.. but revamping default auto-retalliation from f0 to f1 is a pretty solution, if only it's not hard to implement.
