### ISSUE TITLE
[bug] TERROR stack with FAST

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#239]
eat mushrooms of terror together with speed potion to get +20 speed buff

**Comment by draconisPW** [comment]
Totally a feature.

**Comment by igroglaz** [comment]
I see, thanks http://angband.oook.cz/forum/showthread.php?t=7652
but it sounds quite imba.. ranged classes already powerful enough

**Comment by igroglaz** [comment]
Solved this problem in T by adding effect:TIMED_INC_NO_RES:IMAGE to Terror

also I've added legacy mushrooms of Paranoia.. designed them to have 
effect:TIMED_INC_NO_RES:AFRAID
dice:25+5d5
effect:TIMED_INC:STEALTH
dice:5+1d5

looks good
