### ISSUE TITLE
Unhardcode NPC phrases @ ui-store.c

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#24]
```
static const char *comment_welcome[] =
{
    "",
    "%s nods to you.",
    "%s says hello.",
    "%s: \"See anything you like, adventurer?\"",
.......
```

It would be great to unhardcode NPC phrases in shops, so there would be possibility for RP lore in custom stores. Eg at this picture top phrase is breaking lore of this old wizard who lives alone in swamp:
https://cdn.discordapp.com/attachments/535396965433868288/640236237399130112/Untitled-1.jpg

**Comment by draconisPW** [comment]
Preliminary work in f55f524. If we want this to work, messages must be managed on server.

**Comment by draconisPW** [comment]
Implemented in 2be9eef as default messages. All is left to do is add override for specific stores.

**Comment by draconisPW** [comment]
And this is done in b18e320.

**Comment by igroglaz** [comment]
It seems custom welcome messages doesn't work atm. They don't work for custom shops and to regular shops (store:Expensive Black Market) too. When I speak to Expensive Black Market owner, he tell me # _Default welcome messages_ or even staff from 'hints.txt'

**Comment by draconisPW** [comment]
Custom messages work perfectly. They are displayed 1/3 of the time and chosen between a random hint from hints.txt and a message depending on player level. There are 9 custom messages displayed at levels 6-10, 11-15, 16-20, 21-25, 26-30, 31-35, 36-40, 41-45, 46-50. For player below level 6, only random hint is displayed.
