### ISSUE TITLE
can't generate rod of polymorph

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#242]
how to generate rod of polymorph with admin char?
```
&
4
2
k
Polymorph
```
it shows wand of polymorph
and if I type Rod of Polymorph - it doesn't show anything

`00:13] PowerWyrm: #rod of polymorph maybe? I think # is used to specify literal string so it doesn't use the "fuzzy" function`

tried, didn't work

**Comment by draconisPW** [comment]
Ok I had to check the code for this one. To generate an item, you need to pass the exact kind name: "dagger", "lantern", "experience", "polymorph", ... so putting "potion of experience" or "rod of polymorph" won't work. Problem is: if you use "polymorph" for kind name, the code will pick the FIRST kind with that name, which mean "wand" and never "rod" (same for "strength" for example -- you will get a potion and not a ring). To fix this, it's possible to put a symbol at the beginning of the name so the parser knows what item to generate: !strength for a potion, =strength for a ring. But there's still a problem remaining: wands and rods use the same symbol "-". To fix that last problem, the parser uses "*" to recognize rods.

So the answer is: to generate a rod of polymorph from the "&42k" menu, you need to specify "*polymorph".
