### ISSUE TITLE
legacy house pricing

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#245]
I've removed from T's code cfg_house_floor_size in house pricing formula as I like old way of house pricing. With the new way new player can't but 2*3 house, while with old way it was possible and it was fun.

/rfe add cfg option to use old way of house pricing

It's much better to regulate game's economy with gold drop table rather than with house price. Having piles in houses makes game much better in terms of comfort. The biggest pain in *bands is item managment; house piles in help with it a bit. But houses should be hard to get. Eg in T there is 1 char/account, so players won't take exessive houses.

**Comment by igroglaz** [comment]
So, as I said - I've removed from T's code cfg_house_floor_size in house pricing formula. As I really want to be able to stick only with 'pure' PWMA server and do not push this change into PWMA code after every new version, please could you add legacy option.

**Comment by draconisPW** [comment]
I am seriously considering reverting the last changes and simply fixing the bug that allows multiple objects at the same spot in houses. It's absolutely absurd to have access to 4*23=92 item space right at start of the game, you don't need that at all. So not being able to buy a 2*3 house with this setup just makes me laugh...

I don't have time now and I'd like to release the final 1.4.0 (we're at beta 16 so there cannot be more) before doing anything big anyway. Just putting this in the backlog, but clearly I won't add an option for this, I'd rather revert the price change.

**Comment by igroglaz** [comment]
Restriction to put items in a house - is very bad thing for _multiplayer_ roguelike game. It's wrong design. Roguelike compexity comes from "the dungeon" - not from item managament "on the surface"! There is a restriction for items which player could take with him. And it's right. But storage restrictions won't change game much, just make it more annoying and remove possibility for new players to trade between each other.

The idea of this restriction comes from Mang and TomeNET. But there are allowed several players on one account - so this restriction makes players harder to cheeze there by moving items from one char to another. This is outdated and wrong mechanics.

Take a look at T's YASDs. There are plenty of them. They comes not from housing space, but from the dungeon roguelikish situations. Having restricted space _outside of the dungeons_ doesn't make game easier. 

And regulation gold income for player by making player spend it on house - also outdated mechanics. We got `gold table` so we could perfectly balance gold income to make game ideally hard. 

Please take a look on this aspect under new angle :) There just no point to make item restrictions _outside of dungeon_. At the same time having a lot of space makes trading between player easier and also makes easier 'item managment' - the worst thing in keyboard-based games..

Also lets take a look into logic and world's lore. House is huge. Having one item there on 1 spot is just silly. While character inventory is more or less realistic (weight of items and their numbers), house storage restriction is nonsense. You could put 100500 items in house, it's huge :) If your character could hold 23 items, why floor cant hold them? 

So whole picture - game balance, game UI, usability and comfort; logic and lore; trading stimulation.. 

There are some MMO games with houses. Not any of them got such restriction. Eg in Ultima Online (the most famous housing-MMO) - there is 255 items restriction per container. 255, Carl! 🐻

**Comment by draconisPW** [comment]
As commented above, I simply reverted what I did instead of adding an option. Price is now the same as before.
