### ISSUE TITLE
dungeon flag: to hide treasures in labyrinths

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#248]
yet another thing which will greatly improve game's atmosphere togetheri with https://github.com/draconisPW/PWMAngband/issues/247 - is to dramatically reduce chance to meet labirinths where you 'see' treasures.

Levels with treasures which you 'see' - are very dull and grindy. You just run through them like a vacuum cleaner. No adventure, no suprises. Not roguelikish :disappointed: 

Such levels should be extreamely rare. 

At the same time labyrinths themself are very fun level type. The only problem there - item-esp...

**Comment by igroglaz** [comment]
**gen-cave.c**:
changed from 25 to 5
```
	/* Most labyrinths are lit */
	bool lit = ((randint0(wpos->depth) < 5) || (randint0(2) < 1));

    /* Many labyrinths are known */
    bool known = (lit && (randint0(wpos->depth) < 5));
```

**Comment by igroglaz** [comment]
this way player will be REALLY happy to meet level with shown items and will try to explore it.. while meeting such levels all the time reduce excitement.

it's funny that in TNET I hate Maze levels because they are too hard and dull. But in PWMA I also do not like them cause they are too EZPZ and too wealthy - the easiest levels to find items. The right way IMHO is in the middle - they should be hard to go throught them (no light/item shown), but they should have good items. So it will be an exitement to dwell there. But also a danger.

**Comment by draconisPW** [comment]
This should be a z_info constant.

**Comment by draconisPW** [comment]
Implemented as dun-gen:lab-depth (default = 25) in constants.txt.

**Comment by igroglaz** [comment]
```
# Depth where labyrinths start to be generated unlit/unknown
dun-gen:lab-depth:25
```

Maybe I'm wrong, but not sure that it's precise description of this constant. AFAIU it's a probability to generate unlit/unknown lvl, which is based on depth

**Comment by draconisPW** [comment]
It's exactly that. Above this depth, all labyrinths are lit/known.
