### ISSUE TITLE
Infinite loop on custom stores

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#25]
if there are custom stores added which sell normal; not new, but common, regular items - server would go infinite loop after some time and CPU would rise to 100% and server would freeze to death. eg

```
031119 002658 Admin: Server is no-ghost.
031119 002658 Admin: Server is running version 1.3.0 (Build 4)
031119 002658 Admin:
031119 002658 Admin:
031119 002658 Admin: ====================

..............................

031119 003146 Faraday: You failed to disarm the strange rune.
031119 003147 Faraday: You failed to disarm the strange rune. 
031119 003456 Shutting down.
031119 003456 Goodbye Faraday=Faraday@FaradayLab ("Server shutdown (save succeeded)")
031119 003456 Server state save succeeded!
```

you could see it the gap between 031119 003147 and 031119 003456

**Comment by draconisPW** [comment]
Store must have more than one owner, otherwise the shuffle feature will loop endlessly (Angband stores all have 4). If you want only one, just duplicate the entry.
