### ISSUE TITLE
BETA -> cfg file

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#250]
Please lets add it to .cfg options instead of BETA flag:
_– Don’t close VERSION_BETA servers if an object cannot be placed, but just discard the object
– Allow full home capacity on VERSION_BETA servers_

..as beta will end soon 🐻

**Comment by draconisPW** [comment]
"Don’t close VERSION_BETA servers if an object cannot be placed, but just discard the object"

This is internal and should NEVER be exposed. In case this happens in non beta version, the error should be noticed as this would indicate a bug.

For home capacity, I'll add a z_info option instead. In fact, I plan on moving many cfg options to constants.txt, at least those who don't require being exposed on the client.

**Comment by draconisPW** [comment]
Implemented as store:home-inven-max, 12 by default, set to 24 to always get full home capacity.
