### ISSUE TITLE
server option to forbid selling for ID

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#251]
Please lets add an option to forbid selling stuff to NPC for ID. It's cheezing mechanics which spoil roguelikish fun. _No_selling_ for real! 🐻

**Comment by igroglaz** [comment]
I suppose it's the only left cheezing hole in the system :)

**Comment by draconisPW** [comment]
I prefer the current system. It's more "risk vs reward" oriented. You want to sell all scrolls and potions? Fine, you will avoid that scroll of deep descent early on, but you could sell an early potion of augmentation and just cry because you wouldn't be able to buy it back. I'm not a fan of "forcing" people, especially if you need to ID-by-use all debilitating items in the game.

**Comment by igroglaz** [comment]
We do not have selling on T.. it's disabled to make game more interesting and challening, to remove boring grind. But *ID*ing items with shop - it's still 'selling' mechanics. So it's kinda 'ezpz' way to ID items. Safe way. Non-roguelikish way.

The fun from ID system - is to become surprized. When player give away item to ID - player just removing this roguelikish part of the fun from the game. What the point of having non-IDed scrolls and potions if player just put them to the store AGAIN and AGAIN, without trying the risk? It's really boring and non-roguelikish way.

Point of nonIDed items - they could give you small adventure in the game sometimes. And it's fun. There are still ways to ID items more safe - and player need to think about them - it's great thing. Eg to read scrolls not in the middle of the room in case if it's summon scrolls... Actually there is yet another cheezing way to ID items - just use them on surface... but I just donno how to fix it atm (maybe got any idea?).

For now I've commented out from **store.c** , 2885 line in T:
```
  /* Know original object */
    object_notice_everything(p, obj);
```

**Comment by draconisPW** [comment]
As I said you should not "force" people. There is a "birth" option for that if you really want to play without stores.

**Comment by draconisPW** [comment]
After all why not...
Unfortunately the birth option also prevents buying from shops, so it's a bit extreme. Best is to change no_selling (server) option to a gradual value:
- 0: selling allowed
- 1: classic no_selling (you get 0 gold when you sell)
- 2: full no_selling (you can't sell items)
- 3: no_stores (like birth option)

**Comment by igroglaz** [comment]
`As I said you should not "force" people. There is a "birth" option for that if you really want to play without stores.`

AFAIK we have server-side no-selling:
```
# Option: increase gold drops but disable selling.
# Mirrors "birth_no_selling" on the client if set to true.
NO_SELLING = true
```
So atm at T it's not possible to play with selling for anyone.. But still you can ID items in this cheezy way :(

**Comment by draconisPW** [comment]
Yes that NO_SELLING option will be changed like mentioned above.

**Comment by draconisPW** [comment]
Implemented.

# Option: restrict the use of stores/home.
# 0 = no restriction
# 1 = increase gold drops but disable selling (mirrors "birth_no_selling")
# 2 = disable selling completely
# 3 = restrict the use of stores/home (mirrors "birth_no_stores")
# NOTE: setting this option to 3 makes the game very difficult and is not
# recommended.
LIMITED_STORES = 1

Set to 2 to disable selling.

**Comment by draconisPW** [comment]
The NO_STORES option has been removed. Set the above to 3 instead if you don't want players to use stores at all.
