### ISSUE TITLE
Ring of Escaping -> afraid indicator

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#252]
If you wear Ring of Escaping - afraid indicator doesn't appear on UI, you just can't attack anything in melee

```
name:Escaping
graphics:=:d
type:ring
level:15
weight:2
cost:4000
alloc:50:15 to 80
flags:AFRAID | EASY_KNOW
curse:hallucination:100
values:SPEED[3]
```

**Comment by draconisPW** [comment]
It's there...

![Sans titre](https://user-images.githubusercontent.com/56834278/92225700-de9afa80-eea3-11ea-97c1-3e67ab11beca.png)

**Comment by draconisPW** [comment]
At least this showed me that DM doesn't know "water" rune when he should ;)

**Comment by igroglaz** [comment]
I mean - bottom of main UI window; there Light [x] Fed [x] ... Afraid isn't there if you wear Ring of Escaping

**Comment by draconisPW** [comment]
That's because it's a flag (permanent) and not a temporary effect.

**Comment by igroglaz** [comment]
Yep :) So this /rfe is about making it visible in UI because rings often swapped, so it's important to see what happening with your char in UI. Every important _active_ condition on character state should be indicated at UI.
