### ISSUE TITLE
monster flag RAND_100

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#254]
it will be fun to add RAND_100 flag for monster; it will be cool to have if for fish in pools in wilderness as right now it runs away stupidly, so new players do no see it in the T's lake (while friendly fish will come to you which is bad too.. not natural).. Stationary fish is also boring. RAND_100 for the life! :D

**Comment by draconisPW** [comment]
Was planned for 1.6.0 and shouldn't have been closed.

**Comment by draconisPW** [comment]
Implemented and added to Goldfish instead of RAND_50.
