### ISSUE TITLE
remove sex title

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#255]
/rfe remove title 'Sex does not have any...' at char creat screen cause its remove part of fantasy flavour and mystery. new players do not need to know that stuff.

actully all such tooltips destroys fantasy atmosphere. when player enter the game - he should forget about existance of real-world and dive into the tale. only minimal tech stuff should stay, eg description of commands !, ?, etc which are essential.. telling player that something isn't important - is dull; it's like motivate player to ask - why it's exist in the game anyway?.. ruin atmosphere.

**ui-birth.c**

`    mdata->hint = "Sex does not have any significant gameplay effects.";`

could be replaced for some nice quote from JRRT, eg:
_It is not the strength of the body, but the strength of the spirit._

**Comment by draconisPW** [comment]
Sex has been removed from current V but I decided to not do so because it adds flavor. Idea here is interesting I'll implement it for next build.

**Comment by igroglaz** [comment]
Yep, it gives a lot of flavour. How you can create character without association yourself by sex? :D Poor V...

**Comment by draconisPW** [comment]
Done.
