### ISSUE TITLE
SDL: assign char stats to separate window?

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#256]
Maybe it's a good idea to move all UI elements to separate widnows in SLD client? Then player could make his own UI, eg
https://cdn.discordapp.com/attachments/662334347163992104/753945023728582716/Untitled-1.jpg

**Comment by draconisPW** [comment]
This already exists partially with the "player" 1 and 2 subwindows. V added a "player" 3 subwindow recently for the left part of the screen and I ported the client part of it until I realized it was redefining ROW_MAP and COL_MAP definitions with client values while these are hardcoded on the server AND passed to the client, so I had to revert the change.
