### ISSUE TITLE
ascii_mon: monster's glyphs are too small

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#258]
I wonder is it possible to make monsters glyphs bigger in ascii_mon? eg I got them like this:

https://media.discordapp.net/attachments/662334347163992104/753970533149966405/Untitled-1.jpg

I've tried all kind of setup, but failed to make monster's glyphs looks normal. I either have distorted terrain elements (wrong proportions) and correct glyphs OR small glyphs and right terrain

**Comment by draconisPW** [comment]
Same problem as when the tile is missing and the game displays an ASCII char instead of a tile. It uses the font chosen for ASCII, which is usually smaller. Maybe add a second font for these? I'd like to fix this, even if it's not for 1.6.0.

**Comment by s88100** [comment]
maybe need UTF-8 support, it will increase the number of characters 'glyphs'
already enabled wchar_t  #include <wchar.h>

src/client/ui-term.c 
Term->text_hook = Draw some text in the window
Term->pict_hook = Draw some attr/chars in the window

_for text:_
in Angband https://github.com/angband/angband/blob/master/src/ui-term.c#L657
ui-term.c  Term_queue_chars() uses instead  char *s - > wchar_t *s for UTF-8
```
void Term_queue_chars(int x, int y, int n, int a, const wchar_t *s)
. . .
wchar_t *scr_cc = Term->scr->c[y];
```

https://github.com/angband/angband/blob/master/src/main-sdl.c#L543
main-sdl.c  sdl_mapFontDraw()
`text = TTF_RenderUTF8_Shaded(font->sdl_font, s, colour, bg);`

https://github.com/angband/angband/blob/master/src/main-sdl.c#L2832
main-sdl.c  Term_text_sdl(.. const wchar_t *s)
```
/* Take a copy of the incoming string, but truncate it at n chars */
	wcsncpy(src, s, n);
	src[n] = L'\0';
	/* Convert to UTF-8 for display */
	len = wcstombs(mbstr, src, n * MB_LEN_MAX);
	mbstr[len] = '\0';
```

**Comment by draconisPW** [comment]
The problem was to find a way to tell what was a monster glyph on the client, and I think I found it: monster glyphs use the Term_text_xxx method (since they use ascii), but with a "picture" as background (the underlying tile) while regular text use the Term_text_xxx method without transparency, so it was just a matter of adding a parameter to Term telling if background was picture or not before calling Term_text_xxx and then processing text differently. Now all that is to do is "stretching" the text to the size of the rectangle used in that case.

**Comment by draconisPW** [comment]
Using a bigger font works (make same font but tile_height * tile_width bigger) but for some reason it doesn't display anything unless a manual redraw is called.

**Comment by draconisPW** [comment]
Unfortunately I have no solution to the problem above.

**Comment by draconisPW** [comment]
The only other way would be to use a different tileset where monster tiles are replaced by big ascii letters...

**Comment by igroglaz** [comment]
yep, it will be not bad solution

**Comment by draconisPW** [comment]
Looking at all the code that is written to display text and glyphs and all the method used (line of text, single character, char queued, big char queued...), I see it's a total unoptimized mess that's redrawing stuff ten times more than it should and there is probably a lot that could be done to simplify the thing, but unfortunately I don't have time to fix this mess... :(

**Comment by igroglaz** [comment]
np, one day we can return to this stuff. it's not really important. atm game has incredible stability, no crushes for months ;) so it's better go slow, but preserve today's quality

**Comment by draconisPW** [comment]
Initial display uses Term->text_hook directly to display a character, which displays a little symbol in the corner of a big black rectangle. This is fine and can be adapted to display a symbol covering the whole tile. However later calls (from Receive_line_info or Receive_char) use Term_queue_char_safe() to display the symbol in the corner and then Term_big_queue_char_safe() to fill the rest of the rectangle with black background, and that's the problem. If only I could bypass that "erasing" it would work.

**Comment by draconisPW** [comment]
Alright I decided to remove the 'Display monsters in ASCII' option and add a dedicated tileset instead. Not only it's much easier that way, but this will also add transparency which you couldn't get with just symbols.

**Comment by draconisPW** [comment]
Only problem with that: it takes me half an hour to draw a single tile using Gimp because adding text adds another canvas to the tileset and it's a NIGHTMARE to fuse the canvas with the original one... and there are over 900 tiles to redo. There's no way I can find the time to do this...

**Comment by draconisPW** [comment]
Yeah reverting work done. Unfortunately I don't see a way to do this. Redoing a whole tileset would take months even years and trying to stretch glyphs with a bigger font doesn't work because they get erased later on by update calls. Closing this as not possible to implement. If you have problems with small glyphs, either play full ASCII or use a font that minimizes tile height/width (a 32x32 font would be perfect, 21x31tg font works well too) as this only arises for small fonts.
