### ISSUE TITLE
spawn monsters faster if level got several players

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#259]
One of the reasons why players often prefer to play alone - deficit of monsters. Eg if I meet any player in dungeon - I'm trying to get to another level as faster as I could cause there are not enough 'place' for two players (for 1-49 lvl.. at endgame it's alright I suppose) - so you will loose in monsters/loot at level with other player.

It will be GREAT to be able to play with other players at one level, even thought you will be not in one party (I myself like to be a lone wolf till endgame) - you still could ask for help if needed or come to aid. 

So.. Right now you kinda 'fear' other player's presence cause there will be not enough monsters on level.. Especially in newbie dungeon - even 2 players there will fast eliminate all monsters and won't have much to do - this is pretty critical problem.. Imagine having 3 or 4 lvl 1 monsters in newbie dungeon. Or 5. or 10 :D

/rfe spawn monsters faster if level got several monsters. Maybe this parameter should be assigned in dungeon.txt for each dungeon.. Cause at endgame it's definitely not needed; also in newbie dungeon multiplicator could be 3x for two players, while in other dungeons it could be 2x.

**Comment by draconisPW** [comment]
And maybe also slightly increment the difficulty of monsters depending on how many players are on the level (like Diablo for example).

**Comment by igroglaz** [comment]
Hm.. I'm not sure.. As in Diablo monsters also gives extra experience. While in 'T' getting too much experience is a bad thing which could make you miss opportunities to visit certain dungeons/find better items.

Also we need to count that spawning more often = much more dangerous as OOD monsters could spawn, which wasn't written in feeling.. So in general having faster spawn speed = more OOD mobs which could instakill you.

So now I'm thinking - maybe monsters should spawn faster only at very low level dungeon, like <10.. As later on having high chance to spawn OOD mob is super dangerous and player generally trying to spend at each level as little time as possible so he won't spawn OOD there.

But for low lvls dungeons it will be great improvement. As at low levels there are not much dungeons around and people often bump to each other and trying to get away from each other asap - but it's not always possible to do (eg newbie dungeon).

**Comment by igroglaz** [comment]
Atm we got a some new low lvl players which are a bit tight in 1st dungeon. So it will be fun to add dungeon flag which will increase spawn rate if there are more than one player in the dungeon. For now I see this important only for 1st 'newbie' dungeon...

**Comment by igroglaz** [comment]
**game-world.c**

```
    /* Hack -- increase respawn rate on no_recall servers */
    if (one_in_((cfg_diving_mode == 3)? z_info->alloc_monster_chance / 4:
        z_info->alloc_monster_chance))
```

**Comment by draconisPW** [comment]
- add dungeon flag for faster spawn rate
- double the rate if the flag is set
- apply to first dungeon

**Comment by draconisPW** [comment]
Implemented.

**Comment by igroglaz** [comment]
is it possible to include there parameter "player number"? so the more players on lvl - the fastest spawn will be
