### ISSUE TITLE
items/houses problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#26]
There is a ‘problem’ with storage due special balance of items income in PWMA:
1) ‘birth_no_selling’ generate a lot of items which are optionally useful, but player can’t sell them. The only option is to dump them for later in town areas
2) items income is based at V-Angband which got free huge storage ‘0’ in city; in PWMA you could only buy houses which aren’t cheap and smaller onces doesn’t have enough empty space

It brings a problem that players put their items in ‘tavern’ or just hide them in the world surfaces (in ‘town’ locations items won’t be removed). And it brings yet another problem – ‘free’ items which new players occasinally finds – breaks newbie players experience.

In TomeNET/Mang problem with storage doesn’t exist as there you could sell items. In PWMA 95% of players are going with ‘birth_no_selling’, so we got this problem.

An example of this problem is live on server right now, screenshot:

http://tangar.info/wp-content/uploads/2019/10/items.png

On screen you could see my character and his items which he temporary stores at tavern; I got plenty of scrolls, amulets, rings.. and it’s not all, I dumped some other stuff which I wanted to use later; but I destroyed them not to ruin tavern with too much rubbish.

Now lets imagine there would be items not from 1 player, but from 10. Or 50. Everything woul be covered with several layers of rubbish.

There is a very nice way to solve this problem – to add ‘Home’ (‘0’ in terrain.txt) in custom town, so it work not only for base town in no-wilderness mode, but also in normal more (it could be an option in mangband.cfg).

So it would be a building like a ‘bank’. For ‘1-char/account’ this won’t break game balance, but reduce item managment inconvenience (one of the biggest problem in online roguelikes) and would solve this problem with rubbish. Ideally it would be system where you should pay certain amount of gold to ‘open’ more storage in the bank. But as current ‘0’ not too big, it’s alright as it is for now.

This ‘bank’ won’t remove the need of normal houses – because they could be used as player shops and additional storage; which, again, is very needed in online version of the game.. if player got the game on local machine he won’t notice this problem at all.. but at multiplayer version its pretty critical.

**Comment by draconisPW** [comment]
Whatever you do, people will still drop trash on the floor of town levels. Look at TomeNET, all taverns are plagued with garbage. For storage, you now start with a Deed of Property which allows you to buy a 4 space house. IMO you don't need a house at low level, I'd say you won't have use for storage until level 20 or so and at this point you can easily spare the money for a bigger house.

This is a non issue. At worst, I just need to access the issue of drops in towns. Currently, towns are treated as any other level, meaning everything disappears if there are nobody present or saved on the level. Need to be more restrictive while still allowing drops. Let's say an item disappears when there are nobody present only, that should fix the issue.

**Comment by igroglaz** [comment]
> Currently, towns are treated as any other level, meaning everything disappears if there are nobody present or saved on the level. Need to be more restrictive while still allowing drops. Let's say an item disappears when there are nobody present only, that should fix the issue.

Please don't do it :) At least now it's possible to put items in town for storage, so they won't dissapear.

There is a problem not with a trash in town, but with a problem with item income!

> 1) birth_no_selling’ generate a lot of items which are optionally useful, but player can’t sell them. The only option is to dump them for later in town areas
> 2) items income is based at V-Angband which got free huge storage ‘0’ in city; in PWMA you could only buy houses which aren’t cheap and smaller onces doesn’t have enough empty space

'0' home in town won't break anything, but would remove this issues

**Comment by draconisPW** [comment]
We allow access to the Home in 8f03b24. If not in "no wilderness" mode, the Home can only store 12 objects instead of 24. If in "fast wilderness" mode, the character also start with no Deed of Property (becomes obsolete due to early access to the Home in Carn Dum).

**Comment by draconisPW** [comment]
We wipe all trash on the surface every dawn in edbd5a3. This will prevent all cities and wilderness level to become a garbage dump. This should fix this issue porperly now.
