### ISSUE TITLE
lag bar doesn't work properly under linux (constant flood of `Time Out` message)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#260]
Serega88:
> Constantly writes in the Main window -> Time Out, and LAG:[------] not work.
> PWMAngband-source/src/client/ui-display.c
> in line 335 * Redraw the lag bar
> I exchange /*  the code line 351   /* c_msg_print("Time Out"); */ , and (shift+:) show Message:
> maybe look this https://github.com/mangband/mangband/blob/develop/src/client/c-xtra1.c#L646

**Comment by draconisPW** [comment]
Should be fixed by cfe8f1f.
