### ISSUE TITLE
speed up time when digging

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#262]
if your character got low STR - digging stuff takes very long time. But.. As PWMA got pretty cool system of controlling time - we could make digging work as 'R'... It won't make game any easier as you loose time -> satiation.. If in process of digging your char disturbed by monsters - speed become normal

**Comment by draconisPW** [comment]
1.4.0 already helps by telling if digging actually will work or not, so the player doesn't waste time digging granite when weapon/digger/str doesn't allow it. We could change digging to use bullet time like resting or running.

**Comment by draconisPW** [comment]
Implemented.
