### ISSUE TITLE
Prevent negative value for [MOVES]

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#263]
negative value for [MOVES] is great for race's rebalances. also for some items.

`[22:28] PowerWyrm: I also need to check if "moves" can be negative on cursed randarts, that would be a bug that would also happen in V and I would have to report it there`

**Comment by draconisPW** [comment]
Making the function hyperbolic with 0 as a limit.

**Comment by draconisPW** [comment]
MOVES cannot be negative, I checked the code and it's not possible, energy is capped at what a character can spend and negative moves would do nothing except crash the game. I need to ensure that this is always positive, especially on randarts. For randarts, more checks must be made for other modifiers.

To lower movement for chars, use -SPEED instead. It's more brutal, but is the only way to work with extra energy consumption.

**Comment by igroglaz** [comment]
damm.. :( it's sad that so 'easy' thing like reducing movement speed is impossible to implement in _roguelike_ game; while in any MMORPG it's EZPZ thing.

Having possibility to slow down only player movement, but not other actions - is really great thing which makes gameplay more diverse...

**Comment by igroglaz** [comment]
as energy = base energy / moves... maybe then [MOVES] could be changed to work like speed, but only for movement? so there won't be need to divide.. like a special case of 'speed' parameter

**Comment by draconisPW** [comment]
Cannot work as of Angband's implementation because energy cannot be greater than base energy (it's a hard cap that cannot be removed due to how energy is implemented -- changing this would require redesigning the game completely).

**Comment by draconisPW** [comment]
I've harmonized all modifiers so they can all have negative values, but the result must compel to the minimum value for each one. This means:
- for MANA, STEALTH, SEARCH, INFRA, TUNNEL, SPEED, LIGHT, DAM_RED, no minimum required unless the underlying stat has to be positive
- for BLOWS, num_blows must be >= 1 (one bpr)
- for SHOTS, num_shots must be >= 10 (one spr)
- for MIGHT, ammo_mult must be >= 1 (multiplier of x1)
- for MOVES, num_moves must be >= 1 (energy = base energy)

Concerning MOVES, this means a value of -1 on object or race/class will have no effect, but you will need to find something that has +2 MOVES to counterbalance it if you want to benefit from faster movement speed. At least until the V team finds a way to expand energy differently.
