### ISSUE TITLE
monster feeling always, no object feeling

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#267]
```
# Option: level feelings.
# Mirrors "birth_feelings" on the client if set to 2.
# 0 = no feelings
# 1 = monster feeling on exploration, no object feeling
# 2 = monster feeling always, object feeling on exploration
LEVEL_FEELINGS = 1
```

please lets add an option:
`#3 = monster feeling always, no object feeling`

**Comment by draconisPW** [comment]
Implemented as:

# Option: level feelings.
# Mirrors "birth_feelings" on the client if set to 3.
# 0 = no feelings
# 1 = monster feeling on exploration, no object feeling
# 2 = monster feeling always, no object feeling (<-)
# 3 = monster feeling always, object feeling on exploration
LEVEL_FEELINGS = 3
