### ISSUE TITLE
Change default FPS to something more useful

### ISSUE THREAD

**Issue by jjjj12212** [draconisPW/PWMAngband#268]
Hi Draconis,

Please be aware that I am very new to PWMAngband and never played a Angband before.

I downloaded the master repository yesterday and successfully compiled the windows server and client using Borland Builder 6.

When I tested the game, I'm running both the client and server on the same host.

When I was in the game (After the character creation) I moved 1 tile no problem but when I try to move again, nothing happens until about another minute and then my character moved.

It feels like there is a minute lag per move input and again, I'm not sure if this is normal.
All the other keys works as far as I can tell but just moving seems to be very unresponsive.

I tried both the native window client and the SDL client and both have the same results.

Please note I have kept the configuration files default.

Thanks,
jjjj12212

**Comment by igroglaz** [comment]
> [20:27] PowerWyrm: classic mistake -- if you play the game from compiled version, you don't have a mangband.cfg file so the FPS is set to 1 (1 frame per second) instead of 75 and you move 75x slower
> [20:28] PowerWyrm: fix: go to /setup directory and get the file there, edit to fill your needs

**Comment by draconisPW** [comment]
Default FPS has been changed from 1 to 50.
