### ISSUE TITLE
Add race/class description on character creation screen

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#27]
It would be fun to add space for race/class descriptions. Eg to 1 or 2 spots:
https://cdn.discordapp.com/attachments/535396851713835008/643393802928652288/Untitled-1.png

Eg TomeNET got such char creation:
https://cdn.discordapp.com/attachments/535396851713835008/643394401577467914/Untitled-1.png
It got plenty of space for races descriptions. I would like even more space to tell the truth.. So it would [be possible to add lore+resistances in there. But even a few lines would be better than nothing :)

**Comment by draconisPW** [comment]
This will require a separate screen. Or maybe use the "help" area when pressing a key. Since it's race/class related, I'd like to do this for 1.3, but my free time will probably be really low the next weeks so that will be only if I have time.

**Comment by igroglaz** [comment]
I like idea with separate screen! Is it possible to put it to the '[Term-1]'? It would be really nice :bear:

**Comment by draconisPW** [comment]
Implemented in 89019f0.

**Comment by igroglaz** [comment]
there is a problem with current implementation: '?' it resets cursor position - when you check description with '?' and go to race screen - it starts from human again even if you checked other race

Also '?' way is not comfortable to check every race/class by '?'. It would be great to show descriptions at ''[Term-1]' (current message window)

**Comment by igroglaz** [comment]
race:Barbarian
help:Barbarian - wildlings from the North who spread across all Tangaria after
help: undeads have reasen in the past Dragon war. Barbarians came to all parts of
help: the land willing to seek place for their tribes. At first they  came with a
help: fire and steel, but nowadays, after they met Magic Council dread they become
help: less aggressive and trying to find a compromise.
help: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
help: Barbarians resistant to poison as they had to eat all kind of food to 
help: survive in wildlands.

shown like:
https://cdn.discordapp.com/attachments/596389778992398356/651529045648867328/Untitled-1.jpg

**Comment by draconisPW** [comment]
Yes the description doesn't wrap on line because it's one string and not a list (one entry per line).

In 9ecafa3, I've implemented paragraph splitting using the '|' character. You will be able to insert an empty line like this:

help: less aggressive and trying to find a compromise.|
help: Barbarians resistant to poison as they had to eat all kind of food to...
