### ISSUE TITLE
'solo' flag for monsters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#272]
bunch of Blood Falcons:
https://youtu.be/8IhaWR_y_lw
http://angband.oook.cz/ladder-show.php?id=23971

/rfe maybe add 'solo' flag which will make sure that this particular monster spawned on a level only in one specimen. will be very useful - to apply it on a lot of such dangerous very rare mobs.
OR for now just exclude these birdies from pits..

**Comment by draconisPW** [comment]
Jut add a NO_PIT flag to exclude mobs from pits. Would also apply to death golems to remove a current hack.

**Comment by draconisPW** [comment]
Implemented.
