### ISSUE TITLE
not created by default .mangrc file (Linux)

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#275]
Linux client does not create a default .mangrc (like Mangband) as in file mangclient.ini file [MAngband] nick = pass = host =
https://mangband.org/docs/client-cookbook Where is my config file? On UNIX, it's ~/.mangrc
And does not read through running ./pwmangclient --config mangclient.ini the first header must be [MAngband]

**Comment by draconisPW** [comment]
Feel free to provide any fix to this as I don't understand what this is about.

**Comment by s88100** [comment]
The client .../games/pwmangclient looks for the .mangrc file in the folder /home/user is named (~/)or(HOME) (looks like Documents and Settings in WIN)
In the Linux operating system, a hidden file is any file that begins with a "." all settings are in hidden directories /home/user/ if there is no file, then it creates by default.
But with command make install does not copy mangclient.ini, pwmangclient doesn't see [MAngband] first [Angband] Graphics=0... (mangclient.ini is named .mangrc , 
try to get path to config file from command-line --config path mangclient.ini option) 
In Mangband if there is no .mangrc file it creates. https://github.com/mangband/mangband/blob/master/src/client/c-init.c#L89 
101:/* Read/Write path from config file */
my_strcpy(path, ... conf_set_string("MAngband",
maybe: conf_set_string("MAngband", "nick=" ??
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-init.c#L248
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-init.c#L558

**Comment by s88100** [comment]
There are two ways to save settings. In Angband (ANGBAND_DIR_USER) directory /home/user/.angband/Angband 
also in PWMAngband /home/user/.pwmangband/PWMAngband for example created by default /home/user/.pwmangband/PWMAngband/sdlinit.txt https://github.com/draconisPW/PWMAngband/blob/master/src/client/main-sdl.c#L1953
and like in Mangband settings path /home/user/.mangrc https://github.com/mangband/mangband/blob/master/src/client/c-files.c#L2408
  path_build(buf, sizeof(buf), ANGBAND_DIR_USER, "mangclient.ini"); will create settings in the folder /home/user/.pwmangband/PWMAngband/mangclient.ini
  mangclient_settings_file = string_make(buf);
  .....
  config = file_open(mangclient_settings_file, MODE_READ, FTYPE_TEXT);
https://github.com/mangband/mangband/blob/master/src/client/c-files.c#L2453

**Comment by s88100** [comment]
Settings saves with the command: conf_set_int ,conf_set_string
https://github.com/mangband/mangband/blob/develop/src/client/main-sdl.c#L2744

  src/client/ui-init.c

/* Save default config file if it is scheduled */
void conf_default_save()
{
	static char config_name[MSG_LEN];  /* Config filename */
	static bool conf_need_save = false;	/* Scheduled save */

	ang_file* config;

	if (config = file_open(config_name, MODE_READ, -1))
	{
	conf_need_save = false;
	if (!conf_need_save) return;
	}

	conf_set_string("MAngband", "nick", "PLAYER");
	conf_set_string("MAngband", "pass", "pass");
	conf_set_string("MAngband", "\;host", "localhost");
	conf_set_string("MAngband", "meta_address", "mangband.org");
//	conf_set_string("MAngband", "meta_port", "8802");
	conf_set_int("MAngband", "meta_port", meta_port);
	conf_set_string("MAngband", "DisableNumlock", "1");
	conf_set_string("MAngband", "LighterBlue", "1");

	/* Save config */
	conf_save();
}

**Comment by draconisPW** [comment]
Fixed with #276.
