### ISSUE TITLE
macro by name: '(' symbol

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#277]
I've got item Word of Recall (rugged) - starter recall scroll

If I'll macro it like:

```
keymap-act:[Escape]r"Word of Recall (rugged)"
keymap-input:0:[F12]
```

it won't work; 

in query (to test macro) it shows as: 'Word of Recall ('

this is minor thing.. I could just rename such items if needed

**Comment by igroglaz** [comment]
Also actually 
```
keymap-act:[Escape]r"Word of Recall"
keymap-input:0:[F12]
```
will work on "Word of Recall (rugged)". so it's indeed very minor thing

**Comment by draconisPW** [comment]
This is not a bug but should be just documented: macros (in the keymap menu) are limited to 20 characters (when you reach that value you will see your macro turn "red"). There is a line on the screen that explicitely says it. Just use a name that is shorter, the parser uses partial strings anyway.
