### ISSUE TITLE
several different actions at the same hotkey

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#278]
1)
```
keymap-act:[Escape]U"Teleportation"
keymap-input:0:{K}-

keymap-act:[Escape]r"Teleportation"
keymap-input:0:{K}-
```

Scroll works, staff doesn't work. So even if you have staff in your backpack, but don't have scrolls - staff won't be used.

----

2)
```
keymap-act:[Escape]r"Teleportation"
keymap-input:0:{K}-

keymap-act:[Escape]U"Teleportation"
keymap-input:0:{K}-
```

(other order). works both. But always it 'reads' teleportation scrolls and then it uses staff (if there is no teleportation scrolls in backpack).

It will be fun to be able to be able to have both actions at one hotkey... so even if you have one of each items - they will work - but to make it to use staff first, and if there is no staff - to read scrolls. I wonder is it possible?

There is also a two variants:
3)
```
keymap-act:[Escape]U"Teleportation"r"Teleportation"
keymap-input:0:{K}-
```
and vice versa.. but they just show in input sting:
`U"Teleportation"r`
.. and also we don't want to make double teleport in case if we got two of this items in backpack :)

--

/rfe
so this ticket is kinda about 'order' of actions if they are at the same hotkey.. is it possible to control it? Maybe lower (bottom) or higher action should have a priority and always should work 1st?

**Comment by draconisPW** [comment]
The game is not designed to macro multiple actions on the same hotkey. If you do so, it'll just overwrite whatever you set. Use different keys.
