### ISSUE TITLE
trap out of bounds

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#281]
cmd-cave.c
2084 line
`move_player(p, c, dir, !(square_in_bounds(c, &grid) && square_isdisarmabletrap(c, &grid) && trapsafe), true, false, 0);`

**Comment by draconisPW** [comment]
I incorrectly thought that walking to border of level would trigger this, but this is not the case. The above change takes care of the symptom, but doesn't fix the bug at all. Bug is somewhere else, where we allow walking past the border of a level.

For now, I've added a paranoia check. We'll have to put a breakpoint on that check to find why it happens and track the reason to completely fix teh problem.

**Comment by draconisPW** [comment]
This is probably fixed with #321. I've changed the check to use "quit" instead of just logging the error, so if this happens again we'll get a panic save. I'll reopen if this ever happens again.

**Comment by draconisPW** [comment]
https://github.com/angband/angband/pull/4744

" Saw some out of bounds assertions without that change when running with modified dungeon profiles"

This sounds like a good contender for this bug. Fix implemented.
