### ISSUE TITLE
AttConf status stuck

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#284]
I had AttConf status for 2 streams in a row.
https://www.youtube.com/watch?v=u9ItJaalBn8

```
name:Monster Confusion
graphics:?:w
type:scroll
level:5
weight:5
cost:30
alloc:16:5 to 60
pile:25:2
effect:TIMED_INC:ATT_CONF
dice:10000
```

**Comment by draconisPW** [comment]
Works as intended. As soon as you hit a monster in melee, the status disappears.

**Comment by igroglaz** [comment]
I've fixed this issue by reducing from 10.000 turns (it's just dont make any sense to have such timer) to ~250

**Comment by draconisPW** [comment]
The timer was set to 10000 to simulate that the scroll originally was putting a "permanent" effect on (a boolean in the code). It was just "your next melee attack will confuse something". Of course, for non-melee character (spellcaster, archer) this is irrelevent, hence the idea to make any attack trigger the effect.

**Comment by igroglaz** [comment]
Yep.. but 250 turns is more than enough for melee char to trigger off this effect. No need to have there 10k :D
