### ISSUE TITLE
keymap by command -> w -> item name

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#285]
/rfe by  YAROSSS:

keymap by command > items > wear/wield 
makes
Action:[Escape]w

it will be fun if it will show an inventory so you will be able to choose the item to wield; not to write item name manually

**Comment by draconisPW** [comment]
Not sure what the MAng devs were about with the "keymap by command" feature, but I think it was just to translate Enter menu into commands. I'd rather enhance the "keymap by item" to use "w" by default on wearables (currently it is limited to usables).

**Comment by draconisPW** [comment]
Implemented as above (keymap by item).
