### ISSUE TITLE
font-xxx.prf or font-custom-xxx.prf system

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#286]
I'm working on porting my 1 bit tileset https://tangar.info/en/t/tileset to tangaria

1) I setup monster monster:Uvatha the Horseman:1:205 to font-sdl.prf
2) it will work for my fonts where I have special symbol for Uvatha (eg 21x31 font).... but if player will switch to other fonts (not mine, but common ones, eg 10x14x.fon) - he won't be able to see Uvatha at all as at 205 it's empty.

I see there 4 workarounds
1) implement custom font system (like in tomenet), so each custom font will work with it's own prf
2) use only my font in tangaria distribution - I made 23 different sizes... from 5x8 to huge ones.
3) rename manually font-sdl.prf to font-sdl.prf.default (so if player wanna play with my fonts - he uses special .prf for it)
4) implement game option which will swap font-sdl.prf files automatically (like in #3, but will use just two files: font-tangar.prf and font-sdl.prf ). as all my 23 fonts got the same layout.. no need to make custom prfs like in tomenet for each size

---
also this:
5) port to all existing fonts additional tiles... I suppose some of sizes exist in my 23 collection.. so will be easy to port - so ppls will be able to play with regular font (glyphs) and custom mobs... for people who wanna regular onces - could just use default .prf

**Comment by draconisPW** [comment]
For now just use a special file. This is custom client prf and should never impact anything else.

**Comment by igroglaz** [comment]
Yep.. but I wanna provide Tangaria with 1bit tileset by default in classic client.. it makes hard choice which workaround to use than

**Comment by draconisPW** [comment]
Just create font-tangar.prf and add in documentation that you need to replace font-sdl.prf by that file to use your custom mapping.

**Comment by igroglaz** [comment]
it won't be `default` solution. I wanna impress player with cool features by default. but if someone will want use oldschool way to play without monster-glyphs - he could use font-sdl.prf.default

**Comment by flambard-took** [comment]
Not sure if this is still relevant, but here's what we did for MAng, https://github.com/mangband/mangband/blob/develop/lib/pref/font.prf#L43 and this `$FONTFILE` variable was easy to hack in into pref loader.

**Comment by draconisPW** [comment]
Implemented as per MAng: if font selected is 21x31tg.fon or 24x36tg.fon AT START in the SDL client, font-tng.prf is loaded instead of font-sdl.prf. All you have to do is add your mappings in font-tng.prf and you're set!
