### ISSUE TITLE
allowing hydra/dragon polymorph cause glitch

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#289]
1) project-player.c -> project_player_handler_MON_POLY -> trace `player_has(hydra)`
2) commented hydra out there
3) now hydra could be polymorhed. Polymorph it in PvP
4) now polymorph it back. it will become not M, but @.. and not visible to players

**Comment by draconisPW** [comment]
I've added a check so that poly_hydra() and poly_dragon() are called when the player logs in, not only for new characters. This will ensure he stays as a hydra or dragon even if monster.txt evolves.
