### ISSUE TITLE
can't compile client with #ifdef BCC7

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#290]
https://github.com/draconisPW/PWMAngband/pull/288/commits/325462d6188357e3d1a3367fc248d38eaf00d9dc

need a define for BCC7

**Comment by draconisPW** [comment]
I'm an idiot... The define is not included on the line that launches the resource compiler so it is not recognized.

**Comment by draconisPW** [comment]
Fixed.
