### ISSUE TITLE
SDL client shows limited amount of fonts

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#291]
<img width="334" alt="1" src="https://user-images.githubusercontent.com/39904162/102909403-f9f93800-4489-11eb-9592-bc6469f872da.png">

I've got 50 fonts in total. But SDL client shows in options only ~27

**Comment by draconisPW** [comment]
Two issues here:
1) the SDL client only recognizes "xxx.fon" and not "xxx.FON"
2) the number of fonts is limited to 40

**Comment by draconisPW** [comment]
Fonts can now be loaded from ".FON" files + the max number of fonts has been raised to 60.
