### ISSUE TITLE
font-xxx.prf format: use default color

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#292]
atm format in font-xxx.prf:
monster:<name>:<color>:<glyph number>
eg
monster:Uvatha the Horseman:1:205

it will be much easier to map stuff there if there will be possibility to inherit color from monster.txt (or terrain.txt), so it will be possible to use:
monster:<name>:<glyph number>:<color>
eg
monster:Uvatha the Horseman:205

if there is empty last value - we use default one from monster.txt

**Comment by draconisPW** [comment]
This cannot be done as parse_prefs_monster() is used on both client and server for other things. For this, we have to introduce a new parser function, similar to what was done for "feat" lines in "font-xxx-.prf" files (using the new "glyph" parser function).

**Comment by draconisPW** [comment]
Implemented as "monster-char : name : char"
