### ISSUE TITLE
font-xxx.prf format: colors from numbers to glyphs

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#293]
atm font-xxx.prf using numbers for colors - from 1 to 27, eg
monster:Uvatha the Horseman:1:205

https://tangaria.com/wp-content/uploads/2019/10/colors.jpg

it will be fun to use not numbers there, but glyphs, eg

monster:Uvatha the Horseman:1:205,
monster:Uvatha the Horseman:w:205

**Comment by draconisPW** [comment]
This cannot be done as parse_prefs_monster() is used on both client and server for other things. For this, we have to introduce a new parser function, similar to what was done for "feat" lines in "font-xxx-.prf" files (using the new "glyph" parser function).

**Comment by draconisPW** [comment]
Implemented as "monster-attr : name : attr : char".
