### ISSUE TITLE
Allow all alter/teleport effects to be used on items

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#299]
in T problem with ALTER_REALITY at scroll

```
name:Dimension Shake
effect:ALTER_REALITY
```

as  TELEPORT_LEVEL got NONE:1 , we need to add it to ALTER_REALITY too

1) in cmd-obj.c

**case EF_ALTER_REALITY:**
case EF_TELEPORT_LEVEL:

2) in effects.c
static bool effect_handler_ALTER_REALITY(effect_handler_context_t *context)

	**/* Hack -- already used up */
	bool used = (context->radius == 1);**

and 

2x 	**return !used;**

3) in gamedata add :NONE:1 to ALTER_REALITY in items (in T)

**Comment by draconisPW** [comment]
Items that alter the enviromnent or teleport the player needs to be used before applying the effect, otherwise they become empty objects and crash the game.

**Comment by draconisPW** [comment]
Implemented for:
- ALTER_REALITY (add effect:ALTER_REALITY:NONE:1 in object.txt)
- BREATH (already existing)
- GLYPH (already existing)
- TELEPORT (already existing)
- TELEPORT_LEVEL (already existing)
- TELEPORT_TO (add effect:TELEPORT_TO:NONE:1 in object.txt)
