### ISSUE TITLE
shops refreshing while player inside

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#3]
Shop refreshing it's goods while you 'inside' (lookin at list of items). So eg when you want to buy a flask of oil, shop could refresh and you would buy different item not knowingly.

**Comment by draconisPW** [comment]
This is not suppsoed to happen, shops should be "locked" when someone is inside. Sounds like a regression, I'll look into it.

**Comment by draconisPW** [comment]
Shop ID is zero so the check store_num == sidx fails when checking if a player is inside the store. Sounds like I started to refactor some store code and I didn't finish.

**Comment by draconisPW** [comment]
Fixed in 4d020fa.
