### ISSUE TITLE
shapechange feature

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#30]
[22:25]tangar:
> @ list-player-flags.h there is SHAPECHANGE flag
> and @ player-common.h
> /* Necromancers can turn into an undead being */
> maybe it's possible to unhardcode such feature in future? so it would be possible to assign certain forms to certain race?

[01:44]PowerWyrm:
> this is shapechange feature from 4.2 vanilla
> in fact that's a nice idea to add for 1.4 version, since there's already polymorph for classes (druid, necromancer)
> add same for races

**Comment by draconisPW** [comment]
Class work done in 4f89311.

**Comment by draconisPW** [comment]
Race shapes implemented in db9320e.
