### ISSUE TITLE
teleport rings/amulets - faster 

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#301]
PWMA:

```
name:Teleportation
graphics:=:d
type:ring
level:10
weight:2
cost:1000
alloc:20:10 to 50
flags:EASY_KNOW
curse:teleportation:100
values:SPEED[2]


name:Teleportation
graphics:":d
type:amulet
level:10
weight:3
cost:10
alloc:20:10 to 40
flags:EASY_KNOW
curse:teleportation:100
desc:This amulet will randomly teleport you all over the place.
```

There is a problem with tele rings/amulets - they are pretty useless because the rate of their activation is very low; I mean - they teleport you very rarely. So they can not be used as escape option for low-levels. In MAng and TomeNET I used such amu-rings pretty often on swap with @w0 and it was pretty fun. Actually it's my favorite escape option as it requires some gamblins, adrenaline, action... not just push one button to use stuff, but swap items.

Also there is no far-espace option for 1-20 lvl (till you buy tele staff), so this rings/amu had a real purpose before; while now they are useless.. it was crappy of course (not reliable) as you could be unlucky. but for eaely levels it's what's needed... it gives proper roguelikish feeling when you use it (rng fun).

/rfe make teleportation curse activation rate on common ring/amu like it's in MAng; while leave teleport curse rate for other items, like randarts - the same. I suppose it's better to be done with a new flag

p.s.
btw my 1st ever adventure were with such ring :D https://www.youtube.com/watch?v=Fc0PUsyu0-Y

**Comment by draconisPW** [comment]
I'll just put here for reference but this won't probably ever change. Those items are supposed to be junk, their activation should be annoying, not useful.

**Comment by igroglaz** [comment]
np, I'll fork sources and will change it myself one day :(
