### ISSUE TITLE
problem with staircases short-description

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#302]
examples from T:

when you 'l'ook at NPC:

```
name:Sonya the cat
graphics:f:W
priority:18
flags:SHOP | PROJECT | PASSABLE | PERMANENT | INTERESTING | EASY
info:9:0
################################################################################
short-desc:tiny cream colored siamese cat with yellowish brown-green eyes.
desc:Cat looks at you with interest.
```

'l'ook will show short-desc:
**tiny cream colored siamese cat with yellowish brown-green eyes.**

when you 'l'ook at stairs:
```
#15
name:stair down 2
graphics:>:w
priority:18
################################################################################
short-desc:Severs Entrance. Next <20lvl: Orc Mountains[1,2], Fetid Swapms[-1,0]
flags:LOS | PROJECT | PASSABLE | INTERESTING | STAIR | DOWNSTAIR | EASY | TORCH
desc:A staircase down to a deeper part of the dungeon.
```
'l'ook will show:
**You see the entrance to The Severs.**

Only in bottom part of UI you will see fragment of description:
https://cdn.discordapp.com/attachments/699917093717671946/809741166097596436/Untitled-1.jpg

...which is not useful as it's not possible at all to see full description, it's cutted.. full is:
**Severs Entrance. Next <20lvl: Orc Mountains[1,2], Fetid Swapms[-1,0]**

**Comment by draconisPW** [comment]
It's just a wrong use of the descriptions.

- "Severs Entrance. Next <20lvl: Orc Mountains[1,2], Fetid Swapms[-1,0]" should be mapped to "desc"
- "short desc" should contain a "short" description

And it's "sewers" by the way :D

**Comment by draconisPW** [comment]
Proper way to use descriptions:

- short-desc: Sewers Entrance
- desc: A staircase down to the Sewers dungeon. Go to (1,2) for Orc Mountains or (1,0) for Fetid Swamps next.

Proper way to get descriptions:
- look: "you see the entrance to the Sewers" (uses dungeon name)
- press "r" on the stairs: popup with "name" as title and full description
- status line: short description

**Comment by igroglaz** [comment]
Thanks, it's a good solution indeed :) I really forget about 'r' option.

Maybe lets add a description of 'l' command in brackets, like in TomeNET:
https://cdn.discordapp.com/attachments/699917093717671946/811271303327514685/Untitled-1.jpg

It will be a good hint for a new player... as even experienced players forget about this option :)

Also it reminded me about this issue: https://github.com/draconisPW/PWMAngband/issues/51 ... Moving 'r' around will be HUGE breakthrough... it's super important issue - we will be able to get a lot of MUD players with this thing.
