### ISSUE TITLE
removing class/races flags at certain level

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#309]
Archer class in T got brand:5:POIS_2 ... it will be great to make it possible to remove this brand at certain lvl of character development. Eg this buff should work at 5-30 lvls, afterwards it should dissapear

**Comment by draconisPW** [comment]
Brands and slays now have a max level as well as a min level, for example:
brand:5:30:POIS_2

**Comment by draconisPW** [comment]
Rest are innate flags and won't change since innate abilities don't go away like that.
