### ISSUE TITLE
[feature] susceptibilities which couldn't be covered with resistances

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#31]
It would be really fun to have susceptibility property which isn't possible to 'cover' with resistances. Eg right now if race susceptible to light - it's very easy to 'fix' it by wearing light resistance item - and this character won't every would remember about this problem (it makes playing vampires in TomeNET especially easy and kinda imba).

I suppose some uber artifacts or races could have 'strong' susceptibility to certain minor elements (light/dark for example), so it would make game rebalancing more interesting.

Rightn now we got such numbers:
[-1] [1] [3] - susceptibility, resistance, immunity

[-3] could be vulnerability

Some more ideas:
1) Maybe it would be fun to add such mechanics also - make this 'strong' vulnerability possible to cover with immunity. So if character got [-3] to certain element - by wearing immunity item - he could cover it to normal or even become resistant to it (but not immune)
2) What about double immunity (when you drink a potion). Is it possible to add it as separate flag equipment? So it won't be full immunity, but would cut damage more than resistance.. [2] flag :) If it's possible to implement, maybe it would be also interesting to add [-2] flag as well (double vulnerability)

**Comment by draconisPW** [comment]
Closing this as it would mean a death sentence to anything with the flag which would make nobody ever play the corresponding race. I've already added VULN_FIRE to Ents, which IMO is a too big penalty (133% damage from fire, 100% with resist and 33% with double resist which is only available via limited means unless you're willing to carry tons of resist fire potions) and I'm seriously considering removing it. So adding full vulnerability is out of question.

**Comment by igroglaz** [comment]
As I said, it's could be good for minor elements, like light/darkness

**Comment by draconisPW** [comment]
There are no such things as "minor" element. Ungoliant casting a darkness storm at a player with vulnerability of darkness would mean instant death without ANY chance to avoid it... NEVER. Same goes with the Phoenix breathing light. This would mean completely reworking the elemental damage system, not worth it imo.

**Comment by igroglaz** [comment]
Hm.. So we don't have 'cap' for damage? This problem doesn't exist in TomeNET cause of 'caps' limitation of damage. 

Eg, Phoenix: http://muuttuja.org/tomenet/monsters/monster.php?743 would breath 'light' with maximum damage capped at 400 https://tomenet.eu/guide.php?chapter=5.6&highlight=Light#r256

Ungoliant http://muuttuja.org/tomenet/monsters/monster.php?808 darkness is also limited to 400 https://tomenet.eu/guide.php?chapter=5.6&highlight=darkness#r261

So with such caps people often play TomeNET at 50 lvl without light resistance and could manage it. It would be fun to have such caps in PWMA :rainbow:

**Comment by igroglaz** [comment]
I suppose such SUSP, which can't be covered by resistances should work this way:
add additionals % of damage over resistance. It should be quite low amount, like 10%; but it still matters. It will give nice flavour to races and will help to rebalance
