### ISSUE TITLE
constants: dun-gen -> lab-depth -> unlit/unknown

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#310]
in constants.txt 
instead of one modifier dun-gen:lab-depth ( # Depth where labyrinths start to be generated unlit/unknown ) - make two midifiers 1) for chance for unlit 
2) chance for unknown
because unknown chance should be much higher.. while unlit should be ~25 (default value in PWMA). so it will be like this:

```
dun-gen:lab-depth:unlit:25
dun-gen:lab-depth:unknown:1
```

**Comment by draconisPW** [comment]
Changed to:
dun-gen:lab-depth-lit:25
dun-gen:lab-depth-known:25
dun-gen:lab-depth-soft:35
