### ISSUE TITLE
new effect: light up lvl

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#311]
atm there is a spell **effect:LIGHT_LEVEL:NONE:1**; it make:
1) map all lvl (like magic mapping)
2) light up the lvl (so it's not dark)
3) show all objects (treasure detection)

I wanna change it in T so it won't show all objects (remove treasure detection). 

/rfe to add new effect: to light up the lvl (as we got separate effects for mapping and treasure detection)

**Comment by draconisPW** [comment]
effect:LIGHT_LEVEL:NONE:x will now do:
- 0: sense objects
- 1: detect objects
- any other value: don't show objects
