### ISSUE TITLE
noteye doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#312]
it seems noteye doesn't work. I've installed it using the guide: https://tangaria.com/faq#noteye
when I start noteye.exe I see the menu and I see PWMAngband there (under 'p').. when I push 'p' background changes to black, but nothing happens... when I push F4 I see the menu. When I push F4 again - it's just blank black screen

tried with host in D:\games\Tangaria\noteye\pwmangband.ini and without.

**Comment by igroglaz** [comment]
checked server - client does not try to connect.

**Comment by draconisPW** [comment]
I've downloaded it again and there's a crash whenever I try to run the frontend. I guess it's not maintained anymore.

**Comment by draconisPW** [comment]
Im' gonna remove the reference for future versions. No need to maintain something that doesn't work anymore.

**Comment by igroglaz** [comment]
fix by @s88100 :
```
decided how to run NotEye:hiho:  http://www.roguetemple.com/z/noteye/download.php
1. NotEye Roguelike Bundle NotEye 8.2 http://www.roguetemple.com/z/noteye/RLBundle-15.zip (bundle.noe, rlbundle.bat cool menu)
2. UPDATE (Mar 11, 2017): the bundle does not work on some systems because of a bug. Replace noteye.dll (in "noteye" subdirectory) by this file http://www.roguetemple.com/z/noteye/noteye.dll ( maybe need to compile the latter 2017 from github Makefile.mgw mingw ? )
3. \RLBundle\noteye copy and replace noteye.dll
4. edit \common\noteye.noe (for NotEye 8.2) \vep\vp - PWMAngband")  menugames["p"] = "pwmangband"
5. other files copy as in noteye.bat installer
terminal game starts and the splash screen freezes in noteye maybe need to edit \games\pwmangband.noe ?
NetHack works.
```

**Comment by draconisPW** [comment]
This fix doesn't work with either the old dll or the replaced one. In the first case you get "function not found in dll" and in the second case the frontend simply crashes at start.

**Comment by igroglaz** [comment]
noteye made commit recently:  https://github.com/zenorogue/noteye/commit/1a39097f3f5234083027deb0b8ac15d79c60533f

**Comment by igroglaz** [comment]
"I've downloaded it again and there's a crash whenever I try to run the frontend. I guess it's not maintained anymore."

so it seems it's maintained. Should we create an issue ticket https://github.com/zenorogue/noteye/issues ? lets fix it - it was very unique feature of PWMA!!

**Comment by s88100** [comment]
TCP/IP connection doesn't work Linux/Windows

second variant is to compile src/client/main-noteye.c (as in main-gcu.c) https://github.com/zenorogue/noteye/blob/master/sample/c/sample.c
```
#include "../../src/noteye.h"
#include "../../src/noteye-curses.h"
```
NotEye development guide http://www.roguetemple.com/z/noteye/dev.php
mangclient_gcu.exe + noteye.dll
but NotEye doesn't work with WINDOW * win subwindow, need to display 'Term-0' in full screen.
NotEye does have Curses-like output https://forums.roguetemple.com/index.php?topic=3884.0
