### ISSUE TITLE
Add modifiers to races/classes

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#32]
it would be great to unhardcode 'speed' @ player-calcs.c :

            /* Ent: penalty to speed */
            /* Unencumbered monks get speed bonus */
            /* Rogues get speed bonus */

Right now there is only SPEED_BONUS for rogues which could be assigned..

There is a wonderful possibility to assign interesting progress for certain races. Adjustment for speed property could greatly help in rebalance, eg trolls (not half-trolls, but pure trolls from Tangaria) could have:

value:1:SPEED[0] #young troll
value:25:SPEED[-1] #mature troll become heavier and more huge when become more experienced.. and slower. But he got additional resistance
value:50:SPEED[-3] #ancient trolls are slow.. but their skin is like stone

This values are just an example, not a real parameters.. Another example - undeads, could have vice versa situation:

value:1:SPEED[-2] // 'fresh' reanimated
value:25:SPEED[-1] // more dangerous 'zombie'
value:50:SPEED[0] // fully evolved undead

It would be great to have [x] as not a flag like in resistance/immunity, but an absolute value, so it would be possible to assign speed like it work on items, eg:

```
name:of Nevrast
base-object:boots:Pair of Leather Sandals
info:30:15:0
alloc:0:30 to 127
power:1:1d1:0:0:13
values:STEALTH[4] | SPEED[4]
```

Also it would be great to be able to reassign numeric (absolute) values for stealth, infravision, stats (STR, DEX etc)... Right this stats statically bound to races of course, but if there would be such 'value' for races/classes - it would be possible to make really interesting character progression over lvls.. So for example, young vampire would have low infravision at beginning, but at lvl 50 it would be much better. So it would be awesome if there is a possibility to assign list-object-modifiers.h : 

OBJ_MOD(MANA)
OBJ_MOD(STEALTH)
OBJ_MOD(SEARCH)
OBJ_MOD(INFRA)
OBJ_MOD(TUNNEL)
OBJ_MOD(SPEED)
OBJ_MOD(BLOWS)
OBJ_MOD(SHOTS)
OBJ_MOD(MIGHT)
OBJ_MOD(LIGHT)
OBJ_MOD(POLY_RACE)
OBJ_MOD(ANTI_MAGIC)

and list-stats.h too :)

**Comment by draconisPW** [comment]
Should be pretty straightforward.

**Comment by draconisPW** [comment]
Preliminary work in f47a38b.

**Comment by draconisPW** [comment]
First draft in 0806bea.

Note that this only allows fixed modifiers for now. This un-hardcodes speed penalty for Ents and extra mana capacity for Sorcerors and Elementalists, which now gain a flat +50% and +30% extra mana capacity instead of a multiplier of 1.25 to their mana pool. Makes the classes easier at start (150%/130% mana instead of 125%) and roughly similar with +10 mana gloves (250%/230% instead of 250%).

**Comment by draconisPW** [comment]
Replaced stats by modifiers for race/class entries in ac12dab.

**Comment by draconisPW** [comment]
Replaced infravision by modifier in dfad70f.

Note: stealth, searching and digging are race/class SKILLS, these will NOT be replaced by modifiers. Adding STEALTH, SEARCH or TUNNEL as a modifier for a race or class will simply add/substract that value from the corresponding skill, as if the player was an object.

**Comment by draconisPW** [comment]
Random modifiers implemented in 3c60547.

Values may now be defined as value:level:MODIFIER[a+xdy] to specify a starting value of "a" at level "level" and then an increment of "x" every "y" levels.

For example, we will define: value:5:SPEED[1+1d15] for rogues to specify a speed bonus of 1 at levels 5, 20, 35 and 50.

**Comment by draconisPW** [comment]
Didn't have time to finish this, will resume in next version.

**Comment by igroglaz** [comment]
> For example, we will define: value:5:SPEED[1+1d15] for rogues to specify a speed bonus of 1 at levels 5, 20, 35 and 50.

This modifier looks a bit confusing. Maybe for just make it simple and minimalistic? Like 
value:5:SPEED[1]
value:20:SPEED[1]
value:35:SPEED[1]
value:50:SPEED[1]

Actually it would be even easier to see the progress through levels with such view; eg if there would be more then one modifier:

value:5:SPEED[1]
value:5:STR[1]
value:10:DEX[1]
value:20:SPEED[1]
...

It could be bulky, but it's really easy to look though overall progress of class

**Comment by draconisPW** [comment]
This would heavily complexify the code (array of modifiers), so out of question. The random value keeps it simple.

**Comment by igroglaz** [comment]
Gotcha :) Anyway there is an option to use this and that way. I just thought it was hard to inmplement this particular xdx thingy, when you said "Didn't have time to finish this, will resume in next version." But as I tested the game and it's already there, I see that it's not an issue

**Comment by draconisPW** [comment]
Final work in 9314861. This un-hardcodes everything else except extra shots for Rangers using bow (FAST_SHOT) and extra shots for Monks/Archers using thrown missiles (FAST_THROW) which still use a player flag.

Important note: adding BLOWS as a race/class modifier will add an increment of 0.1 while BLOWS as an object modifier will add an increment of 1.

**Comment by igroglaz** [comment]
> 21:16]PowerWyrm:hope I remember it tomorrow, if so I'll add an upper limit to the modifiers -- random value has a fourth parameter (M) that can be used, so for example value:0:CON[1+1d5M10] could be used to say +1 CON at levels 1, 5 and 10 (+1 per 5 levels and we stop at 10)

**Comment by igroglaz** [comment]
I got an error when try to assign for race:
value:1:SPEED[-1-1d35]

(so it would have -1 speed at lvl 1 and one more -1 at lvl 36)

**Comment by igroglaz** [comment]
just wanna add note there that this feature is kindly implemented, so it's possible to use eg:
value:1:CON[-1+-1d5M10]
