### ISSUE TITLE
Linux client with --config parameter doesn't see 'nick', 'pass' option

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#320]
starting the client with --config parameter ./pwmangclient --config 'file'
sets by default Name: PLAYER, Password: (default) , and do not see 'nick' in the file

Try to get path to config file from command-line "--config" option
https://github.com/draconisPW/PWMAngband/blob/master/src/client/conf.c#L479

I think the problem is in conf_default_save()
https://github.com/draconisPW/PWMAngband/blob/master/src/client/conf.c#L626

if disable then shows Name: Player1 (example)
but the file .pwmangrc should be create by default

**Comment by s88100** [comment]
Change a "string" prefrence and schedule save  `conf_set_string()`
Change an "integer" value. All values are stored as strings. ` conf_set_int()`

conf_set_string, conf_set_int saves and assigns the parameter
example `conf_set_string("MAngband", "nick", "PLAYER2");` - shows Name: PLAYER2

if used '--config' option then don't check conf_default_save() or conf_set_string

**Comment by draconisPW** [comment]
Fixed with latest pull request.
