### ISSUE TITLE
player out of bounds in 1st dungeon

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#321]
p is generated outside the level of the first dungeon (0,0):
```
[00:20] Dawndeath: ok the value out of bounds is grid.x (181 should be < 146)
[00:34] Dawndeath: i'll ahve to look in every profile that can be generated at depth 1 if player can be put outside of bounds
```

**Comment by draconisPW** [comment]
This will be extremely tough to fix as it seems to happen once in a million level generations and once the level is generated there is no way to tell what went wrong. I'll have to add some debug code and hope this get triggered again.

**Comment by draconisPW** [comment]
First dungeon can only be one of: classic, modified, arena. Both classic and arena levels have max size (height=66, width=198), so this problem cannot happen. The bug has to happen on "modified" profile. I've added the profile in the cave structure so that we have a reference in case of a crash after cave generation that is related to cave generation.

**Comment by draconisPW** [comment]
New check for wrong player placement added, let's see if this gives extra info when the problem happens again.

**Comment by draconisPW** [comment]
Latest crashes shows that indeed the crash happens for a "modified" profile, but doesn't trigger the debug code for out of bounds player placement, which tells that either it happens before original player placement or after original placement. I'll do a "stress test" with Tangaria's /lib directory to try and reproduce the problem.

**Comment by draconisPW** [comment]
Bug reproduced locally ;)

**Comment by draconisPW** [comment]
Ok this has nothing to do with player out of bounds or with first dungeon. When a player enters a new level, for a moment its (x,y) position is still the one on the old level while it's depth has changed to the new level. Meanwhile monsters with more energy are processed in update_mon() where we do a update_mon_aux() for all players on the level. The update should NOT be done for players switching levels.

**Comment by draconisPW** [comment]
Should be fixed now.

**Comment by igroglaz** [comment]
mon-util.c
update_player()
[22:37] Dawndeath: ok before "update_player_aux you will add the following:
`if (!p->placed) continue;`

**Comment by igroglaz** [comment]
mon-util.c
void update_players(void) 

[15:46] Dawndeath:
```
struct player *p = player_get(i);
if (!p->placed) continue;
update_player(p);
```

**Comment by draconisPW** [comment]
Fixed again :)

**Comment by igroglaz** [comment]
mon-util.c
void update_player(struct player *q)
after 		`if (!p->placed) continue;`
add
`	if (p->is_dead) continue;`

**Comment by draconisPW** [comment]
FIxed again.
