### ISSUE TITLE
necromancer's form fruit bat do not give levitation flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#324]
RF_LEVITATE monster flag doesn't give OF_FEATHER to player using the form

maybe it's because - this flag does not exist in monsters.txt, but in monster_base.txt (it's monster's "family" flag)

yet another problem - players in fish form (shapechangers) running around in fish form... looks a bit stupid :)

**Comment by draconisPW** [comment]
And I need to check if there are no other flags missing...

**Comment by draconisPW** [comment]
Monster flags:
- RF_FRIGHTENED -> OF_AFRAID
- RF_LEVITATE -> OF_FEATHER

Fixed damaging terrain aborting running for players immune to damage (ie immfire players not able to run in lava or aquatic mimics not being able to run in water).

Fixed aquatic mimics not suffocating outside of water.

**Comment by draconisPW** [comment]
Oh and aquatic mimics were drowning in water because the code was only checking vs IM_WATER and not AQUATIC :D
