### ISSUE TITLE
add account name to log files

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#325]
right now we got:
220321 163401 Welcome <char_name>=<OS_login>@<PC_name> (xxx.xxx.xxx.xxx) (version 1500)
220321 163425 Player Name is [<char_name>], id is <123>

and with it it's pretty hard to analyze logs for cheating activity (multiaccounts etc) cause there is no account name in it

/rfe
add account name to logs so it will be easier to analyze the data

**Comment by draconisPW** [comment]
Sure I can do that, but when you have only one character usually the account is the same...

**Comment by igroglaz** [comment]
some players create several accounts to cheat... and atm it's hard to track such activities

**Comment by draconisPW** [comment]
I see.

**Comment by draconisPW** [comment]
Nothing to do. In fact, the messages are:

Welcome <account_name>=<OS_login>@<PC_name> (xxx.xxx.xxx.xxx) (version 1500)
Player Name is [<char_name>], id is <123>

First line is account name, not char name.

**Comment by igroglaz** [comment]
ooook :D sorry for my stupidity. I was confused by a player who played not two, but 3 accounts, so I thought at first that it's char names. thanks :)
