### ISSUE TITLE
Keymap by spell quotes problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#326]
reproduce:
1) mage character
2) create keymap by spell
3) choose "Find traps, doors & stairs" and assign to ctrl+6 (numpad)
4) try it - it will work
5) exit the game and enter it again
6) try it - it won't work. you will see macro without " (quotation mark) at the end.

screenshot: https://cdn.discordapp.com/attachments/699917093717671946/825269531265073182/Untitled-1.jpg

**Comment by draconisPW** [comment]
OK I've checked all spells and "Find traps, doors & stairs" is the longest name, topping at exactly 30 characters. I'll increase KEYMAP_ACTION_MAX again from 30 to 35 so there's no more problem.

**Comment by draconisPW** [comment]
Fixed.
