### ISSUE TITLE
shift+.  macro problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#333]
reproduce:
1) assign macro to` shift`+`.` (numpad):
`{/a!O[Enter]`
2) save it.. it will work. running also will work
3) exit the game - and reenter.. macro won't work afterwards... it will be rewritten by `^@`

at the same time `ctrl`+`.` macro:
`}/a`
 works alright

**Comment by igroglaz** [comment]
the same thing happening when I made macro for ~ (shift+`).. it become replaced on ^@... by default ~ it is "display current knowledge"

**Comment by draconisPW** [comment]
This will require some investigation. The macro is properly saved as {/a!O[Enter], but loaded as ^@.

**Comment by draconisPW** [comment]
Ok found the problem. Characters '\', '[', '{' and '^' are reserved and cannot be used in keymaps. This means you cannot make a keymap with the "inscribe" command.

**Comment by draconisPW** [comment]
I added hacks for the reserved characters so that it's treated as that character if it's doubled. It was already the case for '\\', so I added the same for '[', '{' and '^'.

**Comment by draconisPW** [comment]
Same bug in V code, I'll report that on Angband forums.

**Comment by draconisPW** [comment]
In fact, all reserved symbols are fine except '{'. For '[' and '^', the code saved an "escaped" version of the symbol and checks for it when loading the keypress. This is not the case for '{' and this is the only thing to fix.

**Comment by draconisPW** [comment]
Fixed. Now the macros are saved and loaded as \{/a!O[Enter].
