### ISSUE TITLE
/ commands-alternatives for shift+1...4 commands

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#334]
I wanna map  "~" hotkey for a spell.. but then I won't be able to see "display current knowledge" window. Players need very rarely so see this window so it will be alright to assign it to / command. Not replace, but add an alternative commands. So lets ~ by default still be "display current knowledge", but if someone wants to remap it - he will be able to use / command.

It will be great to add bunch of alternative commands so it will be possible to remap more hotkeys.

First 5 hotkeys is shift+<~-4> - very usefull space on keyboard for a spells. Could be a good start for / commands:

/know - ~ "display current knowledge"
/party - ! (access party menu)
/who - @ (players online)
/abi - # (race/class abilities)
/$ or /gold - drop certain amount of gold

**Comment by draconisPW** [comment]
Implemented as described above.
