### ISSUE TITLE
monster knowledge: from character to account

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#338]
atm monster knowledge which player could see with / hotkey saved for character.. so if player do not reincarnate (which is very rare case) - you loose it every time.

/rfe save reincarnation info bound to account, not character

**Comment by igroglaz** [comment]
also there is a bug - actually this info doesn't saved upon reincarnation too

**Comment by draconisPW** [comment]
Monster knowledge is never saved. You have to relearn with every character, same as flavors.

**Comment by draconisPW** [comment]
Putting here for future reference, but this would mean redo the whole monster memory, not gonna happen soon.
