### ISSUE TITLE
necromancer's raise dead doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#340]
```
[01:14] igroglaz: @PowerWyrm raise dead spell doesn't work it seems
[02:20] PowerWyrm: manarequired to raise = level of the monster race
[02:22] PowerWyrm: I just think the level of the summoned monsters is too high, worst is skeleton kobold I think and for that you need the skeleton of a kobold
```

https://youtu.be/LA6WUHe-FzU?t=4519

snaga skeleton (level 6 monster)
I had 19 mana (after 1st fail it went from 25 to 19 and second cast was successful).... 

6 mana to cast spell... 19-6 = 13. snaga level is 6, while I have 13 mana; twice much than needed

**Comment by draconisPW** [comment]
Not a bug. A snaga skeleton will NOT resurrect a snaga, but a "skeleton orc". The race must exist in monster.txt and be summonable on the level. If not, it will fail.

**Comment by igroglaz** [comment]
oook. Then:

```
name:skeleton orc
base:skeleton
color:w
speed:110
hit-points:45
hearing:20
armor-class:54
sleepiness:70
depth:8
```

Skeleton orc is 8 level mob. 

https://youtu.be/LA6WUHe-FzU?t=4519

snaga skeleton (level 6 monster)
I had 19 mana (after 1st fail it went from 25 to 19 and second cast was successful)....

6 mana to cast spell... 19-6 = 13. skeleton orc level is 8, while I have 13 mana

**Comment by draconisPW** [comment]
But can you summon a skeleton orc on the level? By using the admin command?

**Comment by igroglaz** [comment]
Yep. Just summoned 10 skeleton orcs :D

**Comment by draconisPW** [comment]
At 1:15:33 I can't see the mana remaining because the color is too dark. Starting from 19 mana, raising a skeleton orc should cost 6 mana + 8 mana from monster level. If mana remaining was 13, then the raising failed. I'll add explicit messages to be sure.

**Comment by igroglaz** [comment]
"I can't see the mana remaining because the color is too dark."
https://discord.com/channels/531163320384880660/699917093717671946

if we assume that this:
`[02:20] PowerWyrm: manarequired to raise = level of the monster race`
correct, then:

https://youtu.be/LA6WUHe-FzU?t=4519
As I said above:
1) I had 19 mana
2) I cast spell Raise Dead
3) nothing happens.

So:
1) with 19 mana I cast spell which costs 6 mana

19-6 = 13 mana LEFT after cast.

Skeleton orc level is 8. So to have successful cast I need
6+8 = 13 mana TOTAL.

But I had 19 mana when I casted spell.

**Comment by draconisPW** [comment]
So yes, if mana was 13, the summoning failed. I'll add messages explaining why it could fail (multiple reasons).

**Comment by draconisPW** [comment]
To fix this in a easy way, I've added two new level 1 monsters: skeleton and zombie. Those are really weak versions that can be summoned at level 1.

**Comment by draconisPW** [comment]
Oh and I've refactored the raise code so that it uses the common get_mon_num() function to determine what to raise.

**Comment by draconisPW** [comment]
Tested. Works fine now.
