### ISSUE TITLE
Other players' light not accounted for SQUARE_SEEN

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#341]
https://youtu.be/mw7seEh83nA
pretty minor thingy :)

also certain light from buildings doesn't work too (light right on top of temple in T)

**Comment by draconisPW** [comment]
Player square is "seen" only if player is carrying a light or the square is permanently "glowing".

**Comment by draconisPW** [comment]
Same bug in V: if I use a mage, remove my torch, go near an "apprentice" mob which is carrying a light and try to cast a spell, I get "you cannot see" message.

**Comment by draconisPW** [comment]
V fixed this, I'll port the fix asap.

**Comment by draconisPW** [comment]
Fixed.
