### ISSUE TITLE
allow switching places

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#344]
we got plenty of people online and blocking tavern and shops become a big issue as people go afk sometimes...

based at this two old posts:
http://angband.oook.cz/forum/showpost.php?p=135423&postcount=32
http://angband.oook.cz/forum/showpost.php?p=135431&postcount=35

the solution came at last:
make it possible to switch places only if there is no damaging terrain (including water)

**Comment by draconisPW** [comment]
I don't like this and prefer keeping MAng's current behavior where you still can switch places when you run. Blocking on purpose should just be reported and dealt as innappropriate behavior (just add a rule).
