### ISSUE TITLE
non-IDed books can't be sold in players stores

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#347]
reproduce:
1) find a book with a warrior (or any class who can't read :P )
2) try to inscribe it with ~100
3) it will say y need to ID book 1st

magic classes sell books alright

**Comment by draconisPW** [comment]
Huh...

**Comment by draconisPW** [comment]
Reproduced. You cannot put books for sale unless it's a "known" book (aka bought from store).

**Comment by draconisPW** [comment]
Nice catch. Books should be EASY_KNOW, like all other consumables (scrolls, potions...), but the EASY_KNOW flag is on the object base ("scroll", "potion", "book"), and flags are transfered from base to object during the finish_parse_object() function, which works for object.txt. But books are defined in class.txt!

**Comment by draconisPW** [comment]
Note that this bug is also in V code, but doesn't seem to be impactful there...

**Comment by draconisPW** [comment]
Fixed :)
