### ISSUE TITLE
effect_avg_dam problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#349]
temp fix:
```
[21:11] Dawndeath: in V class.txt those spells have a dice
[21:12] Dawndeath: and V uses "power" not "dam"
[21:14] Dawndeath: so for now just open list-effects.h and change "dam" to "power" for PROJECT_LOS_AWARE
```

**Comment by draconisPW** [comment]
Correct fix: check every effect that uses "dam" and see if they all use "dice" or not. Add check for non NULL dice in effect_damages().

**Comment by draconisPW** [comment]
Effects that use "dam" and don't have "dice":
- BOW_BRAND (mix of exploding shots and status effect shots)
- PROJECT_LOS_AWARE (mix of dispel effects and status effects)

Note: all hacks concerning effect_info() descriptions have been added in get_spell_info(), the correct fix is then to move these into effect_info() itself and just add a paranoia check on the dice in effect_damages().

**Comment by draconisPW** [comment]
Fixed.
