### ISSUE TITLE
console 'whois' command -> crush console

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#35]
When you use 'whois' command with 0 players on server it would crush. 'who' works alright

**Comment by draconisPW** [comment]
Probably because 'whois' is suppsoed to take a player parameter... should be a trivial fix.

**Comment by draconisPW** [comment]
Not a bug. My console works when I type "whois foo" with 0 players on server (response: "no such player"). If you type "whois" without parameter, then the console exits with "missing argument", which is normal.
