### ISSUE TITLE
Auto-repeat broken

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#352]
[15:23] igroglaz: Serega reported that after update 'T'unnel doesn't work properly - it does not auto repeat digging
[15:24] igroglaz: (so y need to push T each time)

**Comment by draconisPW** [comment]
Good catch. We break auto-repeat (digging and firing) each time we receive a packet that is not PKT_TUNNEL, PKT_FIRE_AT_NEAREST, PKT_SPELL or PKT_KEEPALIVE.

But since last update, we also send PKT_MONWIDTH each turn...

**Comment by draconisPW** [comment]
Fixed.

**Comment by draconisPW** [comment]
Also changed the way Send_monwidth() is called to only call it when the width actually changed!
