### ISSUE TITLE
`l`ook server crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#353]
https://youtu.be/Y6bKaP61Ml4

tried to look around to reproduce - didn't manage

**Comment by draconisPW** [comment]
panel_wid is 0 and provokes a division by zero when displaying the sector. This is because p->tile_wid (16) is greater than PANEL_SIZE (11).

This can occur in two places:
- do_cmd_locate (looking around)
- house_list (knowledge menu -> display owned houses)

**Comment by draconisPW** [comment]
I opened V, increased tile size to 16x16, used look command -> crash. Same bug in V.

**Comment by draconisPW** [comment]
Posted in V forums, for me the sector displayed makes no sense, it should be [0,0] -> [0,1] -> [0,n] or [1,0] -> [n,0] and not some arbitrary value that makes no sense like [0,23] -> [0,46]...

Either we disable tile size greater than 11, or I revert the change on sectors to use what is done in MAng, which is the correct way.

**Comment by draconisPW** [comment]
I've reverted to the MAng way by simply using the same code as for change_panel(). The bug still occurs if you use a small window (for example with 5x8 font) and 16x16 tile size, because changing panel shifts by half a panel, which in this case is zero (panel size = 1). The "l"ook command is also broken in that case (infinite loop -- same bug in V).

**Comment by draconisPW** [comment]
Using this code everywhere panel dimensions are used:

`int screen_hgt, screen_wid;
    int panel_wid, panel_hgt;

    screen_hgt = p->screen_rows / p->tile_hgt;
    screen_wid = p->screen_cols / p->tile_wid;

    panel_wid = screen_wid / 2;
    panel_hgt = screen_hgt / 2;

    /* Paranoia */
    if (panel_wid < 1) panel_wid = 1;
    if (panel_hgt < 1) panel_hgt = 1;`

This now works, except when there is only one line displayed -- the player symbol is still displayed one row below.

**Comment by draconisPW** [comment]
Just had to remove previous check for verify_panel(), the check must be done only if the panel changes. This now works as intended.
