### ISSUE TITLE
auto-retaliation adjustment

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#356]
most of the time I die cause of auto-retalliator feature.. in most cases it blocks ?phase door, but sometimes it also blocks ! drinking.. which is strange as I didn't had such troubles with it in TomeNET for example; maybe they handle it differently?

I wonder is it possible to adjust auto-retaliation somehow to reduce death toll? It's kinda UI-ish problem which mess with player's possibility to control his character.

eg:
cancel auto-retalliation for the next turn when player used any command in current turn

**Comment by igroglaz** [comment]
it's definitely feels bugged... auto-retaliation continues after player made a command to drink a potions or read the scroll.

**Comment by draconisPW** [comment]
Following https://github.com/mangband/mangband/issues/1353...

Each time a macro is called, escape is sent that clears the queue via Receive_clear() before receiving the action packet (like Receive_cast() for casting a spell). All commands check for energy before getting executed. However, auto-retaliation use up a turn, so energy is always 0 at this point, making all actions fail. Easily reproduced with a mage and magic missile macro vs Farmer Maggot in town: spell will never trigger at melee range.

**Comment by draconisPW** [comment]
Prevent auto-retaliator after clear request. This doesn't fix the problem completely, but improves things a lot.
