### ISSUE TITLE
SHAPE_SPELLS flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#359]
I've added some forms for races, eg for beholder:
shape:1:floating eye'

monster.txt for floating eye' gotassigned:
spell-freq:5
spells:MIND_BLAST | HOLD

But it's not possible to cast spells. I've tried adding to race
player-flags:MONSTER_SPELLS
but it doesn't work either.

I suppose to assign spells to forms for races we need to add MONSTER_SPELLS flag analogue.. something like SHAPE_SPELLS

**Comment by draconisPW** [comment]
Spells are bound to class, no idea if this is even possible.

**Comment by igroglaz** [comment]
BR_FIRE works for races in different shapes. Maybe SHAPE_SPELLS could be implemented like BR_ stuff
