### ISSUE TITLE
Transition from BCC5.5

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#36]
I'm learning ANSI C in C++ Builder 6 right now and it's very powerful program in many ways, but as far as I understand it's a bit outdated. Anyway I'm alright with Borland, it's just a theoretical proposal - maybe it's good idea to transit PWMA to open-source IDE? I found that there are a lot of variants:
CodeLite https://codelite.org/
Netbeans https://netbeans.org/
CodeBlocks http://www.codeblocks.org/
Visual Studio Code https://code.visualstudio.com/
Eclipse https://www.eclipse.org/
qt https://www.qt.io/
and much more others

Or are there some troubles with the process of transition from Borland to other IDEs?

----

**Update:**
I've tried CodeLite.. and I didn't like it, it doesn't have proper UI scaling for high DPI screens. Then I've tried to customize stuff in Notepad++ (I've linked there compiler) and found that it's there is no possiblity to reassign code style for default C language style and making new user defined language is a huge mess which got loads of glitches. So.... Maybe continuing with Borland 6 actually is a good thing :)

**Comment by draconisPW** [comment]
I'm using Borland C++ 6 just because I have the CD for it, and I compile using makefiles anyway, the IDE is just for debugging. I'm sure you could use anything for IDE as long as the code compiles.

**Comment by igroglaz** [comment]
from the PWMA guide, 5.2   Compiling Instructions:

`PWMAngband uses Borland C++ as compiler tool. You can download a free version of the compiler (see for example: **https://edn.embarcadero.com/article/20633**).`

it's not possible to download there "Borland C++ 5.5 Compiler" anywhere from embarcadero website. I even wrote to embarcadero devs via contact form, email and twitter a few months ago and informed them that it's not available for download. They didn't react at all.

Other places to download it is a scumm and full of virus. The only way to get it - via torrents which isn't very legal thing.

/rfe port PWMA to C++Builder Community Edition

Attaching 'C++Builder Community Edition' project file for the server which I've made following this guide  https://tangaria.com/coding/ :
https://tangaria.com/wp-content/uploads/2020/11/mangband.cbproj

it's only for server though..

**Comment by igroglaz** [comment]
found this one https://www.embarcadero.com/free-tools/ccompiler
it's modern version of borland compiler.. not sure will it work. will try.

I've tried MingGW compiler, it required to edit scripts, eg 
`make -f win32\Makefile.bor` -> `make -f win32\Makefile.gcc`
but it failed to compile zlib-1.2.11 for me

**Comment by igroglaz** [comment]
Nope, modern version won't work:
```
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        bcc32 -c -a -d -k- -O2  adler32.c
'bcc32' is not recognized as an internal or external command,
operable program or batch file.

** error 1 ** deleting adler32.obj
```
cause it has bcc32c.exe , not bcc32.exe in C:\BCC102\bin

**Comment by igroglaz** [comment]
I've tried to rename bcc32c.exe to bcc32.exe to make it work:

```
D:\GitHub\PWMA\zlib-1.2.11>make -f win32\Makefile.bor
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        bcc32 -c -a -d -k- -O2  adler32.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
adler32.c:
        bcc32 -c -a -d -k- -O2  compress.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
compress.c:
        bcc32 -c -a -d -k- -O2  crc32.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
crc32.c:
        bcc32 -c -a -d -k- -O2  deflate.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
deflate.c:
        bcc32 -c -a -d -k- -O2  gzclose.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
gzclose.c:
        bcc32 -c -a -d -k- -O2  gzlib.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
gzlib.c:
        bcc32 -c -a -d -k- -O2  gzread.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
gzread.c:
        bcc32 -c -a -d -k- -O2  gzwrite.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
gzwrite.c:
        bcc32 -c -a -d -k- -O2  infback.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
infback.c:
        bcc32 -c -a -d -k- -O2  inffast.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
inffast.c:
        bcc32 -c -a -d -k- -O2  inflate.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
inflate.c:
        bcc32 -c -a -d -k- -O2  inftrees.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
inftrees.c:
        bcc32 -c -a -d -k- -O2  trees.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
trees.c:
        bcc32 -c -a -d -k- -O2  uncompr.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
uncompr.c:
        bcc32 -c -a -d -k- -O2  zutil.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
zutil.c:
        del zlib.lib
Could Not Find D:\GitHub\PWMA\zlib-1.2.11\zlib.lib
        tlib zlib.lib +adler32.obj+compress.obj+crc32.obj+deflate.obj+gzclose.obj+gzlib.obj+gzread.obj
TLIB 6.4 Copyright (c) 1987-2014 Embarcadero Technologies, Inc.
        tlib zlib.lib +gzwrite.obj+infback.obj+inffast.obj+inflate.obj+inftrees.obj+trees.obj+uncompr.obj+zutil.obj
TLIB 6.4 Copyright (c) 1987-2014 Embarcadero Technologies, Inc.
        tlib zlib.lib
TLIB 6.4 Copyright (c) 1987-2014 Embarcadero Technologies, Inc.
        bcc32 -c -a -d -k- -O2  test/example.c
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
Warning: option '-k-' is not supported in Clang-based compiler.
test/example.c:
test/example.c:8:10: fatal error: 'zlib.h' file not found
#include "zlib.h"
         ^
1 error generated.

** error 1 ** deleting example.obj
```

**Comment by igroglaz** [comment]
Found 5.5 version, but... it doesn't work:

`D:\GitHub\PWMA\PWMAngband\src>make -f SDL.mak
MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
        C:\BCC55\Bin\..\BIN\bcc32 -WD -O2 -Hc -w- -Vx -Ve -X-   -a8 -b -k- -vi -tWD -tWM -c -DENABLE_WINDIB -DHAVE_ALLOCA=1 -w-par -I..\..\SDL\SDL-1.2.15\include;..\..\SDL\SDL-1.2.15\src\video;..\..\SDL\SDL-1.2.15\src\video\windx5;..\..\SDL\SDL-1.2.15\src\video\windib;..\..\SDL\SDL-1.2.15\src\video\wincommon;..\..\SDL\SDL-1.2.15\src\timer\win32;..\..\SDL\SDL-1.2.15\src\timer;..\..\SDL\SDL-1.2.15\src\thread\win32;..\..\SDL\SDL-1.2.15\src\thread;..\..\SDL\SDL-1.2.15\src\joystick\win32;..\..\SDL\SDL-1.2.15\src\joystick;..\..\SDL\SDL-1.2.15\src\file;..\..\SDL\SDL-1.2.15\src\events;..\..\SDL\SDL-1.2.15\src\endian;..\..\SDL\SDL-1.2.15\src\cdrom;..\..\SDL\SDL-1.2.15\src\cdrom\win32;..\..\SDL\SDL-1.2.15\src\audio\windx5;..\..\SDL\SDL-1.2.15\src\audio\windib;..\..\SDL\SDL-1.2.15\src\audio;..\..\SDL\SDL-1.2.15\src;C:\BCC55\Bin\..\include -DWIN32;BUILD_SDL;__FREEBCC__;ENABLE_WINDIB;ENABLE_DIRECTX;HAVE_ALLOCA=1;HAVE_OPENGL;NO_STRICT;_NO_VCL -n..\..\SDL\SDL-1.2.15\src\stdlib\ ..\..\SDL\SDL-1.2.15\src\stdlib\SDL_getenv.c
Borland C++ 5.5 for Win32 Copyright (c) 1993, 2000 Borland
..\..\SDL\SDL-1.2.15\src\stdlib\SDL_getenv.c:
Error E2176 ..\..\SDL\SDL-1.2.15\include\SDL_config_win32.h 62: Too many types in declaration
Error E2176 ..\..\SDL\SDL-1.2.15\include\SDL_config_win32.h 63: Too many types in declaration
Error E2021 ..\..\SDL\SDL-1.2.15\include\SDL_stdinc.h 131: Array must have at least one element
Error E2021 ..\..\SDL\SDL-1.2.15\include\SDL_stdinc.h 132: Array must have at least one element
*** 4 errors in Compile ***`
..even though I've assigned stuff in makefile.bcc

Installed Borland 6 and it worked instantly... so it seems PWMA guide should be revamped.

**Comment by draconisPW** [comment]
Conclusion:
- BCC5.5 is outdated and not supported, and even worse, it doesn't work anymore -- need to find a replacement for it when compiling with makefiles + update the documantation
- BCC6.0 works, but comes only with IDE (C++Builder 6)
- new compiler is Embarcadero C++ 7.20 from here: https://www.embarcadero.com/free-tools/ccompiler -- need to study if using it would work

**Comment by igroglaz** [comment]
also we could use MinGW :D I've made a guide about it: https://www.youtube.com/watch?v=FQs7ybhcpJk

also V uses MinGW too in their guide about compiling on 1st place:
https://angband.readthedocs.io/en/latest/hacking/compiling.html#id10

**Comment by draconisPW** [comment]
After trying to compile SDL with Embarcadero C++ 7.20 I gave up, it seems some options are simply not working:
- treat enum as int doesn't work (so any sizeof enum will be incorrect)
- compiling C doesn't work (for example: using "this" as variable name will throw error, and there are like 6000+ of those in SDL code)
- pointer casting doesn't work (so variable = void* other variable will throw error)

**Comment by draconisPW** [comment]
Client now compiles using Embarcadero C++ 7.20 (minor changes).

**Comment by draconisPW** [comment]
Note that compiling with newer compiler unveils some warnings that didn't get caught previously (a "good thing")...

**Comment by draconisPW** [comment]
Wow, GCU client looks funny compiled with with BCC7, now you can see 4 windows, a bit like SDL client.

**Comment by draconisPW** [comment]
This also fixes GCU bug with PDCurses! Even better... Now I'll probably have to go back at V code which fixed GCU client further (I didn't port that since our GCU client was mono-window).

**Comment by draconisPW** [comment]
Server now compiles using Embarcadero C++ 7.20 (minor changes). Everything's fine except SDL. I'll add the compiled DLL to Git so we get the total package. In case we need to recompile them, BCC6 will have to be used.

**Comment by draconisPW** [comment]
Latest V changes for GCU client have been ported. Feel free to compile it with Embarcadero C++ 7.20 to get the full potential of this console port.

**Comment by draconisPW** [comment]
Closing this, works with BCC7.

**Comment by igroglaz** [comment]
When I go through the guide for compilation:
https://tangaria.com/windows/

I'm done with WIN client (runned PWMAngband\src\bcc32c\\WIN.bat and it worked).

Now I'm running PWMAngband\src\SDL.bat (to prepare SDL) and it gives such output:

```
C:\GitHub\Tangaria\PWMAngband\src>make -f SDL.mak
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        C:\BCC102\bin\..\BIN\bcc32 -WD -O2 -Hc -w- -Vx -Ve -X-   -a8 -b -k- -vi -tWD -tWM -c -DENABLE_WINDIB -DHAVE_ALLOCA=1 -w-par -I..\..\SDL\SDL-1.2.15\include;..\..\SDL\SDL-1.2.15\src\video;..\..\SDL\SDL-1.2.15\src\video\windx5;..\..\SDL\SDL-1.2.15\src\video\windib;..\..\SDL\SDL-1.2.15\src\video\wincommon;..\..\SDL\SDL-1.2.15\src\timer\win32;..\..\SDL\SDL-1.2.15\src\timer;..\..\SDL\SDL-1.2.15\src\thread\win32;..\..\SDL\SDL-1.2.15\src\thread;..\..\SDL\SDL-1.2.15\src\joystick\win32;..\..\SDL\SDL-1.2.15\src\joystick;..\..\SDL\SDL-1.2.15\src\file;..\..\SDL\SDL-1.2.15\src\events;..\..\SDL\SDL-1.2.15\src\endian;..\..\SDL\SDL-1.2.15\src\cdrom;..\..\SDL\SDL-1.2.15\src\cdrom\win32;..\..\SDL\SDL-1.2.15\src\audio\windx5;..\..\SDL\SDL-1.2.15\src\audio\windib;..\..\SDL\SDL-1.2.15\src\audio;..\..\SDL\SDL-1.2.15\src;C:\BCC102\bin\..\include -DWIN32;BUILD_SDL;__FREEBCC__;ENABLE_WINDIB;ENABLE_DIRECTX;HAVE_ALLOCA=1;HAVE_OPENGL;NO_STRICT;_NO_VCL -n..\..\SDL\SDL-1.2.15\src\stdlib\ ..\..\SDL\SDL-1.2.15\src\stdlib\SDL_getenv.C
Fatal: Unable to execute command: C:\BCC102\bin\..\BIN\bcc32

C:\GitHub\Tangaria\PWMAngband\src>pause
Press any key to continue . . .
```

seems as a problem with paths
