### ISSUE TITLE
EMPTY_MIND -> disable ESP for polymorphed player

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#360]
eg if player polymorphed to EMPTY_MIND monster - make this disable player's ESP while he is in this form

mon-util.c 1542
```
            /* Empty mind, no telepathy */
            if (q->poly_race && rf_has(q->poly_race->flags, RF_EMPTY_MIND)) {}
```
something like this for p

**Comment by draconisPW** [comment]
No reason to since it's the other way around.... too much variant territory can't add this by default. Unless you mean "other players can't ESP this player while using EMPTY_MIND form".

**Comment by igroglaz** [comment]
it's not only Tangaria stuff. imagine getting EMPTY_MIND form with Shapechanger.. it's logical to have disabled ESP if you got such form. and it's perfect way to rebalance some imba forms

**Comment by draconisPW** [comment]
In fact other players can't ESP players with empty mind, so this is already implemented. The other way around makes no sense and would be variant territory.

**Comment by igroglaz** [comment]
It makes a lot of sense :D anyway it's up to you. I'll implement it in my fork one day
