### ISSUE TITLE
character creation screen -> ! flags sorting

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#361]
minor thing - weird sorting for flags
https://media.discordapp.net/attachments/699917093717671946/836574725660344320/Untitled-1.png

fire should be first, then cold... as it much fancies to have stuff sorted by lvl (as in p_race.txt)

**Comment by draconisPW** [comment]
No. Flags in p_race have no order, they are parsed "as is". Flags rendered in character creation screen are ordered by flag number, which should prevail.

**Comment by igroglaz** [comment]
our players made a point that flags on char creation screen should have proper sort by level (when you have certain ability) and I agree with it... it's weird to have random sorting there

**Comment by draconisPW** [comment]
Hmm maybe.

**Comment by igroglaz** [comment]
it's very minor thing, so alright to postpone in for years to come

**Comment by draconisPW** [comment]
Oh while I was working on player flags, I thought this was a good time to implement this as well... :)
