### ISSUE TITLE
allow negative values for monster's AC

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#362]
eg I've tried to assign negative value to armor-class:-10 for poly form, but it doesn't change character AC.. 

so atm AC from forms could only be positive value, as having low form AC doesn't effect overal AC.. there could be two approaches: 
1) HP-way: ([20:29] PowerWyrm: hp formula = 60% of char hp + 40% of form hp)
2) allow negative values
3) use both approaches (best)

**Comment by draconisPW** [comment]
Polymorphed ac is calculated as follows:
- if form ac is greater than equipment ac, we take the average of the two
- if form ac is lower, we take the equipment value

So putting negative values will have no effect. Low form ac has effect at the beginning when player ac is low, and that's how it should be.

**Comment by igroglaz** [comment]
yep, I know that, thanks :) the ticket was about possibility to assign negative values there. Because right now there are not enough ways to rebalance poly races. We need more malus factors. Atm there are only HP (which is bad factor as for some classes form will give too much hp, while for others too small), -STEALTH (weight), -INT (smart and spell freq), dmg... and HURT_FIRE, COLD, LIGHT. We near moar factors for the scales ⚖️

**Comment by igroglaz** [comment]
it's the reason why we need limit ESP for EMPTY_MIND https://github.com/draconisPW/PWMAngband/issues/360 ... right now there are not enough ways to make interesting gamedesign decisions for forms.
