### ISSUE TITLE
unhardcode perma form progression

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#363]
dragon and hydra got awesome feature to advance through forms.. it will be fun to unhardcode it one day, eg in T there are spiders who miss this feature a lot. I suppose it's pretty big task to do, so it's just a notice do not forget to do it one day ❤️

**Comment by draconisPW** [comment]
Agreed. Perma form should be a parameter of the "shape" entry. Hydra has no reason to be hardcoded. For Dragon, this is more difficult to do, as the form chosen at level 5 is random and cannot be inferred from a static file.

**Comment by draconisPW** [comment]
Implemented for Hydra and any future race that are permanently polymorphed:
- add PERM_SHAPE player flag to the race
- add "shape" line for each level with the name of the race at that level (be sure to include a line for level 1)

**Comment by draconisPW** [comment]
Closing this. Dragon has his own file and uses RNG for polymorphing, won't change that.
