### ISSUE TITLE
CIRCULAR_ROOMS crash server

### ISSUE THREAD

**Issue by draconisPW** [draconisPW/PWMAngband#365]
Following latest V changes, dungeons with CIRCULAR_ROOMS will crash on generation.

**Comment by draconisPW** [comment]
I've disabled the set_bordering_walls() code for CIRCULAR_ROOMS dungeons and put back the old code instead in that case. Doesn't seem to crash for regular dungeons when generating a circular room.

**Comment by igroglaz** [comment]
it seems it's still there: https://youtu.be/qKAZutZYzzU

**Comment by igroglaz** [comment]
yep, pretty easy to reproduce - just enter and exit 1st dungeon bunch of times and server will crush

**Comment by draconisPW** [comment]
Damn...

**Comment by draconisPW** [comment]
I see, this happens on arena levels. That's because the V code assumes we generate the rooms from granite, while arena level is already filled with floors. I'll also disable the V code for arena levels.

**Comment by draconisPW** [comment]
Ok should be fixed again.

**Comment by igroglaz** [comment]
please could you push fix asap as server continues to drop once and then :D so I had to guard and restart it every few minutes

**Comment by draconisPW** [comment]
Done
