### ISSUE TITLE
house expansion broken

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#369]
I've tested house expansion in pure PWMA enviroment (tried in T first, it didn't work; so I've tested in PWMA) - it crushes server

```
050521 172621 Shutting down (panic save).
050521 172622 Server panic info save succeeded!
```

repro:

1) buy house stones and scrolls
2) go 2 locations away from city, out of suburbs (so get into 3rd location)
3) buy house, drop stones (3 rows), read scroll... CRUSH!

**Comment by igroglaz** [comment]
note: I've tested it at https://github.com/draconisPW/PWMAngband/commit/1ed576721f4c9bd1aebd943cec7a701c3dcc75ff build

**Comment by draconisPW** [comment]
I tried to expand a house with 3x5 stones, it doesn't crash but it says "you don't have enough money to pay the local tax of 81919165154354354354 gold". It seems it's just a problem with house pricing, and I bet it crashes when the number becomes too high or even negative...

**Comment by draconisPW** [comment]
Yeah... I forgot to set the coordinates of the house before calculating tax. Nice catch...

**Comment by draconisPW** [comment]
Fixed.
