### ISSUE TITLE
'you see the entrance'..

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#37]
Applying 'l'ook command on NPC show them as 'entrances', eg:
https://i.ibb.co/JqX6mbK/Untitled-1.jpg
(on this picture there is a new _short-desc:_ )

**Comment by draconisPW** [comment]
Fixed in cec4598.

For all custom shops that appear as a NPC (and don't have entrances), use the VENDOR flag in terrain.txt:

flags:SHOP | **VENDOR** | PROJECT | PASSABLE | PERMANENT | INTERESTING | EASY
