### ISSUE TITLE
building commands -> place feature

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#370]
I've tested & 2 stuff and it seems 'place feature' doesn't work. 

repro
1) set feature: granite wall
2) try 'Place feature'

Draw line and fill rectangle works: https://cdn.discordapp.com/attachments/699917093717671946/839939946152591360/Untitled-1.jpg :D

**Comment by draconisPW** [comment]
Err... I must have had a seizure, the function simply makes some checks about staircases and only allows to place up/down staircases. There is clearly a line for other features missing...

**Comment by draconisPW** [comment]
Fixed.
