### ISSUE TITLE
add custom player stores in town

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#371]
it will be really great to have custom player stores in 'town' locations. Maybe it's possible to implement it with 'building commands' (& 2)? Or some other way..

I've looked mang_town_gen, but don't get how it could be implemented together with defined town. Eg in PWMA there is Hobbiton which do not have hobbiton.txt file, it's generated `on the go`. While in T there is .txt file with Farfest town.. how to superimpose Farfest on generated town player stores?

**Comment by draconisPW** [comment]
Player stores are engraved in marble, there is no way to do this without rewriting everything sorry.

**Comment by igroglaz** [comment]
yep.. but I suppose it's quite possible to make hack which will do the job. just take needed stuff from mang town and put it to the new ' dirty' function

**Comment by igroglaz** [comment]
Aaaand another idea is to use house expansion code to add new houses:
cmd-cave.c

```
        /* Setup house info */
        loc_init(&h_local.grid_1, x1 + 1, y1 + 1);
        loc_init(&h_local.grid_2, x2 - 1, y2 - 1);
        loc_copy(&h_local.door, &door);
        memcpy(&h_local.wpos, &p->wpos, sizeof(struct worldpos));
        h_local.price = price;
        set_house_owner(p, &h_local);
        h_local.state = HOUSE_CUSTOM;

        /* Add a house to our houses list */
        house_set(house, &h_local);
```

**Comment by igroglaz** [comment]
OMG... actually this feature already there :DDDDDDDDD

you could build houses. just put stones, read scroll and house will be builded! YAY!

**Comment by igroglaz** [comment]
the only thing to do is comment out:

//    /* Houses can only be created in the wilderness */
//    if (!in_wild(&p->wpos))
//    {
//        msg(p, "This location is not suited for a house.");
//        return false;
//    }

**Comment by igroglaz** [comment]
now I'll add check so only DM could build houses.. then I'll build houses with admin char and them sell them. players will be able to buy..

**Comment by igroglaz** [comment]
@draconisPW do you have ideas how to improve house building system? maybe we could add certain rules which will allow players  to build houses by themselves in town, if there is no other NPC or buildings nearby? hmm... we need to brainstorm :D

**Comment by igroglaz** [comment]
but actually why not to allow players to build houses in town right now. I'll add rules on which houses should be build. If players will   violate rules - I'll just demolish house... Hm. BTW is there way to demolish house? :D
