### ISSUE TITLE
DM -> demolish house

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#372]
DM can reset house:
**cmd-cave.c**
```
            /* The DM can reset a house */
            if (p->dm_flags & DM_HOUSE_CONTROL)
            {
                /* House is no longer owned */
                reset_house(i);
                msg(p, "The house has been reset.");

                /* Done */
                return;
            }
```
It will be fun also to add possibility to demolish house. Maybe it should be in & commands

**Comment by draconisPW** [comment]
Same as for previous issue, the system is engraved, you cannot demolish houses.

**Comment by igroglaz** [comment]
The same as for previous one - it's already there.. just need to tinker building commands a bit to implement it

**Comment by igroglaz** [comment]
yep, I've just demolished house with building commands, though it crush server. but after restart house removed.

how:

1) build a house (in T 3x3)
2) &51g (ghost form)
3) stay inside of perma wall
4) building commands -> fill rectangle

now we just need to make it don't crush the server and voila :)

**Comment by igroglaz** [comment]
it crushes in **cave-square.c** square_set_feat():
`    my_assert(square_in_bounds(c, grid));`

**Comment by igroglaz** [comment]
another note: we do not need to care about properly deleting this house for player. Demolishing houses - it's a punishment for players who block entrance to the shop, dungeon or just put house to the center of town (in T rules I'll write detailed guidelines where players shouldn't place their houses). 

so.. if player violated house building rules - his house demolished. We need possiblity to just wipe the ground from it (replace with a grass), that's it.

I hope it will be super rare thing - to delete someone house... as our community is not too big and most of use are pretty good persons :) but in case for protection from some trolls - we need this feature. Otherwise we will have to delete server file to reset world (characters will stay, but all houses will be deleted) - it will be bad thing to do.. So the best thing is to allow wiping house with `building commands -> fill rectangle`.. just to fix it so it won't crush server.

**Comment by igroglaz** [comment]
OOOMMMGG :DDDD actually demolishing houses already exist!!!
sell the house. if it does not owned by anyone - exit the location and it will be dissapear
