### ISSUE TITLE
assign bonus gold to class/race

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#373]
/rfe allow assigning gold to class/race, eg
equip:gold:adamantite:100000:100000:none

it will be very useful to testing reasons.. atm when I'm testing houses I have to give gold to test char from admin every time. also this could be used as compensation for certain chars who got too small amount of gold at start

**Comment by draconisPW** [comment]
Use #DEBUG define for testing. Gold at start is balanced in PWMAng and no change is required.

**Comment by draconisPW** [comment]
somewhere in the code (probably in h-basic.h), there is:
/* #define DEBUG */
just remove the comments and it will make the server in debug mode, which gives all characters the same stuff as the DM
(do that only for debug purposes, not when there are other players around)

**Comment by igroglaz** [comment]
debug mode is nice thing but it's bad for testing stuff fast as when you toggle server to debug - you need recompile it which takes time and PC resources. so gold is still needed thing for chars. will add it in T

**Comment by igroglaz** [comment]
for now I've just added additional #define TEST_MODE to load DM equipment and $ on normal chars without need to compile in debug
