### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#377]
maybe need UTF-8 support, it will increase the number of characters
or will be able to display more symbols in text
already enabled wchar_t  `#include <wchar.h>`

src/client/ui-term.c 
Term->text_hook = Draw some text in the window
Term->pict_hook = Draw some attr/chars in the window

_for text:_
in Angband https://github.com/angband/angband/blob/master/src/ui-term.c#L657
ui-term.c  Term_queue_chars() uses instead  char *s - > **wchar_t *s** for **UTF-8**
```
void Term_queue_chars(int x, int y, int n, int a, const wchar_t *s)
. . .
wchar_t *scr_cc = Term->scr->c[y];
```

https://github.com/angband/angband/blob/master/src/main-sdl.c#L543
sdl_mapFontDraw()
`text = TTF_RenderUTF8_Shaded(font->sdl_font, s, colour, bg);`

https://github.com/angband/angband/blob/master/src/main-sdl.c#L2832
main-sdl.c  Term_text_sdl(.. const **wchar_t *s**)
```
/* Take a copy of the incoming string, but truncate it at n chars */
	wcsncpy(src, s, n);
	src[n] = L'\0';
	/* Convert to UTF-8 for display */
	len = wcstombs(mbstr, src, n * MB_LEN_MAX);
	mbstr[len] = '\0';
```

**Comment by draconisPW** [comment]
This would take forever to implement, as it would require recoding everything using wchar instead of char. It was a nightmare in V which doesn't have client/server interaction...
