### ISSUE TITLE
Mix_CloseAudio() causes segmentation fault

### ISSUE THREAD

**Issue by nanoqsh** [draconisPW/PWMAngband#379]
I noticed that when I quit the game, I get segmentation fault error message. I found out that the reason is `Mix_CloseAudio` function call. This is fixed by adding library dependency SDL_sound. I added `-lSDL_sound` after `-lSDL_mixer`, compile again and segfault disappeared. This error is not very critical, just this was annoying and I thought there is some problem in source code. A right solution would be to add SDL_sound in dependencies, but I don't know how how to do it right.

**Comment by draconisPW** [comment]
I checked Vanilla configuration and they don't use SDL_sound and nobody ever reported this so this must be a specific problem with your Linux configuration. Use your workaround, there's nothing in the code to modify.
