### ISSUE TITLE
[rfe] dungeon lvl size customization

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#38]
AFAIK in PWMA all dungeon lvls got the same size (max). It could be fun to give certain dungeons customization in this property. Eg in TomeNET sometimes you could meet very tiny or middle-sized lvls and it's fun; the problem is that at high lvl dungeons this tiny levels could be deadly - as there are not much space around to teleport. But we could solve this problem by assigning size to certain dungeons - so low-mid lvl dungeons lvl would have small size rooms, while end-game dungeons would be big enought.

**Comment by draconisPW** [comment]
This already exists: size of levels is randomized between 75% and 100% of the maximum size. Special levels (cave, labyrinth, moria...) can be even smaller. Tiny levels (aka TomeNET levels) are plain stupid.

**Comment by igroglaz** [comment]
Yep, but it would be fun to be able to customize it in dungeon.txt so certain dungeons could have big floors and some - smaller ones.

**Comment by igroglaz** [comment]
We really need smaller levels. It will GREATLY increase dungeon diversity. Right now all dungeons feels too 'the same'. Some of low-level pre-35 lvl dungeons could really have 50% or even less size to make some dungeons very unique.

End-game (and even-mid game) dungeons will stay big as they are now - as at end-game having tiny dungeon is too dangerous as you can't teleport away on significant distance from the danger (TomeNET got such problem). We, on the countrary, will have small dungeons only for early game - and it will GREATLY increase dungeon atmosphere - having smaller dungeons, but deeper levels. Must have! :)
