### ISSUE TITLE
volume doesn't work for MP3 files

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#380]
[23:53] igroglaz: tried to restart client
[23:54] igroglaz: controls works, but it doesn't influence volume
[23:54] igroglaz: and having 0 volume doesn't make game silent
[01:28] PowerWyrm: strange...  I tried it and it worked perfectly for me
[09:27] igroglaz: yep, strange. for me it doesn't work. my Windows 10 build is 19042
[09:31] igroglaz: TomeNET volume works for me..
[09:32] igroglaz: and all other games
[11:57] Serega88: @igroglaz Mix_PlayChannel()'s first argument is which mixing channel we're going to play the sound in. Since it's set to -1, Mix_PlayChannel() just looks for the first channel that's available and plays the sound. (lazyfoo.net)

it seems that on the streams the sound is played by one. https://youtu.be/HfFvuFdvkDY?t=632 must play all sound (open door + arrr + hit) /src/client/sound-core.c MAX_SOUNDS_PER_MESSAGE  16
maybe bug Windows 10 (build 19042) ? or the first one loads the .mp3 file should load the ogg.

**Comment by igroglaz** [comment]
[12:31] Serega88: SDL_CHUNK:  Mix_PlayChannel(-1 ...
https://cdn.discordapp.com/attachments/535396965433868288/855379276404490270/sound-2021-06-18_15.23.30.mp3

**Comment by s88100** [comment]
checked Windows 10. if remove sounds\ .ogg files. loads (mp3) SDL_MUSIC: music channel Mix_PlayMusic(... volume doesn't work.
maybe need `Mix_VolumeMusic` https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_61.html#SEC61
`Mix_VolumeChunk`  https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_23.html#SEC23

**Comment by draconisPW** [comment]
Need to test out of VM.

**Comment by draconisPW** [comment]
Works perfectly on my Win 10.

**Comment by draconisPW** [comment]
Windows 10 version 20H2. Previous builds of Win 10 are not supported anymore, if you have a problem just upgrade.

**Comment by igroglaz** [comment]
I got 20H too... Version	10.0.19042 Build 19042 it is 20H.

So there is a bug.

**Comment by igroglaz** [comment]
Actually I got 21H1.. 20H is already old one :D

https://en.wikipedia.org/wiki/Windows_10_version_history

**Comment by draconisPW** [comment]
Did you try regular PWMAngband with the OGG files? For me it works... Since there is the case of using MP3 files, I'll check that too.

**Comment by igroglaz** [comment]
oook. PWMA worked. and new client works too.. I got 2 clients setuped at my PC - for testing and for playing. and playing client doesn't work, while testing works.. I suppose it could be something in it's config files, though binary files there are fresh. I'll just replace whole folder to fix.

Thanks.

**Comment by draconisPW** [comment]
Volume change only works for OGG files. If you remove the OGG files and try with MP3, it doesn't work.

**Comment by draconisPW** [comment]
I've reworked sound volume management again and made it even simpler. No more hook, setting volume now only sets a variable and the MIX_ function is called directly when playing a sound if the variable has changed in the meantime. This allows to split between SDL_CHUNK (OGG) and SDL_MUSIC (MP3) and call different functions to make it work in both cases.
