### ISSUE TITLE
flickering to msgt()

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#381]
/rfe add flickering (dynamic changing colors; cycling them, eg red->blue->green->red->blue....) for text messages

it will help to make certain critical effects (eg undress during seducing) more visible

**Comment by igroglaz** [comment]
the real reason why we need flickering:
https://cdn.discordapp.com/attachments/531163320384880663/855917386099589130/2475289_CreateAgif.gif
!!!! NSFW !!!!

**Comment by draconisPW** [comment]
Variant territory.
