### ISSUE TITLE
message in different colors

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#382]
/rfe add possibility to make parts of message in different color in msgt( )

I suppose it could be imlemented as a new function which will work without \n

eg right now this:
msgt(p, MSG_DESTROY, "Ignoring %s.", o_name);
means: 
msgt(p, MSG_DESTROY, "Ignoring %s.**\n**", o_name);

so if there would be a way to make it without \n, we would be able to make two msgt, eg 
msgt**c**(p, MSG_COMMON, "Ignoring ");
msgt(p, MSG_DESTROY, "%s.", o_name);
(so 1st function is msgt**c** and it doesn't have \n and second is msgt with \n))... MSG_COMMON could be a regular white message and could be used in most cases

or maybe there is more elegant way to print messages... actually it will be fun to be able to print messages in the same way as we got news.txt file to make them easier to write in the code, eg:

{Teal}.:*~*:._.:*~*:._.:*~*;._.:*~*:.{/}
 {Red}PWMAngband{/}{Light Teal}   `----'`=-='   '{/}                   {Light Dark}..Akha gum-ishi ashi gurum...{/}

hm.. but now with the names of colors but with our color codes: r, g, b, V, p etc... and combine it with a sound as argument

**Comment by draconisPW** [comment]
Would require rewriting too much stuff, neither I know how to do this nor I have the time.

**Comment by igroglaz** [comment]
Serega got into this task and found some useful info which he will post there. I just wanna say that this is very important task as atm sometimes it's hard to read fast-paces messages about monster's immunity to certain spell. Coloring will help to recognize such stuff much better

I suppose it's enough to implement it just in SDL client (ezpz way), but if it's possible to do everywhere - it's cool.

we just need a new function which will give possibility to have different color messages; while leaving possibility to use old function.

so the task is to find way to have two (or more) different colors in one message, eg

Balrog {r resist a lot

"Balrog" will be white color, "resist a lot" red

**Comment by s88100** [comment]
_messages subwindow and chat in_
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-display.c#L772
update_messages_subwindow()
update_message_chat_subwindow()

_example for test_
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-output.c#L273
```
int prt_multi()
    //Term_putstr(sx, sy + i * d, line_end[l], attr, line_ptr[l]);
    text_out_e(line_ptr[l], sy + i * d, sx);
```

tags like {red}{/} splash 'news.txt file'
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-output.c#L431
  next_section()
  text_out_e()

https://github.com/draconisPW/PWMAngband/blob/master/src/common/z-color.c#L175
  color_text_to_attr()
  color_type color_table[MAX_COLORS]

> Hello {light red} PWMAngband {/} chat {yellow} hiho {/} !

![chat-1a](https://user-images.githubusercontent.com/71586060/129338023-b85d7077-0dab-4d38-81c4-eea2f9be0335.png)

**Comment by s88100** [comment]
all text is displayed in
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-term.c#L1588
`errr Term_putstr(int x, int y, int n, u16b a, const char *s)`

in TomeNet https://github.com/TomenetGame/tomenet/blob/master/src/client/z-term.c#L2034
`errr Term_putstr(int x, int y, int n, byte a, char *s)`

tag check
```
    /* Look for color codes */
    ptr = strchr(s, '\377');
        . . . . .
    if (*ptr == '\377') {
    /* Convert double '\377' into one '{' */
    Term_addch(a, '{');
```
if a tag is found then enable the function for coloring text.
`Term_putstr(10, 15, -1, TERM_GREEN, "To return to your normal form, use  \377GPlayer\377g  or its code  \377G0\377g  .");`

https://github.com/TomenetGame/tomenet/blob/master/src/client/c-cmd.c#L6221
```
    case '8':
    {
        int j;
        buf[0] = 'B';
        get_string("Message:", &buf[1], 69);
        for (j = 0; j < 60; j++)
            if (buf[j] == '{') buf[j] = '\377';
    }
```
sample msg(p, "There is a {r player } in the {Y way! }");
Term_putstr()
determines if there are '{' tags, if found then coloring text.
or find colour_code '\377' like in TomeNet
also requires checking the logs (printing without tags)
https://github.com/draconisPW/PWMAngband/blob/master/src/server/display-ui.c#L5323
display_message_aux()
```
    /* We don't need to log *everything* */
    if (strchr("[", *msg)) log = false;
```

**Comment by s88100** [comment]
https://github.com/mangband/mangband/blob/develop/src/client/c-xtra1.c#L1791
_Mangband_
```
/* Determine message color based on string templates */ 
bool message_color(cptr msg, byte *ap)
```
https://github.com/draconisPW/PWMAngband/blob/master/src/client/ui-display.c#L1594
`message_color_hack()`
sample, check if ((strstr(s, "{") != NULL))

_please look at simple example_
src/client/ui-term.c
```
Term_putstr()
if ((strstr(s, "{") != NULL))
    {
        if (!res) res = text_out_m(n, a, s);
    }
    else
    {
        /* Then add the string */
        if (!res) res = Term_addstr(n, a, s);
    }
```
/src/client/ui-output.c

static bool next_section_m()
errr text_out_m(int n, u16b b, const char *buf)
```
if (strlen(tagbuffer) > 1)
    a = color_text_to_attr(tagbuffer);
else
    a = color_char_to_attr(tagbuffer[0]);
```

code takes color from https://github.com/draconisPW/PWMAngband/blob/master/src/common/z-color.c#L69
not only long {light red}..{/} and also letters {R}..{/}, {r},{g},{b} ...

> 0/ {r}PWMAngband{/}hiho{G}!{/}{y}abc{/}

![chat-2](https://user-images.githubusercontent.com/71586060/129385213-f926d1e2-0f2a-4833-8395-4f3d0e1c4b82.png)
![message-1](https://user-images.githubusercontent.com/71586060/129385263-d9ddab69-327b-44fb-9750-fa019cf10ee9.png)

but need a solution with simple tags next_section_m()

> {r PWMAngband } hiho {G ! } {y abc }

[pwma-tag-color-1.zip](https://github.com/draconisPW/PWMAngband/files/6983656/pwma-tag-color-1.zip)
^^^^^^^^^^

**Comment by igroglaz** [comment]
@draconisPW should we add this code to the game? Or it require some rework? Screenshots looks fancy

**Comment by draconisPW** [comment]
It also looks stupid and unneccessary. Feel free to add it to Tangaria if you want, but for me it's work for nothing and I won't.

**Comment by igroglaz** [comment]
:) It may look stupid in test examples above. But if applied properly it looks awesome and used everywhere, eg
https://imgur.com/q0I2e.jpg

**Comment by igroglaz** [comment]
Without it we have quite bad readability of game's text. Even text MUDs from 90' got this feature...

**Comment by igroglaz** [comment]
Its easy enough to see the difference of readability. Please compare this two examples (WoW):
![2](https://user-images.githubusercontent.com/39904162/132813763-f58979fe-95ee-4604-b2a3-b3660874613a.png)

and

![q0I2e_d](https://user-images.githubusercontent.com/39904162/132813775-30014208-9ef9-4d2a-b2ee-fd74970f926f.png)

**Comment by igroglaz** [comment]
Another example from TomeNET:
![t1](https://user-images.githubusercontent.com/39904162/132815623-5a896714-71e3-4e59-b0c6-2bbca345e967.png)

in PWMA the same text would look like this:
![2](https://user-images.githubusercontent.com/39904162/132815656-4908d5d6-b5b8-4de6-983d-4fb907691ebf.png)

**Comment by draconisPW** [comment]
Yes it looks great when used to color "game" messages. I was just referring to the coloring of chat messages, with dumbasses spamming colored messages thinking they're funny while they're just pissing off other players. This will never happen.

Colored game messages already exists. All is to do is decide which ones become colored (currently we have begin/end, level ups, boss kills + everything from message.prf). All that is missing is the "You hit the crow for {13} damage." type. Since this is pretty much done for monster descriptions (the use of { and } in the description makes the description use colors), this could be added using the same method.

**Comment by draconisPW** [comment]
Also looking at the code above, all this should be done on the server, not on the client. It's just a matter of choosing which extra server messages are colored.

**Comment by igroglaz** [comment]
I agree 100% about chat messages, I dislike excessive coloring too as it makes harder to read the message. Whole ticket was about messages in game's event (damage, player's state (confusion, stun, etc), spells colors.

So yeah, we miss {13} stuff. But I've checked the code and failed to find the way to apply color on certain _part_ of the message; AFAIU now we can color only whole stroke.

"this is pretty much done for monster descriptions" - strange, I can't find it.. maybe I don't understand something:
![image](https://user-images.githubusercontent.com/39904162/132818404-6838e4e1-0f9d-46d1-93be-dda323419d47.png)

**Comment by draconisPW** [comment]
Use "look" then "r", or the monster recall window on a monster. If you use "/" and there are more than one monster, the game will use the "peruse" functionnality (like a "search") which doesn't use colors at all. Or simply type "merchant" to get only one description.

**Comment by draconisPW** [comment]
Reopening for the above functionnality.

**Comment by igroglaz** [comment]
Oh, thats cool:
![image](https://user-images.githubusercontent.com/39904162/132825808-9feec440-e496-43e6-8d73-86100b20e0f8.png)

![image](https://user-images.githubusercontent.com/39904162/132825924-e739d819-c2a7-4242-82b0-cd9b9729dbaf.png)

**Comment by draconisPW** [comment]
Looking again at this there is no way to color messages on the server, as the client code uses a single color to display things and splits messages totally randomly, even displaying them backwards. We'll have to go with the above method of checking color markers in Term_putstr().

**Comment by igroglaz** [comment]
double \n in motd.txt crush client
![image](https://user-images.githubusercontent.com/39904162/204379585-ef840359-c2df-4f14-9021-8c18c29ee1a3.png)

**Comment by draconisPW** [comment]
Fixed. Code was assuming that added string was not empty.
