### ISSUE TITLE
Sleep Monster stuff doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#387]
I've tested Sleep Monster with debugger and it doesn't trigger project_monster_sleep()... then I've tested it in-game VS different monsters (eg pack of jackals) and it seems it doesn't work at all.. tested with normal (non-admin) char - generated bunch of staves with admin for him..

**Comment by igroglaz** [comment]
tested with pure PWMA - the same..

**Comment by draconisPW** [comment]
When you code stupidly you get stupid bugs... *facepalm*...

Fixed ;)

**Comment by draconisPW** [comment]
(note this was breaking a TON of stuff, in particular: sleep, slow, confuse, dispel...)
