### ISSUE TITLE
gcu client -> manual selection of server doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#388]
tested with pure PWMA. on client start -> Ctrl+m doesn't work

**Comment by draconisPW** [comment]
For some reason, ctrl-m is turned into key=13, which is interpreted as KC_ENTER.
ctrl-a -> 1 to ctrl-z -> 26
We get duplicated key values.

**Comment by draconisPW** [comment]
Problem arises in two cases: ctrl-i / TAB (key 9) and ctrl-m / ENTER (key 13). For the GCU client, only one of the two in each pair can be defined.

**Comment by draconisPW** [comment]
Looking at the command documentation, we can clearly see:
^I   (special - tab)
^M   (special - return)
Basically it tells that ctrl-i and ctrl-m should not be used. Moral of the story: I'll change manual selection to ctrl-s.
