### ISSUE TITLE
add state.stat_real

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#389]
it will be fun to add state.stat_real...

state.stat_real = p->state.stat_ind +3

as it's more convenient to use values from player's stat bar.. better from gamedesign perspective.. as when we have in-game +3 stats and at the same time we (from gamedesign perspective) should calculate staff in out heads from 0.. it makes a real unnecessary mess in head

**Comment by igroglaz** [comment]
for now I've used manual calculation eg there https://github.com/igroglaz/Tangaria/commit/46ba57df71ea2f2b1e8e82a170b11e9473089c24 ... but I suppose adding special constant will make code better

**Comment by draconisPW** [comment]
Add this in T if you want, I don't see the point in PWMA. It's used nowhere.
