### ISSUE TITLE
Assign dungeon profile to certain dungeon

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#39]
in dungeon_profile.txt there are some hardcoded dungeon types, eg Labyrinth. It would be fun to have possibility to pre-define certain dungeon_profile to certain dungeon (in dungeon.txt). Eg:

name:The Sandworm Lair
wpos:-2:2
min-depth:23
max-depth:30
max-level:30
flags:NO_DOORS | SAND_VEIN
floor:sand:10
wall:sandwall:10
rule:90:0
rule-symbols:w
rule:10:0
rule-flags:MULTIPLY
**profile:labyrinth:50 | Cavern:50**

it means that cutoff (from dungeon_profile.txt) would take predefined chances for labyrinth and cavern (50+50=100) and also there would be still 100 more cutoff points left chances for random dungeons profiles from dungeon_profile.txt

**Comment by draconisPW** [comment]
Not sure if the dungeon code can allow this. Putting this to future, but I don't think I'll change the udngeon code.

**Comment by draconisPW** [comment]
Variant territory.
