### ISSUE TITLE
add a delay to solve problem with timeouts

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#392]
there is an old problem which scary people off... https://www.reddit.com/r/roguelikes/comments/obpnst/any_roguelikes_like_tangaria_or_pwangband_but/

sometimes when you create character or enter the game too fast (pushing 'Enter' key several times in a row) - there comes timeout which is kinda client crush. It's an old issue which haunts us for 2 years 👯  maybe to hardcode a delay (cooldown) on which client won't accept any pushdowns when entering the game?

**Comment by draconisPW** [comment]
MoTD now can only be exited with the SPACE key.

**Comment by igroglaz** [comment]
it's still possible to trigger timeout right after you choose character if you enter the game fast - you can see game "Enter" menu ( https://cdn.discordapp.com/attachments/699917093717671946/861873896574812170/Untitled-1.png )

Maybe a solution could be to add to mangclient.INI disable_enter (this option exist for character atm)

**Comment by draconisPW** [comment]
How? Since you can only press SPACE now, this should not be possible...

**Comment by igroglaz** [comment]
https://youtu.be/yKPwhNhQGJQ

**Comment by draconisPW** [comment]
I see. Enter still counts as a "packet request" in this case so I need to disable this until we're properly playing.

**Comment by draconisPW** [comment]
Enter is now disabled until client is"ready" to play. If this is still not sufficient, I will need you to provide debugging video because I can't reproduce it locally.
