### ISSUE TITLE
nazguls destoying weapons

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#396]
in PWMAT (PWMA & T) player find LOADS of randarts-true arts weapons. LOADS (and it doesn't hurt cause of 1-char-1-account permadeath). But at certain moment players don't start even to pick up these arts... which is quite irrealistic and not fun in terms of narrative.. bright and shiny powerful weapon arts scattered in dungeon floor when players leaves it.

I suppose it will be cool to take TomeNET idea - to destroy weapons when you fighting Nazgul. In TomeNET this design actually works not so good as it will work in PWMAT, because in TomeNET there is MUCH rare drop of artifacts than in PWMAT. So there were cases in TomeNET when I simply didn't had any weapon to fight nazguls cause they destroyed all. But it won't be the case in PWMA, as you get enough of true-arts. But at least you will have to think about it.

**Comment by draconisPW** [comment]
Lol... nope :)

**Comment by draconisPW** [comment]
(simple reason: in PWMAng, Nazguls are level 80+ uniques and at this point you will not fight with the crap artifacts you find, but with your endgame weapon -- losing main weapon to an arbitrary roll is just plain stupid)

**Comment by igroglaz** [comment]
yep.. it seems PWMA not suited for this idea :) while in T it will be alright as Nazguls there got traditional lvls
