### ISSUE TITLE
generic town and dungeon playlists

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#397]
/rfe add
'generic-town' folder - will play music for all towns
'generic-dungeon' folder - will play music for all dungeons

for example, right now I got 200 MB (and it will be more) generic dungeons music playlist which I wanna play in every dungeon. Now I need to copy this 200 MB to every dungeon folder.. so there will be 30+ folders with the same files in it :D 30*200 = 6GB of music when it could be only 200 ;)

**Comment by draconisPW** [comment]
Implemented.
