### ISSUE TITLE
specific dungeon/town music doesn't work

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#398]
custom music for cities/dungeons doesn't work :frowning:

when I put music track in music 'root' folder - it works, but inside of folders - doesn't.. eg:

D:\games\Tangaria\lib\music\reconor-0_0.mp3              --  works

D:\games\Tangaria\lib\music\0_0\reconor-0_0.mp3       --  doesn't work

I've made test branch with examples
https://github.com/igroglaz/Tangaria_release/commit/8969c0267486d37915e830facff2754efb9383ee

**Comment by igroglaz** [comment]
[02:28] PowerWyrm: I just need to check what happens when a dungeon is below a town

**Comment by draconisPW** [comment]
I just checked and it works for me. Has to be a problem with your /lib folder.

**Comment by draconisPW** [comment]
I have:
/music/1.mp3
/music/Hobbiton/2.mp3
/music/Training Cave/3.mp3

When in Hobbiton it properly plays "2", in Training Cave (dungeon below) it plays "3" and everywhere else it plays "1".

short:Training Cave in dungeon.txt
short:Hobbiton in town.txt

**Comment by igroglaz** [comment]
My simple setup in Tangaria_release 'test' branch:

https://github.com/igroglaz/Tangaria_release/commit/55f49f6bbf1cab11dc920df1fe9f20cf0b20c37f

I have:
/music/Forest_Ambience.mp3
/music/0_0/suonatore-di-liuto.mp3
/music/0_1/suonatore-di-liuto.mp3
/music/Old Ruins/reconor-0_0.mp3

Everywhere it plays only :"Forest_Ambience.mp3"

short:0_0 in dungeon.txt (starting location)
short:0_1 in dungeon.txt (town)
short:Old Ruins in town.txt (1st dungeon in starting location)

**Comment by igroglaz** [comment]
maybe it's bacause short startin from number? "0_1"...

**Comment by igroglaz** [comment]
oook. I was really stupid! forgot to update server

sorry :)
