### ISSUE TITLE
[bug or feature?] fire-till-kill won't stop after killing monster

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#4]
Right now there is a quite interesting feature - fire-till-kill works without breaks while there are monsters around. In TomeNET fire-till-kill stops after you kill particular monster even if there are more of them on sight.

Actually I like this feature so far and not sure that I want it to go away, it's seems for me more fun than FTK in TomeNET :) But I want to report it to you, so you would know about this behaivour. Maybe there could be an option added - to stop fire-till-kill when you kill monster, so some players would like to have it ON.

**Comment by draconisPW** [comment]
Feature -- fire-till-kill is simply a repeat count that is canceled when the player is disturbed, and therefor works exactly the same as digging. This was *much* easier to implement than stopping after monster is killed.
