### ISSUE TITLE
Add aquatic monsters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#40]
I've got some wilderness locations with a lot of water, but they are quite empty right now because currently monster can't be spawned on water tiles. 

/rfe to add monster (or terrain? hm...) flag which will allow certain monsters to spawn on water, eg
water spirit, water elemental.. also I'll add some fish monsters :)

**Comment by draconisPW** [comment]
From my roadmap.txt file: "add aquatic monsters". Been there forever, never found time to implement it. Since 1.4 is supposed to be monster rework, it's a good time to do this. There is already an "aquatic" monster base, but only one "aquatic" monster (The Watcher in the Water).

**Comment by draconisPW** [comment]
Implemented in 7357c37.
