### ISSUE TITLE
character dump file name

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#401]
/rfe make character dumps files having time/date in filename
eg atm is 23:45 01.06.2021.. so filename:
Foo-234501062021.txt
cause atm we don't have time/date in char dumps :( to use it there https://stat.tangaria.com/

**Comment by draconisPW** [comment]
The user dump has the server turn in the name. That's more pertinent than the date. If you want the date, just add it with the tool that generates your stats.

**Comment by igroglaz** [comment]
nope, it's not pertinent.. because it's probable that there will be duplicates in ladder: https://stat.tangaria.com/ after server wipe..  imagine what happen after 10 or 50 server wipes after some years? while having date - exclude this probability

also having date/time is very useful for ladder purposes. eg oook ladder has it http://angband.oook.cz/ladder.php , but there it's uploading date, which is not precise. having date of death is much more relevant
