### ISSUE TITLE
character dump file: add account name

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#402]
/rfe add account name to character dump file (at the bottom of file, so we will preserve compatibility with old dumps). then we will be able to find all dumps made by certain player

**Comment by draconisPW** [comment]
Done.

**Comment by draconisPW** [comment]
Note: the info added is the "real name" part of the connection, which identifies the player.

FOR NO REASON WHATSOEVER MUST THE ACCOUNT NAME BE DISPLAYED PUBLICLY!!!

**Comment by igroglaz** [comment]
"real name" will change when you change PC.. so it's better to use account name. I play from notebook sometimes (even two notebooks)..

I don't think it's a big deal as everyone anyway could figure out player's account name - most of people got their account names the same as main character names. The best defense is long strong password
