### ISSUE TITLE
brute-force protection

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#403]
btw.. speaking of security there https://github.com/draconisPW/PWMAngband/issues/402

/rfe add simple protection VS brute-force; it could be a cooldown between attempts to enter the game when you enter wrong password, example:
hacker trying to brute-force certain account and enter wrong password 3 times in a row. now this account (on which he is trying to brute-force) become non-available to login from this IP for n (5?) minutes. This trick will make brute-force almost non-possible for long digits password (15+), so it will be quite safe to have account logins visible in dump files.

I got such protection on each of my websites ;)

**Comment by draconisPW** [comment]
Reminder for next version (will require reset). Like any login page where the login is saved into a database, add a flag for number of erroneous attempts to connect and lock the account in case this is reached. Usually that number is 3. Save this number in the account file with name/password. Allow the admin to unlock accounts.

**Comment by draconisPW** [comment]
To make this easy, I simply added an "accountname.lock" file with one line having the number of failed attempts to connect. If the number reaches three, the account is locked. Admin can edit that file and set the number to zero to unlock an account.

**Comment by igroglaz** [comment]
there might be a problem that someone will block other's person account on purpose :( is it possible to add somekind of cooldown? possible solution could be: purge this file every hour or so

**Comment by igroglaz** [comment]
![image](https://user-images.githubusercontent.com/39904162/202871910-9b5c0491-cb38-420f-83d5-389ae87742e7.png)

seems this feature need some polish ;) eg atm I've got 214 lock files.. some got 0 inside, some 1, some 3.. it's hell to manage it.

How it could be redesigned IMHO:
1) by default all unlocked
2) if some player missed password for several times - his account name added to a new file locked.raw
3) in this file there are ONLY account names and number of attempts, eg

GImly
3
Torin
1
Gandalf
2

4) also add routine to _delete_ this file each hour

**Comment by igroglaz** [comment]
Also no need to make a wipe..

**Comment by igroglaz** [comment]
Or... even more simpler solution. Just auto-delete all .lock files once per day.

**Comment by draconisPW** [comment]
All lock files are now in /save/lock to separate them from the actual save files. Every day when the log file is created, all lock files inside /save/lock are deleted.
