### ISSUE TITLE
SELECT effect

### ISSUE THREAD

**Issue by draconisPW** [draconisPW/PWMAngband#409]
Keeping this as a reminder for future consideration (due to V implementation totally unpracticable in real time).

Refers to the following commits from V:
- Add a SELECT effect; use it for items with multi-breath effects (May 30, 2021)
- Use SELECT rather than RANDOM for randart activations (Jul 4, 2021)

The functionnality:

>At the moment a wand of Dragon's Breath or a multi-hued DSM activation is actually worse than a single-breath attack: if the monster resists one or more elements, there is a chance that the random breath attack will be wasted, whereas you always know whether or not your single-breath attack will work.

>d_m's proposal is that these multi-breath attacks should automatically find any resistance holes the monster has.

>My own idea was to let the player choose the element to be used, but that would involve creating an additional prompt.

In real time, adding a prompt each time you want to use multi-breath to choose the effect is really not a good choice. Plus you may want to target multiple monsters which you have no idea of their resistances.

Finding resistance holes to select the effect is also not really feasible, since it involves trying every effect on the target before choosing one, actually forcing to call the effect routine n+1 times.

Another idea would be to "average" all effects instead, like what is done with the "Thunderstorm" spell (sound + lightning + light effects with 1/3 damage each).

**Comment by draconisPW** [comment]
Implementing as SELECT would require too much work and would not be really practical. So I will implement the "average" idea. Effect will be AVERAGE and will simply apply all effects with damage divided by the number of effects.

**Comment by draconisPW** [comment]
In fact I don't really need an effect. I will just halve the dice values and apply all effects.

**Comment by igroglaz** [comment]
I don't get it. Why to change old, random system? It was totally alright. SELECT is meh, but also IMHO there is no need to change it to 'average'... it was alright and roguelikish.... now it seems dull
