### ISSUE TITLE
random gift and their max price

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#410]
/rfe add possibility to assign random gift to race/class, eg hobbit will receive 3 different mushrooms:
```
gift:mushroom:random:1:1
gift:mushroom:random:1:2
```

it means that hobbit will get 1 mushroom of one kinds, 1-2 mushrooms of another kind

The problem is: some of items could be quite expensive, eg if it will be random potions and certain race will get potion of augmentation right on...

To solve this problem may be different solutions:

1) make it based on items: cost: and alloc:
but there are plenty of powerful 'cost:0' items - 0 value used to prevent item from appearing in the shop.... so to solve it maybe we should add new value for preventing buying item: "-1"

OR

2) adding new value to object.txt:
gift:1
which will mean that this item could be included to gifts.. so we manually will assign all items suitable for gifts. I think this is best solution for this problem..

Also it will be fun to make this items unidentified (not the case for hobbits mushrooms ;D ), eg Kobold will get:

gift:potion:Poison:1:2
gift:potion:random:1:2

So kobold will get 1-2 potions of poison (IDed) and 2 unidentified potions 🧴

**Comment by draconisPW** [comment]
Sorry but this would mean adding a ton of hacks for the generation routine. Variant territory.
