### ISSUE TITLE
play specific location tracks and them play generic one

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#417]
/rfe to complete PWMA beautiful music system: play specific location tracks and them play generic one, eg

- town location **'Bree'** got inside music track **bree1.ogg** **bree2.ogg**
- **'town-day'** got inside **generic-day1.ogg generic-day2.ogg**...
- **'town-night'** got inside **generic-day3.ogg generic-day4.ogg**...

player enters Bree location and first it's played *bree2.ogg* or *bree2.ogg*. After town-specific playlist played completely - it will play stuff from 'town-day' or 'town-night' (depend on time of the day): generic-day1.ogg or generic-day2.ogg...

So each location will have it's "branded" music theme which will play once and afterward, when "branded" playlist will be played, - it will play generic music

this will complete music system and will make it really awesome :)

**Comment by draconisPW** [comment]
I'm closing this, music system is gone as far as it could for regular PWMAngband.
