### ISSUE TITLE
throw equipped weapon crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#418]
![image](https://user-images.githubusercontent.com/39904162/127037219-84e1978e-2d03-4b78-99e3-adb07fbfe389.png)

player tried to throw equipped armour (Robe)

player-attack.c

```
  if (object_is_equipped(p->body, obj))
    {
        my_assert(obj_can_takeoff(obj) && tval_is_melee_weapon(obj)); <<<<<<<<< CRUSH
        inven_takeoff(p, obj);
    }
```

so robe (armour) checked - is it a melee weapon... and it's not. and game stops

I suppose we need to add return false; if it's not a melee weapon

**Comment by draconisPW** [comment]
Throw command should check tval_is_melee_weapon already so it should not propose the robe as valid item. Need to check why it does and fix it.

**Comment by draconisPW** [comment]
This is impossible and can only happen if the client is hacked.

**Comment by igroglaz** [comment]
The problem is that it leads to server crush. And if user can 'hack' client and crush server with it - this is serious bug and should be fixed on server side.

Also I very doubt that this user hacked the client.

**Comment by draconisPW** [comment]
I'll remove the assert. It assumes the client is using restrict_for_throwing(), which could be removed and client recompiled to allow throwing anything, which the server responds by exiting. I'll replace this with a return, like what it is done everywhere else.

**Comment by igroglaz** [comment]
👍 I've made it like this:
`    if (object_is_equipped(p->body, obj))
    {
		if (!tval_is_melee_weapon(obj) && !obj_can_takeoff(obj))
			return false;
		inven_takeoff(p, obj);
    }`

**Comment by draconisPW** [comment]
if (obj_can_takeoff(obj) && tval_is_melee_weapon(obj)) inven_takeoff(p, obj);
        else return false;

Your statement is incorrect ;)

**Comment by igroglaz** [comment]
I'm noob for sure :) But please could you explain, why my statement is incorrect?

**Comment by draconisPW** [comment]
The opposite of (A && B) is (!A || !B)...

**Comment by igroglaz** [comment]
Oh, sure :D It was stupid :DD THanks
