### ISSUE TITLE
lesser fractions of volume on low values

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#419]
/rfe for volume panel: if user sets volume to 10% and then reduces it farther - make it decrease not for -5%, but for -1%

atm it's possible to do by editing the sdl ini file, but it will be easier to do in client for new players

**Comment by igroglaz** [comment]
though.. I suppose it will be easier to remaster volume of music

**Comment by igroglaz** [comment]
nope.. this stuff still needed. cause even at 5% volume music is too loud. so I got to set it to 2-3% in config file. I suppose there will be plenty of people who would want to setup precise volume..

**Comment by s88100** [comment]
to change the values ​​(volume + -) button-> tag = 5; by 1 need to completely reload the Options menu (MoreActivate)
The volume is refreshed after a reboot or music change, value of 5 should play music very quietly.

**Comment by igroglaz** [comment]
I see, thanks. Lets leave close this then. It's a minor issue after all - possible to assign in config file
