### ISSUE TITLE
Increase chances of successfully digging

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#42]
I'm not sure in this (is it good or bad), but wanna share the idea:

increase chances of successfully digging with each attempt. because sometimes if you are not lucky it could take very long to dig through something :)

If chances are increasing - it's like more realistic model of digging (pieces of rock fall from wall, it become less thick -> eventually you would dig through it).

**Comment by igroglaz** [comment]
I suppose there is a relative easy way to implement it - the same way as it's done for locked doors https://github.com/draconisPW/PWMAngband/issues/188#issuecomment-626516564

**Comment by draconisPW** [comment]
Variant territory.
