### ISSUE TITLE
ncurses (terminal client) - symbols '@' are not displayed correctly inside some buildings.

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#420]
in PWMAngband I start in Tavern. The character is not updated '@' and other symbols appear.

if I maximize the window to full screen this will make Term-0 bigger, after a while the client hangs 'Segmentation fault'

![ncurses-bug1](https://user-images.githubusercontent.com/71586060/128060861-4abf2b5e-58f2-4aaa-8617-7b651ebf2f27.png)

**Comment by s88100** [comment]
PWMAngband/etc/pwmangband/customize/font-gcu.prf
```
### Terrain features (solid walls) ###

# Floors
#feat:open floor:*:0x01:0xB7
```
removed `'feat:open floor:*:0x01:0xB7'` displays without bug.
problem in 0xB7 if change to 0x2E (ASCII) or another value displays normally

/src/client/main-gcu.c :L845
`Term_text_gcu()`
uses `wchar_t buf` for text

`char` value supports 'ascii byte' up to 0x80
```
if ( (ch & 0x80) == 0x0 ) {
  //ascii byte
}
else if ( (ch & 0xe0) == 0xc0 ) {
  // 2 bytes
}
```
https://lwp.interglacial.com/appf_01.htm

0xB7 (2 bytes) requires `wchar_t` to display correctly

**Comment by s88100** [comment]
/src/client/main-gcu.c :L845
`static errr Term_text_gcu(int x, int y, int n, u16b a, const char *s)`
should display objects 'open floor' etc.
but after `mbstowcs(buf, s, n);`
does not see 0xB7, 0xAE ... (2 bytes) `if (buf[i] == 0xAE)`

in /angband/blob/master/src/z-util.c :L744
```
/**
 * Allow override of the multi-byte to wide char conversion
 */
size_t text_mbstowcs(wchar_t *dest, const char *src, int n)
{
	if (text_mbcs_hook)
		return (*text_mbcs_hook)(dest, src, n);
	else
		return mbstowcs(dest, src, n);
}
```

**Comment by draconisPW** [comment]
I don't have this problem when using the GCU client on Windows. If I use 0xB7 as char to display, I get s[x]=-73 or 0xFFB7 passed to Term_text_gcu() which translates into buf[x]=183 or 0x00B7 properly. Angband uses wchar_t in all text hooks, but I don't have time to port everything using wchar_t so I'll simply add a check for non Windows and discard anything > 127.

**Comment by draconisPW** [comment]
Fixed. If not on Windows, all fancy stuff in font-gcu.prf is discarded.
