### ISSUE TITLE
'Detect monsters' spell: delay to 'Monster list'

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#421]
as for now this issue can't be done: https://github.com/draconisPW/PWMAngband/issues/135
lets do this: add a delay to 'Monster list' window after casting detect spells.. eg in my today's stream ( https://youtu.be/_pF6kzNo44Y ) it was very hard to read monster names/directions cause it dissapears faster than in a second 

another way to solve problem - to duplicate monster names-directions to Message Window... maybe sending it to message window is actually better solution

**Comment by igroglaz** [comment]
there is pause_after_detect option, but it doesn't help, on the countrary it freeze the main screen (which leads to player to necessity to push any other key after casting spell to unpause it), but do not freeze Monster List window :(

The best way to solve it - duplicate monster names-directions to Message Window. then there won't be need to freeze anything

**Comment by draconisPW** [comment]
This makes no sense as everything is updated in real time. Best I can do is propagate the "icky" flag to the monster list and also freeze it while waiting for the user to press a key.

**Comment by igroglaz** [comment]
Hm.. We can just add an option to send (duplicate) monster names-directions to Message Window. It make sense as it's not possible to read monster list window as it blink too fast.

**Comment by draconisPW** [comment]
Well the point is to make it not blink, but give info until the user presses a key after the "You sense (foo)!" message. Should fix this nicely.

**Comment by igroglaz** [comment]
Hm.. So it won't freeze main screen? Only monster list? Cause freezing main screen is a problem as while player is reading Monster List coordinates (could take awhile) - he could be attacked and won't know it as screen not refreshed... Maybe any disturbance should interrupt "You sense (foo)!" - then it will be indeed perfect solution.

**Comment by draconisPW** [comment]
Implemented: don't refresh monster list after a pause due to detecting some monsters.
