### ISSUE TITLE
empty scroll name

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#422]
https://youtu.be/_pF6kzNo44Y?t=243 (timecode) - empty scroll flavour..

possible reason:
T's flavours: https://github.com/igroglaz/Tangaria/blob/dev/lib/gamedata/flavor.txt

Sometime ago (before wipe) I've added 4 extra flavours for scrolls, just in case, for later..

Should number of items of certain type be equal to number of flavours of this type?.. Or is it different bug?

**Comment by draconisPW** [comment]
This is because max number of scrolls is hardcoded: #define MAX_TITLES 50. Note that this should also happen in regular PWMangband, as the number of flavors defined is 51. I'll increase the value of the defined constant.

**Comment by draconisPW** [comment]
Increased to 60.
