### ISSUE TITLE
GCC (Linux) 'implicit declaration of function'

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#423]
gcc asks a few questions when compiling

```
common/sockbuf.c:334:26: warning: implicit declaration of function ‘GetSocketErrorMessageAux’; did you mean ‘GetSocketError’? [-Wimplicit-function-declaration]
                     plog(GetSocketErrorMessageAux(errno));
                          ^~~~~~~~~~~~~~~~~~~~~~~~
                          GetSocketError

client/netclient.c:136:5: warning: implicit declaration of function ‘gettimeofday’; did you mean ‘SetTimeout’? [-Wimplicit-function-declaration]
     gettimeofday(&cur_time, NULL);
     ^~~~~~~~~~~~
     SetTimeout

server/netserver.c:835:63: warning: implicit declaration of function ‘Sleep’; did you mean ‘sleep’? [-Wimplicit-function-declaration]
     while ((Socket = CreateServerSocket(cfg_tcp_port)) == -1) Sleep(1);
                                                               ^~~~~
                                                               sleep
```
'implicit declaration of function' means that you are trying to use a function that has not been declared.

```
/* For gettimeofday */
#include <sys/time.h>
```

Sleep() function to wait for a period of milliseconds.
int sleep (unsigned int seconds)

```
/* 1 second */
#ifdef WINDOWS
		Sleep(1000);
#else
		sleep(1);
#endif

```
usleep() - suspend execution for microsecond intervals
1 millisecond to microsecond = 1000 microsecond
usleep(1000);

**Comment by draconisPW** [comment]
1) Need to declare GetSocketErrorMessageAux() in net-unix.h (it's defined in net-unix.c)
2) Need to include <sys/time.h> for gettimeofday() in netclient.c
3) Need to declare Sleep in net-unix.h (it's defined in net-unix.c)

**Comment by draconisPW** [comment]
Fixed.

**Comment by s88100** [comment]
in /src/common/net-unix.c :L34
```
void Sleep(int time)
{
    sleep(time);
}
```
Sleep(1) - Windows in milliseconds
sleep(time); - number in seconds

https://stackoverflow.com/questions/1157209/is-there-an-alternative-sleep-function-in-c-to-milliseconds
_it should be_

```
void Sleep(int time)
{
    sleep(time / 1000);
}
```

**Comment by s88100** [comment]
or Sleep() should be in seconds?

/src/client/main-gcu.c :L792
`case TERM_XTRA_DELAY: if (v > 0) Sleep(v); return 0;`

/src/server/netserver.c :L835
`while ((Socket = CreateServerSocket(cfg_tcp_port)) == -1) Sleep(1);`

**Comment by s88100** [comment]
check, please
angband/blob/master/src/main-gcu.c :L70
```
#if defined(WIN32_CONSOLE_MODE)
# undef USE_TPOSIX
_stdcall void Sleep(int);
#define usleep(v) Sleep(v / 1000)
#endif
```
src/main-gcu.c :L796
```
/* Delay */
case TERM_XTRA_DELAY: if (v > 0) usleep(1000 * v); return 0;
```

_sample_
```
void setup_contact_socket(void) {
	plog(format("Create TCP socket on port %d...", cfg.game_port));
	while ((Socket = CreateServerSocket(cfg.game_port)) == -1) {
#ifdef WINDOWS
		Sleep(1000);
#else
		sleep(1);
#endif
```

**Comment by draconisPW** [comment]
Sleep() definitely uses milliseconds, so I'll replace the code in net-unix.c with call to usleep().
