### ISSUE TITLE
race: resistance -> immunity progress problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#425]
If Spider race got:

value:1:RES_POIS[1]
value:15:RES_POIS[3]

new character won't have resistance to poison....

if I put it in other order:

value:15:RES_POIS[3]
value:1:RES_POIS[1]

new char got resistance... but at level 15 character won't receive immunity

**Comment by draconisPW** [comment]
There is no such thing as poison immunity. Setting RES_POIS[3] will not work, it only works for fire/cold/elec/acid.

**Comment by igroglaz** [comment]
Lets add it to all kind of magic? :D
