### ISSUE TITLE
Allow multiple values for race/class abilities depending on level

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#426]
goes close to this issue: 
https://github.com/draconisPW/PWMAngband/issues/425

Spider race. Lets made it for testing purpose:
value:10:RES_POIS[3]
it means that at lvl 10 it will become immune to poison

Spider race is PERM_SHAPE.... so it take shapes of s'spiders which got
flags:IM_POIS
So cause of shapes IM_POIS (which is not IM for poly player, but simple resist) - value:10:RES_POIS[3] won't work. When I get lvl 15 with my perma shape spider - I got only simple resist, not immunity

**Comment by igroglaz** [comment]
and funny thing... I've made Spider to start with:
value:1:RES_POIS[3]

right after we create char we see that we got immunity in 'C'

then I get lvl 3 to get first s'spider form.. anf my immunity is gone, I got resistance now 🕷️

**Comment by draconisPW** [comment]
Same as previous, immunity to poison does not exist, RES_POIS[3] is meaningless.

**Comment by igroglaz** [comment]
ok, thanks. Another case: I've got Elemental race:
value:1:RES_ELEC[-1]
value:20:RES_ELEC[3]
value:20:RES_COLD[-1]

when I start new character, it doesn't have -1 elec... when it receive lvl20 - it's got immunity, but there is no -1 cold

**Comment by draconisPW** [comment]
Whoops :)
In fact the init parser is not configured to allow multiple values for the same flag, so it is simply overwritten (in this case the immunity overwrites the vulnerability).

**Comment by draconisPW** [comment]
Unfortunately I don't see what I can do without having to break everything, so this will have to wait to be implemented. For now, only one entry is allowed, meaning that you can only assign an element to a race or class once.

**Comment by igroglaz** [comment]
Got any idea how to fix it? It's very critical issue for T :( Please could you look into it ❤️

**Comment by draconisPW** [comment]
No idea why this was closed, it was planned for 1.6.0.

**Comment by draconisPW** [comment]
Implemented for elements (tested with Elemental example above).
