### ISSUE TITLE
TYP_RUBBLE, TYP_TRAP, TYP_FOUNTAIN

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#427]
atm this formula:
    /* General amount of rubble, traps and monsters */
    k = MAX(MIN(wpos->depth / 3, 10), 2);

makes very small amount of rubble, traps and fountains on low lvls.. eg on lvl 15 it's almost impossible to find fountain, which is quite critical as without fountain it's hard to cure batty.. 

/rfe add rubble, trap and fountain to dungeon_profile.txt (similar to https://github.com/draconisPW/PWMAngband/issues/189 )

**Comment by igroglaz** [comment]
I've made temp solution https://github.com/igroglaz/Tangaria/commit/65b9aadb03b9025697c4968da7ac029b8ffaa853 , will do for now.. also I've added at least one fountain even to 'strange' places (gauntlet) - as finding fountain may be quite critical and player may not recognize certain dungeon patterns, trying to find fountain till the last room... when it maybe too late.

I suppose we may think about leaving 'general' formulas in gen-cave.c , while adding to dungeon_profile.txt only 'common' staff for general levels. I mean - we don't want to have a lot of fountains in Gauntlet level aka we don't want to have the same amount of fountains in all levels at certain dungeon. So unhardcoding should include only "general" levels, like: classic, cavern, modified etc.... but specific stuff like labyrinth, gauntlet, lair, etc - should stay hardcoded to be able to set there special numbers

**Comment by draconisPW** [comment]
Rubble and traps are fixed by V values and won't be touched. For fountains, I set an arbitrary value when adding the feature without really playtesting it, I'll just use the same value as rubble for all profiles.

**Comment by draconisPW** [comment]
Was planned for 1.6.0 and shouldn't have been closed.

**Comment by draconisPW** [comment]
Increased the amount of fountains using the same value as rubble.
