### ISSUE TITLE
server logs bug

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#430]
logs works at Version 1.5.0 beta 5 - f94825122f10dadc63e55cbe10ca271f801a769f
doesn't works at Fixes - 3ac7bff92c6034e9b5ed46bfcf292caea0de1f15

**Comment by igroglaz** [comment]
reverted in T https://github.com/igroglaz/Tangaria/commit/581642289ea0222fef655a76c8927c1e94580ce6

**Comment by draconisPW** [comment]
Change was made because the log was crashing (silently) when shutting down the server due to trying to log stuff after file descriptor being already released. Apparently the fix didn't work.

**Comment by draconisPW** [comment]
Properly fixed this time.
