### ISSUE TITLE
monster BR_CHAOS -> crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#432]
https://youtu.be/TunvYhT2n3k

**Comment by draconisPW** [comment]
context->origin->player is not always defined in project_m_apply_side_effects() so a check vs NULL must be made.

**Comment by draconisPW** [comment]
Fixed.

**Comment by igroglaz** [comment]
please could you publish this fix asap as it crush server from time to time, eg today at night it was crushed and players weren't be able to play till I wake up to restart server

**Comment by draconisPW** [comment]
I won't publish anything before final version for obvious reasons (not wanting to manage intermediate version for clients). To fix this, just replace locally in project_m_apply_side_effects() line 1676:

if (!context->seen && context->mon &&
                monster_is_visible(context->origin->player, *m_idx))

with:

if (!context->seen && context->mon && context->origin->player &&
                monster_is_visible(context->origin->player, *m_idx))

and recompile.

**Comment by igroglaz** [comment]
thanks! fixed on server
