### ISSUE TITLE
refilling light source by dropping it in house

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#434]
it's possible to refill light source by dropping it in house (I suppose it's cause atm it's possible to recharge wands/rods this way).

also funny that dropping 15000 turns lantern - you pick up from the floor 7500 turns :)

this way it's possible to refill torches which other way not possible to refill... so maybe leave possibility to refill this way torches, but forbid all other types of light sources.

**Comment by draconisPW** [comment]
Works as intended (see MAngband).

**Comment by igroglaz** [comment]
are you sure? :D  torch (torch, Karl!) could be refilled by dropping it on the floor in house.. 
[21:01] igroglaz: @PowerWyrm why torches can't be refilled? is there any important reason behind such restriction?
[21:03] PowerWyrm: because it's made of wood which is consumed, once you reach 0 turns the torch is gone

cant see logic how we can 'recharge' torch by dropping it on the floor :D 

anyway I'm fine with it. refilling torches doesn't make any disbalance
