### ISSUE TITLE
problem with keymaps remapping

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#435]
I've reassigned 'c' (close command) to 'ctrl'+'c' and assigned a spell to 'c'. So if I wanna use 'close' command - I press ctrl+c. And for spell I press simple 'c'.

it works alright (I can close doors and cast spell) but now I can not operate with inventory or buy/sell items in shops

/rfe while there is item prompt (shop or we use items or drop something) - make reassigned **_(Aa-Zz)_** keys work by default. so when player choose to drink a potion and game asks "which one?" - player will be able to press 'c' and instead of casting spell he will choose a potion.. or maybe there are some other ways to fix it.

**Comment by draconisPW** [comment]
You should NEVER remap command keys, unless you know you won't ever use the command (for example, remapping the Dig spell to 'T' is perfectly fine since it's basically the same and there are really few cases of lists that go as far as T).

**Comment by igroglaz** [comment]
the problem is that we don't have enough keys to play mage. in V it's easy as there players don't need hotkeys at all as they play TURN-BASED. but in PWMA Sorcerer class got 37 spells. 37, CARL! + we need additional actions for MD, potions and misc stuff.

So when you play REAL-TIME - it's essential to be able to press 'single' hotkeys - 1 push = 1 action. `Shift` and `Ctrl` for F1-F12 is bad stuff as you need both hands to input such command, while player should always have one hand on NumPad in case of emergency. 

So.. we really need a to give experienced players (who play mages) a way to map more hotkeys. In TomeNET there are 
'command' and 'hybrid' system macroes available:

https://www.tomenet.eu/guide.php?chapter=3.6

Command macros:
---------------
Command macros are only executed if the game isn't currently waiting for a
specific input, for example "quaff which potion?" or while you're typing chat
messages. That means they won't "disrupt" any other command which is currently
being run. This is convenient for keys which you use in chat, but can be
dangerous if you define vital macros as command macros.
It is recommended to make your most important macros normal macros or at least
hybrid macros (for example a "panic key" macro). Command macros don't work
in shops.


Hybrid macros:
--------------
Use 'create hybrid macro' instead of 'create normal macro' in case you don't
want the macro to appear on hitting the corresponding key in a normal chat
message (for example useful for '-' key so it won't prevent you from
inscribing your Word of Recall scrolls).
Hybrid macros still work within input requests such as "quaff which potion?",
just not in STRING INPUT such as chat lines, polymorph-codes or money amounts.
Hybrid macros don't work in shops.

Such system solves this problem.. When I played TomeNET with runie I had all my keyboard remapped and it was comfortable ;)

**Comment by igroglaz** [comment]
We have atm:
numpad section + ctrl+numpad = 20 keys (~7 mapped to misc items)
F1-F12 = 12 keys (~5 mapped to misc items)
winkey(mapped to shift+F12) + caps lock(mapped to shift+F11)  + tab + ~ + ` = 6

(20-7) + (12-5) + 6 = 26 keys left. For 37 spells. while I didn't count some additional swap items hotkeys and MD activation

**Comment by igroglaz** [comment]
what about such solution: give possibility to use \ command in shops and in prompts? ('\' special: bypass keymap ). this will solve this problem once and for all :D

**Comment by igroglaz** [comment]
[16:12] YAROSSS: Just use arrows and "enter" to buy in shop
[16:15] YAROSSS: And to operate inventory (use witch potion to quaff wne pressed q) and so on

:D pretty interesting idea. didn't though about such way (I didn't use Enter and arrows ever).. will try, thanks :D
