### ISSUE TITLE
Failed to load sound: _

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#439]
recently I've added new sounds to be aware of attacking immune/resistant monsters. they works alright, but sometimes very strange thing happens:
if you attack 'resist_a_lot' monster, game gives 'Warning' prompt:
"Failed to load sound: _"
game does not crush... so you can click OK and continue to play until next prompt. demo:

https://youtu.be/P7RMocJ6E60

sound-core.c
166
```
        if (!load_success)
            plog_fmt("Failed to load sound: %s", sound_data->name);
    }
```

**Comment by igroglaz** [comment]
commits with new sounds:
https://github.com/igroglaz/Tangaria/commit/b3b2879e34ba0a8c6904f6ef1229aa8d877de8b5
https://github.com/igroglaz/Tangaria/commit/15b716ee13976deba5c7ce68a6945969871969d4
https://github.com/igroglaz/Tangaria/commit/c53a5f44c8d5588274946a6c1b95258791206082
https://github.com/igroglaz/Tangaria/commit/b3b2879e34ba0a8c6904f6ef1229aa8d877de8b5

**Comment by igroglaz** [comment]
https://github.com/igroglaz/Tangaria/blob/dev/lib/sounds/sound.cfg
https://github.com/igroglaz/Tangaria/blob/dev/lib/customize/sound.prf

reproduce:
cast druid's Stinking Cloud spell on White jelly

**Comment by draconisPW** [comment]
Looking at 15b716e, you added the sounds in list-message.h at the end of the file. This is incorrect. The entries need to be added before:

/* Max message index (sound) */
MSG(MAX, NULL)

because they are sounds.

**Comment by draconisPW** [comment]
Sorry, I can't reproduce this problem, sounds works fine for me. You will have to install your client in debug mode and debug locally. Feel free to post your results here.

**Comment by igroglaz** [comment]
Several players reported this problem. To reproduce I spawn several White jelly in 1st dungeon by admin and then starting to cast Stinking Cloud by druid

**Comment by draconisPW** [comment]
I've spent 20 mins casting, never triggered an error. This means the problem is somewhere else in Tangaria code. Best is to debug locally and report the error.

**Comment by igroglaz** [comment]
I'm still not sure what was the reason why this bug happened. It seems the reason was bad line ending there:
https://github.com/igroglaz/Tangaria/commit/00c10dfeade6dd5eacae1d893e1d4818070a1386#diff-301b775c137bc4c272c3c10813e763937d7f08e489219898ef0733855410cdc7

**Comment by draconisPW** [comment]
Ah I didn't see that (when I tested, I didn't leave that extra space). Yeah if you leave a blank, the parser will interpret that as a blank entry. Good catch.
