### ISSUE TITLE
Add digging/chopping sound flags

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#44]
there is no sound for digging in PWMA. In TomeNET which is very nice one:
'TomeNET\lib\xtra\sound\player\commands\tunnel'

/rfe add 3 new sound flags:
digging rock
digging rubble
chopping tree

**Comment by igroglaz** [comment]
considering copyright for sounds from TomeNET - as there is no precise copyright for sounds in 'TomeNET\lib\xtra\sound\credits.txt', but the list with all nicknames (most of them from freesound.org , 
I suppose) - we could just include this list to the game package; and port sounds from TomeNET as they are very nice ones.

**Comment by draconisPW** [comment]
Keep the default sound for rock, add sound for trees.

**Comment by draconisPW** [comment]
Was planned for 1.6.0 and shouldn't have been closed.

**Comment by draconisPW** [comment]
On after thoughts, there is already MSG_DIG for digging which is fine for any terrain. Adding a sound each time you fail to dig doesn't bring anything and would just lag the client. Closing this then.
