### ISSUE TITLE
debug client in C++ Builder

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#440]
![image](https://user-images.githubusercontent.com/39904162/131996673-53b74871-b445-4b3f-8fbe-a79b41e1f43d.png)

error log:
`Checking project dependencies...
Compiling mangclient_sdl.cbproj (Debug, Win32)
ilink32 command line
  c:\program files (x86)\embarcadero\studio\20.0\bin\ilink32.exe -G8 -LD:\GitHub\Tangaria\PWMAngband;D:\GitHub\Tangaria\PWMAngband\src\_SDL;"c:\program 
  files (x86)\embarcadero\studio\20.0\lib\Win32\debug";PWMAngband\src\win;PWMAngband\src\common;PWMAngband\src\client;..\Tangaria;
  ..\Tangaria\PWMAngband\src\client;"c:\program files (x86)\embarcadero\studio\20.0\lib\win32\release";"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\win32\release\psdk";C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP;.\Win32\Debug 
  -jD:\GitHub\Tangaria\PWMAngband;D:\GitHub\Tangaria\PWMAngband\src\_SDL;"c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\debug";
  PWMAngband\src\win;PWMAngband\src\common;PWMAngband\src\client;..\Tangaria;..\Tangaria\PWMAngband\src\client;"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\win32\release";"c:\program files (x86)\embarcadero\studio\20.0\lib\win32\release\psdk";
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP;.\Win32\Debug -lD:\GitHub\Tangaria\PWMAngband -v -Tpe c0x32 
  "D:\GitHub\Tangaria\PWMAngband\c-cmd-obj.obj" "D:\GitHub\Tangaria\PWMAngband\c-cmd.obj" "D:\GitHub\Tangaria\PWMAngband\c-option.obj" 
  "D:\GitHub\Tangaria\PWMAngband\c-player.obj" "D:\GitHub\Tangaria\PWMAngband\cmd-core.obj" D:\GitHub\Tangaria\PWMAngband\conf.obj 
  "D:\GitHub\Tangaria\PWMAngband\game-event.obj" "D:\GitHub\Tangaria\PWMAngband\game-input.obj" D:\GitHub\Tangaria\PWMAngband\grafmode.obj 
  "D:\GitHub\Tangaria\PWMAngband\main-gcu.obj" "D:\GitHub\Tangaria\PWMAngband\main-sdl.obj" "D:\GitHub\Tangaria\PWMAngband\main-win.obj" 
  D:\GitHub\Tangaria\PWMAngband\main.obj D:\GitHub\Tangaria\PWMAngband\netclient.obj "D:\GitHub\Tangaria\PWMAngband\player-properties.obj" 
  D:\GitHub\Tangaria\PWMAngband\set_focus.obj "D:\GitHub\Tangaria\PWMAngband\snd-sdl.obj" "D:\GitHub\Tangaria\PWMAngband\snd-win.obj" 
  "D:\GitHub\Tangaria\PWMAngband\sound-core.obj" "D:\GitHub\Tangaria\PWMAngband\ui-birth.obj" "D:\GitHub\Tangaria\PWMAngband\ui-command.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-context.obj" "D:\GitHub\Tangaria\PWMAngband\ui-curse.obj" "D:\GitHub\Tangaria\PWMAngband\ui-death.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-display.obj" "D:\GitHub\Tangaria\PWMAngband\ui-event.obj" "D:\GitHub\Tangaria\PWMAngband\ui-game.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-init.obj" "D:\GitHub\Tangaria\PWMAngband\ui-input.obj" "D:\GitHub\Tangaria\PWMAngband\ui-keymap.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-knowledge.obj" "D:\GitHub\Tangaria\PWMAngband\ui-menu.obj" "D:\GitHub\Tangaria\PWMAngband\ui-message.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-object.obj" "D:\GitHub\Tangaria\PWMAngband\ui-options.obj" "D:\GitHub\Tangaria\PWMAngband\ui-output.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-prefs.obj" "D:\GitHub\Tangaria\PWMAngband\ui-spell.obj" "D:\GitHub\Tangaria\PWMAngband\ui-store.obj" 
  "D:\GitHub\Tangaria\PWMAngband\ui-term.obj" "D:\GitHub\Tangaria\PWMAngband\win-layout.obj" D:\GitHub\Tangaria\PWMAngband\buildid.obj 
  D:\GitHub\Tangaria\PWMAngband\datafile.obj D:\GitHub\Tangaria\PWMAngband\display.obj D:\GitHub\Tangaria\PWMAngband\guid.obj 
  D:\GitHub\Tangaria\PWMAngband\md5.obj "D:\GitHub\Tangaria\PWMAngband\net-win.obj" "D:\GitHub\Tangaria\PWMAngband\obj-gear-common.obj" 
  "D:\GitHub\Tangaria\PWMAngband\obj-tval.obj" D:\GitHub\Tangaria\PWMAngband\option.obj D:\GitHub\Tangaria\PWMAngband\parser.obj 
  D:\GitHub\Tangaria\PWMAngband\randname.obj D:\GitHub\Tangaria\PWMAngband\sockbuf.obj D:\GitHub\Tangaria\PWMAngband\source.obj 
  D:\GitHub\Tangaria\PWMAngband\util.obj "D:\GitHub\Tangaria\PWMAngband\z-bitflag.obj" "D:\GitHub\Tangaria\PWMAngband\z-color.obj" 
  "D:\GitHub\Tangaria\PWMAngband\z-dice.obj" "D:\GitHub\Tangaria\PWMAngband\z-expression.obj" "D:\GitHub\Tangaria\PWMAngband\z-file.obj" 
  "D:\GitHub\Tangaria\PWMAngband\z-form.obj" "D:\GitHub\Tangaria\PWMAngband\z-rand.obj" "D:\GitHub\Tangaria\PWMAngband\z-set.obj" 
  "D:\GitHub\Tangaria\PWMAngband\z-type.obj" "D:\GitHub\Tangaria\PWMAngband\z-util.obj" "D:\GitHub\Tangaria\PWMAngband\z-virt.obj" , 
  D:\GitHub\Tangaria\PWMAngband\mangclient_sdl.exe , D:\GitHub\Tangaria\PWMAngband\mangclient_sdl.map , import32.lib cw32.lib , , 
  .\Win32\Debug\angband.res mangclient_sdl.res 
[ilink32 Error] Error: Unresolved external '_SDL_Init' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_OpenAudio' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_GetError' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_Init' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_RWFromFile' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_LoadWAV_RW' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_LoadMUS' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_Volume' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_PlayChannelTimed' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_VolumeMusic' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_PlayMusic' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_FreeChunk' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_HookMusicFinished' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_FreeMusic' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_Quit' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_Mix_CloseAudio' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_QuitSubSystem' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\SND-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_CloseFont' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_OpenFont' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_SizeText' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_SetFontHinting' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_RenderText_Shaded' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_LockSurface' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_RenderText_Solid' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_UnlockSurface' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_Quit' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_UpdateRect' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_PushEvent' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_UpdateRects' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_PeepEvents' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_WaitEvent' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_PollEvent' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_Delay' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_CreateRGBSurface' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_UpperBlit' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_FillRect' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_DisplayFormatAlpha' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_FreeSurface' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_GetVideoInfo' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_SetVideoMode' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_WM_SetCaption' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_EnableKeyRepeat' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_EnableUNICODE' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_MapRGB' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_IMG_Load' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_TTF_Init' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unresolved external '_SDL_Quit' referenced from D:\GITHUB\TANGARIA\PWMANGBAND\MAIN-SDL.OBJ
[ilink32 Error] Error: Unable to perform link
Failed
Elapsed time: 00:00:01.4`

Project file:
[mangclient_sdl.zip](https://github.com/draconisPW/PWMAngband/files/7105395/mangclient_sdl.zip)

I did basically the same thing as https://tangaria.com/coding/ (guide at the bottom), but instead of srv, added client, win and common.

Also
1) looked in mangclient_sdl.bpr and instead of server's _DEBUG;STRICT;BCC_IDE;WINDOWS (Directories and Conditionals → conditional defines:), I've made:
STRICT;BCC_IDE;WINDOWS;SOUND_SDL;USE_SDL;_DEBUG

2) added another library path th the project:
D:\GitHub\Tangaria\PWMAngband\src\_SDL

p.s.
C++Builder 10.3 Update 3 Community edition

**Comment by igroglaz** [comment]
and another difference towards initial guide: I saved initial project not to /src/bcb6, but to ../../ folder.. but I doubt that it matters

**Comment by igroglaz** [comment]
at the same time regular console compilation works alright (I generate binaries with it).

**Comment by draconisPW** [comment]
Did you add ..\_SDL\SDL.lib ..\_SDL\SDL_ttf.lib ..\_SDL\SDL_image.lib ..\_SDL\SDL_mixer.lib to the linker?

**Comment by igroglaz** [comment]
yep, as I wrote 2 messages upper:
"added another library path the the project:
D:\GitHub\Tangaria\PWMAngband\src\_SDL"

**Comment by igroglaz** [comment]
![image](https://user-images.githubusercontent.com/39904162/132013639-88a0ef5a-0bf1-4b82-9487-24b4afc883ac.png)

**Comment by draconisPW** [comment]
No you just added SDL to the lib path but didn't add the actual lib files to the project (after the .c files and the .rc files you must add the .lib files).

**Comment by igroglaz** [comment]
YAY, it works now :D Thanks!

**Comment by igroglaz** [comment]
![image](https://user-images.githubusercontent.com/39904162/132020629-487f1f0d-a9c0-4da1-876f-38d607159734.png)

compiled client got 'underlying' blank window, how to remove it?

**Comment by draconisPW** [comment]
Just ignore it.
