### ISSUE TITLE
sorceror class OP?

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#441]
I'm 1st time playing sorceror. I play quite badly, but still managed to get to lvl 30 with 1st attempt (and continuing). I got quite good items in terms of INT (traded with players), but I suppose playing with 'regular' INT will be quite close experience (especially for experienced fella).

1) `Radiate Fear` - good early utility/escape, but there is no point to use it.
1-20 lvl wasn't too bad. Damage from `Magic Missile`, `Fire Ball`, `Frost Bolt`, `Lightning` not too big I suppose... It wasn't too easy to kill certain bosses (like Shtukensia) and you need some skill to choose which one to take. But still maybe it should have some tweaking - so player will have to use `Radiate Fear` at least sometimes (like necromancer). I didn't had opportunity to use `Radiate Fear` cause I killed everything on sight or run away with teleport.

2) now about damage... I suppose we should compare Sorceror with Mage class:
sorcs:
`Elemental Bolt`: 50x4 dmg. it's quite a lot, but it's often could be resistant. but in comparison to mage's spells **maybe** it's too much
`Sunfire`: **PLAYER_LEVEL:* 2 + 130**.... @ 28 lvl: 186
vs
mages:
`Shock Wave`: PLAYER_LEVEL:+ 10 (with stun.. still meh..)
`Explosion`: PLAYER_LEVEL:* 2 + 20. Average @ 28 = 76.
`Acid Spray`: PLAYER_LEVEL:/ 2 d 8 (eg lvl 28... 14d8 = 14-112. Average 63.

So `Sunfire` is 186 vs ~70 mages (and it's not counting that there are LOADS of hurt_light mobs early on and almost no resistant onces).

I suppose there could be two ways of balancing `Sunfire`: 
a) make sunfire more gradual. +130 damage right on is too much. start with +60 (@28 lvl), lets it gradually increase to 130?
OR
b) add some additional light resistance to some mobs/bosses. Eg I got angels without light resistance (meh), will fix it

3) OP utility spells.. I won't comment `Meditation` spell as I'm noob in sorc, so can't figure out it's full potential for now (and I don't use it yet). But maybe it will be OP with Disruption Shield..

But having !three! OP escape utils: `Stone Prison`, `Teleport Other` & `Wipe` in 3rd (town) book feels too much. I didn't yet used TO and Wipe in any of my battles. Stone Prison and tele is enough to get out of most trouble. But I can imagine experienced player using all this arsenal and it feels very OP in compare to mage's poor spells (create doors is nice for protect from summon though.. but it won't be useful till 35, while sorc's stone prison is the best protection for early-mid game.

`Speed` spell. It's alone enough to survive. If there won't be Stone prison, Teleport Other & Wipe - having perma 10 speed + Sunfire is enough to PWN everything on sight.

Now I got 4th book. `Resistance, Wraithform, Destruction` (btw why to have it if we have Wipe with effect_handler_WIPE_AREA?), `Telepathy, Mass Banishment`.. and 
`Plasma Blast` (36 lvl): PLAYER_LEVEL:* 2 + 250    @ 36 = 322
vs sorcs
`Mana Bolt`: (PLAYER_LEVEL:- 10) d8 ... at 36 it will be: 26d8: **8-208**, average 108 (non-resistable though).

I won't continue as I'm new to this class. What I can say - it's pleasure to play it.. but everything dies too fast, too easy.  Especially bosses (check https://www.youtube.com/watch?v=E0Oh8iC3iYo past stream - how I killed Minotaur and 3xTrolls bosses.. the easiest kills ever). Maybe this class should be tweaked a bit.

I suppose damage output of sorcerer should be 50% more that mage's one. Not 200-250% more like now :D And though mage can have 4 BpR in melee (and +50 hp at 50lvl), it's still mainly magic user, I hardly imagine mage fighting in melee often, unless he found super weapon.

Maybe I misunderstand philosophy and some weak spots of the sorc. Of course playing with 200 HP at lvl 30 it quite kamikaze style. If any appropriate mob come in melee sorc become as good as dead very soon (I had plenty of such close calls in my streams),

Maybe there could be another way to rebalance sorc. Leave spells as it is, but forbid sorc wear certain type of equipment OR make mana malus for heavy equipment. Eg I got gloves (4 lb!):
![image](https://user-images.githubusercontent.com/39904162/132175993-bf1b963f-6f37-4e17-984e-83eda342da6c.png)
but they don't affect my mana.

Eg maybe sorcs should be able to play only with staves.. having any other weapon in hand reduce their spellcaseing success chance.. Lets brainstorm ;D We can find some unusual and interesting ways to leave sorc as glass cannon, but make it less OP in comparison to mage.. Eg maybe reduce stealth of sorc by -1?

**Comment by igroglaz** [comment]
So far I've did in T:
- spell of Identify require some satiation
- Detect Treasure, Find traps/doors/stairs: now cause blind status for some time

I wanna be very careful in touching any classes, so I won't break it's gameplay as I don't have much experience playing them.. When I'll get most at least to lvl 40 it will be easier to feel class balance. Atm I'm feeling like blind kitten ;)

**Comment by draconisPW** [comment]
Out of scope. Sorceror is good as it is. You can't compare with Mage, as they are completely different classes. Mage is balanced with decent melee vs spells and is based off Tolkien's Arcane realm (see V 4.x discussion). Sorceror is a pure spellcaster that should be played that way, you should do nothing but cast spells. It is a one trick pony. You're out of mana, you're dead, period. That's why they get a boost to mana/damage.

Radiate fear: I understand it's underwhelming, but as any other caster, there are filler spells (Mage has Mass Sleep, which I alos never use). Making all spells useful would take ages (and that's why it's not done in V).

Elemental Bolt: yes it's a high damaging spell, but 1) it's elemental so it can be resisted and 2) it costs 9 mana compared to frost bolt that cost 2 for better dice.

Sunfire: same consideration, at start it costs a ton of mana (15) so you can't rely on it, plus it has high fail rate. Don't compare with Mage spells, which imo are garbage and just fillers (you should never use these spells).

Meditation is how you survive at high level, as you're practically replacing your HP pool with your mana pool. This supposes very difficult mana management and what makes the class difficult to play.

Stone Prison should be fixed with next V update (create doors nerf will be applied). And higher threats pass/kill walls anyway...

Wipe is nice, but you create a big empty hole. You lose everything (monster exp, loot, wall protection). See it as low risk low reward spell (personnally I never use it). Later on you get Destruction, which is more useful (every endgame player in V uses it to "control" fights).

Again don't compare Plasma Blast and Mana Bolt. Mana Bolt does 100 damage in a line. Plasma Blast does 300 centered on the player, meaning you only get the value against mobs in melee range. Fine to get rid of weaklings, but not really powerful when you need to melee a Greater Titan and take 4x 12d12 melee damage every round. One square away, the damage is already halved.

Note: you find the class easy because you have access to equipment you shouldn't have at your level because people sell items WAY too cheap on the server. With the same character and without that equipment boost, my sorceror is struggling big time.

Also to consider: Sorceror has already been MASSIVELY nerfed since the 1.0 era, it had roughly the same mana pool as TomeNET mana, but now the factor has been reduced from 40% to 25%, which makes them comparable to a warrior at high level.

**Comment by igroglaz** [comment]
I see, thanks. Some comments:

1) _"You can't compare with Mage, as they are completely different classes"_ 

sorry I can hardly imagine mage playing melee with HP dice 1.

2) _"You're out of mana, you're dead, period"_

Restore mana potions + 'Meditation'

3) _"Elemental Bolt: .... 2) it costs 9 mana compared to frost bolt that cost 2 for better dice."_

it's kinda the same dice. Atm I don't see the point to use Frost bolt at all. So maybe it's one of ways to make Elemental bolt less OP: remove "BOLT_OR_BEAM:COLD" from it. Than it will still be powerful, but for cold-vulnerable monsters player will use Frost Bolt.

4) "Don't compare with Mage spells, which imo are garbage and just fillers (you should never use these spells)."... 

... OK :D The question is - **if all Mage's attack spells are garbage - how to play it than** (1 hp dice low damage class weak in melee). 

5) "Stone Prison" - maybe at first this spell should create one tile of wall... (like stone-to-mud in reverse)... and only at ~35 lvl player should have access to real stone prison

6) "Wipe" - I thing it will be good to make it increase it's radius with lvls.. so when you first aquire this spell - it will be 2 radius.. and with each 3-5 lvls it will grow with radius. Make sense.

7) _"you find the class easy because you have access to equipment you shouldn't have at your level because people sell items WAY too cheap on the server"_ People sell items mostly at alright prices - I had money because I've sold some items which I found in the dungeon and also I'm selling all speed potions (while other classes can't do it). For this gold I've bought some +INT items; 2-3 of items for 5k per item. I have good, but not great equipment. And most items which I wear atm I've found in the dungeon, with some exception like ring of INT +5 (but when I take it off I have the same MP with 18/192 INT).. which is not important as I found 3 rings +3 INT recently :D I don't have most of resists, eg even don't have basic ELEC
![image](https://user-images.githubusercontent.com/39904162/132205027-5aca50ba-7f6f-435f-9dfc-572dfa8091ca.png)

![image](https://user-images.githubusercontent.com/39904162/132205065-d3e9753d-32b2-4d3e-b2df-48c6ac5c5cf5.png)

The important thing there is SPEED potions. Mage doesn't need to spend loads of gold on it while other classes have to do it. So it's the way to get easy gold. The same goes to Identify spell and Resistance. So when we comparing Sorc with other classes - we shall also take into consideration that this mage got biggest gold pool as it doesn't spent $ for consumables! And this class should be balanced including this fact. Of course if you play without selling anything to other players it will be harder.. But I assume that we should target balance somewhere in the middle - when you sometimes sell some stuff.

----

Important thing about balance is to compare one class to another. It's the only way to find proper balance. So we need to compare Sorc to other classes, even if it could be irrelevant in certain ways. So with which class we can compare sorc? With mage and (maybe) necro.. elementalist also. I've played mage - it was HARD (low dmg) and fun; I'll say it was appropriate. I've played necro - it was HARD, but it was appropriate hard. Sorc feels OP compared to them. 

**_The experiment:_**
After you get `Sunfire` - you destroy everything very fast. It should have 25% less damage at least I think (at the time when you get this spell) - it still will be fine and you will kill everything fast. Take a look at this battle with "The Minotaur of the Labyrinth" (lvl 30 boss, 130 speed): https://youtu.be/E0Oh8iC3iYo?t=5489 (timecode):
I've watched this battle in 0.25 speed:
1) 8 Sunfire spells and Mino 1500 dead. 
2) spend 15*8 = 120 mana (and it was regenerated during fight, so it wasn't hard). So even if I throw away all my mana INT items it will be ezpz fight. He didn't manage to come even to 1/2 of the path. Good way will be if he will come 5/6 of the path and player will have to make at least one Phase Door or Teleport during the fight.. Fighting with 3xTrolls was the same too.

**Comment by igroglaz** [comment]
We can compare my char with your dump: http://stat.tangaria.com/chars/PowerWyrm-23877.txt
lvl 29, got 283 mana. It will be more than enough to finish 2x Labyrinths' Minotaurs :D

**Comment by igroglaz** [comment]
My dump:
[Tangar.txt](https://github.com/draconisPW/PWMAngband/files/7115487/Tangar.txt)

**Comment by igroglaz** [comment]
So.. the question is - could mage class kill The Minotaur of the Labyrinth with the same ease as sorceror with the same gear? I doubt that Mage will hand it without several teleports around lvl and overall a lot of sweating :)

**Comment by igroglaz** [comment]
O_o
![image](https://user-images.githubusercontent.com/39904162/132217203-2833b449-36b8-4d11-8f42-278a702484db.png)

**Comment by draconisPW** [comment]
You can't compare a character with 18/*** INT and full ESP at level < 30 with a regular char. Try again killing the troll bosses with something like 18/90 to 18/120 which is a normal range and no ESP. And throw something like 140-150 hps in the process, your Maiar with over 200 hps at level < 30 is quite over average in this domain.

The Minotaur is a pure melee character, any spellcaster should be able to obliterate him without being hit once. Mage will probably use wands or rods and missiles, or Mana Bolt. Plus Mage has Mana Channel which allows to cast spells twice per round, actually doubling the damage.

**Comment by igroglaz** [comment]
I like 'contrast' of sorcerer as most devastating glass canon. But maybe it should have some limitations.. So mage won't look near by to sorcerer as whipping boy.

My ideas so far:
1) -1 stealth to sorc (quite logical - as you are best mage without any fighting skills - you should be bad in stealth)
2) (maybe) revamp `Elemental Bolt`.... maybe make it something like Poison attack with high damage - then it will leave fireball, lightning and frost bolt still useful. Or just remove frost from Elemental Bolt so at least Frost Bolt will be still useful.
3) `Sunfire` -20% dmg and add some light resistance, eg to angels (it's a shame I didn't put it yet).. maybe also remove some "hurt light"
3) (maybe one day) `Stone Prison`.. more it to deeper lvls. Instead add `Stone Wall` spell instead of useless `Radiate Fear`
4) Wipe - make less radius and increase it by leveling
5) add _small_ satiation spending for Speed (25 points? at least something) and maybe on Teleport too. So in comparison to Mage, Sorcerer will need to spend some satiation on utility spells. Fair and square.

**Comment by igroglaz** [comment]
"Try again killing the troll bosses with something like 18/90 to 18/120 which is a normal range and no ESP. And throw something like 140-150 hps in the process, your Maiar with over 200 hps at level < 30 is quite over average in this domain." 

Yes, the biggest problem of trolls is their ranged attack by throwing stones. ESP is nice thing, but I found it myself, not bought it (Axe, dropped by Koschei the Deathless at 1350 feet (level 27)).. It's luck, but it's possible to spot trolls with detect (reveal) monster spell. Considering HP: my CON is 7.. But yep, maybe I got some extra lucky HP dices.. BUT. I am newbie in sorcery. It's my 1st go with this class.. So it's kinda more or less fair.

**Comment by igroglaz** [comment]
addition considering #2 suggestion:
"(maybe) revamp Elemental Bolt.... maybe make it something like Poison attack with high damage - then it will leave fireball, lightning and frost bolt still useful. Or just remove frost from Elemental Bolt so at least Frost Bolt will be still useful."

I suppose we could increase damage of fireball, frost bolt, lightning over levels - so at high lvls they will also be useful. While replace elemental bolt with acid bolt. So playing sorcerer would mean knowing enemy immunities, which will make gameplay a bit harder.

**Comment by igroglaz** [comment]
"Plus Mage has Mana Channel which allows to cast spells twice per round, actually doubling the damage."
This is a very good point, thank you.. but we also need to consider:
1) it got very low duration: dice:5+1d5; `Mana Channel` average time: `7,5`
compare to sorc speed:
dice:$B+1d$S
PLAYER_LEVEL:+ 20 + 1dPlvl... eg at lvl 25.. result: 45 + 1d25; `Speed` average time: `57`
2) Mage still need to rely on Speed potions which cost $$$.

So Mana Channel is powerful stuff, but it's hard to use. I'll say that our Mage is based on V balance - TURN-BASED gameplay, where you can play very effectively, having precise timing for Mana Channel.. In real time 7 turns will pass very fast, so it's hard..

**Comment by igroglaz** [comment]
I've decided not to change (not to replace) sorcerer spells.. At first I've changed some spells like:

```
spell:Fire Ball:3:2:17:3:0
effect:BALL:FIRE:2
dice:$B+$S
expr:B:DUNGEON_LEVEL:/ 10 * 55 - 40
expr:S:PLAYER_LEVEL:+ 0
msg_other: fires a fire ball.
desc:Shoots a radius-2 fire ball.
```

```
spell:Lightning Beam:5:4:20:4:0
effect:BEAM:ELEC
# it's nice to have big diapason for lightning
dice:$Dd$S
expr:D:DUNGEON_LEVEL:+ 10
expr:S:PLAYER_LEVEL:/ 5
msg_other: fires a lightning beam.
desc:Fires a lightning beam that hurts each monster in its path.
```
revamped Frost bolt and replaced Radiate Fear with Poison cloud:
```
spell:Poison Cloud:14:7:45:8:0
effect:BLAST_OBVIOUS:POISON:5
dice:$B
expr:B:DUNGEON_LEVEL:/ 10 * 50
msg_other: emits a hazardous blast of terror.
desc:Attempts to poison monsters around you for a level-dependent duration.
```

and replaced Elemental bolt with

```
spell:Acid Bolt:17:6:40:14:0
effect:BOLT_OR_BEAM:ACID:0:-10
dice:$B
expr:B:DUNGEON_LEVEL:/ 10 * 50
msg_other: fires an acid bolt.
desc:Fires an acid bolt that always hits its target.
desc: Sometimes a beam is fired instead that hurts each monster
desc: in its path.
desc: The chance to get a beam goes up with your character level.
```

BUT. Then I thought.. You created this class after all and it's your 'child' so it should be your field of responsibility :) I'll put my dirty fingers away, so I won't spoil the idea. Maybe I'll just make a new class, eg "Wizard" where I'll try my silly experiments. At the same time I'll a bit nerf sorc in T as it the most powerful class IMHO, while not change anything in major way.

**Comment by igroglaz** [comment]
I'm adding IM_LIGHT to monsters (priests, paladins, gold dragons, etc).. it will be enough to make Sunfire less imba, so I won't touch the damage. At the same time I'm thinking instead of all different nerfs - just reduce sorc stealth from +2 to 0. It will stay the same glass cannon, but it won't be too ninja glass cannon. Anyway mid-late game it's easy enough to get some stealth...
