### ISSUE TITLE
fraction of satiation for class.txt / objects.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#443]
it will be fun to be able to assign satiation not in percent, but in fractions of a percent. eg right now:

```
effect:NOURISH:DEC_BY
dice:1
```

it will be fun to be able to change nourish values like this:

```
effect:NOURISH:DEC_BY
dice:50
```

(so instead of minimum 100 satiation we will be able to assign there 1, 5, 25, 50, for example).

**Comment by draconisPW** [comment]
No idea what you mean here :)
DEC_BY 50 does x -> x - 50, you mean x - 1/50 ?

**Comment by igroglaz** [comment]
effect:NOURISH:DEC_BY
dice:1

means atm -1% from satiation, which is `player_dec_timed(p, TMD_FOOD, 100, false);`
it will be fun to be able to reduce less fraction, eg 0.01% (which will be  `player_dec_timed(p, TMD_FOOD, 1, false);` )

**Comment by draconisPW** [comment]
Ok so what I thought (x -> x- 1/50). Will require adding something to the parser to differentiate x from 1/x.

**Comment by draconisPW** [comment]
Implemented with two new tags: INC_BY_FIXED and DEC_BY_FIXED, which don't multiply the amount passed by z_info->food_value (100 by default).

effect:NOURISH:DEC_BY_FIXED
dice:1

actually means player_dec_timed(p, TMD_FOOD, 1, false);
