### ISSUE TITLE
wrong "context->cave->profile" for first floor of the dungeon

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#444]
problem:
wrong context->cave->profile number when you enter first level of the dungeon

relevance:
it's important cause I'm trying to restict DETECT_TREASURES in labyrinths. As 1st level in the dungeon showed context->cave->profile as 0 (town @ list-dun-profiles.h) instead of 6 (DUN("labyrinth", labyrinth) @ list-dun-profiles.h) - this restriction works in all deep lvls of labyrinths, but doesn't work at first floor.

reproduce:
enter Maze dungeon in degub mode and check  context->cave->profile. 1st lvl will have 0; all other will have 6

**Comment by draconisPW** [comment]
Can't reproduce. This is a Tangaria issue.

**Comment by igroglaz** [comment]
Strange. I didn't change any of such stuff.

**Comment by igroglaz** [comment]
Testing:
1) pure-PWMA environment. Copied Maze dungeon OK
2) added all huge list of T's terrain.txt OK
3) added T mangband.cfg OK
...
retested it with Tangaria client... and it's OK too.

This is very strange. As 100% profile was 0 at 1st lvl when I've tested it! I suppose it should be some super rare case for which it should be special circumstances which rarely occur.
