### ISSUE TITLE
WIPE_AREA artifact hunting

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#445]
WIPE spell gives possibility to farm artifacts. enter Maze (small level full of items) and just cast it at each screen to destroy stuff and get arts

**Comment by draconisPW** [comment]
When Destruction spell was changed by V, I forgot to update Wipe accordingly. Not only it doesn't remove artifacts, but the code is incorrect as well.

**Comment by draconisPW** [comment]
I've factorized the code for Destruction and Wipe so that they use the same function. Destruction changes the squares randomly between floor and wall while Wipe changes all squares to floor.
