### ISSUE TITLE
forgetting spell crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#446]
**https://youtu.be/bAVZF7Qci08**

player: dragon sorcerer lvl 8
drinked potion of ruination, got some exp from it and gained lvl

![image](https://user-images.githubusercontent.com/39904162/132455072-dc093778-5daa-4c0f-a33e-4b71531a5c70.png)

**Comment by draconisPW** [comment]
Nevermind the reason. In calc_spells(), there is this loop:
for (i = num_total; i >= 0; i--)
The first index is out of bounds, it should be (num_total-1). 
Facepalm...

**Comment by draconisPW** [comment]
Checked with V, the -1 is only missing in PWMAng. Fixed.
