### ISSUE TITLE
newborn spider not visible by other player in graphical mode

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#447]
Tested spider race in SLD/win clients - other player can not see them if graphics turned on. 

initial demo:
**https://youtu.be/z-Wi4IWr1ZQ**

then I've tested when spider was hurt:
![image](https://user-images.githubusercontent.com/39904162/132494268-48e18b56-2a8d-4bea-9d6f-8f8be3778a80.png)

and when spider healed:
![image](https://user-images.githubusercontent.com/39904162/132494328-6ecaed0f-d9c0-42eb-a91e-bb077e00dcd4.png)

lvl 2 spider wasn't visible the same as lvl 1.

BUT. Then I've drinked potion of experience with spider. Spider become level 12, got new form and now spider become visible alright:
![image](https://user-images.githubusercontent.com/39904162/132494604-3315ee45-80a0-4310-b0b4-d064af068983.png)

p.s.
Tested at the same PC (the same folder to start several clients) and then tested on 2 separate PCs - the same.

**Comment by draconisPW** [comment]
Spider race misses form at level 1. Please test locally before submitting bugs to PWMAngband when it doesn't concern PWMAngband code.

**Comment by igroglaz** [comment]
I've tested locally a lot, that's why I've made such detailed issue ticket with pictures and even video demo. I didn't know there must be form at lvl 1, so you helped me to solve this issue, thanks a lot.. But I don't feel that I've made bad thing by posting it there, sorry. I put a lot of efforts in making detailed tickets and it's frustration to see a GTFO-feedback on it 😢
