### ISSUE TITLE
reincarnation of the character takes wrong appearence

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#448]
reproduce:

1) create `elf` `mage`:
![image](https://user-images.githubusercontent.com/39904162/132496320-1ecc34f2-2a76-4d66-9e3a-7874bfe21710.png)

2) kill it by shift+Q

3) recreate this char by:
a)"play a new incarnation of this character"
b) "quick start character..." -> yes

4) it will appear as... `Halfling` `Priest`

![image](https://user-images.githubusercontent.com/39904162/132496571-2c41dd25-8285-4d8a-ad86-8c0aa82cd3ba.png)

the same goes with other races which got !different appearances! within different classes. Eg if we will reincarnate dragon or any of T races (they all got 1 graphical appearance) - this glitch won't happen.

**Comment by draconisPW** [comment]
Again a Tangaria bug. Doing this in PWMAngband works fine, it must be a mismatch somewhere in your prf files.

**Comment by igroglaz** [comment]
Ok, thanks. I'll try to test such stuff in pure PWMA environment next time.
