### ISSUE TITLE
Space bar problem on entering the game

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#449]
I use [Space] ([space bar](https://en.wikipedia.org/wiki/Space_bar)) to 'L' around. For this I have this keymap:

```
keymap-act:[Escape]L
keymap-input:0: 
```

after `:0:` there is actually space... empty space bar symbol: " "

this keymap works alright in-game. BUT when I login to the game _**and push space bar several times fast**_ - it seems game trying to use this command while game isn't loaded. So i have timeout. Demo:

https://www.youtube.com/watch?v=teWOWtvi44M

I've tried to replace it with

```
keymap-act:[Escape]L
keymap-input:0:[SPACE]
```

but then it doesn't work in-game..

**Comment by draconisPW** [comment]
Interesting...

**Comment by draconisPW** [comment]
This is easily reproduced. The easiest way is to disable macros during setup phase... because we simply don't need them! The game will read the command (space) and leave it as a space instead of translating to whatever key it is mapped for gameplay.

**Comment by draconisPW** [comment]
Finally fixed (I hope)!
