### ISSUE TITLE
Add possibility to macro by items' names

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#45]
It's impelemented in TomeNET and then in MAgnband (ticket: https://github.com/mangband/mangband/issues/1182):

> It would be really great to be able to indicate not only @-inscriptions, but actully item names in macroses. EX: to make macro \erPhase to read 'phase door scroll'.

**Comment by draconisPW** [comment]
Will be ported in 1.5.0 at the same time as I port all other features from MAngband I'm still missing.

**Comment by draconisPW** [comment]
I've implemented #1182 from MAngband. For a macro by item, use "[Escape]q@healing[Enter]" for example.
