### ISSUE TITLE
not visible equipment slots for new chars

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#450]
reproduce: simply create dragon/hydra

![image](https://user-images.githubusercontent.com/39904162/132525443-56ec0ca1-6674-439e-8cad-0910ed5fdaa3.png)

slots won't be visible until you wear items

**Comment by draconisPW** [comment]
What's wrong with this screenshot? It's the same as any other char...

**Comment by igroglaz** [comment]
oook. it seems it's not only for POLY races, but for all races... at the screenshot we see that char don't have certain equipment slots... it's 'e'quipment window toggled. when we equip items in slots - they appears. 

1) create char
2) press 'e' to see not complete list of slots

previously we always had this:
![image](https://user-images.githubusercontent.com/39904162/132543813-b87252ac-564b-455e-975a-98286dc936f7.png)

**Comment by draconisPW** [comment]
Definitely a bug:

build_obj_list(player->body.count - 1, NULL, tester, mode);

Last slot displayed should be player->body.count but isn't (it's the last slot having an item).

**Comment by draconisPW** [comment]
V code is slightly different, I'll port that (it fixes the problem) and hope it doesn't break anything else.

**Comment by draconisPW** [comment]
Seems fine.
