### ISSUE TITLE
light dissapear sometimes

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#451]
![1](https://user-images.githubusercontent.com/39904162/132917043-9e4e76b9-f2d4-4ce8-8bb6-07e39c68b3fe.png)

![2](https://user-images.githubusercontent.com/39904162/132917049-3f2470a3-c0ae-4e62-823b-fa8349bb8feb.png)

**Comment by draconisPW** [comment]
How to reproduce (steps, options...)? Don't seem to have this issue...

**Comment by igroglaz** [comment]
I've met it too accidentally at yesterdays stream:

![image](https://user-images.githubusercontent.com/39904162/133087630-8505e4a4-be8b-47ab-9623-d441efa78e9b.png)

Timecode from this moment: https://youtu.be/8dZ06ugvqoc?t=1567

No idea how to reproduce though

**Comment by draconisPW** [comment]
Looking at your client it seems it lacks the flag updates for build 1, so I'd say it's a problem with your source. Can you recompile client + server and try again?

**Comment by igroglaz** [comment]
Clients compiled from clean install:
```
call clean.bat
pause
call client.bat
pause
call server.bat
```
...and it's got new version in header - other way it won't be possible to enter the game.. other problem (unknown packed upon spamming 'space' key on login fixed..

**Comment by igroglaz** [comment]
Previous light glitch felt different.. it was not like this one.

**Comment by igroglaz** [comment]
darn. closed accidentally

**Comment by draconisPW** [comment]
Hmm I need to check if the glitch happens only when there are other players around, that could mean there is a mismatch in player parameter somewhere...

**Comment by draconisPW** [comment]
Reproduced: if I play one character, the bug doesn't happen; if I connect the admin char and go to the same level, the bug appears.

**Comment by draconisPW** [comment]
For some reason, the "lit" square appears unlit for the second player, making it unlit for the first player when the update() function is called for the second player.

**Comment by draconisPW** [comment]
calc_lightning() for each player calls add_light() which sets square->light globally for the cave. This can only work in V with a single player environment. For us, we will have to move "light" from cave to player structure, as well as the WASLIT flag :(

**Comment by draconisPW** [comment]
This should FINALLY be fixed...
