### ISSUE TITLE
length of player status

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#452]
![24a765c563b89a06](https://user-images.githubusercontent.com/39904162/132949895-e4e1c225-fc4d-4f7c-99ac-0ee724495c30.png)

Is it possible to make it longer? Or maybe wrap it into 2 lines?

**Comment by draconisPW** [comment]
Wrapping the location information on a second line. It's the logical thing to do, since this info is not displayed for hostile players.

**Comment by draconisPW** [comment]
Done.
