### ISSUE TITLE
min. items price in player's store

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#454]
we got problem that players put items too cheap in their stores, eg Magic Arrows for 80g, while in the "preferred price" (in item's "I"nspection) is 200 (and you won't meet it in regular shop for this price, so real min price for it in NPC store is 600 gold in BM).

In the past there were some limitation which were reworked: https://github.com/draconisPW/PWMAngband/issues/243 Now i think it may be good idea to add it, but make minimum sale price not as 2xBM (it's way too much), but 50% of BM (so eg minimum price for Magic Arrows in player store will be 300, which is fair price)... 

..But it may cause problem with some equipment types, eg:
![image](https://user-images.githubusercontent.com/39904162/133342032-3cc5f46d-2f98-4cd7-a967-5a5897aea46f.png)
Player selling this weapon for 150g.. maybe it's a bit low, it may be sold eg for 500 gold (or even less as it useful only for blackguard.. and atm there is no BG playing, so this can be bought only for low BpR char like Ranger who plays some unusual race).. But anyway, using preferred price on this War Hammer is madness - it can't cost 3.5k gold... and it it will be 50% of BM it will be like 5k. No way.

So.. Maybe we should add minimum price only for certain types of items... food, projectiles, potions... not for weapon/armour. But even with projectiles there will be trouble, eg:
![image](https://user-images.githubusercontent.com/39904162/133342521-68e127fc-d7b5-4d90-a74b-6e88b0285bb8.png)
there we see actually quite fair price from player. 250 g per crappy pebbles - no one will pay.

So.. finally /rfe:
add new field in object.txt
mincost:x
which will show minimum price (in gold) for this item in player store. So if an item in object.txt doesn't have mincost - there won't be any threshold. And if mincost is there - it will be used. Eg

```
name:& Magic Arrow~
graphics:{:v
type:arrow
level:10
weight:2
cost:100
mincost:300
alloc:10:10 to 100
attack:1d4:0:0
armor:0:0
flags:EASY_KNOW | AMMO_MAGIC
desc:An ethereal arrow, made of pure mana.
```

players still will be able to use 'hand-to-hand' trade, but at least there will be less stupid priced items

**Comment by draconisPW** [comment]
Putting a min cost is out of the question since cost is computed by an in-game formula. The "preferred" price is the rightful indication on how much an item costs.

**Comment by igroglaz** [comment]
_"Putting a min cost is out of the question since cost is computed by an in-game formula."_

:( We had min cost as 2xBM before ( https://github.com/draconisPW/PWMAngband/issues/243#issuecomment-682019905 ), so maybe it's somehow possible to add check to make it will work only for players stores, while in shops there would be used only formula? It will make player's market much better

**Comment by draconisPW** [comment]
#243 removed the MAX cap (2x the XBM price), here we're talking about the MIN price. The preferred price is roughly the BM price (2x the normal price in fact). I could add a restriction on the min price, maybe half it's value (a 50% discount)?

**Comment by igroglaz** [comment]
As I wrote above - if min price will be applied to ALL items - there will be a lot of bad priced enhanced equipment and randarts among equipment and weapons - too expensive ones. Average player atm live till ~20 lvl (in good case, https://stat.tangaria.com/ ).. so if we will just add MIN price simply based at BM, people won't ever buy items like cause it's overpriced:
![133342032-3cc5f46d-2f98-4cd7-a967-5a5897aea46f](https://user-images.githubusercontent.com/39904162/133569433-15e745ac-dbf4-4a7a-abe8-58b05bb2dc44.png)
...while it's the most popular category of items (1-20 lvl players).. too high price on such equipment will make players stores useless.

I see there two ways:
1) (which I've wrote previously) - add "mincost" field for object.txt which we will be able to apply to the most of regular (static) consumables
OR
2) add MIN price which will be applied only for certain tval:
- potions
- scrolls
- magic books
- rods
- wands
- staves
- food
- mushrooms
- magic projectiles
- rings
- amulets
...so it won't include equipment

**Comment by draconisPW** [comment]
OK so I won't do anything in that case and leave as it is. You can trade manually anyway so nothing prevents you to put a lower price when selling directly, which renders min price on items pointless. Just need to "teach" players to price properly.

**Comment by igroglaz** [comment]
Please lets implement second option: add a restriction on the min price based on tval 🙏
