### ISSUE TITLE
Hitpoint warning toggle hotkey

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#46]
Implemented in MAng, veeeery cool feature: https://github.com/mangband/mangband/issues/1326

> It would be great to have possibility to turn on/off 'Hitpoint warning' mode by hotkey. Eg
player was attacked and got his HP to 50%.. 'HP warning' mode become triggered and time become slowed. Now if he want to have regular speed - he could push a hotkey (eg F1) to put time to normal speed... But if he wish to turn 'hp warning' mode on again - he could push this hotkey again.

**Comment by draconisPW** [comment]
Will be implemented along the 1.5.0 MAng alignment version.

**Comment by draconisPW** [comment]
Ported MAngband's feature. Use:
- [Escape]=h0[Escape] - disable time bubbles
- [Escape]=hn[Escape] - set threshold to (10 x n)% hp (1 <= n <= 9)
- [Escape]=h=[Escape] - set 100% threshold
- [Escape]=h-[Escape] - toggle between 0 and your setting
