### ISSUE TITLE
"Identify Rune" bug

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#461]
[01:49] PowerWyrm: hmm I thought this was fixed long ago, but it seems it can still happen: I used an unidentified scroll, which happened to be "Identify Rune", I use it on an unid robe (of resist fire), but instead of using up the scroll it used the scroll of word of recall instead

**Comment by draconisPW** [comment]
This must be a borderline case that happens for all unidentified consumables that have an effect on other consumables (identify, enchant, remove curse...)
In my case: I had unid scrolls of identify + a scroll of word of recall + an unidentified robe (+1) + an unidentified robe (+4) and I used the scrolls on the +4 robe.
This must have something to do with pack reordering.

**Comment by draconisPW** [comment]
Probably due to this code:

`/* Check for "obvious" effects beforehand */
    if (effect->index == EF_IDENTIFY)
    {
        object_flavor_aware(p, *obj_address);

        /* PWMAngband: mark "aware" and redisplay */
        set_redraw_inven(p, *obj_address);
        redraw_stuff(p);
    }`

A redraw is done prior to the effect, probably switching the ID and the WoR around...

**Comment by draconisPW** [comment]
This is really tricky to fix. The above code should trigger every time, but I can't fix by using up the item beforehand like for breath or teleport because you still can cancel ID (or trigger ID on an item which cannot be IDed) which should not use up the item.

**Comment by draconisPW** [comment]
I've managed to reproduce the bug. Now let's see if I can fix it...

**Comment by draconisPW** [comment]
Aborting item selection when IDing, enchanting, removing curse, etc doesn't re-arrange pack when the flavor is discovered. In this case, a "flush" packet is sent. Fix: call notice_stuff() in Receive_flush() to trigger pack re-arrangement.

**Comment by draconisPW** [comment]
I decided to remove the above code, which I have no idea where it comes from. Hope this fixes the bug.
