### ISSUE TITLE
check icy aura

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#464]
21:52] PowerWyrm: ..... + icy aura not working (this I will have to check)...

**Comment by draconisPW** [comment]
After some testing, icy aura is actually working but the effect is abysmally useless. I'll pump the effect to work like the subzero shield in ToS.

**Comment by draconisPW** [comment]
Freezing aura effect strongly buffed. It now blocks incoming attacks (temporary +10 AC), reduces damage by 10%, applies any time PROJ_ICE damage at value 1 + player level / 5 + 10% of the incoming damage (which can be zero).

**Comment by draconisPW** [comment]
Well it was not enough, the monster attack code is not able to handle the fact that the monster dies and crashes everywhere. I need to put a hack, so that the monster becomes "unconscious" (0 hp) instead of "dead" when hit by icy aura.

**Comment by draconisPW** [comment]
This should be finally fixed.
