### ISSUE TITLE
"keymap for spell" doesn't work if you don't learn spells from all the books

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#467]
Admin char.. trying to create "Keymap by spell" macro for "Acid Spray" and than switching "Monster friend: No" makes weird problem.. this spell can not be cast, while "Fire Ball" or "Frost Bolt" (also made by "Keymap by spell") - can be casted. This somehow unsynchronize server, so even non-admin char got this problem. It was even possible to crush server with "Create Doors" spell after this events..

also maybe (mystery...) this problem caused by entering client with old .prf.. while switching to new client afterwards inherits problem

**Comment by draconisPW** [comment]
Reproduced locally. If you use the admin char, learn Acid Spray, macro it by name then set monster friend to false, the macro doesn't work.

**Comment by draconisPW** [comment]
Ok I found the bug. To reproduce, you need to learn spells from not all the books you own. For my case, I used the admin char as a mage and only learned Acid Spray. When the client constructs the menu for the "From which book?" prompt, it only considers books that have learned spells (for my case: only Incantations and Illusions). But when you choose a spell from name, it is set by book + spell index from class and then compared to the list of books from the menu (for my case: Acid Spray is spell 3 in book 2, but the menu only has listed one book, so returns NULL as book 2 doesn't exist in the menu). Therefore no selection is made and no spell is cast.

**Comment by draconisPW** [comment]
Note: this bug also appears when selecting a spell by name manually (m + " + enter Acid Spray + "). Selection returned is NULL and nothing happens.

**Comment by draconisPW** [comment]
Fixed!
