### ISSUE TITLE
AI in wide corridors

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#469]
btw.. we should do something with AI in wide corridors
in V there is regular 1x corridors, so mobs don't need to try to surround player
in PWMA mobs in such corridors staying behind each other often
maybe there is a possibility to make them a bit more smarty
with minimal effort..
I suppose AI is quite hard to modify
we may take a sneak-peak to TomeNET solution of this problem
I'm looking into swimming atm.. so mobs won't look stupid in case if there is 1 tile of water between them and player 
corridor is another thing which a bit stupid..
I suppose it's the only two weak spots: corridors and water behaviour
all other AI aspects are fine

**Comment by draconisPW** [comment]
Not going to do this. Wide corridors are only convenience for players to move past each other and should be considered like that.
Fixing water is planned for 1.6.0.

**Comment by igroglaz** [comment]
1) move past each other is good thing, though why do we need it if we have 'swap' system?
2) currently it doesn't make sense to stay together in corridors, back to back, eg why to do this to stay together:

###############
...........ooooo@........
...........ooooo@.....
###############

while you can stay like this alone:
###############
...........ooooo........
...........ooooo@.....
###############

which makes tactical party gameplay much less fun.

3) the main problem that it's looks stupid when orcs do not surround player in such corridors. In TomeNET they do and it makes much better impression. When mobs act stupidly - it make an impression on players that our game is half-cooked.

Considering water - I'm fixing it right now in T, so maybe we need to work together on it. I'll publish my solution this week.
