### ISSUE TITLE
Shimmer - client side

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#479]
_works in ASCII_
```
src/client/netclient.c
/* flickering/multi-hued characters */
    if ((!use_graphics) && (!OPT(player, animate_shimmer)))
    do_flicker();

```
turning off 'animate_shimmer' displays a black symbol.
  maybe 'animate_shimmer - off' COLOUR_FIRE = COLOUR_RED
flicker() a 'for' loop overwrites tiles (black screen)

src/client/ui-term.c :L876
```
flicker()
// Show animated text colours in sub-windows
/* break; // Show animated text colours in Main window */
```
src/common/z-color.c
color_text_to_attr()
`color:!<shimmer>`

/lib/gamedata/ sample:

> color:!p
> graphics:~:!f
> graphics:$:!L

not all colors work correctly with characters 'color:!2', '!3'..
but `*ap = COLOUR_LAMP;` displayed in the text.

in Windows color flickers 2x faster. (FL_SPEED 1)
it does not overload server CPU

src/client/netclient.c
modified updateTicks()
  `cur_time, newticks, ticks`

![ezgif-2-0e33cb344367](https://user-images.githubusercontent.com/71586060/139041348-a2db5c7a-ddac-4395-a40f-b78bc2c34690.gif)
VVVVV
[PWMAngband-build5(shimmer).zip](https://github.com/draconisPW/PWMAngband/files/7424992/PWMAngband-build5.shimmer.zip)

**Comment by draconisPW** [comment]
No idea what this is about. "animate_shimmer" doesn't exist in PWMAng, seems like TomeNET stuff...

**Comment by igroglaz** [comment]
I suppose @s88100 proposed to include his implementation of animate_shimmer to PWMA, so he uploaded new source files:
![image](https://user-images.githubusercontent.com/39904162/140717458-f7afcc20-4c41-4ab0-b2fe-b066a84a3d33.png)
