### ISSUE TITLE
[rfe] Last object key in item selection

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#48]
@ mang repo: https://github.com/mangband/mangband/issues/1345

> I had an idea, which was kindly **implemented by TomeNET** devs; it would be fun to see it in MAng too

> last object macro: an action to choose last 'used' object. used means - picked up.
> good spot for this macro is '+' key. but it should work only when you see list of inventory
> 
> eg:
> you take unidentificated scroll. you could push
> r -> +
> and your char reads it.
> 
> It's much faster then push r, then look for the right letter for this item.

**Comment by draconisPW** [comment]
Pointless since you can use objects from the floor.
