### ISSUE TITLE
refresh screen after ignoring item

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#483]
small bug, repro:
1) ignore item
2) now try to unignore it - you will see that you only can ignore it again
3) now if you will refresh screen with ctr+r - you will see right option

**Comment by igroglaz** [comment]
sidenote: ignoring glitches only in inventory, equipment seems alright

**Comment by draconisPW** [comment]
Yeah I've seen this before, didn't consider fixing since it was minor.

**Comment by draconisPW** [comment]
Equipment is alright because set_redraw_equip() is called if ignored item is equipped, but not if it's the inventory.

**Comment by draconisPW** [comment]
Also happens for items on the floor.

**Comment by draconisPW** [comment]
For items in inventory, this only happens in town, as the igoned object is dropped on the floor otherwise. Fix: add a redraw if object is in inventory in town or on the floor.
