### ISSUE TITLE
item ignore problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#484]
repro:
1) ignore any item from inventory with 'k'
2) drop it to the ground - you will see it.
- even if you reenter the game - you will still see it
- even if you will add it in = i menu - you will still still it

**Comment by draconisPW** [comment]
Working as intended. You cannot ignore the following:
- starting items
- items picked up with ',' instead of 'g'
- items equipped
However, the menu should not propose the "ignore" options for these items, but just "destroy", so it is less confusing.

**Comment by draconisPW** [comment]
Items with ignore_protect flag cannot be ignored anymore, just destroyed.
