### ISSUE TITLE
'Pipe-weed' + 'Moist mushroom' string crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#485]
https://youtu.be/JeHDnZZAJQc

**Comment by draconisPW** [comment]
PWMAngband doesn't know anything about those, fix locally first thanks...
(this is clearly a local error)

**Comment by igroglaz** [comment]
I'm not sure that it's local issue. As pipe-weed is simple 'food' object, there is nothing hardcoded there. So with high probability it's PWMA issue.

**Comment by igroglaz** [comment]
It's is very easy to reproduce:

1) create halfling character in Tangaria (they start with pipe-weed)
2) drop pipe-weed on the ground
3) CRUSH.

When you 'E'at pipe-weed - it works alright. When you inspect it - too. Only drop cause crush.

**Comment by igroglaz** [comment]
I've rolled back code to 2 months earlier, when I've just added new food and this Pipe-weed. Compiled and runned this build:

https://github.com/igroglaz/Tangaria/commit/9b3f714

And it got the same behaviour - server crush when you drop Pipe-weed. So it means that this is not the problem of some recent drop changes. It seems T reached there some limits for 'food' type of something like this. Please could you help to find where is the 'bottleneck'?

**Comment by igroglaz** [comment]
I've tried to change parameters or rename Pipe-weed.. eg there I've renamed it to "Testing"
![image](https://user-images.githubusercontent.com/39904162/139848861-4fd26171-0c5b-40c1-b90d-e06295db4024.png)
the same result

**Comment by igroglaz** [comment]
Reproduced at pure PWMA enviroment:

1) add this item to object.txt

```
name:Pipe-weed
graphics:,:U
type:food
level:1
weight:1
cost:0
effect:RESTORE_STAT:WIS
effect:TIMED_INC:IMAGE
dice:1
effect:NOURISH:INC_BY
dice:1
msg_self:*You blow several smoke rings*
msg_other: blows several smoke rings
desc:Also called as sweet galenas or westmansweed.
desc: Hm... Which sort is this one? Longbottom Leaf, Old Toby,
desc: or Southern Star?
```

2) start server and create this item with admin menu - it will drop on the ground and crush the server

**Comment by draconisPW** [comment]
Here's a hint to solve your problem:

name:& Apple~

Look above and compare...

**Comment by igroglaz** [comment]
Thanks, it works. But I don't get it. As I've tested this food:
`Salted Pork from Isengard`
and it worked alright without `&`
