### ISSUE TITLE
3 players party → swap place → leave → trap → crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#486]
Link removed as it contains private info.

@draconisPW I've sent the link to the video to your PM in discord

**Comment by draconisPW** [comment]
Interesting...

**Comment by draconisPW** [comment]
Well it seems that square_note_spot() is called for a player that just left a level, so its cave pointer is still the same as the other player but its player_cave pointer is not valid. Need to make a check about "player leaving level" in square_note_spot().
