### ISSUE TITLE
TIMED_INC:HARMONY

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#487]
Summoner spell

```
spell:Elemental Harmony:42:42:72:20:0
effect:TIMED_INC:HARMONY
dice:10+1d10
desc:Attunes you to nature, increasing your defensive abilities for 10+1d10
desc: turns.
desc: At a first stage, blesses you, giving a bonus of +5 to AC and +10 to-hit.
desc: At a second stage, increases strength, dexterity and constitution.
desc: At a third stage, shields you, granting +50 to AC.
desc: At a fourth stage, grants you resistance to acid, cold, fire, lightning
desc: and poison.
desc: At a fifth and last stage, hastes you (+10 to speed).
```

doesn't work it seems - only 1st staage works, then it ends.
![image](https://user-images.githubusercontent.com/39904162/140649752-a32d4d7a-deac-4e85-89a6-364235bf6044.png)

**Comment by draconisPW** [comment]
Works perfectly, you just don't understand how the spell works...

**Comment by igroglaz** [comment]
How it works then? :) Maybe it should have more clear description..

**Comment by igroglaz** [comment]
oook. I see, thanks. You need to cast it several times when it's still on. I'll add a note to description

**Comment by igroglaz** [comment]
I've added:
`desc: Each cast of this spell when it is active promotes it to the next stage.`
