### ISSUE TITLE
pets kill each other to move closer to their master

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#488]
Summoned pets attack each other because they try to move closer to the master.. and if there is already a pet there - they will attack it

demo in T with new necro class:
https://youtu.be/RDLazthvpyI
at the video you can see 2 different cases. when I run from mobs - they just follow me. when I stop - they start brawling for the spot

reproduced in pure PWMA (made Summoner and edited mon->lifespan so monsters won't disappear):
![image](https://user-images.githubusercontent.com/39904162/141367743-30af5288-5aff-463c-b4e5-addd36c09684.png)
![image](https://user-images.githubusercontent.com/39904162/141367799-b9e180b4-381e-4827-a224-7825251a04ac.png)
![image](https://user-images.githubusercontent.com/39904162/141367781-a8374098-14a1-4b72-a9af-2251764fe25f.png)

**Comment by igroglaz** [comment]
`[02:31] PowerWyrm: you summoned with admin command, maybe that's why? try using summon scrolls with summoner`

I tested it with summoner spell 'Summon Monster' (see screenshots above)

**Comment by draconisPW** [comment]
Obvious bug in monster_turn_try_push(), now fixed.
