### ISSUE TITLE
[idea] random flavours on potions (scrolls, mushrooms)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#49]
@ Mang git issues: https://github.com/mangband/mangband/issues/1184

> After a while (after I died 10+ times) I've become to remember flavours for potions (EX: gold potion is speed). It's not fun because it's kinda cheezing - I'm REALY enjoying tastying potions for the first time to ID them :DDD The same goes to other items with flavours.
> 
> Idea: to make flavours to potions to become random somehow.. There could be different approach to this, EX:
> 
> client-side randomize flavours which you find items in the dungeon
> server-side change flavours every day (or after server restart).
> hide 'real' potions flavours till you try a potion with 'fake' onces
> Any more suggestions? :)

**Comment by draconisPW** [comment]
Imagine there are 100 players, you would need 100 different flavors for each single item. This is not realistic and has no way to be implemented.

**Comment by igroglaz** [comment]
Then solution could be - to hide 'real' potions flavours till you try a potion. So when player find a potion - he doesn't get flavour at all, if he didn't try this potion before (quite logical - your character remember it's smell and taste). Eg

Player found a potion:
a) if player already tried this potion - he got it in inventory identified automatically. END
b) if player meet this potions for the fist time - he doesn't receive it's flavour. It's just an 'unidentified potion' for him, till he would try or identify it

This is quite important issue.. Identify system is one of big 'cheeze' problems in multiplayer roguelikes right now, which make ID system less advanced than singleplayer roguelikes.

**Comment by draconisPW** [comment]
Solution is to remove the flavors? I don't think so...

**Comment by igroglaz** [comment]
not to remove, but make 'fake' flavours which become uncovered to true onces after ID

**Comment by igroglaz** [comment]
For now I simply solved this problem by resetting server file from time to time (due hames rehauling).. But in future, when we will have more people (right now there are already several houses) - it will be hard to do it....

So the way to solve it - just to add 'resetting' of flavours every few days - mix them and problem solved.. Even maybe mix flavours every time when server starts.
