### ISSUE TITLE
Implement SHORT_BEAM

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#490]
/rfe it will be fun to be able to use LASH / SPIT abilities (limited distance attack) in class.txt . Atm it's only possible to use it only if you polymorphed in certain monster

**Comment by igroglaz** [comment]
actually it will be fun not to have LASH/SPIT in class.txt, but to add distance modifier for attacks, eg:
`effect:BOLT:MISSILE:2`
means that this bolt attack will hit target at max distance 2

**Comment by draconisPW** [comment]
V has this effect (SHORT_BEAM) which I didn't port yet because it's not used in PWMAng. I should also harmonize BOLT_MELEE, which is a special case with distance 1.

**Comment by draconisPW** [comment]
Implemented.

**Comment by draconisPW** [comment]
BOLT_MELEE has been removed and replaced with SHORT_BEAM:1

**Comment by igroglaz** [comment]
> actually it will be fun not to have LASH/SPIT in class.txt, but to add distance modifier for attacks, eg: `effect:BOLT:MISSILE:2` means that this bolt attack will hit target at max distance 2
> 
> I suppose it will be better not to modify existing BOLT, BEAM, etc effects, but to add new EFFECT (call it RANGED?), eg:
> 
> `effect:RANGED:MISSILE:2`

Implemented: added BOLT_RADIUS in T https://github.com/igroglaz/Tangaria/commit/a015ab7e460d1448ab20faefc2033fe6408b45fe

Short beam won't stop when hit target, while bolt - stops.. I'll use it for various effects eg Balrog whip and some spells..
