### ISSUE TITLE
mana drain crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#491]
https://youtu.be/ma57oAfjMEs

**Comment by igroglaz** [comment]
T got spells which mana comsumption depends on char level, eg:

```
spell:Once Bitten:5:3:32:5:0
effect:TIMED_INC:OPP_POIS
dice:20+1d20
effect:DRAIN_MANA
dice:$B
expr:B:PLAYER_LEVEL:/ 2
desc:Grants you resistance to poison for 20+1d20 turns.
```

seems this crush has to do with it

**Comment by draconisPW** [comment]
DRAIN_MANA is a monster effect, cannot used on player, you'll have to make a new effect.
