### ISSUE TITLE
Character creation menu - Options (SDL client) 'Segmentation fault'

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#493]
in character creation menu open options window (SDL client) if tileset is selected when ok button is pressed 'Segmentation fault' hangs.

```
(gdb)
Thread 1 "pwmangclient" received signal SIGSEGV, Segmentation fault.
0x00005555555a5be3 in process_pref_file_expr (sp=0x7fffffffd1d0, fp=0x7fffffffd1cf " \262\204\245UUU")
    at client/ui-prefs.c:485
485                 else if (streq(b+1, "CLASS")) v = player->clazz->name;
(gdb) n
0x00007ffff7f1a540 in ?? () from /lib/x86_64-linux-gnu/libSDL-1.2.so.0
```
![options-pwmangband1](https://user-images.githubusercontent.com/71586060/145944002-9291fc5b-316a-43c0-9239-661633b0448d.jpg)

**Comment by draconisPW** [comment]
Player class is not defined at this time, need to add a check for NULL.
