### ISSUE TITLE
Linux server PWMAngband after close 'Segmentation fault' (Commits on Dec 16, 2021)

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#495]
> 171221 201732 Goodbye Player1=PLAYER@dhcppc1 ("Client quit")
> ^C^C^C^C171221 201736 Warning: Next signal kills server!
> ^C171221 201736 Shutting down.
> 171221 201736 Server state save succeeded!
> double free or corruption (out)
> 171221 201736 Unexpected signal, panic saving.
> 171221 201736 Shutting down (panic save).
> 171221 201736 Unexpected signal, panic saving.
> 171221 201736 Shutting down (panic save).
> Segmentation fault

_but Player is saved and loaded._

```
gdb ./pwmangband
(gdb) run
171221 210102 Shutting down.
171221 210102 Server state save succeeded!
double free or corruption (out)
Program received signal SIGABRT, Aborted.
(gdb) n
handle_signal_abort (sig=0) at server/game-world.c:2814
2814    {
(gdb) 
2816        if (signalbusy) raise(sig);
(gdb) 
2817        signalbusy = 1;
(gdb) 
2819        plog("Unexpected signal, panic saving.");
(gdb) 
171221 210108 Unexpected signal, panic saving.
2822        if (!server_generated) quit(NULL);
(gdb) 
2825        exit_game_panic();
(gdb) 
171221 210110 Shutting down (panic save).

Program received signal SIGSEGV, Segmentation fault.
preserve_artifacts () at server/game-world.c:2386
2386                    struct chunk *c = w_ptr->chunk_list[i];
(gdb) 
handle_signal_abort (sig=32767) at server/game-world.c:2814
2814    {
(gdb) 
2816        if (signalbusy) raise(sig);
(gdb) 
2817        signalbusy = 1;
(gdb) 
2819        plog("Unexpected signal, panic saving.");
(gdb) 
171221 210113 Unexpected signal, panic saving.
2822        if (!server_generated) quit(NULL);
(gdb) 
2825        exit_game_panic();
(gdb) 
171221 210114 Shutting down (panic save).

Program received signal SIGSEGV, Segmentation fault.
preserve_artifacts () at server/game-world.c:2386
2386                    struct chunk *c = w_ptr->chunk_list[i];
(gdb) 

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) 
The program is not being run.
(gdb) q

```

**Comment by draconisPW** [comment]
This is because trying to panic save after save has already been done, which is in fact pointless.

**Comment by draconisPW** [comment]
The "server_generated" boolean is set to false in exit_panic_save() but not in shutdown_server(), need to add it to avoid reentrance.

**Comment by draconisPW** [comment]
Should be fixed.

**Comment by s88100** [comment]
after Commits on Dec 23, 2021
_double free or corruption (out) ?_

> 231221 224302 Create TCP socket...
> ^C^C^C^C231221 224305 Warning: Next signal kills server!
> ^C231221 224305 Shutting down.
> 231221 224305 Server state save succeeded!
> 231221 224305 Account info save succeeded!
> double free or corruption (out)
> 231221 224305 Unexpected signal, panic saving.

```
gdb ./pwmangband
(gdb) run
231221 223454 Create TCP socket...
231221 223454 Shutting down.
231221 223454 Server state save succeeded!
231221 223454 Account info save succeeded!
double free or corruption (out)

Program received signal SIGABRT, Aborted.
(gdb) n
handle_signal_abort (sig=21845) at server/game-world.c:2819
2819    {
(gdb) 
2821        if (signalbusy) raise(sig);
(gdb) 
2822        signalbusy = 1;
(gdb) 
2824        plog("Unexpected signal, panic saving.");
(gdb) 
231221 230620 Unexpected signal, panic saving.
2827        if (!server_generated) quit(NULL);
(gdb) 
[Inferior 1 (process 1915937) exited normally]
(gdb) 
The program is not being run.
(gdb) q
```

**Comment by draconisPW** [comment]
I have the same problem sometimes when killing Windows server, it happens at the end after all saves are done in some assembler code and I have no clue why.

**Comment by draconisPW** [comment]
I've reinstalled the Ubuntu VM locally and can reproduce the problem, let's see if I can figure out where the double free occurs...

**Comment by draconisPW** [comment]
Bug occurs in cleanup_artifact() while freeing aup_info.

**Comment by draconisPW** [comment]
This pointer is totally valid, I have no clue why it triggers "double free or corruption", I can only imagine something else freed some memory space allocated for aup_info before causing a corruption. At least while looking at this, I found an indexing bug in finish_parse_artifact()...

**Comment by draconisPW** [comment]
Well... fixing that indexing bug happens to fix the issue.
