### ISSUE TITLE
Savefile corrupted

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#496]
updated the game to past version:
https://cdn.discordapp.com/attachments/699917093717671946/921375789788844082/unknown.png

should I roll back update.. or we have to make wipe?
maybe it's cause save.c was modified

**Comment by draconisPW** [comment]
Told that the update broke savefile compatibility (savefile format was changed from 1.5.2 to 1.6.0), so you need a total wipe to apply the change.

**Comment by igroglaz** [comment]
I did full wipe after this commit  
https://github.com/draconisPW/PWMAngband/commit/02b670d16ad2d5597fea6c05c9d994b89437f240

this problem appeared after past 2 updates.. you didn't mention about wipe in their patchnotes
