### ISSUE TITLE
admin command to dumps of all current chars

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#497]
/rfe to add console or admin menu (&) command or somekind of script... to make dumps for all current alive characters starting with lvl 5.

Then it will be much less painful for players to wipe server - at least all characters will be honoured in ladded list... eg some people may go on vacation for a few weeks having 40+ lvl character, so then didn't have ability to finish it.. with this command their heroic  deeds won't be forgotten in case of wipe :)

**Comment by draconisPW** [comment]
Closing this. Unfortunately there's no way to make a chardump without the corresponding player being connected.
