### ISSUE TITLE
pressing '@' causes client error

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#498]
![image](https://user-images.githubusercontent.com/39904162/146825117-8e69429d-ce15-4367-99e7-59d04ca39f3e.png)

reproduce:
start the game to create character. during char creation press '@' fast several times

**Comment by draconisPW** [comment]
Same issue as pressing space or enter I suppose, I probably need to disable @ packet during startup.

**Comment by draconisPW** [comment]
Fixed.
