### ISSUE TITLE
[rfe] restrictions for certain race/class combinations

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#5]
Right now there is a possibility to create any race/class combination. Actually I like current system and this feature isn't critical, but maybe in future there would be need to limit access for certain races to certain classes for the game balance sake, so I wanna add this issue in case I won't forget it in future :)

**Comment by draconisPW** [comment]
This was existing in Angband and was removed because it was discussed it was stupid (example: even the most idiotic half-troll can be a mage -- a crappy mage but still a mage). Will never come back.

**Comment by igroglaz** [comment]
Actually this is very useful thing for variants. I also like idea to have a crappy troll mage. But this 'tool' could be used for restricting some too powerful race/class combinations in Tangaria (no weak ones, like troll mage). It would be great to have it one day.

**Comment by igroglaz** [comment]
Just an example of apply of this idea: I'm thinking about race with antimagic. Without restriction to such combination it will break balance if player would choose such race + unbeliever

**Comment by draconisPW** [comment]
Currently this cannot work since antimagic is hardcoded to be the value on the dark sword + the level of the player restricted to the unbeliever class. Adding antimagic on race simply means rebalancing antimagic and adding the possibility on race. I'll do that.

**Comment by igroglaz** [comment]
Tangaria got trouble with certain race-class combination, eg monk class is imba for certain races

**Comment by igroglaz** [comment]
I thought about adding 'adventurer' class which will be available only for some of traditional V races (human, hobbit...). Adventurer - it's some one like Bilbo, who went to see adventures and only after a while found out his purpose (talents).

Such restriction could help with setting it up this class properly.

**Comment by igroglaz** [comment]
Also having such restriction will make game more newbie friendly, eg if player choose hydra race - he should play as monk. no point to try play other classes if you are hydra... so haveing a lot of other classes in the list for hydra is just confusing new players.

**Comment by igroglaz** [comment]
I have an idea of a new class, but without this feature it's not possible to implement it :( Please lets add this 'tool'; as it existed in the game for a long time - it shouldn't be hard. 

It's not a tool for restricting players to choose uncommon combinations (it's great fun to play troll mage, for example), but the tool which could give possibility to implement some very unusual classes and races.

Eg I got an idea to implement very powerful class in a certain way which will operate time... but it should be playable only by very weak races or it will be too imba.

**Comment by igroglaz** [comment]
> example: even the most idiotic half-troll can be a mage -- a crappy mage but still a mage

This feature needed not to restrict crappy combos, but to make balanced powerful ones. It should be used on extra powerful exotic races... eg all V races won't have any limits in T, but new races like Enlightened or Cambion (maiars) - will have it. So Cambion will be balanced for 'fighters' classes, while Enlightened will be balanced for 'magic' ones. Atm I balance all exotic races for fighters so at least it won't be ezpz to faceroll with them through the game - that's why it's almost impossible to play with them with magic classes. So.. Without this limits it's impossible to rebalance powerful races :(

**Comment by draconisPW** [comment]
Why wouldn't be Dragon Archer playable? You have a breath and backup rocks/shurikens, and throwing is now very powerful. Oh yeah I forgot... they have -20 to DEX in Tangaria...

**Comment by igroglaz** [comment]
I see, thanks.. so dragon is thrower in PWMA :) funny, but good solution. Considering DEX in Tangaria - till recent time dragon was balanced only for Monk class; recently I've added bonuns mana to him, so now it's alright to play (ooook, not really cause of bad stealth) as magic-user. But considering archer I suppose I got to either hardcode bonus to dex only for dragon-archer.. cause with extra DEX monks will pwn everything :D
