### ISSUE TITLE
Repeat chat message

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#50]
in TomeNET ctrl+p means repeat previously sent message to chat. Eg: when I say "hi", I could open prompt, push ctrl+p and "hi" would appear in prompt and I could send this message again. In TomeNET its even possible to go back no to only previous messages, but to all past messages during session. It's quite useful in a lot of situation - when player fight monsters he often doesn't see your message so you need to repeat it.

**Comment by draconisPW** [comment]
There is the chat window for this.

**Comment by igroglaz** [comment]
quite high % of players play in 2 window setup without chat window :)
