### ISSUE TITLE
CPU load problem

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#500]
https://youtu.be/eyASiAUG2vI

**Comment by igroglaz** [comment]
Description of video: I've paused IDE and went step-by-step with F7... then it become 'Process is not acessible' so I paused it again and went with F7 one more time

**Comment by igroglaz** [comment]
Problem occured again.. seems as serious issue which didn't happen before past updates (server was stable for weeks):
![Untitled-1](https://user-images.githubusercontent.com/39904162/147234734-bb8252a5-4257-4e9c-b28a-c096005747b8.jpg)

**Comment by draconisPW** [comment]
This is a problem with the debugger. It creates too many threads for whatever reason and that clogs the CPU. Most obvious fix is to run server without debugging. Other solution is to use 32 bit server to run Tangaria. Otherwise there is nothing to do.

**Comment by igroglaz** [comment]
For 2 years there wasn't such problem. It appeared after past update

**Comment by igroglaz** [comment]
This two cases which we had got some similar stuff:
![Untitled-1](https://user-images.githubusercontent.com/39904162/147249347-969ef573-8b30-4f21-9ac9-9c02199b2e70.jpg)

both happened after previous user exited the game.. server become idle.. and then another user connected.

**Comment by igroglaz** [comment]
This problem repeats regularly. Today I had two cases. One of them
![Untitled-1](https://user-images.githubusercontent.com/39904162/147388286-ae989262-405e-461f-acf5-ef9f1d3711db.jpg)

So I'm pretty sure that this problem is !NEW!. We didn't had it before recent times, though server had the same setup.

p.s.
Could this problem be triggered if player trying to connect with outdated client?

**Comment by igroglaz** [comment]
For now I turn off debugging mode on server, so players will be able to play without issues this holydays... but it means that we won't get proper testing and won't find new bug for a while...

**Comment by igroglaz** [comment]
I've created thread at stackoverflow:
https://stackoverflow.com/questions/70470634/c-builder-debugger-creates-too-many-threads

**Comment by igroglaz** [comment]
OOOOK. this is not a debugger problem. I've started the server with mangband.exe without IDE and made CPU freeze again:
![Untitled-1](https://user-images.githubusercontent.com/39904162/147388572-e05e0311-4e87-4039-aa9a-5132fa907237.jpg)

🐞

**Comment by igroglaz** [comment]
Yep, problem confirmed:
![Untitled-1](https://user-images.githubusercontent.com/39904162/147389092-18c06b1b-057f-4efd-bf88-690a2485afd2.jpg)

I may be wrong, but it looks like that this problem triggered when someone tries to create character... maybe culprit is new '@' character creation system?

**Comment by igroglaz** [comment]
It's funny, but when Serega tries to enter the game - he reproduces this bug every time. So the server (without debug mode) makes CPU 100% every time when he enters the game:
![Untitled-1](https://user-images.githubusercontent.com/39904162/147390294-d3ad98e8-4a83-4dc7-9455-008210978edf.jpg)

**Comment by igroglaz** [comment]
Yep, Serega trashes server each time when he login:
![Untitled-1](https://user-images.githubusercontent.com/39904162/147390373-07efacfa-d753-46d7-b03d-5473197b8312.jpg)

**Comment by igroglaz** [comment]
Serega uses the same client as I am. And he got Windows10 too... he got this in his client when he hang server:
https://media.discordapp.net/attachments/531175775760678933/924352780179738644/screen.png

**Comment by igroglaz** [comment]
We used the same new testing account. We used new client. When Serega enters - server go down. When I enter with the same account - everything works.

**Comment by igroglaz** [comment]
Hypothesis: maybe it's because different version of Windows (creepy version, but it's all what I can figure for now)

I've got latest Windows 10: https://media.discordapp.net/attachments/753931696012918876/924358725362397274/unknown.png

Serega got old Windows 10:
https://media.discordapp.net/attachments/753931696012918876/924359263835553863/screen1.png

**Comment by igroglaz** [comment]
Yep. Serega can enter the game alright with Linux client.

So it seems old versions of Windows kills server. Very creepy, but... looks so.

**Comment by igroglaz** [comment]
Important note:
- other players can play the game alright (me and several other people)... but also there are some people who put down server when they enters the game..

Note about Serega:
- when Serega enters the game with Linux client under the test account where I've created character - he can play
- when Serega tries to enter the game with Linux client under the NEW account - after character creation (after splash scree - /screens/news.txt) screen become blank:
https://media.discordapp.net/attachments/531175775760678933/924352780179738644/screen.png
and server go down..
- also Serega can not enter the game with his old (original account)

**Comment by igroglaz** [comment]
Ok. Problem finally found:
this problem triggered when player creates character using **b) Standard roller**

**Comment by igroglaz** [comment]
fixed https://github.com/igroglaz/Tangaria/commit/ad1301c7e9dba206e3d3d7714cac90a54f92fa14
