### ISSUE TITLE
update_mon() crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#507]
https://youtu.be/1L-ma-RH8uE

Player entered Ettendales location (not in the dungeon):

```
name:Ettendales
########### Ettenmoors
short:2_1
wpos:2:1
max-townies:7
```

He killed there Ettendales ogre mage:

```
name:Ettendales ogre mage
base:ogre
color:r
speed:110
hit-points:163
hearing:20
smell:20
armor-class:60
sleepiness:140
depth:0
rarity:2
weight:240
experience:20
blow:HIT:HURT:3d8
blow:HIT:HURT:3d8
blow:HIT:HURT:3d8
blow:HIT:HURT:3d8
flags:FORCE_SLEEP
flags:DROP_CORPSE | DROP_SKELETON
spell-freq:4
spell-power:27
spells:HEAL | HOLD | TRAPS
spells:BA_COLD
spells:S_MONSTER
desc:A hideous ogre wrapped in black sorcerous robes.
locations:Ettendales
```

**Comment by igroglaz** [comment]
log fragment:
[pwmangband050122.log](https://github.com/draconisPW/PWMAngband/files/7813349/pwmangband050122.log)

**Comment by draconisPW** [comment]
Well players cannot summon on the surface, maybe you're right. I'll check.

**Comment by igroglaz** [comment]
I meant that 'Ettendales ogre mage' may summoned something which is NULL.. Player who caused this crush is 48 lvl Rogue.. and he don't have access to SUMMON:MONSTERS yet (in T this spell starting with lvl 50)..

**Comment by draconisPW** [comment]
After looking at the vid, it clearly seems the code tries to fade detect over a monster that doesn't exist anymore (probably the ogre mage), which of course is problematic. This seems very easy to reproduce (for example: two players on the same level, first player casts Detect Monsters and second player kills a monster while the spell lasts). I'll add a check for existence of mon->race for doing the update.

**Comment by draconisPW** [comment]
Fixed (also added a check for players at the same location in case two players are on the same level, one casts detect and the other dies).
