### ISSUE TITLE
building mode: arena walls dissapears

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#508]
As we can't change map by editing town_xx.txt without server wipe, I'm trying to draw arena in T manually:

https://youtu.be/Y0q7BC0PA-8

but it dissapears. When I bump into arena walls it says:
"Arena is currently occupied"

Other stuff which I build (eg grass terrain) stays when I leave the location.

**Comment by igroglaz** [comment]
hm.. I suppose arenas initialized on worlds creation, aren't they? so the only way to fix it is to make wipe. it's np :) anyway sooner or later we will have some changes which will require it and than I'll add arena to town

**Comment by igroglaz** [comment]
hm.. but wait. will such arena (added to town_xx.txt) work? shouldn't it be initialized somehow?

**Comment by draconisPW** [comment]
Arenas are not supposed to be built that way, you need to generate wilderness area as desert and have it built there by the code so it has correct dimensions and gets saved in server savefile.
