### ISSUE TITLE
QUIT_TIMEOUT: from seconds to turns

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#509]
Player reported about possible abuse of this:

```
# Option: quit timeout.
# This is the number of seconds after which a regular player is disconnected
# from the game. Be careful when setting this to a high value, as during this
# timeout, the character is left hopeless and will surely die if something
# bad happens. Default value is five seconds. Maximum allowed is 60 seconds.
QUIT_TIMEOUT = 4
```

when time become slowed due player's injuries - it's possible to exit the game safely to prevent death... due QUIT_TIMEOUT value is in seconds - player will guaranteed survive due time bubble feature..

/rfe to make timeout not in seconds, but in turns.

**Comment by draconisPW** [comment]
Non issue. It's server clock not player clock (client).
