### ISSUE TITLE
[rfe] enhance looking around (MUD feature)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#51]
From https://github.com/draconisPW/PWMAngband/issues/20 I found out about beautiful feature:
**"l" + "p" + "r"**

This is really great feature - because it could make dream come true - http://tangar.info/en/blog/roguelike-mud

The only tiny problem - when I push "l" + "p" - I could move cursor around. but when I push "r" - cursor dissapear so to continue looking around player has to push ("l" + "p" + "r") again. It would be so awesome if it would be possible to look around while in 'r'-mode continuosly, so cursor won't go away. Then player could look around and relax reading descriptions, getting into game lore.. it's hard to push 'l+p+r' again and again to look at every feature :(

Also it would be fun to give 'r' window maximum weight so it would be possible to write really nice descriptions.

**Comment by igroglaz** [comment]
Another use of l+p+r - FINALLY it would be possible to create proper in-game turorial!!!.. if this feature would be enhanced :)

**Comment by draconisPW** [comment]
Pressing "l" + "p" stays on server side. Pressing "r" goes back to client to display the description, so you need another command after that. In current state, this is impossible to do.

**Comment by igroglaz** [comment]
Hm.. is it possible to show this tooltip in a new window? So user will switch between objects like in regular "l"ook, but he will see long descriptions in a new window
