### ISSUE TITLE
monsters pathfinding problems

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#511]
monsters become stupid on pathfinding where there is a corners

timecode: https://youtu.be/NyzDXaV0vZY?t=882

trolls just stop dead without reason... 

also I've noticed that my pet got problems to follow me if there is a corner, eg
https://youtu.be/NyzDXaV0vZY?t=1079 (not the best example, there are a lot of cases in my streams)
so often I must come back to it to 'pick it up'.

**Comment by draconisPW** [comment]
Closing this, recent AI fix should have fixed this.
