### ISSUE TITLE
add character progression to # menu

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#512]
players asked to have possibility to see race/class features not only on char creation screen, but actually in-game too... so /rfe is to add '!' info from character creation screen:

![image](https://user-images.githubusercontent.com/39904162/148682153-1ecbf911-a0e9-4287-aad4-be1887c6069b.png)

To '#' in-game info:

![image](https://user-images.githubusercontent.com/39904162/148682173-0dd762a1-bad8-438c-bedb-02c50f7a0781.png)

**Comment by draconisPW** [comment]
Implemented as "/race" and "/class" custom commands (to mirror the "/abilities" custom command) to keep '#' as is. Refactored menu_stats() on character birth to use same methods do_cmd_race_stats() and do_cmd_class_stats().
