### ISSUE TITLE
death dump crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#513]
https://youtu.be/iRAQBCG6hTg

interesting thing that after this crush player appeared to be alive after I've started server (crush prevented to save server state it seems) - lucky player. Here he is after restart:

![image](https://user-images.githubusercontent.com/39904162/148695652-bdf3c94f-d918-4f27-a0fc-bae743e0134a.png)

His dump:
![image](https://user-images.githubusercontent.com/39904162/148695691-b9634fd5-7d2a-4a98-adb4-6f659b901210.png)

The dump file (renamed to .txt as it's not possible to upload to github .new files):
[Lnk1 II-20513609012022.txt](https://github.com/draconisPW/PWMAngband/files/7835668/Lnk1.II-20513609012022.txt)

It's his destiny to stay alive it seems this time ;)

**Comment by draconisPW** [comment]
Screenshot at the end of the dump is too big for labyrinth level, need to restrict its size to the size of the level.

**Comment by draconisPW** [comment]
Fixed.
