### ISSUE TITLE
Client crush when wearing cloak

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#514]
Player bought cloak in the shop, but forgot to wear it. He went to the dungeon (Very Old Ruins) and there found a robe; he  wears it and then he noticed that he forget to wear cloak which he bought.. He 'w'ears cloak and....

<img width="960" alt="2022-01-10" src="https://user-images.githubusercontent.com/39904162/148753130-e65d214a-53f1-4b00-a975-c495e3614a8d.png">

<img width="960" alt="2022-01-10_1" src="https://user-images.githubusercontent.com/39904162/148753139-31e6f105-fe92-427a-bca9-20d8a25b1d94.png">

**Comment by draconisPW** [comment]
Can't reproduce and since Tangaria has modified number of slots I bet it's a bug in your code.

**Comment by igroglaz** [comment]
T got the same number of slots:

![image](https://user-images.githubusercontent.com/39904162/148795248-a6373d0b-09c3-4f0b-a26b-01090096fa6f.png)

![image](https://user-images.githubusercontent.com/39904162/148795330-41334979-185a-4151-891b-d813fbe03e8e.png)

**Comment by igroglaz** [comment]
Should it be open? As in T there is the same number of slots

**Comment by draconisPW** [comment]
Can't reproduce unfortunately, I'll reopen if you manage to catch the bug in debug mode.

**Comment by igroglaz** [comment]
I suppose it might be super rare case.. so I donno will we be able to trigger it again soon
