### ISSUE TITLE
l->p->r on the pile of items 'Segmentation fault'

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#515]
_configure server:_

> constants.txt:
> carry-cap:floor-size:8

If throw pile of 8 items (l->p->r), then it will exit with the error 'Segmentation fault'

**Comment by draconisPW** [comment]
Reproduced also with Windows client.

**Comment by draconisPW** [comment]
That's an absolutely moronic bug: build_obj_list() takes the last object index as parameter, but show_floor() sets that parameter to floor_num (number of items on the floor) instead of floor_num - 1 (last index).
