### ISSUE TITLE
Limited teleportation flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#52]
I've [added](http://tangaria.com/news/races-improvements-and-not-only/) quite special race:

> Half-giants can't teleport (but become very.. very strong. They are descendants of Titans after all..)

They got obj-flag:1:NO_TELEPORT

It would be fun to add another flag which would allow phase door (and word of recall), but forbid all other teleportation. Alsi this flag could be useful for artifact design

**Comment by igroglaz** [comment]
Another idea - to have flag which makes 'teleportation scroll' work like 'phase door' :) kinda reducing range

**Comment by igroglaz** [comment]
as now we got limited teleport for terrain https://github.com/draconisPW/PWMAngband/issues/300 , maybe it's possible to add it as character flag? for equipment/race/class

**Comment by draconisPW** [comment]
Implemented.
