### ISSUE TITLE
TELE_TO fail due objects on the floor

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#522]
Boss: Old Man Willow.

Player shoots arrows - they fall around the boss:
https://cdn.discordapp.com/attachments/903709543316480041/934764524781854731/Old_man_Willow.png

Now when boss trying to TELE_TO player - it fails cause of this arrows on the floor.

I suppose TELE_TO and SUMMON should work if there is an object on the floor. Only glyphs and some terrain (like closed doors) should protect VS tele/summon magic

**Comment by draconisPW** [comment]
Fixed by porting above commit.
