### ISSUE TITLE
Keymap by spell: Minor Healing vs Healing

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#525]
Paladin class: when you make 'Keymap by spell' -> 'Healing'  -- it cast not `Healing`, but 'Minor Healing'

**Comment by draconisPW** [comment]
Ah yeah, it takes the first spell with the string as substring. I'll have to adapt this like I did for items/monster search.

**Comment by draconisPW** [comment]
In fact, the problem occurs because on the client we don't have access to spell names, but just spell info: "Minor Healing                  3    2   2% heal 60/28%". I'll add the spell name to the packet we send to client and use that instead.

**Comment by draconisPW** [comment]
Fixed.
