### ISSUE TITLE
Respawn townies every dawn

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#53]
As we got 'Wipe all trash on the surface every dawn' feature:
https://github.com/draconisPW/PWMAngband/commit/edbd5a3ade881cfffccc52d1985ded290f67db6a

maybe it will be fun to wipe also all townies-NPCs from surface? It will make areas much interesting, because right now when server was started and generated certain animals, they will be always the same, which become a bit boring.. world become too static. With this feature world will be more special and 'alive' :)

**Comment by draconisPW** [comment]
Currently, this is done for wilderness only. Expand also to towns.

**Comment by draconisPW** [comment]
In fact the current system is stupid... monsters are only wiped if the wilderness area is not static, but if the level is not static then any player who enters actually wipe the monsters. I change it so that the level is wiped if there are no actual players on the level instead.

**Comment by draconisPW** [comment]
Implemented in 0cf6479.
