### ISSUE TITLE
client/main-sdl2.c alpha window bug

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#534]
after commit 'V changes up to Nov 22, 2021' 683fdfc95c441b8631676dfaf7699b5fa948622f
resets settings window's Alpha (:255) if set transparency, then '=' key resets.

**Comment by draconisPW** [comment]
No idea what this is, but there is another change in main-sdl2.c from V I didn't port yet which does "SDL_EventState(SDL_KEYMAPCHANGED, SDL_DISABLE);", dunno if that's what need to be done to fix this.

**Comment by s88100** [comment]
checked in V same bug

**Comment by draconisPW** [comment]
V fixed this by setting rgb colors directly instead of using structure copy. I've ported the change so this can now be closed.
