### ISSUE TITLE
[rfe] night sound on location change

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#54]
every time when you change location in wilderness you hear 'night' sound. I suppose it should sound only once - at the moment when time of day changes, not every time when you change location. Cause after 1st alers, afterwards it's understandable when it's day/night cause everything is dark around :)

**Comment by draconisPW** [comment]
Sound is displayed whatever day or night during map change. It's global.

**Comment by igroglaz** [comment]
Ok, then it's easier just to replace nigth sound with something less 'visible' :)
