### ISSUE TITLE
unIDed wands on monster which is outside of my vision

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#540]
https://youtu.be/ERsK0PawKnA?t=1827 (timecode)
used unIDed wands on monster which is outside of my vision
but wand become IDed 
though I didn't see what it did (confused stationary mob and slowed it)
it shouldn't ID I suppose in such case

[00:39] PowerWyrm: you're confusing out of vision and offscreen, it will work if in sight range
[00:39] PowerWyrm: offscreen is just a window/panel notion

Nope, my char has torch equipped and and his vision is 1 radius. So I stood away from monster (but in borders of my screen) and used wand not by target, but by direction. Mob is outside of my vision, 2 tiles away.

**Comment by draconisPW** [comment]
As I said, offscreen != out of range, works as intended.

**Comment by igroglaz** [comment]
it is not offscreen! It's 2 tiles away from my character. And it is outside of my light radius. Player DO NOT see whats happening in the darkness. How come zapping wand make it IDed if you didn't see the result? Moan in the darkness may be anything.

It's 100% bug

**Comment by draconisPW** [comment]
Ask on V forums then. I checked V and it's even worse since hitting a mob with a wand while blind not only IDs the wand, but also gives no message at all...

**Comment by igroglaz** [comment]
yep, I've checked V too right now. it's the same. I'll report at V tracker

**Comment by draconisPW** [comment]
Fixed by V and ported.
