### ISSUE TITLE
client does not close properly 

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#542]
repro:
- compile fresh PWMA client
- run it
- press 'Quit' button:

![image](https://user-images.githubusercontent.com/39904162/161376799-5f36d743-9d65-4f5e-8471-605cc4af68c5.png)

**Comment by draconisPW** [comment]
Can't reproduce, this is probably a compilation problem locally.

**Comment by igroglaz** [comment]
Indeed. I've re-tested it and it works alright. Seems it was problem with my OS
