### ISSUE TITLE
Throwing shots vs shooting them with sling

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#543]
Strange: throwing a shot makes the same (or even more) dmg that shooting it with a sling. PWMA:

![image](https://user-images.githubusercontent.com/39904162/164175774-79617578-2c09-440f-bcba-8dd45723d069.png)

![image](https://user-images.githubusercontent.com/39904162/164175845-609aa154-2f42-4c05-889a-896e386a4c02.png)

maybe throwing mod should work only on enged light weapons like daggers.. and stuff like shuriken or boomerang

**Comment by draconisPW** [comment]
Works as intended (V feature).
