### ISSUE TITLE
displaying ASCII symbols in 'knowledge-ui'

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#544]
it would be nice to add support ASCII symbols 'knowledge-ui' in graphics mode
similar to 'server/display-ui.c'  prt_equippy()  _Use ASCII symbol for distorted tiles_
'server/mon-list-ui.c' 'server/obj-list-ui.c'  `if (p->tile_distorted)`

**Comment by draconisPW** [comment]
Implemented for:
a) Display object knowledge
e) Display monster knowledge
f) Display feature knowledge
g) Display trap knowledge

(I hope I understood the RFE correctly...)
