### ISSUE TITLE
training_grounds crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#545]
seems new V code conflicts with Training Dummy

![image](https://user-images.githubusercontent.com/39904162/168040558-77353a1c-3f0c-4fba-b2f2-013ec9fa2be5.png)

![image](https://user-images.githubusercontent.com/39904162/168040412-854485ae-f4dd-44e6-acfe-26f44a68148c.png)

repro:
run PWMA and recall to -9,37 (town)

please could you commit fix asap as I can't test sounds for T without it :)

**Comment by draconisPW** [comment]
Oops.

**Comment by draconisPW** [comment]
Bug in cave_find() now triggers due to latest V change in cave_find_in_range(). Good thing this happened, because I would never have found that error otherwise.
