### ISSUE TITLE
audit channel

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#548]
Audit code is turned on by default and gives info to #audit channel which is hidden by default

I'm not sure about this idea, but maybe it should work only while server is in debug mode? OR as code is already there and it runs every time when player buy something, maybe we should put this info use this info somewhere as additional way to catch errors? So

1) I wonder if we already have it turned by default, maybe it should also be turned by default for admin character?
2) also maybe duplicate audit info to server logs? or make additional 'new' log file for audit code.

Actually audit could be pretty useful to catch cheaters at the server - which give their items from one of their character to another. So maybe we should enhance this system even further - eg create additional log file with all items operations - whe player drop something on the ground and when pick it up.. so with the help of such log we will be able to catch cheaters.

**Comment by draconisPW** [comment]
This is Mang code, don't have the time or will to change or improve this, should be use as is.

**Comment by igroglaz** [comment]
Ok ;) it's pretty simple stuff, so I'll just add it to T
