### ISSUE TITLE
 endless cursed jar (UNDEAD_FORM + READ_MINDS)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#551]
There is funky item in T, 'Cursed Jar'. It's got:

```
effect:BATTY
effect:SUMMON:UNDEAD:0:-1
dice:1d1
effect:UNDEAD_FORM
effect:DARKEN_LEVEL:NONE:1
effect:READ_MINDS
dice:$Dd$S
expr:D:PLAYER_LEVEL:/ 10 + 1
expr:S:PLAYER_LEVEL:/ 10 + 1
effect:DETECT_SOUL
effect-yx:22:40
#positive:
effect:DESTRUCTION:LIGHT:13
effect:MASS_BANISH
```

After some recent changes it's become 'endless' - when you 'E'at it - it do not dissapear.

I've tested and it happens cause of two properties:
`effect:UNDEAD_FORM`
and
```
effect:READ_MINDS
dice:$Dd$S
expr:D:PLAYER_LEVEL:/ 10 + 1
expr:S:PLAYER_LEVEL:/ 10 + 1
```

Strange as before now I've tested it several times and it worked (dissapeared when eaten) alright

**How repro in pure PWMA:**

add object:

```
name:& Cursed Jar~
graphics:,:U
type:food
level:30
weight:5
cost:0
alloc:1:1 to 30
effect:READ_MINDS
dice:$Dd$S
expr:D:PLAYER_LEVEL:/ 10 + 1
expr:S:PLAYER_LEVEL:/ 10 + 1
desc:.
```

**Comment by draconisPW** [comment]
Read minds returns "false" if no minds are read, meaning the effect is not completed. Same error in V. I checked MAP_AREA and there's no such problem so I'll fix READ_MINDS directly and post a comment on V forums.

**Comment by draconisPW** [comment]
Note: for the effect to work, you need to use any means of detection prior to READ_MINDS, otherwise it does nothing.
