### ISSUE TITLE
log chat in server log

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#558]
I've just noticed that chat messages do not shown in server logs and don't save. It's a problem as atm there is a conflict between players and without looking into their chat logs it's not possible to understand who was first to start a enmity

**Comment by s88100** [comment]
https://github.com/draconisPW/PWMAngband/blob/master/src/server/display-ui.c#L5489
```
display_message_aux()
/* Excludes all channels but #public from the log file */
if (type > MSG_CHAT) log = false;

if (msg)
{
    /* We don't need to log *everything* */
    if (strchr("[", *msg)) log = false;
. . . .
```

**Comment by igroglaz** [comment]
right now all chat excluded from logs, public channel too

**Comment by s88100** [comment]
`if (strchr("[", *msg)) log = true;`
`'log = true'` writes logs, but it also writes in server-side character dumps last messages.
> [Last Messages]
> [Player] ok
> [Player] )))

**Comment by igroglaz** [comment]
Thanks :) I'll enable it in T. Not sure if PowerWyrm wants it to have in PWMA, will close ticket just in case

**Comment by igroglaz** [comment]
btw it will be fun to be able to log player's chat messages, but exclude them from 'last messages' in 'tomb' dump files
