### ISSUE TITLE
TARGET_HELP allows selecting monsters but checks on most wounded player using those entries

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#559]
seems some players had a rawl between each other and start doing such thing: 
1) start 'Tamer' character (which has a pet)
2) Entering the dungeon
3) Leaving the dungeon
4) Pet becomes 'wild' and hostile to everyone and attack player.. (btw we see that player killed this pet in logs)

This tactic provoked eventually server crush :D

https://youtu.be/bHBTU9nENmo

I'm not against such 'feature' with PKing with pets.. :) But we need to fix a crush of course

p.s.
UPDATE: but maybe it's not this algorithm which I've described above.. As in logs (will be below) I don't see that player go out of dungeon..

**Comment by igroglaz** [comment]
And some frog PvP logs, just for a memory :DDD

250622 102714 PetK: You can learn 1 more task.
250622 102714 Azken Zutik: PetK begins a new game.
250622 102714 Sebastian: PetK begins a new game.
250622 102725 PetK: You have 0 account points.
250622 102842 PetK: You bump into Sebastian.
250622 102842 Sebastian: PetK bumps into you.
250622 102923 PetK: You have 0 account points.
250622 102943 PetK: You switch places with Sebastian.
250622 102943 Sebastian: You switch places with PetK.
250622 102950 Sebastian: The chicken wakes up.
250622 102951 New Level 50ft at (0, 0) Ratings obj:25/mon:23
250622 102951 PetK: This seems a quiet, peaceful place.
250622 102958 Sebastian: You enter a maze of down staircases.
250622 102958 Sebastian: This seemed a quiet, peaceful place.
250622 102958 PetK: Someone gropes around blindly.
250622 102958 PetK: Someone fades in the shadows.
250622 102958 PetK: Someone is surrounded by an aura of power.
250622 102958 PetK: Someone
250622 102959 PetK: You hit the tamed frog (3).
250622 102959 Sebastian: Someone has slain the tamed frog.
250622 102959 PetK: You have slain the tamed frog.
250622 103000 PetK: You hit the tamed frog (3).
250622 103000 Sebastian: Someone has slain the tamed frog.
250622 103000 PetK: You have slain the tamed frog.
250622 103001 PetK: You hit the tamed frog (5).
250622 103001 Sebastian: Someone has slain the tamed frog.
250622 103001 PetK: You have slain the tamed frog.
250622 103001 PetK: Someone can see again.
250622 103001 PetK: Someone is visible once again.
250622 103001 PetK: Someone's aura of power disappears.
250622 103001 PetK: Someone
250622 103002 PetK: You hit the tamed frog (2).
250622 103002 Sebastian: PetK has slain the tamed frog.
250622 103002 PetK: You have slain the tamed frog.
250622 103002 PetK: You have learned the task of Summon Pet.
250622 103003 PetK: You miss the tamed frog.
250622 103004 Sebastian: You bump into PetK.
250622 103004 PetK: Sebastian bumps into you.
250622 103004 PetK: The tamed frog touches you (1).
250622 103004 Sebastian: PetK appears poisoned.
250622 103004 PetK: The tamed frog touches you (2).
250622 103005 PetK: You hit the tamed frog (3).
250622 103005 Sebastian: PetK has slain the tamed frog.
250622 103005 PetK: You have slain the tamed frog.
250622 103005 PetK: You hit the tamed frog (5).
250622 103005 Sebastian: PetK has slain the tamed frog.
250622 103005 PetK: You have slain the tamed frog.
250622 103005 Sebastian: PetK appears less poisoned.
250622 103007 PetK: You hit the tamed frog (5).
250622 103007 Sebastian: PetK has slain the tamed frog.
250622 103007 PetK: You have slain the tamed frog.
250622 103008 PetK: You hit the tamed frog (2).
250622 103008 Sebastian: PetK has slain the tamed frog.
250622 103008 PetK: You have slain the tamed frog.
250622 103009 PetK: You hit the tamed frog (4).
250622 103009 Sebastian: PetK has slain the tamed frog.
250622 103009 PetK: You have slain the tamed frog.
250622 103010 PetK: You hit the tamed frog (3).
250622 103010 Sebastian: PetK has slain the tamed frog.
250622 103010 PetK: You have slain the tamed frog.
250622 103011 PetK: You hit the tamed frog (3).
250622 103011 Sebastian: PetK has slain the tamed frog.
250622 103011 PetK: You have slain the tamed frog.
250622 103012 PetK: You hit the tamed frog (5).
250622 103012 Sebastian: PetK has slain the tamed frog.
250622 103012 PetK: You have slain the tamed frog.
250622 103017 PetK: You hit the tamed frog (2).
250622 103017 Sebastian: PetK has slain the tamed frog.
250622 103017 PetK: You have slain the tamed frog.
250622 103018 Sebastian: You bump into PetK.
250622 103018 PetK: Sebastian bumps into you.
250622 103019 Sebastian: You bump into PetK.
250622 103019 PetK: Sebastian bumps into you.
250622 103021 PetK: You hit the tamed frog (5).
250622 103021 Sebastian: PetK has slain the tamed frog.
250622 103021 PetK: You have slain the tamed frog.
250622 103023 PetK: You see a Wooden Torch (5000 turns).
250622 103025 PetK: You hit the tamed frog (2).
250622 103025 Sebastian: PetK has slain the tamed frog.
250622 103025 PetK: You have slain the tamed frog.
250622 103026 Sebastian: You bump into PetK.
250622 103026 PetK: Sebastian bumps into you.
250622 103026 PetK: You hit the tamed frog (4).
250622 103026 Sebastian: PetK has slain the tamed frog.
250622 103026 PetK: You have slain the tamed frog.
250622 103027 PetK: You hit the tamed frog (5).
250622 103027 Sebastian: PetK has slain the tamed frog.
250622 103027 PetK: You have slain the tamed frog.
250622 103027 PetK: You hit the tamed frog (5).
250622 103027 Sebastian: PetK has slain the tamed frog.
250622 103027 PetK: You have slain the tamed frog.
250622 103035 PetK: You hit the tamed frog (4).
250622 103035 Sebastian: PetK has slain the tamed frog.
250622 103035 PetK: You have slain the tamed frog.
250622 103035 Sebastian: You bump into PetK.
250622 103035 PetK: Sebastian bumps into you.
250622 103035 PetK: You hit the tamed frog (2).
250622 103035 Sebastian: PetK has slain the tamed frog.
250622 103035 PetK: You have slain the tamed frog.
250622 103035 PetK: The small kobold hits you (1).
250622 103036 Sebastian: PetK summons a pet.
250622 103036 Sebastian: You hit the jackal (2).
250622 103036 PetK: The small kobold hits you (4).
250622 103036 PetK: *** LOW HITPOINT WARNING! ***
250622 103038 PetK: The jackal misses the tamed frog.
250622 103038 PetK: You hit the small kobold (4).
250622 103039 Sebastian: The tamed frog touches the jackal (1).
250622 103039 Sebastian: The tamed frog touches the jackal (1).
250622 103039 Sebastian: The jackal is poisoned!
250622 103039 PetK: The small kobold hits you (4).
250622 103039 Sebastian: PetK is stunned.
250622 103040 Sebastian: PetK is no longer stunned.
250622 103040 PetK: The jackal bites the tamed frog (2).
250622 103040 Sebastian: The tamed frog dies.
250622 103040 PetK: The tamed frog dies.
250622 103041 PetK: You miss the small kobold.
250622 103042 PetK: The small kobold hits you (2).
250622 103043 PetK: The jackal bites the tamed frog (4).
250622 103043 Sebastian: The tamed frog dies.
250622 103043 PetK: The jackal croaks in agony.
250622 103043 PetK: The tamed frog dies.
250622 103045 Sebastian: The small kobold hits you (5).
250622 103048 Sebastian: The small kobold hits the tamed frog (2).
250622 103048 Sebastian: The tamed frog dies.
250622 103048 PetK: The tamed frog dies.
250622 103051 Sebastian: The tamed frog touches the jackal (1).
250622 103051 Sebastian: Welcome to level 2.
250622 103051 Azken Zutik: Sebastian has attained level 2.
250622 103051 PetK: Sebastian has attained level 2.
250622 103051 Sebastian: The jackal dies.
250622 103051 PetK: You hear a scream of agony!
250622 103054 Sebastian: The tamed frog misses the small kobold.
250622 103054 Sebastian: The tamed frog touches the small kobold (1).
250622 103056 PetK: Sebastian is surrounded by a clear aura.
250622 103056 Sebastian: You feel much better.
250622 103056 Sebastian: You have a Potion of Cure Light Wounds (c).
250622 103057 Sebastian: The tamed frog misses the small kobold.
250622 103057 Sebastian: The tamed frog touches the small kobold (1).
250622 103058 PetK: Sebastian's clear aura disappears.
250622 103059 Sebastian: You bump into PetK.
250622 103059 PetK: Sebastian bumps into you.
250622 103102 Sebastian: You bump into PetK.
250622 103102 PetK: Sebastian bumps into you.
250622 103102 Sebastian: The small kobold hits you (2).
250622 103102 Sebastian: The tamed frog misses the small kobold.
250622 103102 Sebastian: The tamed frog misses the small kobold.
250622 103105 Sebastian: You bump into PetK.
250622 103105 PetK: Sebastian bumps into you.
250622 103105 Sebastian: The small kobold hits you (3).
250622 103105 Sebastian: The tamed frog misses the small kobold.
250622 103105 Sebastian: The tamed frog misses the small kobold.
250622 103107 Sebastian: You hit the small kobold (3).
250622 103107 Sebastian: The small kobold flees in terror!
250622 103108 Sebastian: The tamed frog misses the small kobold.
250622 103108 Sebastian: The tamed frog touches the small kobold (1).
250622 103108 Sebastian: The small kobold dies.
250622 103108 PetK: The small kobold dies.
250622 103109 Sebastian: You have found 27 gold pieces worth of copper.
250622 103121 Sebastian: The tamed frog touches it (1).
250622 103121 Sebastian: The tamed frog touches it (2).
250622 103124 Sebastian: The tamed frog misses the newt.
250622 103124 Sebastian: The tamed frog touches the newt (1).
250622 103127 Sebastian: The tamed frog touches the newt (1).
250622 103127 Sebastian: The newt dies.
250622 103127 PetK: The newt dies.
250622 103133 PetK: You hit the tamed frog (5).
250622 103133 Sebastian: PetK has slain the tamed frog.
250622 103133 PetK: You have slain the tamed frog.
250622 103136 PetK: You hit the tamed frog (5).
250622 103136 Sebastian: PetK has slain the tamed frog.
250622 103136 PetK: You have slain the tamed frog.
250622 103142 Azken Zutik: The sun has risen.
250622 103142 Sebastian: The sun has risen.
250622 103142 PetK: The sun has risen.
250622 103145 PetK: You miss the tamed frog.
250622 103148 Sebastian: You see a Scroll titled "agis pes vus".
250622 103149 Sebastian: You have a Scroll titled "agis pes vus" (g).
250622 121430 Game Restarted

**Comment by draconisPW** [comment]
Note that pets are by default hostile unless you're in the same party. Maybe I should change the behavior such that they're hostile only if the player is himself hostile...

**Comment by draconisPW** [comment]
The crash has nothing to do with pet fight. When using a projected healing spell, the code lists all potential targets as non-hostile nearby players AND monsters (pets, slaves, summons...), but tries to select the most wounded player. Of course, applying player_wounded() on a monster entry crashes the game...
