### ISSUE TITLE
items descriptions (and min lvl req) cloning

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#563]
Player found 2 rings of speed in different places. First ring found on very low lvl (so item req was 13). Next ring he found much later. But after he replaced one ring to another (_swapped_) - high lvl ring become copy of the 1st ring:
![ring_pf_speed](https://user-images.githubusercontent.com/39904162/178114244-391eaac4-aba2-4bf2-9d5c-f8a7cfeaba81.png)
![ring_in_shop](https://user-images.githubusercontent.com/39904162/178114245-3bd098c2-716e-48d2-a6f5-a7d1d8ba6456.png)

**Comment by igroglaz** [comment]
The harm from this bug: players can cheeze to lower lvl reqs. for items. In V it doesn't matter as there is no trading between players.

**Comment by draconisPW** [comment]
Stacking objects blending level requirement is working as intended, there is no reason for two identical items to have different level requirements. The problem here is computing the level from depth and player level instead of object value as suggested.

**Comment by draconisPW** [comment]
This will require a bit of rework to get a feel of what to use. Object level instead of player level/depth is a good start, as it's a simple value, adding a bit of object power in the mix. Maybe also add some manual +/- correction too.

**Comment by draconisPW** [comment]
I've reworked level requirement very basically:
- for regular objects, use half object level
- for artifacts, use half artifact level
- add 1/100th of object power
- bound between 1 and 50
Only manual correction applied is for rings of polymorphing, which use half race level for base and 1/50th of race experience as power.
