### ISSUE TITLE
server makefile.bcc issue?

### ISSUE THREAD

**Issue by jjjj12212** [draconisPW/PWMAngband#564]
Hi Devs,
Just cloned this project yesterday.
I'm not sure if this was just me but while compiling using Embarcadero, I was getting errors while running the bcc32c\server.bat.

`Error: Unresolved external '_fire_ball' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\MON-ATTACK.OBJ`
`Error: Unresolved external '_desc_stat' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\MON-BLOWS.OBJ`
`Error: Unresolved external '_effect_handler_ACQUIRE' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\EFFECTS.OBJ`
`Error: Unresolved external '_effect_handler_ALTER' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\EFFECTS.OBJ`
`Error: Unresolved external '_effect_handler_ALTER_REALITY' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\EFFECTS.OBJ`
`Error: Unresolved external '_effect_handler_ARC' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\EFFECTS.OBJ`
`Error: Unresolved external '_effect_handler_BALL' referenced from C:\ANGBAND\PWMANGBAND\SRC\SERVER\EFFECTS.OBJ`
...
`Error: Unable to perform link`

`** error 2 ** deleting mangband.exe`

I managed to get it compiled by adding the following in makefile.bcc:

line 203:  ` ..\server\effect-handler-attack.c \`
line 204:  ` ..\server\effect-handler-general.c`

line 334:  ` ..\server\effect-handler-attack.obj \`
line 335:  `..\server\effect-handler-general.obj`

Is this the correct way handling this issue or is there something else I should be doing instead?

Thanks,

**Comment by draconisPW** [comment]
Yeah I forgot to update the makefile when splitting effect handler into two files. It's the correct way and I'll update the makefile.

**Comment by draconisPW** [comment]
Fixed.
