### ISSUE TITLE
Spawning dangerous mobs at entrance to the level

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#566]
Today player (25 lvl) reported the situation - he enter the dungeon level (deep descent scroll) and right near entrance there was Saruman (60 lvl). Feeling was 6. 

Dump
[Patr-05020103082022.txt](https://github.com/draconisPW/PWMAngband/files/9248586/Patr-05020103082022.txt)
:

Log of fight:
[pwmangband030822.log](https://github.com/draconisPW/PWMAngband/files/9248595/pwmangband030822.log)

It's rare piece of bad luck.. and a bit strange that it's only 6 danger, must be higher. But most importantly - I suppose we should restrict appearance of too OP monsters near the place where player enter the level. Like hounds (which already wiped on lvl generation). Other player (Siegfried) reported that he had situation when he got downstairs and appeared right near Death Mold (might be deadly for weak mage chars). `GoI` might be a solution to such cases, but it's already could be used for cheezing.. so more legit way is to ban too OOD mobs from 10 tiles around the char

**Comment by igroglaz** [comment]
Thought this particular fight with Saruman was pretty legit. Player had stuff of teleportation and made like 4 (5?) turns before was dead. So he could easily escape. Also he coudl escape when he saw Saruman on sight from the far. But anyway we might want to investigate this case in terms of Level Danger indicator.. and thing about safe zone near the entrance point

**Comment by draconisPW** [comment]
Non issue. This is basic game mechanism where OoD monster has slight chance to appear on the level. If this needs to be addressed just make a post on V forums and I'll port the change if it gets changed in V.

**Comment by igroglaz** [comment]
Ok, I'll deal with safe zone in T :)

But what about 6 danger for meeting Saruman at 25 lvl? ;) 35 lvl difference...

**Comment by igroglaz** [comment]
Suppose add_to_monster_rating() should go to 7 if mob level is bigger than player's lvl in 2x times. so if player is 25 and mob is 50 - should be 7 already
