### ISSUE TITLE
highlight party members on the mapscreen

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#569]
```
[01:53]Sebastian_: Can you please make it so party members are highlighted on the Mapscreen
[01:53]Sebastian_: (like how your character has a yellow outline)
```

**Comment by draconisPW** [comment]
First thing first, I've ensured that all @s are actually displayed on the map, not only the player character. It was not the case, since @ didn't have the highest priority.

**Comment by draconisPW** [comment]
Note: GCU and SDL2 clients only use one cursor, so highlighting other players is not possible. This can only be done for WIN and SDL clients.
