### ISSUE TITLE
Diminishing Returns for stun

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#57]
Mang, TN and PWMA greatly needs [Diminishing Returns](https://www.wowhead.com/crowd-control-diminishing-returns-wow-pvp) mechanics for stunning. Right now if your char got knocked-outed and even if he got loads of HP - he will die. You just sit and watch how it happened (feedback from http://angband.oook.cz/ladder-show.php?id=23096 ; and also I've died like this once too: http://angband.oook.cz/ladder-show.php?id=22245 ). 

Right now stunning is one of the top reasons why char could die, only because you don't have a resistance. And actually in PWMA situation is worse than in TN or Mang as 
> resist sound doesn't provide resist stun anymore

and PROT_STUN is quite rare property on items to get.

Maybe there could be implemented such 'Diminishing Returns' mechanics:
after character got knock-outed he got 10% chance to wake up (still being stunned, but not in a crucial way when you can't not do any actions); every turn this chances raise for +10%. So at 10th turn character garanteed become awake. This will make stun more fun as it will give player a chance.

**Comment by draconisPW** [comment]
Same as Free Action. I won't change V behavior unless they change it too. Being KOed is really low chance, unless you charge a pack of plasma hounds and then it's the player's fault, not the game. Stun can be cured instantly with any !CCW in case it happens.

**Comment by igroglaz** [comment]
1) the problem is that it's kinda situation where you are doomed if you got KOed. It's like getting into no-tele vault after you've entered stairs. There are always has to be a chance to survive, it could be tiny, but it should be there.
2) For V it's alright to have it as it's turn-based and it's easy to react in time. While in online roguelikes it's much more problematic to drink potion on time after stun.
3) Insta-stunning (and 100% dying) after getting into pack of plasma hounds (eg random teleport) isn't fair.

**Comment by draconisPW** [comment]
I'll check if it's not already the case. Otherwise a simple solution is to prevent the stun counter from going to 0 (fine) to max (KOed), so you get at least one turn to react. I'm pretty sure it's what is done in TomeNET and is already the case for the Mystics' physical stunning attack (they can "Heavy Stun" you in one round, but not "KO" you).

**Comment by igroglaz** [comment]
Erm. Not sure that it's "variant territory" :) is it? as you get blasted by plasma to KO in PWMAng pretty often which is overhard thing.

**Comment by igroglaz** [comment]
oh damm.. I've already did it in T :D very ez fix - TMD_effects threshold: https://github.com/igroglaz/Tangaria/commit/637d8969cddab4184e5ca46b27a134d13f1d2b1b

**Comment by igroglaz** [comment]
but I didn't test it yet. values need adjustment for sure
