### ISSUE TITLE
Terms not saving when not visible in SDL2

### ISSUE THREAD

**Issue by TreeOfSelf** [draconisPW/PWMAngband#571]
If you have term 7 open, and quit the game it saves it. If you have term 7 closed, and quit the game it will reset to default when you reopen the game. Thanks!

**Comment by draconisPW** [comment]
Posted on V forums, I'll wait for fix from the V team as I never touched the SDL2 client code and I don't want to make a blunder...

**Comment by TreeOfSelf** [comment]
I was able to fix it with just a hacky one line change in SDL2-Main. And then I found out you can use multiple windows and now prefer to use my second monitor as a map anyways.

**Comment by draconisPW** [comment]
Fix available from V, I'll port it.
