### ISSUE TITLE
recalling from dungeon to custom 'town' location 

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#58]
Recalling from dungeon to custom 'town' location makes you appear in left upper corner, which could crush the game if it's a mountains.

**Comment by draconisPW** [comment]
This is due to the fact that the game checks for FEAT_MORE/LESS instead of TF_STAIR to generate the up/down recall point. To do: replace all checks unless it's a definite check vs the feat (for ex: when creating stairs).

**Comment by draconisPW** [comment]
This should also be backported to 1.3.0.

**Comment by draconisPW** [comment]
Fixed in 68bcdfd.
