### ISSUE TITLE
non-ASCII characters is not displayed

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#580]
`'§' - non-ASCII characters are not allowed outside of literals and identifiers`
if use '§' symbol, then the whole line is not displayed
```
Problem in Semantic analysis
Location: ui-term.c :1686
Illegal character encoding in string literal [-Winvalid-source-encoding]
```
_checked in GNU/Linux_

**Comment by draconisPW** [comment]
Dang, it's hard to find an ASCII character that is not used anywhere. I'll use $ instead, it should not appear too much in a regular message string.

**Comment by s88100** [comment]
TomeNET uses key `'\377'` and it works
```
t = strtok(tmp, "\377^");
format(" for \377g%d^g damage", dmg);
```

**Comment by s88100** [comment]
The highest possible octal value is `\377` (in decimal 255)

**Comment by s88100** [comment]
_sample in hexadecimal_
```
t = strtok(tmp, "\xFF^");
format(" for \xFFg%d^g damage", dmg);
```

**Comment by s88100** [comment]
`'§'` - is `\xA7`
ASCII characters on display 32-127 (0x20 - 0x7F),
as a sample something like `format(' for \x80g%d\x81g damage', dmg);`

**Comment by igroglaz** [comment]
§ is very nasty symbol.. I know that at some EU keyboards it exists.. but  at 90% other keyboards its not exist

**Comment by s88100** [comment]
strange, but only hexadecimal `'\xA7'` works
