### ISSUE TITLE
SDL2 Client - doesn't display custom characters font-sdl2.prf over 127 (0x7F)

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#582]
Checked in V works correctly font-sdl2.prf 1-255
but in PWMAngband client it shows up to 1-127

**Comment by s88100** [comment]
accidentally found a solution 
client/main-sdl2.c
render_glyph_mono()
SDL_Surface *surface = TTF_RenderGlyph_Blended(font->ttf.handle,
        (**Uint8**) codepoint, *fg);

make_font_cache()
SDL_Surface *surface = TTF_RenderGlyph_Blended(font->ttf.handle,
        (**Uint8**) g_ascii_codepoints_for_cache[i], white);

Uint8 — [0 : 255] and it worked, all 1-255 are displayed
check please

**Comment by draconisPW** [comment]
Fixed by PR.
