### ISSUE TITLE
EXP penalty which changes in time

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#59]
Continuing this idea: https://github.com/draconisPW/PWMAngband/issues/32

Add EXP mods:

value:0:EXP[10d10]
EXP bonus +10% at level 10, 20, 30, 40, 50.

It means that character will have exp penalty 100% at 0-10 lvl; 110% at 10-20 lvl; 120% at 20-30, etc. It will help all races to start in equal conditions. 

For dragons it will be, eg:
value:0:EXP[45+50d10]
145% at lvl 0-10; 195% lvl 10; 245% lvl 20; 295% lvl 30.. etc

so all races could have 100% exp by default.. and EXP value which will change in time. It won't solve all the exp problem, but will help quite a lot.

**Comment by igroglaz** [comment]
Actually I'm thinking about rebalancing races certain way to equalize exp penalty for all of them... Would be hard to rebalance 200%+ races though...

**Comment by draconisPW** [comment]
Thinking of this... this is simply impossible to implement, since it would require computing level based on... level. Need to think of something else.
