### ISSUE TITLE
SDL crush while in ASCII mode

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#590]
**Initial report:**
[20:10]Wraiths: Is there any reason for SDL2 to crash when I'm running it in ASCII? It seems to happen more when I'm playing in a party than solo.

I can let you know any specifics next time it happens. I just finished playing for a couple of hours in ASCII solo, no crashes at all. But whenever I'm playing with friends it'll crash within 1-20 minutes. There's no error message, just straight up closes.

client is up-to-date.

**Detailed report later on with crush repro:**
[10:18]Wraiths: @igroglaz Just started playing with @Xcelar and it crashed for me in ASCII again. It seems to happen whenever certain things come into vision, and it only ever does it when I'm with another person. Not sure how helpful it'll be, but I got @Xcelar to take some screenshots both times that I DC'd with him.

https://cdn.discordapp.com/attachments/535396965433868288/1068444934396452945/image.png

https://cdn.discordapp.com/attachments/535396965433868288/1068444988695908362/image.png

log from server:
270123 111240 Xcelar IV: This seemed a quiet, peaceful place.
270123 111240 Wraithz: Xcelar IV has been added to party Wraithz & Friends.
270123 111240 Xcelar IV: You've been added to party 'Wraithz & Friends'.
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111249 Xcelar IV: You are drowning!
270123 111249 Xcelar IV: There is a wall in the way!
270123 111252 Wraithz: You see a Dagger (1d4) (+0,+0).
270123 111253 Xcelar IV: You are drowning!
270123 111256 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111257 Xcelar IV: There is a wall in the way!
270123 111302 Xcelar IV: There is a wall in the way!
270123 111302 Xcelar IV: There is a wall in the way!
270123 111302 Xcelar IV: There is a wall in the way!
270123 111302 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111303 Xcelar IV: There is a wall in the way!
270123 111304 Xcelar IV: You enter a maze of up staircases.
270123 111305 New Level 200ft at (1, 0) Ratings obj:0/mon:45
270123 111305 Xcelar IV: This seems a quiet, peaceful place.
270123 111305 Wraithz: You enter a maze of up staircases.
270123 111305 Wraithz: This seemed a quiet, peaceful place.
270123 111307 Xcelar IV: You bump into Wraithz.
270123 111307 Wraithz: Xcelar IV bumps into you.
270123 111310 Xcelar IV: You cannot recite that prayer.
270123 111312 Xcelar IV: You cannot recite that prayer.
270123 111317 Wraithz: You have found a trap.
270123 111319 Wraithz: You have found a trap.
270123 111321 Xcelar IV: You bump into Wraithz.
270123 111321 Wraithz: Xcelar IV bumps into you.
270123 111322 Wraithz: There is a wall in the way!
270123 111322 Wraithz: You hear a scream of agony!
270123 111322 Xcelar IV: You hear a scream of agony!
270123 111328 Xcelar IV: There is a wall blocking your way.
270123 111329 Wraithz: You have 2 Potions of Neutralize Poison (m).
270123 111329 Xcelar IV: There is a wall blocking your way.
270123 111333 Wraithz: You are drowning!
270123 111334 Xcelar IV: There is a wall in the way!
270123 111334 Wraithz: The sun has risen.
270123 111334 Xcelar IV: The sun has risen.
270123 111335 Wraithz: You are drowning!
270123 111336 Wraithz: You are drowning!
270123 111337 Wraithz: Xcelar IV summons a monster.
270123 111337 Disconnected from server...
270123 111338 Xcelar IV: The master yeek hits the giant white ant for $r8^r damage.
270123 111338 Xcelar IV: The giant white ant is stunned.
270123 111341 Xcelar IV: The giant white ant misses the giant white ant.
270123 111341 Xcelar IV: The master yeek tries to cast a spell, but fails.
270123 111341 Goodbye Wraithz=Wraiths@DESKTOP-RB4SDTU ("Client quit")
270123 111341 Xcelar IV: Wraithz has left the game.

**Comment by s88100** [comment]
in **PWMAngband** (sdl2,ascii,localhost, two clients)
added party Player1 - Player2 (Elf - Summoner)
(1) Create a party / and alternately (2) Add a player to party (3) Delete a player from party. many times

> free(): double free detected in tcache 2

(gdb) client
```
Starting program: /tmp/test-pwmangband/Tangaria/games/pwmangclient 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff28ec700 (LWP 387992)]
[New Thread 0x7ffff1d61700 (LWP 387993)]

Thread 1 "pwmangclient" received signal SIGSEGV, Segmentation fault.
unlink_chunk (p=p@entry=0x555557eda790, av=<optimized out>) at malloc.c:1459
1459    malloc.c: There is no such file or directory.
```

```
[New Thread 0x7ffff28ec700 (LWP 407286)]
[New Thread 0x7ffff1d61700 (LWP 407287)]
free(): double free detected in tcache 2

Thread 1 "pwmangclient" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: There is no such file or directory.
```
in **Tangaria**

> malloc(): smallbin double linked list corrupted

(gdb) client
```
double free or corruption (out)

Thread 1 "pwmangclient" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: There is no such file or directory.
(gdb) 
Couldn't get registers: There is no such process.
Couldn't get registers: There is no such process.
(gdb) 
Couldn't get registers: There is no such process.
(gdb) [Thread 0x7fffe107e700 (LWP 304621) exited]
[Thread 0x7fffe10bf700 (LWP 304620) exited]

Cannot execute this command without a live selected thread.
(gdb) 
Cannot execute this command without a live selected thread.
(gdb) 
Program terminated with signal SIGABRT, Aborted.
The program no longer exists.
```

```
corrupted double-linked list

Thread 1 "pwmangclient" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: There is no such file or directory.
(gdb) 
Couldn't get registers: There is no such process.
Couldn't get registers: There is no such process.
(gdb) 
Couldn't get registers: There is no such process.
(gdb) [Thread 0x7fffe1e89700 (LWP 340008) exited]
[Thread 0x7fffe1eca700 (LWP 340007) exited]
```

**Comment by draconisPW** [comment]
Sounds like a bug in update_message_chat_subwindow(), I got a call on message iterator -> older with a freed value for the pointer.

**Comment by draconisPW** [comment]
Could not reproduce the issue. I would tend to think this was the same as #591 since it involves two players in the same party and the double free could potentially impact anything.
