### ISSUE TITLE
free memory after death crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#592]
https://youtu.be/5C-XEgnIpf8

**Comment by draconisPW** [comment]
The video unfortunately doesn't show the value of p->body which would have helped greatly.

**Comment by igroglaz** [comment]
Maybe dump would help: https://stat.tangaria.com/chars/Varatorn-12450310022023.txt

**Comment by igroglaz** [comment]
And log:

100223 124449 New Level 3150ft at (0, -3) Ratings obj:365/mon:1323
100223 124449 Varatorn: You feel nervous about this place.
100223 124452 Varatorn: You sense the presence of creatures!
100223 124455 Varatorn: You sense no stairs.
100223 124458 Varatorn: You have found a trap.
100223 124458 Varatorn: You miss the ancient gold dragon.
100223 124458 Varatorn: You zap the ancient gold dragon for 64 damage.
100223 124458 Varatorn: You miss the ancient gold dragon.
100223 124458 Varatorn: You zap the ancient gold dragon for 58 damage.
100223 124458 Varatorn: You miss the ancient gold dragon.
100223 124458 Varatorn: The ancient gold dragon misses you.
100223 124458 Varatorn: The ancient gold dragon misses you.
100223 124458 Varatorn: The ancient gold dragon bites you for 46 damage.
100223 124459 Varatorn: The ancient gold dragon claws you for 20 damage.
100223 124459 Varatorn: The ancient gold dragon misses you.
100223 124459 Varatorn: The ancient gold dragon misses you.
100223 124459 Varatorn: You zap the ancient gold dragon for 80 damage.
100223 124459 Varatorn: You zap the ancient gold dragon for 52 damage.
100223 124459 Varatorn: You feel better.
100223 124459 Varatorn: You zap the ancient gold dragon for 60 damage.
100223 124459 Varatorn: You feel better.
100223 124459 Varatorn: You miss the ancient gold dragon.
100223 124459 Varatorn: You zap the ancient gold dragon for 56 damage.
100223 124459 Varatorn: The ancient gold dragon misses you.
100223 124459 Varatorn: The ancient gold dragon misses you.
100223 124459 Varatorn: The ancient gold dragon bites you for 44 damage.
100223 124459 Varatorn: You zap the ancient gold dragon for 58 damage.
100223 124459 Varatorn: You zap the ancient gold dragon for 76 damage.
100223 124459 Varatorn: You feel better.
100223 124459 Varatorn: You zap the ancient gold dragon for 70 damage.
100223 124459 Varatorn: You feel better.
100223 124459 Varatorn: You zap the ancient gold dragon for 121 damage. It was a good hit!
100223 124459 Varatorn: You feel better.
100223 124459 Varatorn: You miss the ancient gold dragon.
100223 124500 Varatorn: The ancient gold dragon breathes sound.
100223 124500 Varatorn: You resist the effect!
100223 124500 Varatorn: You zap the ancient gold dragon for 74 damage.
100223 124500 Varatorn: You zap the ancient gold dragon for 70 damage.
100223 124500 Varatorn: You miss the ancient gold dragon.
100223 124500 Varatorn: You zap the ancient gold dragon for 64 damage.
100223 124500 Varatorn: You zap the ancient gold dragon for 78 damage.
100223 124500 Varatorn: You feel better.
100223 124500 Varatorn: You miss the ancient gold dragon.
100223 124500 Varatorn: You zap the ancient gold dragon for 70 damage.
100223 124500 Varatorn: You miss the ancient gold dragon.
100223 124500 Varatorn: You zap the ancient gold dragon for 58 damage.
100223 124500 Varatorn: You feel better.
100223 124500 Varatorn: You zap the ancient gold dragon for 62 damage.
100223 124500 Varatorn: You feel better.
100223 124500 Varatorn: The ancient gold dragon misses you.
100223 124500 Varatorn: The ancient gold dragon misses you.
100223 124500 Varatorn: The ancient gold dragon bites you for 55 damage.
100223 124500 Varatorn: You zap the ancient gold dragon for 66 damage.
100223 124500 Varatorn: You feel better.
100223 124500 Varatorn: You zap the ancient gold dragon for 64 damage.
100223 124500 Varatorn: You zap the ancient gold dragon for 78 damage.
100223 124500 Varatorn: You zap the ancient gold dragon for 78 damage.
100223 124500 Varatorn: You feel better.
100223 124500 Varatorn: You zap the ancient gold dragon for 62 damage.
100223 124500 Varatorn: The ancient gold dragon flees in terror!
100223 124501 Varatorn: Your weapon calls beyond the grave!
100223 124501 Varatorn: Your weapon calls beyond the grave!
100223 124501 Varatorn: You drain the eye druj for 82 damage. It was a great hit!
100223 124501 Varatorn: You drain the eye druj for 49 damage.
100223 124501 Varatorn: You drain the eye druj for 46 damage.
100223 124501 Varatorn: You miss the eye druj.
100223 124501 Varatorn: You drain the eye druj for 47 damage.
100223 124501 Varatorn: The eye druj can move again.
100223 124501 Varatorn: The eye druj casts a bolt of nether.
100223 124501 Varatorn: You resist the effect!
100223 124501 Varatorn: You drain the eye druj for 52 damage.
100223 124501 Varatorn: You drain the eye druj for 46 damage.
100223 124501 Varatorn: You drain the eye druj for 57 damage.
100223 124501 Varatorn: You miss the eye druj.
100223 124501 Varatorn: You drain the eye druj for 87 damage. It was a good hit!
100223 124501 Varatorn: The ancient gold dragon is no longer afraid.
100223 124502 Varatorn: The eye druj casts a ball of nether.
100223 124502 Varatorn: *** LOW HITPOINT WARNING! ***
100223 124502 Varatorn: You resist the effect!
100223 124502 Varatorn: The ancient gold dragon dies.
100223 124502 Varatorn: You drain the eye druj for 52 damage.
100223 124502 Varatorn: You drain the eye druj for 51 damage.
100223 124502 Varatorn: You drain the eye druj for 54 damage.
100223 124502 Varatorn: You drain the eye druj for 49 damage.
100223 124502 Varatorn: You drain the eye druj for 55 damage.
100223 124503 Varatorn: The eye druj smashes you with psionic energy.
100223 124503 Varatorn: You resist the effect!
100223 124503 Varatorn: You resist the effect!
100223 124503 Varatorn: You resist the effect!
100223 124503 Varatorn: You resist the effect!
100223 124503 Varatorn: You die.
100223 124503 Character dump successful (server).
100223 124503 Character dump successful (client).
100223 124503 Varatorn: You re-arrange your quiver.
100223 124503 Varatorn: You re-arrange your quiver.
100223 124503 Varatorn: You re-arrange your quiver.
100223 124503 Varatorn: You re-arrange your quiver.
100223 124503 Varatorn: You have been killed by an eye druj.
100223 124504 Goodbye Varatorn=Varatorn@HOME-PC ("Killed by an eye druj")

**Comment by draconisPW** [comment]
Need to check if this comes from Vampire race or it's just some random memory corruption like the one from #591 because I don't see how slots pointer could provoke a crash...

**Comment by igroglaz** [comment]
good point. but #591 was client crush, while this issue is server crush.. but who knows, maybe there is a connection

**Comment by draconisPW** [comment]
For me it looks like another instance of double free somewhere. I will consolidate the code by adding p = NULL lines after every mem_free(p).

**Comment by draconisPW** [comment]
Server side work done.

**Comment by draconisPW** [comment]
Client side work done.

**Comment by draconisPW** [comment]
Common code updated (without string_free).

**Comment by igroglaz** [comment]
![image](https://user-images.githubusercontent.com/39904162/221170702-52ea3a81-2759-4567-92a5-b3359084d8b5.png)

![image](https://user-images.githubusercontent.com/39904162/221170827-8687e8dc-9a19-4df1-a581-b21673c808db.png)


![image](https://user-images.githubusercontent.com/39904162/221170890-291a2871-fe86-4cc5-b2a7-7b2806864cf3.png)


![image](https://user-images.githubusercontent.com/39904162/221170913-b2864af0-bfc1-4acc-97cc-d952eea1e549.png)






![image](https://user-images.githubusercontent.com/39904162/221170649-9f69f006-869e-41dd-8dc3-1e9b704261cf.png)


![image](https://user-images.githubusercontent.com/39904162/221170524-7e15fdf2-70be-48fd-8061-a13959a2b128.png)

![image](https://user-images.githubusercontent.com/39904162/221170958-618387ef-9b68-44e5-a713-fdb835321361.png)


it's crush from today..  all updates ported except 2 last ones (88a70ad92725d6279a69c4288dfd8f28e5aa056b)

**Comment by draconisPW** [comment]
Seems like memory is erased from something else, as there is nothing wrong with the screens above. Only explanation is that the string s is acceding deleted memory.

**Comment by igroglaz** [comment]
Serakin XXVII died.. but after death log says that he re-arranged pack and quiver. This message shouldn't appear in log after char death

**Comment by igroglaz** [comment]
![image](https://user-images.githubusercontent.com/39904162/221425639-b91aeb39-1f4a-4b7f-bcff-304093f7e4ca.png)

![image](https://user-images.githubusercontent.com/39904162/221425657-20136606-490c-4d3f-981a-7b8f7c2b980f.png)


![image](https://user-images.githubusercontent.com/39904162/221425662-8782d197-eae6-4eda-9d93-f4a9e1eb7968.png)


![image](https://user-images.githubusercontent.com/39904162/221425673-449b1b34-6d50-4aa9-8bf5-17b2ca4a0467.png)

![image](https://user-images.githubusercontent.com/39904162/221425691-9cab39bc-3fca-4d65-a6e0-863a16612154.png)

![image](https://user-images.githubusercontent.com/39904162/221425697-270525e5-9f1e-42f8-996f-272a5861e8d6.png)

![image](https://user-images.githubusercontent.com/39904162/221425707-4f3e4fc4-856e-4731-bbea-cc9d1125cf55.png)


![image](https://user-images.githubusercontent.com/39904162/221425723-e258a05f-edd4-4243-95ab-7e7fe2a412c6.png)

**Comment by draconisPW** [comment]
Input handler seems to be called after character leaves before it is removed by the "leave" function. I'll look into that.

**Comment by igroglaz** [comment]
great :D

**Comment by draconisPW** [comment]
Problem: method Contact is not called when I disconnect a character, it's the input handler that is removed. I fear the problem comes from Tangaria loading too much stuff.

- player logs
- server creates socket to communicate with client, arg = 0
- client responds
- server creates socket for client to communicate with server, arg = 2

At stage 2 if the client takes too long the server will listen on an empty socket and since it's asynchronous it will respond with EWOULDBLOCK.

**Comment by draconisPW** [comment]
Handled EWOULDBLOCK in Contact. If other errors still occur (errno != EWOULDBLOCK ) just disable the "quit" line in Tangaria so at least the server doesn't quit and just refuses the connection from client.

**Comment by igroglaz** [comment]
Back to original crush (p->body....):

![image](https://user-images.githubusercontent.com/39904162/221768017-d30e8f11-5054-4230-84b0-330f0d8d8690.png)

![image](https://user-images.githubusercontent.com/39904162/221768294-04386f4c-8bc8-4ca4-a28b-e2b1497ec71c.png)

![image](https://user-images.githubusercontent.com/39904162/221768315-a7a178a6-5171-4bb8-8db4-c503ae658825.png)

![image](https://user-images.githubusercontent.com/39904162/221768356-f733c8be-f76d-42bc-b6ad-5cf687704151.png)

![image](https://user-images.githubusercontent.com/39904162/221768394-286b0b79-a1a8-4e68-a9db-8de5e19f9380.png)

![image](https://user-images.githubusercontent.com/39904162/221768906-8baee57c-b4af-4d6b-969d-e3922623fe78.png)

aaand p->body... :

![image](https://user-images.githubusercontent.com/39904162/221769148-364fe861-462a-4348-a02e-ce560bc262df.png)

![image](https://user-images.githubusercontent.com/39904162/221769233-45fec732-aecf-4197-81b7-45b7c66c5b72.png)

![image](https://user-images.githubusercontent.com/39904162/221769421-17b628b6-234a-48f7-b88e-6fa6d1a18721.png)

![image](https://user-images.githubusercontent.com/39904162/221769500-d1fa7970-500b-4435-b1a9-82f4d2691f64.png)

![image](https://user-images.githubusercontent.com/39904162/221769582-6c2e1913-a67d-44e6-a9b5-40207a35a145.png)

**Comment by igroglaz** [comment]
*updated some screenshots in previous post*

**Comment by draconisPW** [comment]
body.slots pointer seems to be valid, this is really confusing. Maybe it's because "obj" is pointing to a valid object and shouldn't be freed... I'll take a look.

**Comment by draconisPW** [comment]
Unfortunately the most vital information (value of p->body.slots) is missing from the post above, which makes it impossible to debug the issue. I wont be able to "guess" the reason here...
Looking at V code, I suspect it's because I condensed the allocation with a "memcpy" when I shouldn't have, so I'll revert the code to what is done in V. If the issue still happens after this fix, we'll have to check in detail the value of p->body.slots (it's an array so it has to be expanded since the debugger only shows the first item).

**Comment by draconisPW** [comment]
Ofc I'm an idiot.

p->body.slots[i].name must me allocated and freed separately, that's obviously the reason why it crashes...
Fixing this moronic bug...
