### ISSUE TITLE
square_issecretdoor() crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#595]
I used skill `Roll` which makes....
```
effect:TELEPORT
dice:2
```
....in this location:
![image](https://user-images.githubusercontent.com/39904162/223492003-8a4c73a6-0f85-4bda-bfaa-f97b475e7aa6.png)

and server crushed

![image](https://user-images.githubusercontent.com/39904162/223493052-55566214-9b15-4c7e-8d88-bc35e107177c.png)

![image](https://user-images.githubusercontent.com/39904162/223492304-785b1a53-ad7b-4d23-ae75-839cd37fd2c5.png)

![image](https://user-images.githubusercontent.com/39904162/223492381-65a59839-4847-4e58-9af6-d3997d7bf62d.png)

![image](https://user-images.githubusercontent.com/39904162/223492496-234cbd4c-8e1a-447a-bf6e-068b12fc3b13.png)

![image](https://user-images.githubusercontent.com/39904162/223492812-41dd19f1-ff85-4475-9a3b-3d704a5ee822.png)

**Comment by igroglaz** [comment]
YAOOB (yet another out of bound) :D

**Comment by igroglaz** [comment]
I suppose as it's very narrow place - it tries hard to put player somewhere, but a lot of places occupied by walls... and it fails somehow. As distance is not standart (2 tiles) it might be the reason why it's triggered so rare

**Comment by draconisPW** [comment]
Since I don't see exactly what happened there, I just added a safe check so teleport attempt fails if the teleport routine cannot find a valid destination for teleport. Better than a crash.
