### ISSUE TITLE
host arg

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#603]
it would be fun to add .bat file which will start server and client right on:

```
@echo off

   start mangband.exe
   start mangclient_sdl2.exe

@echo on
```

as it's fun to distribute game with proper IP already there - it will be useful to be albe to pass to client args eg 
   start mangclient_sdl2.exe -host=127.0.0.1

this way we can add name singleplayer.bat with this tiny script which will give new player ez way to get into the game without digging tech savvy cfgs :)

**Comment by s88100** [comment]
https://github.com/draconisPW/PWMAngband/blob/master/src/client/conf.c#L709
```
clia_find()
if (prefix(p_argv[i], "--"))
```
**--host**
**--port**

use '.bat' file

```
@echo off

   start mangband.exe
   start mangclient_sdl2.exe --host 127.0.0.1

@echo on
```
