### ISSUE TITLE
gen lvl stairs crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#604]
https://youtu.be/jUBOg5WOATc

**Comment by igroglaz** [comment]
seems caused by lake generation in T

**Comment by igroglaz** [comment]
seems it wasn't lake after all. two more crushes (different onces) on localhost.
https://youtu.be/0wVSRqOPXXM

**Comment by igroglaz** [comment]
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/f6f7ce3f-4884-4058-b22e-dc0ab339fd6e)
![image](https://github.com/draconisPW/PWMAngba
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/bd59ae41-151f-42b3-991b-33fee50f16d3)
nd/assets/39904162/b89f239c-3fe1-4fb0-b3e4-270e1bce9c73)
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/cd79e110-7c7c-441a-87fa-708b9d8ceb2c)
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/50276c4e-06b5-416e-b359-86f5a4ecc839)
![image](https://github.com/draconisPW/PW
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/a3bc1e2d-f293-4b9c-acc5-85992216f93e)
MAngband/assets/39904162/c1b871a7-ba98-4729-8ba4-36f7474ca4f9)
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/e09ecf51-2283-45fe-94f5-9a5a588bb228)
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/89ecef6a-c31b-4941-9fcb-6fc98f9625a2)

**Comment by draconisPW** [comment]
Yeah as expected, this crashes where the game tries to generate exactly 8 stairs. There is an array overflow because of the developer's moronic coding...

**Comment by draconisPW** [comment]
Fixed in commit 3468d19.
