### ISSUE TITLE
broken server savefiles

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#612]
Server had crush, but there is no breakpoint in void exit_game_panic(void).
Server logs:
220124 074559 Actavis II: You punch Bert the Stone Troll for 23 damage.
220124 074559 Actavis II: You punch Bert the Stone Troll for 30 damage.
220124 074559 Actavis II: You punch Bert the Stone Troll for 30 damage.
220124 074559 Actavis II: Something makes a high-pitched shriek.
220124 074600 Actavis II: Bert the Stone Troll hurls a boulder.
220124 074601 Actavis II: Bert the Stone Troll hits you for 21 damage.
220124 074601 Actavis II: Bert the Stone Troll hits you for 10 damage.
220124 074601 Actavis II: Bert the Stone Troll bites you for 15 damage.
220124 074602 Actavis II: Bert the Stone Troll hurls a boulder, but misses.
220124 074605 Actavis II: Bert the Stone Troll misses you.
220124 074605 Actavis II: Bert the Stone Troll hits you for 18 damage.
220124 074605 Actavis II: Bert the Stone Troll misses you.
220124 074606 Actavis II: Bert the Stone Troll hits you for 17 damage.
220124 074606 Actavis II: Bert the Stone Troll misses you.
220124 074606 Actavis II: Bert the Stone Troll bites you for 14 damage.
220124 074606 Actavis II: You polymorph back into your normal form.
220124 074606 Actavis II: You are starving!!
220124 074606 Actavis II: You rise up through the ceiling.
220124 074606 Actavis II: You are still hungry.
220124 074606 Actavis II: Death nearly grasped you, but in the last moment....
220124 074606 Actavis II: ........something pulled you into the aether........
220124 074606 New Level 1450ft at (2, 1) Ratings obj:447/mon:3096
220124 074606 Actavis II: This place seems terribly dangerous.
220124 074606 Actavis II: You have 36 Scrolls of Phase Door {@1} (m).
220124 074607 remove illegal input handler fd -1

Now when I try to start server:
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/4cb9afc6-c35c-4d0b-a207-b7645bffa899)

**Comment by draconisPW** [comment]
Frankly teleporting level during death check makes no sense, just remove that from your code and it should be fine. The game is totally lost there, a new level is generated completely out of sequence and totally confuses the game. Won't even try to check why since it should never happen.

**Comment by igroglaz** [comment]
thanks. replaced with regular teleport :D
