### ISSUE TITLE
SDL client options buttons bug

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#623]
1. launch the client
2. press Options button, press 'ok'
3. login in the game
4. Options menu there are no 'off', '+'.. buttons (Fullscreen is .., Window borders is)

![screen123options](https://github.com/draconisPW/PWMAngband/assets/71586060/c6e615ef-326f-4ba7-84a5-ad331234f0b4)

1. launch the client
2. login in the game
3. Options menu, buttons are displayed correctly

**Comment by draconisPW** [comment]
Available graphics creates two buttons only in setup mode but tries to display them anyway, leading to a shift of two in the index of the following buttons. Fix: only display the buttons in setup mode.

**Comment by draconisPW** [comment]
Fixed in commit 6cf5413.
