### ISSUE TITLE
new lvl gen crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#626]
character entered the game (inside of the dungeon) and got crush
https://youtu.be/hcveTNiHVgI

As it's (walls == 0) problem, maybe it's because in T we replace walls with floors sometimes to make more interesting layout... like this:
`
wall:obj_grass2 f:300

wall:obj_grass2 g:300

wall:obj_grass2 h:300

**Comment by igroglaz** [comment]
https://github.com/igroglaz/Tangaria/commit/767c82cd398ceaf8e03163619a55571c5c0dcada

**Comment by draconisPW** [comment]
Above commit doesn't do anything because when walls = 0 the code already doesn't care about walls (square_num_walls_adjacent returns 0). The problem happens before: either square_isempty() always returns false, square_isvault() always returns true or square_isno_stairs() always returns true. Since the first two cases seem unlikely (level completely filled with objects or just consisting of one big vault), I suspect the issue comes from the third case: all floor features on the level prevent the generation of stairs.

**Comment by igroglaz** [comment]
it does the job. crushes stopped :)

**Comment by draconisPW** [comment]
Yes because you removed the "quit" line. However the commit itself does nothing, the code doesn't work and doesn't do anything to fix the problem. Instead of "quitting", the code continues normally and simply doesn't place any stair. The risk is having someone land on a level with no stairs to leave.

**Comment by igroglaz** [comment]
AFAIU problem appears rarely with one staircase which game fail to place. So if it placed several stairs and fail to place one - it's alright. 

Anyway you are welcome to make proper fix and commit it to T repo :) Thanks for getting into this issue.

**Comment by draconisPW** [comment]
Commit 75126493406e4042b266b007fa9705e21792c5d0 fixes a memory leak and dumps the level for post-mortem analysis when stair placement fails. You should revert your code and use this instead to understand what truly happens so we can come with a proper fix.

See generated file: dumpedlevel.html when server quits due to failed stair placement.

**Comment by igroglaz** [comment]
`Stair Placement Failure

###########################################################################################
###########################################################################################
#########<............<####################################################################
#########....................##############################################################
#########...........##.......########################.......<...........###################
######################.......########################...................###################
######################..###..#...################<......................###################
#################................###############........................###################
#################.............#..###############..###...................###################
#################.............#..###############..###...................###################
#################.............#..###############..###..................<###################
#################............<#..###############..###########..############################
###############################..###############..###########..############################
###############################..###############..###########..############################
###############<.............##...........######..###########..############################
###############..............##...........######..........<##..############################
###############..............##................................############################
###############..............##................................############################
############################..#...........######...........################################
############################..#...........#####<.##########################################
############################..##########..####..###########################################
############################..##########..####..###########################################
#########################.............<.........###########################################
#########################.......................###########################################
#########################............################.###.#################################
############################..#####..#####################.################################
############################<........######################################################
#############################........###################.###.##############################
########################################################.#...##############################
###########################################################...#############################
#########################################################.#.....#.#########################
############################################################.###.##########################
###########################################################################################
    `

**Comment by igroglaz** [comment]
``<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Stair Placement Failure</title>
  </head>
  <body>
    <p>Stair Placement Failure
    <pre>
###########################################################################################
###########################################################################################
#########&lt;............&lt;####################################################################
#########....................##############################################################
#########...........##.......########################.......&lt;...........###################
######################.......########################...................###################
######################..###..#...################&lt;......................###################
#################................###############........................###################
#################.............#..###############..###...................###################
#################.............#..###############..###...................###################
#################.............#..###############..###..................&lt;###################
#################............&lt;#..###############..###########..############################
###############################..###############..###########..############################
###############################..###############..###########..############################
###############&lt;.............##...........######..###########..############################
###############..............##...........######..........&lt;##..############################
###############..............##................................############################
###############..............##................................############################
############################..#...........######...........################################
############################..#...........#####&lt;.##########################################
############################..##########..####..###########################################
############################..##########..####..###########################################
#########################.............&lt;.........###########################################
#########################.......................###########################################
#########################............################.###.#################################
############################..#####..#####################.################################
############################&lt;........######################################################
#############################........###################.###.##############################
########################################################.#...##############################
###########################################################...#############################
#########################################################.#.....#.#########################
############################################################.###.##########################
###########################################################################################
    </pre>
  </body>
</html>
``

**Comment by igroglaz** [comment]
![image](https://github.com/user-attachments/assets/35459ea7-fe5d-4c28-b0ec-ccb013651673)
![image](https://github.com/user-attachments/assets/113c8fa0-0945-4e3f-b511-0a7cbf88cd79)
![image](https://github.com/user-attachments/assets/1cbf55f6-3b32-43cc-ab81-d99f52857378)
![image](https://github.com/user-attachments/assets/b164415a-9671-44aa-a8a6-c1db4313c53c)
![image](https://github.com/user-attachments/assets/36f2157d-5a4d-461c-8ad4-d306d9d6eb4d)
`<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Stair Placement Failure</title>
  </head>
  <body>
    <p>Stair Placement Failure
    <pre>
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
##################################################################################################################&gt;#####################################
##################################################################################################################..####################################
##################################################################################################################..####################################
###########################################################################################################..#####..####################################
###########################################################################################################...####..####################################
###########################################################################################   #############...####..####################################
#####################################################    ######        ##################     #############.........####################################
############################################ ###          #            #################      #############.........## ####         ### ###  ###########
########################################  #   #                         ###############   :  :: ##......###....####.    #                     ##########
########################################                                ###############   ::    # .......##....#####                          ##########
#######################################                                  ######.......&gt;  : : :    #####..##....#####                           #########
#####################################                                    # ...........#####   #########..##....#                               #########
#####################################                                      ....#############  #########........#                                ########
######################################                                   ###############################.......##                       #      #########
######################################            #                      ##################################....##                      ###     #########
#######################################          #   ##   #         ### ###################################....#########################################
############################################  #  #&gt;########################################################&gt;...#########################################
############################################..#....#########################################################...#####################...............#####
############################################..#.......#########..###########################################..######################.#############.#####
############################################..#.......#########...&gt;#########################################...........#############.#MMMMMMMMMMM#.#####
##########################################....#..###..#########  #  ##. #####################################...........############.#MMMMMMMMMMM#.#####
##########################################.......###..## ###   #      #  ##    #######################################..############.#MMMMMMMMMMM#.#####
###########################################......####    ###                   #######################################.....#########.#MMMMMMMMMMM#.#####
###############################################..## ##                         ############### # # ### ###  ########### ....########.#MMMMMMMMMMM#.#####
###############################################..##                            ######### #          #   #       #   ##  ##..########.######+######.#####
###############################################..#                               .....##                               ###....######..&gt;............#####
########################################.........#                               .....                                  ##.....########..###############
########################################.........#                            #####..###                                ##...............###############
####################################  ##..#########                          ##&gt;.....###                               ###...............###############
###################################   ##..#########          ##              ###.....####                              ####....#########################
################################## :   ##&gt;########          ####                .########      #                      #..#####.#########################
################################## : :   ###############################  ######.####################################  ..###############################
##################################    :  ###############################..#####..#####################################..################################
################################## : :   ###############################.........#####################################..################################
##################################   :: ################################.........#####################################&gt;#################################
##################################    : ################################....############################################################################
##################################   : : ################################...############################################################################
###################################      ###############################################################################################################
########################################################################################################################################################
########################################################################################################################################################
    </pre>
  </body>
</html>
`

**Comment by igroglaz** [comment]
maybe it's connected with https://github.com/igroglaz/Tangaria/commit/d1217609a3605dd7785628676e419bf674f07bab

**Comment by igroglaz** [comment]
seems you are at vacation :) for now I'll limit stairs numbers
https://github.com/igroglaz/Tangaria/commit/30f91da36b52dbe2cc27c4cbe4b60add2d77fff1

**Comment by igroglaz** [comment]
Maybe might happen cause too big number of staircases

**Comment by draconisPW** [comment]
I need to check, but I think V added a bit of code to prevent stairs from being generated too close to other stairs, which explains the first problem. For the second problem, the post-mortem analysis shows locations not suited for stairs as white instead of dots, which tells that all the rooms cannot have stairs, which also greatly limits the places where stairs can be generated.

**Comment by draconisPW** [comment]
Ok I changed a bit how stairs are generated. Instead of one pass, there is now a loop that starts to generate all the stairs using the original minstep (for PWMAngband, I've tried many times and this first pass seems to always work). If the first pass cannot generate all stairs, another pass is done with num = num - number of stairs generated during the first pass with minstep halved. This continues until either all stairs are generated or minstep falls to zero, in which case the post-mortem analysis is thrown as before (that's for the case there is not enough tiles on the floor which allow stair placement).

**Comment by draconisPW** [comment]
Should be fixed with commit 4eedb22.
