### ISSUE TITLE
add all resistances to character sheet

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#63]
'C' -> 'm' : some resistances are absent there, eg 'time', 'water' etc. It will be fun to have them all there. There is a third page available with plenty of space ('C' -> 'm' -> 'm')

**Comment by draconisPW** [comment]
Retargeting this for 1.4.0, as V enlarged character resist display, so it's a good moment to implement this at the same time.

**Comment by draconisPW** [comment]
Implemented in fc8ce3d.
