### ISSUE TITLE
MotD shown on login in 'message window'

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#64]
it will be fun to add news message which will be shown at 'message window' upon each login (such feature exist in TomeNET). It will give possibility to notify players about news/wipes (cause not all players read website/discord).

There is a 'news.txt' file in \lib\screens ; but it shows as loading screen and it has decorative meaning (having nice picture there); so it will be fun to have additional MotD text..

**Comment by draconisPW** [comment]
Added file motd.txt which is displayed after "Server is running version" and before any message. By default, file is empty, feel free to add any text relevant to your server.

**Comment by igroglaz** [comment]
I wonder - please can we show MotD only to player, without recording it to server logs? As now it's spam a lot when there are a lot of players re-entering the game

**Comment by draconisPW** [comment]
Done.
