### ISSUE TITLE
dungeon descriptions in dungeon.txt

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#66]
it will be great to have 'short-desc:' in dungeon.txt to be able to look into dungeon description upon looking at dungeon entrance as it made in terrain.txt

It will give possibility to give a hint where to go next, eg

`short-desc:Entrance to The Severs. Next dungeon is Fetid Swamps [-1,0]`

**Comment by draconisPW** [comment]
IIRC Tangaria uses different entrances in terrain.txt for each dungeon with their own descriptions. This is not needed anymore.
