### ISSUE TITLE
dungeon_breed customization (unhardcode dragon race)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#67]
> value:1:STR[-10+1d5]

doesn't work for dragons (stats won't raise each 5 lvls).

Also it will be fun to add more customization for different types of dragons

**Comment by draconisPW** [comment]
Tested locally and value:1:STR[-10+1d5] on dragons works perfectly, if it doesn't work for you then it's a typo in your file.

**Comment by igroglaz** [comment]
https://youtu.be/KLmxdlg7q0k?t=1640 - at my stream.. I don't see there any typo. 

Anyway I suppose you've already answered to this issue on discord - as it gives 0.5 bonus instead of 1.0 for dragons. I've tested one more time:
value:1:STR[-10+1d5]
made dragon warrior. at start it got 8 STR.
drinked exp potion, got lvl 30 - and now he has 10 STR.
so dragon instead of 1d5, has 1d10 it seems. So we could call it not a bug, but 'feature' ;)
