### ISSUE TITLE
server crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#68]
> 230220 024107 Kirke: Lora the Red hits you.
> 230220 024107 Kirke: Lora the Red hits you.
> 230220 024108 Kirke: You hit Lora the Red.
> 230220 024108 Kirke: You hit Lora the Red.
> 230220 024108 Kirke: You have slain Lora the Red.
> 230220 024108 Kirke: Welcome to level 7.
> 230220 024108 Kirke: You are no longer bleeding.
> 230220 024111 Kirke: You feel the Phial of Galadriel on the ground is special...
> 230220 024111 Kirke: You see the Phial of Galadriel {Lora the Red, ??}.
> 230220 024112 Kirke: You have the Phial of Galadriel {Lora the Red, ??} (i).
> 230220 024116 Kirke: You were holding a Wooden Torch (4650 turns) (f).
> 230220 024116 Shutting down (panic save).
> 230220 024116 Server panic info save succeeded!

**Comment by draconisPW** [comment]
Commit 431e844 fixed two nasty bugs that could easily crash the server. I hope this problem was one of them. Leaving this open in case it was something else, but without debug mode there is no way to tell...

**Comment by draconisPW** [comment]
Bumped to 1.4.0 in case this happens again.

**Comment by draconisPW** [comment]
Closing this. We already have a ticket opened for crash and I'm tempted to think it's the same.
