### ISSUE TITLE
add label for dump file in mangband.cfg

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#7]
As Tangaria got new races and some other differences from PWMA it would be right thing to use separate ladder @ oook for it, so we won't spoil PWMA ladder http://angband.oook.cz/ladder-browse.php?v=PWMAngband 

AFAIU to be able to use it we need to have different 'label' in dump files, eg right now PWMA got dumps starting as:

  [PWMAngband 1.3.0 Character Dump]

/rfe to add a 'label' field in mangband.cfg which would appear in dump file header

**Comment by draconisPW** [comment]
Fixed in bd338d5.
