### ISSUE TITLE
dragon monk can't sell weapons in house-shop

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#71]
Says 'You must identify this item first' when I try to put Long Bow (x3) (+4, +5) - without magic - in my house. but I can't equip it to ID as I dragon monk

**Comment by draconisPW** [comment]
Oops, of course since some innate properties can only be learned "on wield", this cannot work. No idea how to fix that lol...

**Comment by draconisPW** [comment]
Fixed by learning obvious object properties on carry instead of on wield for dragons and monks.
