### ISSUE TITLE
more than one dungeon entrance in location

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#73]
it will be very fun to have possibility to add more than one dungeon entrance to location; eg in TomeNET there is Barrow Downs and Training Tower stairs in start location.

I suppose it's possible to add new terrain.txt object, new stairs type. so current stairs will be stair_1; and to add there stair_2, stair_3 ... etc. Or maybe to add new flag in terrain.txt

**Comment by draconisPW** [comment]
The game is not designed for multiple dungeon locations, sorry.

**Comment by igroglaz** [comment]
I really want to add a first newbie dungeon inside of 1st location house - to make it `old cellar` and put there rats and other cellar stuff. Then second dungeon will be old ruins which won't be so newbie as it's now... I suppose it shouldn't be too impossible to add such feature, as TomeNET got it.
