### ISSUE TITLE
Can't dig through new terrain types

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#76]
I'm adding new terrain types which I wanna use in dungeon.txt, eg:
```
name:dark wall 0
graphics:#:D
priority:25
flags:WALL | ROCK | NO_SCENT | NO_FLOW | MAGMA
desc:.
```

it's got the same flag as
```
name:magma vein
graphics:%:s
priority:15
flags:WALL | ROCK | NO_SCENT | NO_FLOW | MAGMA
info:0:3
desc:A seam of soft rock. It can be removed by digging or magic, and passed
desc: through by immaterial monsters. It stops any spells, missiles or line of
desc: sight.
```

But digging this tile doesn't work - character make attempt after attempt, but won't success ever. It seems digging is hardcoded for granite, quartz and magma..

**Comment by draconisPW** [comment]
Yes digging is hardcoded, I should probably add a DIGGABLE flag.

**Comment by draconisPW** [comment]
I've added a new magma and it works fine. You simply forgot the "info:0:3" for your terrain, which gives the chance of digging. Without that line, chance is zero.
