### ISSUE TITLE
using item from the floor without need to choose it

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#77]
1) there is an potion on the floor.. 
2) 'q' -> '-'
3) game prompts you with the list there this potions written as: "a) potions..."
4) you need to push 'a' to drink it.

/rfe if there is only one type of item on the floor - do not prompt user with the list - just use this item. Will make everything much more faster and comfortable

**Comment by igroglaz** [comment]
this is quite close issue to https://github.com/draconisPW/PWMAngband/issues/74

**Comment by draconisPW** [comment]
It was like that before porting the menu selection from V.

**Comment by draconisPW** [comment]
In fact I don't like this at all. Displaying a menu allows some sort of confirmation before doing something stupid like quaffing bad potion or destroying item. Implemented in 6ac97f3 as an option, being false by default. Use at your own risk.
