### ISSUE TITLE
allow negative stats

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#78]
1) I'm a dragon with 9 STR and 9 CON; all other stats are 3... 
2) if I drink stat potion which raise one stat, but lower another - it won't lower my parameters more than for 3... the same to fountains
3) it means that I could safely drink as much STR as I want; without need to fear that it will drop my other stats.. which is kinda cheezing in certain way

/rfe to allow game to make negative stats, BUT make negavite stats work as '3' stat. For example, if your character has '-7 DEX' - the game will count your brp and attack as if it was 3 DEX.. but to raise stat to 4 DEX - you will need to drink 11 DEX potions.

It will also help in character creation balancing.

**Comment by draconisPW** [comment]
It is already the case, the game just displays "3".
