### ISSUE TITLE
'for sale' -> '@S' or '~'

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#81]
it's quite long and tidious way to inscribe items for sale with 'for sale' words. TomeNET uses @S for this purpose which is quite good. But actually ideal would be some single symbol, like '~', for example. So inscribing item as
~10000 or ~10k
means that it will be sold in player's shop for 10k

As player finds a lot of items, putting all of them for sale will take several extra minutes total with 'for sale' inscriptions for each character.

**Comment by draconisPW** [comment]
'~xxx' can now be used along 'for sale xxx' to price items.
System also simplified so any value that is incorrect is treated as 0 (show item in player shop but disable selling).
