### ISSUE TITLE
always_run flag for terrain

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#83]
If we use such terrains as walls in dungeon.txt:

```
name:obj_grass L ruins
graphics:::s
priority:18
flags:LOS | PROJECT | PASSABLE | TORCH | BORING
```

They prevent running. It will be fun to have special flag 'RUN' which will allow running nearby to that terrain without pause :)

---
[14:58] PowerWyrm: it existed before (option "run past corners") but got removed
[14:59] PowerWyrm: but yeah could be an option -- don't make adjacent features stop running

**Comment by igroglaz** [comment]
please could you add this flag, it will help a great deal in LOS/PROJ terrain adjustment :)

**Comment by draconisPW** [comment]
I'll re-add the option to run past corners.

**Comment by draconisPW** [comment]
Looking at the code, this is gonna be a nightmare to implement, pushing to future.

**Comment by igroglaz** [comment]
"wwwwaaaaiitt.. don't close me!", - squicked this tiny issue... tiny but nightmarish to implement (as always!) :D

maybe there is a dirty fast sneak-peak hack to implement it somehow?

**Comment by igroglaz** [comment]
You said in the past:
_[14:58] PowerWyrm: it existed before (option "run past corners") but got removed_

Maybe it's possible to backport somehow? As plenty of players ask for this feature (eg new Ent/Ranger feature to pass trees in T with this flag will be awesome)

**Comment by draconisPW** [comment]
No it's not possible to backport due to the path code being totally different now. Plus it was only working with V dungeons where all walls were walls.
