### ISSUE TITLE
number of 'normal' items in shop

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#85]
I've spent like an hour trying to customize proper number of items in shop, eg

```
slots:5:10
turnover:1
..
normal:fortune cookie:Fortune Cookie:10:300
normal:food:Flask of Whisky:2:150
normal:food:Pint of Fine Wine:5:150
normal:food:Pint of Fine Ale:3:150
normal:potion:Healing:1:500
normal:potion:Speed:1:500
normal:potion:Restore Mana:1:500
normal:scroll:Teleportation:1:500
```

It's super random. Sometimes there is like 30 of each items. Sometimes 3.

/rfe
add quantity parameter like `<x>d<y>+n`, eg
normal:potion:Speed:1:500:1d3+2
means that there will appear 3-5 potions

**Comment by draconisPW** [comment]
This will be SUPER hard to implement. What would be MUCH easier is a parameter to the staples ("always" slots) to produce n items instead of the default max stack (40).
