### ISSUE TITLE
resistance vulnerability + immunity = 10% damage

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#86]
Vulnerability to certain element:
1. resistance makes you neutral (100% damage VS 30% without vuln)
2. double resist to be resistant (so you will receive 30% of damage VS 10% without vuln)
3. immunity to get immune (0% of damage - the same as without vuln)

/rfe to make vulnerability more interesting mechanics - it won't hurt to allow 10% of damage to soak though immunity; it will give more individuality to certain races/classes. At the same time current vulnerability feels a bit harsh at the beginning. What if vulnerability will become:
1. resistance makes you better protected (you receive 60% damage VS 30% without vuln)
2. double resist to be resistant (so you will receive 30% damage VS 10% without vuln)
3. immunity to get _almost_ immune (10% of damage vs 0% without vuln)

It will be more mild and could reduce numbers of earlier YASDs for Ents and upcomming Hydras; to reduce a bit crucial need of random finding immune item.

**Comment by igroglaz** [comment]
Addition.... 

From current syste:
resistance makes you neutral (100% damage VS 30% without vuln)
double resist to be resistant (so you will receive 30% of damage VS 10% without vuln)
immunity to get immune (0% of damage - the same as without vuln)

We should make:
resistance makes you better protected (you receive 60% damage VS 30% without vuln)
double resist to be resistant (so you will receive **15%** damage VS 10% without vuln)
immunity to get almost immune (**10%** of damage vs **5%** without vuln)

**Comment by draconisPW** [comment]
I just checked the code and there's no way I can implement this easily, there are too many things intertwined and that would require rewriting the resistance code completely since it's currently based on adding resistance + vulnerability. I simply don't have the time to do this currently, so it's postponed to a later release.

**Comment by igroglaz** [comment]
Hm.. Maybe it's possible for now to make quick&dirty hack directly in server code; without making it as option?

**Comment by draconisPW** [comment]
No you can't. This requires changing how vulnerability works from setting resistance to -1 to a new flag. Currently the info is lost and you'd have to recalculate everything  when applying damage. Plus the whole resistance panel would have to be reworked. Clearly not manageable by a simple hack.

**Comment by igroglaz** [comment]
actually it's quite beautiful task to do in PWMA. Maybe we can just add it as a new function without edition existing ones? On top of things
