### ISSUE TITLE
"/" chat command

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#87]
currently it's pretty uncomfortable each time to re-inscribe scrolls to be able to recall to certain location. eg I've got @r9#R0,1 scrolls.. and when I need to go to dungeon - I have to inscribe it #Rxy - and old inscription will vanish; after I came to the spot - I have to add @r9#R0,1 one more time. I've figured out way to drop scrolls, buy 2, inscribe, pick up.. But it's quite uncomfortable too. 

As temporary solution I plan to add one more WoR-type scrolls so at least there won't be need to drop scrolls.. But the best solution is /rec chat command (like in TomeNET https://tomenet.eu/guide.php?chapter=0.2b ).

Btw it's possible to assign to / commands a lot of useful stuff like https://github.com/draconisPW/PWMAngband/issues/69
and https://github.com/draconisPW/PWMAngband/issues/46

It will be fun to have / in PWMA, as keyboard doesn't have enough keys for all sort of actions. / commands are easely assigned to macros

**Comment by igroglaz** [comment]
another good command could be /purge to reduce satiation on 10% (make this command take turn or two of energy)... to get rid of excessive food satiation, as having the only way to cure it with salt water (or wating looong time) isn't really logical

**Comment by draconisPW** [comment]
I've improved the #R inscription to ask for depth manually if it is not defined specifically. This makes /rec command pointless. I keep this as a general "/" chat command if I ever decide to implement it.

**Comment by igroglaz** [comment]
good / command could be /puke to remove satiation limit as now it's quite hard to avoid being gorged (in T I'll remove all satiation from healing pots, hope it will help a bit).

/puke could work like this - it takes one turn idling (you can't do nothing this turn) after which you have -5 to satiation

**Comment by draconisPW** [comment]
Client has been modified to pre-process "/command" on the chat line. For now, only "/house" is recognized and will trigger the do_cmd_purchase_house() method as if the user pressed 'H' or '§' (which may not exist on some keyboards). Other commands could be added via new RFEs in a future version.
