### ISSUE TITLE
can't wear item from house

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#88]
1) put item on sale in my house
2) drop item to the ground (to trade it for food)
3) other player tried to pick it up, but failed
4) now I can't wear it too

demo:
https://youtu.be/xHpIwriTM3Q?t=4205

**Comment by draconisPW** [comment]
I have no idea what is happening, I'll try to reproduce the problem.

**Comment by draconisPW** [comment]
Not a bug. The boots you are wearing are inscribed "!*" which also means you cannot take them off... Remove the insccription on the boots first if you want to switch.
