### ISSUE TITLE
Add class with constant pet

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#9]
Already several players suggested to add a constant pet for a character. I suppose if we would add a pet accessible for every character - it would completely break balance.

But as we already got summoner class and temporary 'pet' mechanics, maybe it's possible to implement such class, as 'tamer', which would have one constant pet and some spells which he could use to heal/buff his pet. Just an idea for a class :)

**Comment by draconisPW** [comment]
I'll leave this here for now but I doubt this will ever be implemented. Don't want the game to become NetHack. And pets in NetHack die after three seconds, a lot of fuss for nothing...

**Comment by igroglaz** [comment]
I didn't see it as nethack pet, rather like pet for Hunter in WoW. So if it would die - it could be ressurected

**Comment by draconisPW** [comment]
Implementation of #358 now makes this possible

**Comment by draconisPW** [comment]
Add pet for Druid and new Adventurer class.

**Comment by igroglaz** [comment]
Also we may want to store pet name in 'p' structure.. so when we have last argment (pet) as true...
`summon_specific_race_aux(p, c, &p->grid, get_race(summon_chance[i].race), 1, true);`
..it will be stored to 'p' structure.

atm we got only p->slaves to count summons.. having summon name will give possibility to make checks for particular summon - eg necromancer will be able to have only  3 skeleton, 1 skeleton mage, etc

**Comment by draconisPW** [comment]
Villager class has this now.
