### ISSUE TITLE
drain life rods doesn't work properly

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#92]
I've tested at several monsters at my streams - they drink not 150 HP, but much less (50?). so right now they are completely useless. I suppose they should be buffed

**Comment by draconisPW** [comment]
Works as intended as per V. Testing in debug mode, they drain 150 hps normally.

**Comment by igroglaz** [comment]
1) I've tried it at my stream at different mobs.. and they didn't make 150 dmg, but much less. Maybe that mobs was resistant? (not taking in account immune mobs, like demons, golems etc)

2)  did you test rods or wands? cause wands drain 150 dice:

> name:Drain Life
> graphics:-:d
> type:wand
> properties:50:10:1200
> alloc:50:50 to 100
> combat:0:1d1:0:0:0
> charges:3+d3
> effect:BOLT_STATUS_DAM:MON_DRAIN
> dice:150

while rods other (which?) amount:

> name:Drain Life
> graphics:-:d
> type:rod
> properties:75:15:3600
> alloc:20:75 to 100
> combat:0:1d1:0:0:0
> act:DRAIN_LIFE3
> time:23

So maybe rods should have just 150 dice?

**Comment by draconisPW** [comment]
Rods and wands do the same damage, tested with debug mode. Mobs are not resistant, they take either the full damage or nothing. Didn't see any other behavior, feel free to bring evidence if you find a monster that doesn't fall into those two categories.

**Comment by igroglaz** [comment]
it's at one of my latest streams:
https://www.youtube.com/watch?v=IOqXNwiBk9Q
or
https://www.youtube.com/watch?v=IOqXNwiBk9Q

but I don't recall exact time.. I'll test it some more times later then.
