### ISSUE TITLE
new dungeon flag for aquatic monsters: underground lake

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#94]
One of the most powerful and interesting features in Angband is dungeon creation algorithm. As we have new aquatic monsters, it will be fun to add new dungeon flags like WATER_RIVER

It could be something like 'lake' which could appear in 3 different sizes (small, medium, large) and also have different forms.

**Comment by draconisPW** [comment]
You mean like a dungeon profile? Ok I'll think of it...

**Comment by igroglaz** [comment]
Not the dungeon profile, but list-dungeon-flags.h flags, like WATER_RIVER flag :)

**Comment by draconisPW** [comment]
Ok a lake instead of a river.

**Comment by igroglaz** [comment]
Yep :) Even maybe add one more river flag - narrow river (like a stream).

I wonder is it possible to unhardcode construction of such terrain elements? To use in it's building different terrain tiles
