### ISSUE TITLE
hardcoded bones

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#95]
> [22:42] PowerWyrm: hmm I think some monster races are hardcoded, especially those who drop skeletons
> [22:43] PowerWyrm: I remember my server crashing because I forgot to rename "ettin skeleton" to "two-headed troll skeleton" in the code and crashed cos it couldn't generate the skeleton whne the mob died

maybe it should be unhardcoded?

**Comment by draconisPW** [comment]
Or simply better handled. Each monster race dropping a skeleton should check if there is a corresponding skeleton from object file automatically and not using hardcoded values. If not, then a regular skeleton should be used (like what is done for corpses).

**Comment by draconisPW** [comment]
Implemented in 9c80ae8.
