### ISSUE TITLE
'torch' light in cities in daylight

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#97]
New V light is great, but it made daylight in town locations as yellow, which looks worse than before.

/rfe to add hack so all town locations will use 'white' light

**Comment by draconisPW** [comment]
Implemented in 4a465e8.

**Comment by igroglaz** [comment]
doesn't work :( light in towns is still yellow

**Comment by draconisPW** [comment]
Was misunderstood. The right thing to do is put back "los" lighting in town instead of "torch" lighting with the option instead of displaying "torch" in white.

**Comment by draconisPW** [comment]
Nevermind. This was actually a bug and lighting in town should never have been "torch" anyway. I've fixed the bug in 627dc19 and removed the option because it now makes no sense.
