### ISSUE TITLE
unhardcode monster_base

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#98]
allow to create new monster base

> [00:17] PowerWyrm: you need to add RSF(S_ANGEL, RST_SUMMON, 0) to list-mon-spells.h and recompile client and server

**Comment by igroglaz** [comment]
please could you take a look at this issue :) it will give possibility to unhardcode loads of monsters (djinns, pixies, angels, etc) and assign them into different objects, traps, etc

**Comment by igroglaz** [comment]
Please, it will be fun to raise priority of this issue if possible - cause atm there are some monsters which look pretty weird in wrong families :(

**Comment by draconisPW** [comment]
Sorry I don't get this. Monster templates are not hardcoded, you can add anything you want in monster_base.txt to make a new family for monsters. Closing this as it's a non issue.
